#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING  "zcode.org ARM STM32F030"
#endif

#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0003
#endif
