#if !defined(ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING) || !defined(ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION)
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING  "zcode.org Arduino API"
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0001
#endif

#if !defined(ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING) || !defined(ZCODE_IDENTIFY_PLATFORM_HARDWARE_VERSION)
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING "Arduino"
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_VERSION 0x0
#endif
