#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING  "zcode.org Arduino"
#endif

#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0001
#endif
