/*
 * Zcode Library - Command System for Microcontrollers)
 * Copyright (c) 2022 Zcode team (Susan Witts, Alicia Witts)
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING  "zcode.org for ARM"
#endif

#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0001
#endif

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F030"
#endif

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_VERSION
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_VERSION 0x0001
#endif
