/*
 * Zscript Library - Command System for Microcontrollers)
 * Copyright (c) 2022 Zscript team (Susan Witts, Alicia Witts)
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef ZSCRIPT_IDENTIFY_CORE_ZSCRIPT_LANG_STRING
#define ZSCRIPT_IDENTIFY_CORE_ZSCRIPT_LANG_STRING  "zscript.net gen-core"
#endif
#ifndef ZSCRIPT_IDENTIFY_CORE_ZSCRIPT_LANG_VERSION
#define ZSCRIPT_IDENTIFY_CORE_ZSCRIPT_LANG_VERSION 0x0001
#endif

#ifndef ZSCRIPT_IDENTIFY_USER_FIRMWARE_STRING
#define ZSCRIPT_IDENTIFY_USER_FIRMWARE_STRING  "User Firmware"
#warning "Using default user firmware string"
#endif
#ifndef ZSCRIPT_IDENTIFY_USER_FIRMWARE_VERSION
#define ZSCRIPT_IDENTIFY_USER_FIRMWARE_VERSION 0x0001
#endif

#ifndef ZSCRIPT_IDENTIFY_USER_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_USER_HARDWARE_STRING  "User Hardware"
#warning "Using default user hardware string"
#endif
#ifndef ZSCRIPT_IDENTIFY_USER_HARDWARE_VERSION
#define ZSCRIPT_IDENTIFY_USER_HARDWARE_VERSION 0x0001
#endif

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_FIRMWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_FIRMWARE_STRING "Platform Firmware"
#warning "Using default platform firmware string"
#endif
#ifndef ZSCRIPT_IDENTIFY_PLATFORM_FIRMWARE_VERSION
#define ZSCRIPT_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0001
#endif

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING "Platform Hardware"
#warning "Using default platform hardware string"
#endif
#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_VERSION
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_VERSION 0x0001
#endif
