/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.402069
 */

#define FIND_VALUE_I2S_CK_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_CK(INDEX,PIN) FIND_VALUE_I2S_CK_inner(INDEX,PIN)

#define FIND_VALUE_I2S_CKIN_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_CKIN(INDEX,PIN) FIND_VALUE_I2S_CKIN_inner(INDEX,PIN)

#define FIND_VALUE_I2S_MCK_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_MCK(INDEX,PIN) FIND_VALUE_I2S_MCK_inner(INDEX,PIN)

#define FIND_VALUE_I2S_SCK_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_SCK(INDEX,PIN) FIND_VALUE_I2S_SCK_inner(INDEX,PIN)

#define FIND_VALUE_I2S_SD_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_SD(INDEX,PIN) FIND_VALUE_I2S_SD_inner(INDEX,PIN)

#define FIND_VALUE_I2S_SDI_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_SDI(INDEX,PIN) FIND_VALUE_I2S_SDI_inner(INDEX,PIN)

#define FIND_VALUE_I2S_SDO_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_SDO(INDEX,PIN) FIND_VALUE_I2S_SDO_inner(INDEX,PIN)

#define FIND_VALUE_I2S_WS_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_WS(INDEX,PIN) FIND_VALUE_I2S_WS_inner(INDEX,PIN)

#define FIND_VALUE_I2S_ext_SD_inner(INDEX,PIN) I2C##_I2S_##PIN
#define FIND_VALUE_I2S_ext_SD(INDEX,PIN) FIND_VALUE_I2S_ext_SD_inner(INDEX,PIN)

#ifdef USE_I2S0
#if !FIND_VALUE_I2S_CK(_I2S0, I2S0_CK)
#error Invalid pin assignment for I2S0 CK pin: I2S0_CK
#endif
#if !FIND_VALUE_I2S_CKIN(_I2S0, I2S0_CKIN)
#error Invalid pin assignment for I2S0 CKIN pin: I2S0_CKIN
#endif
#if !FIND_VALUE_I2S_MCK(_I2S0, I2S0_MCK)
#error Invalid pin assignment for I2S0 MCK pin: I2S0_MCK
#endif
#if !FIND_VALUE_I2S_SCK(_I2S0, I2S0_SCK)
#error Invalid pin assignment for I2S0 SCK pin: I2S0_SCK
#endif
#if !FIND_VALUE_I2S_SD(_I2S0, I2S0_SD)
#error Invalid pin assignment for I2S0 SD pin: I2S0_SD
#endif
#if !FIND_VALUE_I2S_SDI(_I2S0, I2S0_SDI)
#error Invalid pin assignment for I2S0 SDI pin: I2S0_SDI
#endif
#if !FIND_VALUE_I2S_SDO(_I2S0, I2S0_SDO)
#error Invalid pin assignment for I2S0 SDO pin: I2S0_SDO
#endif
#if !FIND_VALUE_I2S_WS(_I2S0, I2S0_WS)
#error Invalid pin assignment for I2S0 WS pin: I2S0_WS
#endif
#if !FIND_VALUE_I2S_ext_SD(_I2S0, I2S0_ext_SD)
#error Invalid pin assignment for I2S0 ext_SD pin: I2S0_ext_SD
#endif
#endif

#ifdef USE_I2S1
#if !FIND_VALUE_I2S_CK(_I2S1, I2S1_CK)
#error Invalid pin assignment for I2S1 CK pin: I2S1_CK
#endif
#if !FIND_VALUE_I2S_CKIN(_I2S1, I2S1_CKIN)
#error Invalid pin assignment for I2S1 CKIN pin: I2S1_CKIN
#endif
#if !FIND_VALUE_I2S_MCK(_I2S1, I2S1_MCK)
#error Invalid pin assignment for I2S1 MCK pin: I2S1_MCK
#endif
#if !FIND_VALUE_I2S_SCK(_I2S1, I2S1_SCK)
#error Invalid pin assignment for I2S1 SCK pin: I2S1_SCK
#endif
#if !FIND_VALUE_I2S_SD(_I2S1, I2S1_SD)
#error Invalid pin assignment for I2S1 SD pin: I2S1_SD
#endif
#if !FIND_VALUE_I2S_SDI(_I2S1, I2S1_SDI)
#error Invalid pin assignment for I2S1 SDI pin: I2S1_SDI
#endif
#if !FIND_VALUE_I2S_SDO(_I2S1, I2S1_SDO)
#error Invalid pin assignment for I2S1 SDO pin: I2S1_SDO
#endif
#if !FIND_VALUE_I2S_WS(_I2S1, I2S1_WS)
#error Invalid pin assignment for I2S1 WS pin: I2S1_WS
#endif
#if !FIND_VALUE_I2S_ext_SD(_I2S1, I2S1_ext_SD)
#error Invalid pin assignment for I2S1 ext_SD pin: I2S1_ext_SD
#endif
#endif

