/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.399059
 */

#define FIND_VALUE_FDCAN_RX_inner(INDEX,PIN) I2C##_FDCAN_##PIN
#define FIND_VALUE_FDCAN_RX(INDEX,PIN) FIND_VALUE_FDCAN_RX_inner(INDEX,PIN)

#define FIND_VALUE_FDCAN_TX_inner(INDEX,PIN) I2C##_FDCAN_##PIN
#define FIND_VALUE_FDCAN_TX(INDEX,PIN) FIND_VALUE_FDCAN_TX_inner(INDEX,PIN)

#ifdef USE_FDCAN0
#if !FIND_VALUE_FDCAN_RX(_FDCAN0, FDCAN0_RX)
#error Invalid pin assignment for FDCAN0 RX pin: FDCAN0_RX
#endif
#if !FIND_VALUE_FDCAN_TX(_FDCAN0, FDCAN0_TX)
#error Invalid pin assignment for FDCAN0 TX pin: FDCAN0_TX
#endif
#endif

#ifdef USE_FDCAN1
#if !FIND_VALUE_FDCAN_RX(_FDCAN1, FDCAN1_RX)
#error Invalid pin assignment for FDCAN1 RX pin: FDCAN1_RX
#endif
#if !FIND_VALUE_FDCAN_TX(_FDCAN1, FDCAN1_TX)
#error Invalid pin assignment for FDCAN1 TX pin: FDCAN1_TX
#endif
#endif

#ifdef USE_FDCAN2
#if !FIND_VALUE_FDCAN_RX(_FDCAN2, FDCAN2_RX)
#error Invalid pin assignment for FDCAN2 RX pin: FDCAN2_RX
#endif
#if !FIND_VALUE_FDCAN_TX(_FDCAN2, FDCAN2_TX)
#error Invalid pin assignment for FDCAN2 TX pin: FDCAN2_TX
#endif
#endif

