/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.405272
 */

#define FIND_VALUE_TRIG_INOUT_inner(INDEX,PIN) I2C##_TRIG_##PIN
#define FIND_VALUE_TRIG_INOUT(INDEX,PIN) FIND_VALUE_TRIG_INOUT_inner(INDEX,PIN)

#ifdef USE_TRIG0
#if !FIND_VALUE_TRIG_INOUT(_TRIG0, TRIG0_INOUT)
#error Invalid pin assignment for TRIG0 INOUT pin: TRIG0_INOUT
#endif
#endif

