/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398234
 */

#define FIND_VALUE_DCMIPP_D0_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D0(INDEX,PIN) FIND_VALUE_DCMIPP_D0_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D1_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D1(INDEX,PIN) FIND_VALUE_DCMIPP_D1_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D10_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D10(INDEX,PIN) FIND_VALUE_DCMIPP_D10_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D11_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D11(INDEX,PIN) FIND_VALUE_DCMIPP_D11_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D12_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D12(INDEX,PIN) FIND_VALUE_DCMIPP_D12_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D13_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D13(INDEX,PIN) FIND_VALUE_DCMIPP_D13_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D14_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D14(INDEX,PIN) FIND_VALUE_DCMIPP_D14_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D15_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D15(INDEX,PIN) FIND_VALUE_DCMIPP_D15_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D2_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D2(INDEX,PIN) FIND_VALUE_DCMIPP_D2_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D3_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D3(INDEX,PIN) FIND_VALUE_DCMIPP_D3_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D4_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D4(INDEX,PIN) FIND_VALUE_DCMIPP_D4_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D5_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D5(INDEX,PIN) FIND_VALUE_DCMIPP_D5_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D6_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D6(INDEX,PIN) FIND_VALUE_DCMIPP_D6_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D7_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D7(INDEX,PIN) FIND_VALUE_DCMIPP_D7_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D8_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D8(INDEX,PIN) FIND_VALUE_DCMIPP_D8_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_D9_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_D9(INDEX,PIN) FIND_VALUE_DCMIPP_D9_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_HSYNC_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_HSYNC(INDEX,PIN) FIND_VALUE_DCMIPP_HSYNC_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_PIXCLK_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_PIXCLK(INDEX,PIN) FIND_VALUE_DCMIPP_PIXCLK_inner(INDEX,PIN)

#define FIND_VALUE_DCMIPP_VSYNC_inner(INDEX,PIN) I2C##_DCMIPP_##PIN
#define FIND_VALUE_DCMIPP_VSYNC(INDEX,PIN) FIND_VALUE_DCMIPP_VSYNC_inner(INDEX,PIN)

#ifdef USE_DCMIPP0
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP0, DCMIPP0_D0)
#error Invalid pin assignment for DCMIPP0 D0 pin: DCMIPP0_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP0, DCMIPP0_D1)
#error Invalid pin assignment for DCMIPP0 D1 pin: DCMIPP0_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP0, DCMIPP0_D10)
#error Invalid pin assignment for DCMIPP0 D10 pin: DCMIPP0_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP0, DCMIPP0_D11)
#error Invalid pin assignment for DCMIPP0 D11 pin: DCMIPP0_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP0, DCMIPP0_D12)
#error Invalid pin assignment for DCMIPP0 D12 pin: DCMIPP0_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP0, DCMIPP0_D13)
#error Invalid pin assignment for DCMIPP0 D13 pin: DCMIPP0_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP0, DCMIPP0_D14)
#error Invalid pin assignment for DCMIPP0 D14 pin: DCMIPP0_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP0, DCMIPP0_D15)
#error Invalid pin assignment for DCMIPP0 D15 pin: DCMIPP0_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP0, DCMIPP0_D2)
#error Invalid pin assignment for DCMIPP0 D2 pin: DCMIPP0_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP0, DCMIPP0_D3)
#error Invalid pin assignment for DCMIPP0 D3 pin: DCMIPP0_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP0, DCMIPP0_D4)
#error Invalid pin assignment for DCMIPP0 D4 pin: DCMIPP0_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP0, DCMIPP0_D5)
#error Invalid pin assignment for DCMIPP0 D5 pin: DCMIPP0_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP0, DCMIPP0_D6)
#error Invalid pin assignment for DCMIPP0 D6 pin: DCMIPP0_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP0, DCMIPP0_D7)
#error Invalid pin assignment for DCMIPP0 D7 pin: DCMIPP0_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP0, DCMIPP0_D8)
#error Invalid pin assignment for DCMIPP0 D8 pin: DCMIPP0_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP0, DCMIPP0_D9)
#error Invalid pin assignment for DCMIPP0 D9 pin: DCMIPP0_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP0, DCMIPP0_HSYNC)
#error Invalid pin assignment for DCMIPP0 HSYNC pin: DCMIPP0_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP0, DCMIPP0_PIXCLK)
#error Invalid pin assignment for DCMIPP0 PIXCLK pin: DCMIPP0_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP0, DCMIPP0_VSYNC)
#error Invalid pin assignment for DCMIPP0 VSYNC pin: DCMIPP0_VSYNC
#endif
#endif

#ifdef USE_DCMIPP1
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP1, DCMIPP1_D0)
#error Invalid pin assignment for DCMIPP1 D0 pin: DCMIPP1_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP1, DCMIPP1_D1)
#error Invalid pin assignment for DCMIPP1 D1 pin: DCMIPP1_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP1, DCMIPP1_D10)
#error Invalid pin assignment for DCMIPP1 D10 pin: DCMIPP1_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP1, DCMIPP1_D11)
#error Invalid pin assignment for DCMIPP1 D11 pin: DCMIPP1_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP1, DCMIPP1_D12)
#error Invalid pin assignment for DCMIPP1 D12 pin: DCMIPP1_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP1, DCMIPP1_D13)
#error Invalid pin assignment for DCMIPP1 D13 pin: DCMIPP1_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP1, DCMIPP1_D14)
#error Invalid pin assignment for DCMIPP1 D14 pin: DCMIPP1_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP1, DCMIPP1_D15)
#error Invalid pin assignment for DCMIPP1 D15 pin: DCMIPP1_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP1, DCMIPP1_D2)
#error Invalid pin assignment for DCMIPP1 D2 pin: DCMIPP1_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP1, DCMIPP1_D3)
#error Invalid pin assignment for DCMIPP1 D3 pin: DCMIPP1_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP1, DCMIPP1_D4)
#error Invalid pin assignment for DCMIPP1 D4 pin: DCMIPP1_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP1, DCMIPP1_D5)
#error Invalid pin assignment for DCMIPP1 D5 pin: DCMIPP1_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP1, DCMIPP1_D6)
#error Invalid pin assignment for DCMIPP1 D6 pin: DCMIPP1_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP1, DCMIPP1_D7)
#error Invalid pin assignment for DCMIPP1 D7 pin: DCMIPP1_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP1, DCMIPP1_D8)
#error Invalid pin assignment for DCMIPP1 D8 pin: DCMIPP1_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP1, DCMIPP1_D9)
#error Invalid pin assignment for DCMIPP1 D9 pin: DCMIPP1_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP1, DCMIPP1_HSYNC)
#error Invalid pin assignment for DCMIPP1 HSYNC pin: DCMIPP1_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP1, DCMIPP1_PIXCLK)
#error Invalid pin assignment for DCMIPP1 PIXCLK pin: DCMIPP1_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP1, DCMIPP1_VSYNC)
#error Invalid pin assignment for DCMIPP1 VSYNC pin: DCMIPP1_VSYNC
#endif
#endif

#ifdef USE_DCMIPP2
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP2, DCMIPP2_D0)
#error Invalid pin assignment for DCMIPP2 D0 pin: DCMIPP2_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP2, DCMIPP2_D1)
#error Invalid pin assignment for DCMIPP2 D1 pin: DCMIPP2_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP2, DCMIPP2_D10)
#error Invalid pin assignment for DCMIPP2 D10 pin: DCMIPP2_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP2, DCMIPP2_D11)
#error Invalid pin assignment for DCMIPP2 D11 pin: DCMIPP2_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP2, DCMIPP2_D12)
#error Invalid pin assignment for DCMIPP2 D12 pin: DCMIPP2_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP2, DCMIPP2_D13)
#error Invalid pin assignment for DCMIPP2 D13 pin: DCMIPP2_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP2, DCMIPP2_D14)
#error Invalid pin assignment for DCMIPP2 D14 pin: DCMIPP2_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP2, DCMIPP2_D15)
#error Invalid pin assignment for DCMIPP2 D15 pin: DCMIPP2_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP2, DCMIPP2_D2)
#error Invalid pin assignment for DCMIPP2 D2 pin: DCMIPP2_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP2, DCMIPP2_D3)
#error Invalid pin assignment for DCMIPP2 D3 pin: DCMIPP2_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP2, DCMIPP2_D4)
#error Invalid pin assignment for DCMIPP2 D4 pin: DCMIPP2_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP2, DCMIPP2_D5)
#error Invalid pin assignment for DCMIPP2 D5 pin: DCMIPP2_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP2, DCMIPP2_D6)
#error Invalid pin assignment for DCMIPP2 D6 pin: DCMIPP2_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP2, DCMIPP2_D7)
#error Invalid pin assignment for DCMIPP2 D7 pin: DCMIPP2_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP2, DCMIPP2_D8)
#error Invalid pin assignment for DCMIPP2 D8 pin: DCMIPP2_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP2, DCMIPP2_D9)
#error Invalid pin assignment for DCMIPP2 D9 pin: DCMIPP2_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP2, DCMIPP2_HSYNC)
#error Invalid pin assignment for DCMIPP2 HSYNC pin: DCMIPP2_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP2, DCMIPP2_PIXCLK)
#error Invalid pin assignment for DCMIPP2 PIXCLK pin: DCMIPP2_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP2, DCMIPP2_VSYNC)
#error Invalid pin assignment for DCMIPP2 VSYNC pin: DCMIPP2_VSYNC
#endif
#endif

#ifdef USE_DCMIPP3
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP3, DCMIPP3_D0)
#error Invalid pin assignment for DCMIPP3 D0 pin: DCMIPP3_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP3, DCMIPP3_D1)
#error Invalid pin assignment for DCMIPP3 D1 pin: DCMIPP3_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP3, DCMIPP3_D10)
#error Invalid pin assignment for DCMIPP3 D10 pin: DCMIPP3_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP3, DCMIPP3_D11)
#error Invalid pin assignment for DCMIPP3 D11 pin: DCMIPP3_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP3, DCMIPP3_D12)
#error Invalid pin assignment for DCMIPP3 D12 pin: DCMIPP3_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP3, DCMIPP3_D13)
#error Invalid pin assignment for DCMIPP3 D13 pin: DCMIPP3_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP3, DCMIPP3_D14)
#error Invalid pin assignment for DCMIPP3 D14 pin: DCMIPP3_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP3, DCMIPP3_D15)
#error Invalid pin assignment for DCMIPP3 D15 pin: DCMIPP3_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP3, DCMIPP3_D2)
#error Invalid pin assignment for DCMIPP3 D2 pin: DCMIPP3_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP3, DCMIPP3_D3)
#error Invalid pin assignment for DCMIPP3 D3 pin: DCMIPP3_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP3, DCMIPP3_D4)
#error Invalid pin assignment for DCMIPP3 D4 pin: DCMIPP3_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP3, DCMIPP3_D5)
#error Invalid pin assignment for DCMIPP3 D5 pin: DCMIPP3_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP3, DCMIPP3_D6)
#error Invalid pin assignment for DCMIPP3 D6 pin: DCMIPP3_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP3, DCMIPP3_D7)
#error Invalid pin assignment for DCMIPP3 D7 pin: DCMIPP3_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP3, DCMIPP3_D8)
#error Invalid pin assignment for DCMIPP3 D8 pin: DCMIPP3_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP3, DCMIPP3_D9)
#error Invalid pin assignment for DCMIPP3 D9 pin: DCMIPP3_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP3, DCMIPP3_HSYNC)
#error Invalid pin assignment for DCMIPP3 HSYNC pin: DCMIPP3_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP3, DCMIPP3_PIXCLK)
#error Invalid pin assignment for DCMIPP3 PIXCLK pin: DCMIPP3_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP3, DCMIPP3_VSYNC)
#error Invalid pin assignment for DCMIPP3 VSYNC pin: DCMIPP3_VSYNC
#endif
#endif

#ifdef USE_DCMIPP4
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP4, DCMIPP4_D0)
#error Invalid pin assignment for DCMIPP4 D0 pin: DCMIPP4_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP4, DCMIPP4_D1)
#error Invalid pin assignment for DCMIPP4 D1 pin: DCMIPP4_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP4, DCMIPP4_D10)
#error Invalid pin assignment for DCMIPP4 D10 pin: DCMIPP4_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP4, DCMIPP4_D11)
#error Invalid pin assignment for DCMIPP4 D11 pin: DCMIPP4_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP4, DCMIPP4_D12)
#error Invalid pin assignment for DCMIPP4 D12 pin: DCMIPP4_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP4, DCMIPP4_D13)
#error Invalid pin assignment for DCMIPP4 D13 pin: DCMIPP4_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP4, DCMIPP4_D14)
#error Invalid pin assignment for DCMIPP4 D14 pin: DCMIPP4_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP4, DCMIPP4_D15)
#error Invalid pin assignment for DCMIPP4 D15 pin: DCMIPP4_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP4, DCMIPP4_D2)
#error Invalid pin assignment for DCMIPP4 D2 pin: DCMIPP4_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP4, DCMIPP4_D3)
#error Invalid pin assignment for DCMIPP4 D3 pin: DCMIPP4_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP4, DCMIPP4_D4)
#error Invalid pin assignment for DCMIPP4 D4 pin: DCMIPP4_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP4, DCMIPP4_D5)
#error Invalid pin assignment for DCMIPP4 D5 pin: DCMIPP4_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP4, DCMIPP4_D6)
#error Invalid pin assignment for DCMIPP4 D6 pin: DCMIPP4_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP4, DCMIPP4_D7)
#error Invalid pin assignment for DCMIPP4 D7 pin: DCMIPP4_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP4, DCMIPP4_D8)
#error Invalid pin assignment for DCMIPP4 D8 pin: DCMIPP4_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP4, DCMIPP4_D9)
#error Invalid pin assignment for DCMIPP4 D9 pin: DCMIPP4_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP4, DCMIPP4_HSYNC)
#error Invalid pin assignment for DCMIPP4 HSYNC pin: DCMIPP4_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP4, DCMIPP4_PIXCLK)
#error Invalid pin assignment for DCMIPP4 PIXCLK pin: DCMIPP4_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP4, DCMIPP4_VSYNC)
#error Invalid pin assignment for DCMIPP4 VSYNC pin: DCMIPP4_VSYNC
#endif
#endif

#ifdef USE_DCMIPP5
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP5, DCMIPP5_D0)
#error Invalid pin assignment for DCMIPP5 D0 pin: DCMIPP5_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP5, DCMIPP5_D1)
#error Invalid pin assignment for DCMIPP5 D1 pin: DCMIPP5_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP5, DCMIPP5_D10)
#error Invalid pin assignment for DCMIPP5 D10 pin: DCMIPP5_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP5, DCMIPP5_D11)
#error Invalid pin assignment for DCMIPP5 D11 pin: DCMIPP5_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP5, DCMIPP5_D12)
#error Invalid pin assignment for DCMIPP5 D12 pin: DCMIPP5_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP5, DCMIPP5_D13)
#error Invalid pin assignment for DCMIPP5 D13 pin: DCMIPP5_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP5, DCMIPP5_D14)
#error Invalid pin assignment for DCMIPP5 D14 pin: DCMIPP5_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP5, DCMIPP5_D15)
#error Invalid pin assignment for DCMIPP5 D15 pin: DCMIPP5_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP5, DCMIPP5_D2)
#error Invalid pin assignment for DCMIPP5 D2 pin: DCMIPP5_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP5, DCMIPP5_D3)
#error Invalid pin assignment for DCMIPP5 D3 pin: DCMIPP5_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP5, DCMIPP5_D4)
#error Invalid pin assignment for DCMIPP5 D4 pin: DCMIPP5_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP5, DCMIPP5_D5)
#error Invalid pin assignment for DCMIPP5 D5 pin: DCMIPP5_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP5, DCMIPP5_D6)
#error Invalid pin assignment for DCMIPP5 D6 pin: DCMIPP5_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP5, DCMIPP5_D7)
#error Invalid pin assignment for DCMIPP5 D7 pin: DCMIPP5_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP5, DCMIPP5_D8)
#error Invalid pin assignment for DCMIPP5 D8 pin: DCMIPP5_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP5, DCMIPP5_D9)
#error Invalid pin assignment for DCMIPP5 D9 pin: DCMIPP5_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP5, DCMIPP5_HSYNC)
#error Invalid pin assignment for DCMIPP5 HSYNC pin: DCMIPP5_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP5, DCMIPP5_PIXCLK)
#error Invalid pin assignment for DCMIPP5 PIXCLK pin: DCMIPP5_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP5, DCMIPP5_VSYNC)
#error Invalid pin assignment for DCMIPP5 VSYNC pin: DCMIPP5_VSYNC
#endif
#endif

#ifdef USE_DCMIPP6
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP6, DCMIPP6_D0)
#error Invalid pin assignment for DCMIPP6 D0 pin: DCMIPP6_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP6, DCMIPP6_D1)
#error Invalid pin assignment for DCMIPP6 D1 pin: DCMIPP6_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP6, DCMIPP6_D10)
#error Invalid pin assignment for DCMIPP6 D10 pin: DCMIPP6_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP6, DCMIPP6_D11)
#error Invalid pin assignment for DCMIPP6 D11 pin: DCMIPP6_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP6, DCMIPP6_D12)
#error Invalid pin assignment for DCMIPP6 D12 pin: DCMIPP6_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP6, DCMIPP6_D13)
#error Invalid pin assignment for DCMIPP6 D13 pin: DCMIPP6_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP6, DCMIPP6_D14)
#error Invalid pin assignment for DCMIPP6 D14 pin: DCMIPP6_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP6, DCMIPP6_D15)
#error Invalid pin assignment for DCMIPP6 D15 pin: DCMIPP6_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP6, DCMIPP6_D2)
#error Invalid pin assignment for DCMIPP6 D2 pin: DCMIPP6_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP6, DCMIPP6_D3)
#error Invalid pin assignment for DCMIPP6 D3 pin: DCMIPP6_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP6, DCMIPP6_D4)
#error Invalid pin assignment for DCMIPP6 D4 pin: DCMIPP6_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP6, DCMIPP6_D5)
#error Invalid pin assignment for DCMIPP6 D5 pin: DCMIPP6_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP6, DCMIPP6_D6)
#error Invalid pin assignment for DCMIPP6 D6 pin: DCMIPP6_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP6, DCMIPP6_D7)
#error Invalid pin assignment for DCMIPP6 D7 pin: DCMIPP6_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP6, DCMIPP6_D8)
#error Invalid pin assignment for DCMIPP6 D8 pin: DCMIPP6_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP6, DCMIPP6_D9)
#error Invalid pin assignment for DCMIPP6 D9 pin: DCMIPP6_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP6, DCMIPP6_HSYNC)
#error Invalid pin assignment for DCMIPP6 HSYNC pin: DCMIPP6_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP6, DCMIPP6_PIXCLK)
#error Invalid pin assignment for DCMIPP6 PIXCLK pin: DCMIPP6_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP6, DCMIPP6_VSYNC)
#error Invalid pin assignment for DCMIPP6 VSYNC pin: DCMIPP6_VSYNC
#endif
#endif

#ifdef USE_DCMIPP7
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP7, DCMIPP7_D0)
#error Invalid pin assignment for DCMIPP7 D0 pin: DCMIPP7_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP7, DCMIPP7_D1)
#error Invalid pin assignment for DCMIPP7 D1 pin: DCMIPP7_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP7, DCMIPP7_D10)
#error Invalid pin assignment for DCMIPP7 D10 pin: DCMIPP7_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP7, DCMIPP7_D11)
#error Invalid pin assignment for DCMIPP7 D11 pin: DCMIPP7_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP7, DCMIPP7_D12)
#error Invalid pin assignment for DCMIPP7 D12 pin: DCMIPP7_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP7, DCMIPP7_D13)
#error Invalid pin assignment for DCMIPP7 D13 pin: DCMIPP7_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP7, DCMIPP7_D14)
#error Invalid pin assignment for DCMIPP7 D14 pin: DCMIPP7_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP7, DCMIPP7_D15)
#error Invalid pin assignment for DCMIPP7 D15 pin: DCMIPP7_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP7, DCMIPP7_D2)
#error Invalid pin assignment for DCMIPP7 D2 pin: DCMIPP7_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP7, DCMIPP7_D3)
#error Invalid pin assignment for DCMIPP7 D3 pin: DCMIPP7_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP7, DCMIPP7_D4)
#error Invalid pin assignment for DCMIPP7 D4 pin: DCMIPP7_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP7, DCMIPP7_D5)
#error Invalid pin assignment for DCMIPP7 D5 pin: DCMIPP7_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP7, DCMIPP7_D6)
#error Invalid pin assignment for DCMIPP7 D6 pin: DCMIPP7_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP7, DCMIPP7_D7)
#error Invalid pin assignment for DCMIPP7 D7 pin: DCMIPP7_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP7, DCMIPP7_D8)
#error Invalid pin assignment for DCMIPP7 D8 pin: DCMIPP7_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP7, DCMIPP7_D9)
#error Invalid pin assignment for DCMIPP7 D9 pin: DCMIPP7_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP7, DCMIPP7_HSYNC)
#error Invalid pin assignment for DCMIPP7 HSYNC pin: DCMIPP7_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP7, DCMIPP7_PIXCLK)
#error Invalid pin assignment for DCMIPP7 PIXCLK pin: DCMIPP7_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP7, DCMIPP7_VSYNC)
#error Invalid pin assignment for DCMIPP7 VSYNC pin: DCMIPP7_VSYNC
#endif
#endif

#ifdef USE_DCMIPP8
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP8, DCMIPP8_D0)
#error Invalid pin assignment for DCMIPP8 D0 pin: DCMIPP8_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP8, DCMIPP8_D1)
#error Invalid pin assignment for DCMIPP8 D1 pin: DCMIPP8_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP8, DCMIPP8_D10)
#error Invalid pin assignment for DCMIPP8 D10 pin: DCMIPP8_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP8, DCMIPP8_D11)
#error Invalid pin assignment for DCMIPP8 D11 pin: DCMIPP8_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP8, DCMIPP8_D12)
#error Invalid pin assignment for DCMIPP8 D12 pin: DCMIPP8_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP8, DCMIPP8_D13)
#error Invalid pin assignment for DCMIPP8 D13 pin: DCMIPP8_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP8, DCMIPP8_D14)
#error Invalid pin assignment for DCMIPP8 D14 pin: DCMIPP8_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP8, DCMIPP8_D15)
#error Invalid pin assignment for DCMIPP8 D15 pin: DCMIPP8_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP8, DCMIPP8_D2)
#error Invalid pin assignment for DCMIPP8 D2 pin: DCMIPP8_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP8, DCMIPP8_D3)
#error Invalid pin assignment for DCMIPP8 D3 pin: DCMIPP8_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP8, DCMIPP8_D4)
#error Invalid pin assignment for DCMIPP8 D4 pin: DCMIPP8_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP8, DCMIPP8_D5)
#error Invalid pin assignment for DCMIPP8 D5 pin: DCMIPP8_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP8, DCMIPP8_D6)
#error Invalid pin assignment for DCMIPP8 D6 pin: DCMIPP8_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP8, DCMIPP8_D7)
#error Invalid pin assignment for DCMIPP8 D7 pin: DCMIPP8_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP8, DCMIPP8_D8)
#error Invalid pin assignment for DCMIPP8 D8 pin: DCMIPP8_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP8, DCMIPP8_D9)
#error Invalid pin assignment for DCMIPP8 D9 pin: DCMIPP8_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP8, DCMIPP8_HSYNC)
#error Invalid pin assignment for DCMIPP8 HSYNC pin: DCMIPP8_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP8, DCMIPP8_PIXCLK)
#error Invalid pin assignment for DCMIPP8 PIXCLK pin: DCMIPP8_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP8, DCMIPP8_VSYNC)
#error Invalid pin assignment for DCMIPP8 VSYNC pin: DCMIPP8_VSYNC
#endif
#endif

#ifdef USE_DCMIPP9
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP9, DCMIPP9_D0)
#error Invalid pin assignment for DCMIPP9 D0 pin: DCMIPP9_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP9, DCMIPP9_D1)
#error Invalid pin assignment for DCMIPP9 D1 pin: DCMIPP9_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP9, DCMIPP9_D10)
#error Invalid pin assignment for DCMIPP9 D10 pin: DCMIPP9_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP9, DCMIPP9_D11)
#error Invalid pin assignment for DCMIPP9 D11 pin: DCMIPP9_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP9, DCMIPP9_D12)
#error Invalid pin assignment for DCMIPP9 D12 pin: DCMIPP9_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP9, DCMIPP9_D13)
#error Invalid pin assignment for DCMIPP9 D13 pin: DCMIPP9_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP9, DCMIPP9_D14)
#error Invalid pin assignment for DCMIPP9 D14 pin: DCMIPP9_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP9, DCMIPP9_D15)
#error Invalid pin assignment for DCMIPP9 D15 pin: DCMIPP9_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP9, DCMIPP9_D2)
#error Invalid pin assignment for DCMIPP9 D2 pin: DCMIPP9_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP9, DCMIPP9_D3)
#error Invalid pin assignment for DCMIPP9 D3 pin: DCMIPP9_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP9, DCMIPP9_D4)
#error Invalid pin assignment for DCMIPP9 D4 pin: DCMIPP9_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP9, DCMIPP9_D5)
#error Invalid pin assignment for DCMIPP9 D5 pin: DCMIPP9_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP9, DCMIPP9_D6)
#error Invalid pin assignment for DCMIPP9 D6 pin: DCMIPP9_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP9, DCMIPP9_D7)
#error Invalid pin assignment for DCMIPP9 D7 pin: DCMIPP9_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP9, DCMIPP9_D8)
#error Invalid pin assignment for DCMIPP9 D8 pin: DCMIPP9_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP9, DCMIPP9_D9)
#error Invalid pin assignment for DCMIPP9 D9 pin: DCMIPP9_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP9, DCMIPP9_HSYNC)
#error Invalid pin assignment for DCMIPP9 HSYNC pin: DCMIPP9_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP9, DCMIPP9_PIXCLK)
#error Invalid pin assignment for DCMIPP9 PIXCLK pin: DCMIPP9_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP9, DCMIPP9_VSYNC)
#error Invalid pin assignment for DCMIPP9 VSYNC pin: DCMIPP9_VSYNC
#endif
#endif

#ifdef USE_DCMIPP10
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP10, DCMIPP10_D0)
#error Invalid pin assignment for DCMIPP10 D0 pin: DCMIPP10_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP10, DCMIPP10_D1)
#error Invalid pin assignment for DCMIPP10 D1 pin: DCMIPP10_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP10, DCMIPP10_D10)
#error Invalid pin assignment for DCMIPP10 D10 pin: DCMIPP10_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP10, DCMIPP10_D11)
#error Invalid pin assignment for DCMIPP10 D11 pin: DCMIPP10_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP10, DCMIPP10_D12)
#error Invalid pin assignment for DCMIPP10 D12 pin: DCMIPP10_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP10, DCMIPP10_D13)
#error Invalid pin assignment for DCMIPP10 D13 pin: DCMIPP10_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP10, DCMIPP10_D14)
#error Invalid pin assignment for DCMIPP10 D14 pin: DCMIPP10_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP10, DCMIPP10_D15)
#error Invalid pin assignment for DCMIPP10 D15 pin: DCMIPP10_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP10, DCMIPP10_D2)
#error Invalid pin assignment for DCMIPP10 D2 pin: DCMIPP10_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP10, DCMIPP10_D3)
#error Invalid pin assignment for DCMIPP10 D3 pin: DCMIPP10_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP10, DCMIPP10_D4)
#error Invalid pin assignment for DCMIPP10 D4 pin: DCMIPP10_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP10, DCMIPP10_D5)
#error Invalid pin assignment for DCMIPP10 D5 pin: DCMIPP10_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP10, DCMIPP10_D6)
#error Invalid pin assignment for DCMIPP10 D6 pin: DCMIPP10_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP10, DCMIPP10_D7)
#error Invalid pin assignment for DCMIPP10 D7 pin: DCMIPP10_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP10, DCMIPP10_D8)
#error Invalid pin assignment for DCMIPP10 D8 pin: DCMIPP10_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP10, DCMIPP10_D9)
#error Invalid pin assignment for DCMIPP10 D9 pin: DCMIPP10_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP10, DCMIPP10_HSYNC)
#error Invalid pin assignment for DCMIPP10 HSYNC pin: DCMIPP10_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP10, DCMIPP10_PIXCLK)
#error Invalid pin assignment for DCMIPP10 PIXCLK pin: DCMIPP10_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP10, DCMIPP10_VSYNC)
#error Invalid pin assignment for DCMIPP10 VSYNC pin: DCMIPP10_VSYNC
#endif
#endif

#ifdef USE_DCMIPP11
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP11, DCMIPP11_D0)
#error Invalid pin assignment for DCMIPP11 D0 pin: DCMIPP11_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP11, DCMIPP11_D1)
#error Invalid pin assignment for DCMIPP11 D1 pin: DCMIPP11_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP11, DCMIPP11_D10)
#error Invalid pin assignment for DCMIPP11 D10 pin: DCMIPP11_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP11, DCMIPP11_D11)
#error Invalid pin assignment for DCMIPP11 D11 pin: DCMIPP11_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP11, DCMIPP11_D12)
#error Invalid pin assignment for DCMIPP11 D12 pin: DCMIPP11_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP11, DCMIPP11_D13)
#error Invalid pin assignment for DCMIPP11 D13 pin: DCMIPP11_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP11, DCMIPP11_D14)
#error Invalid pin assignment for DCMIPP11 D14 pin: DCMIPP11_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP11, DCMIPP11_D15)
#error Invalid pin assignment for DCMIPP11 D15 pin: DCMIPP11_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP11, DCMIPP11_D2)
#error Invalid pin assignment for DCMIPP11 D2 pin: DCMIPP11_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP11, DCMIPP11_D3)
#error Invalid pin assignment for DCMIPP11 D3 pin: DCMIPP11_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP11, DCMIPP11_D4)
#error Invalid pin assignment for DCMIPP11 D4 pin: DCMIPP11_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP11, DCMIPP11_D5)
#error Invalid pin assignment for DCMIPP11 D5 pin: DCMIPP11_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP11, DCMIPP11_D6)
#error Invalid pin assignment for DCMIPP11 D6 pin: DCMIPP11_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP11, DCMIPP11_D7)
#error Invalid pin assignment for DCMIPP11 D7 pin: DCMIPP11_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP11, DCMIPP11_D8)
#error Invalid pin assignment for DCMIPP11 D8 pin: DCMIPP11_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP11, DCMIPP11_D9)
#error Invalid pin assignment for DCMIPP11 D9 pin: DCMIPP11_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP11, DCMIPP11_HSYNC)
#error Invalid pin assignment for DCMIPP11 HSYNC pin: DCMIPP11_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP11, DCMIPP11_PIXCLK)
#error Invalid pin assignment for DCMIPP11 PIXCLK pin: DCMIPP11_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP11, DCMIPP11_VSYNC)
#error Invalid pin assignment for DCMIPP11 VSYNC pin: DCMIPP11_VSYNC
#endif
#endif

#ifdef USE_DCMIPP12
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP12, DCMIPP12_D0)
#error Invalid pin assignment for DCMIPP12 D0 pin: DCMIPP12_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP12, DCMIPP12_D1)
#error Invalid pin assignment for DCMIPP12 D1 pin: DCMIPP12_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP12, DCMIPP12_D10)
#error Invalid pin assignment for DCMIPP12 D10 pin: DCMIPP12_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP12, DCMIPP12_D11)
#error Invalid pin assignment for DCMIPP12 D11 pin: DCMIPP12_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP12, DCMIPP12_D12)
#error Invalid pin assignment for DCMIPP12 D12 pin: DCMIPP12_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP12, DCMIPP12_D13)
#error Invalid pin assignment for DCMIPP12 D13 pin: DCMIPP12_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP12, DCMIPP12_D14)
#error Invalid pin assignment for DCMIPP12 D14 pin: DCMIPP12_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP12, DCMIPP12_D15)
#error Invalid pin assignment for DCMIPP12 D15 pin: DCMIPP12_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP12, DCMIPP12_D2)
#error Invalid pin assignment for DCMIPP12 D2 pin: DCMIPP12_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP12, DCMIPP12_D3)
#error Invalid pin assignment for DCMIPP12 D3 pin: DCMIPP12_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP12, DCMIPP12_D4)
#error Invalid pin assignment for DCMIPP12 D4 pin: DCMIPP12_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP12, DCMIPP12_D5)
#error Invalid pin assignment for DCMIPP12 D5 pin: DCMIPP12_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP12, DCMIPP12_D6)
#error Invalid pin assignment for DCMIPP12 D6 pin: DCMIPP12_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP12, DCMIPP12_D7)
#error Invalid pin assignment for DCMIPP12 D7 pin: DCMIPP12_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP12, DCMIPP12_D8)
#error Invalid pin assignment for DCMIPP12 D8 pin: DCMIPP12_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP12, DCMIPP12_D9)
#error Invalid pin assignment for DCMIPP12 D9 pin: DCMIPP12_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP12, DCMIPP12_HSYNC)
#error Invalid pin assignment for DCMIPP12 HSYNC pin: DCMIPP12_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP12, DCMIPP12_PIXCLK)
#error Invalid pin assignment for DCMIPP12 PIXCLK pin: DCMIPP12_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP12, DCMIPP12_VSYNC)
#error Invalid pin assignment for DCMIPP12 VSYNC pin: DCMIPP12_VSYNC
#endif
#endif

#ifdef USE_DCMIPP13
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP13, DCMIPP13_D0)
#error Invalid pin assignment for DCMIPP13 D0 pin: DCMIPP13_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP13, DCMIPP13_D1)
#error Invalid pin assignment for DCMIPP13 D1 pin: DCMIPP13_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP13, DCMIPP13_D10)
#error Invalid pin assignment for DCMIPP13 D10 pin: DCMIPP13_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP13, DCMIPP13_D11)
#error Invalid pin assignment for DCMIPP13 D11 pin: DCMIPP13_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP13, DCMIPP13_D12)
#error Invalid pin assignment for DCMIPP13 D12 pin: DCMIPP13_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP13, DCMIPP13_D13)
#error Invalid pin assignment for DCMIPP13 D13 pin: DCMIPP13_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP13, DCMIPP13_D14)
#error Invalid pin assignment for DCMIPP13 D14 pin: DCMIPP13_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP13, DCMIPP13_D15)
#error Invalid pin assignment for DCMIPP13 D15 pin: DCMIPP13_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP13, DCMIPP13_D2)
#error Invalid pin assignment for DCMIPP13 D2 pin: DCMIPP13_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP13, DCMIPP13_D3)
#error Invalid pin assignment for DCMIPP13 D3 pin: DCMIPP13_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP13, DCMIPP13_D4)
#error Invalid pin assignment for DCMIPP13 D4 pin: DCMIPP13_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP13, DCMIPP13_D5)
#error Invalid pin assignment for DCMIPP13 D5 pin: DCMIPP13_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP13, DCMIPP13_D6)
#error Invalid pin assignment for DCMIPP13 D6 pin: DCMIPP13_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP13, DCMIPP13_D7)
#error Invalid pin assignment for DCMIPP13 D7 pin: DCMIPP13_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP13, DCMIPP13_D8)
#error Invalid pin assignment for DCMIPP13 D8 pin: DCMIPP13_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP13, DCMIPP13_D9)
#error Invalid pin assignment for DCMIPP13 D9 pin: DCMIPP13_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP13, DCMIPP13_HSYNC)
#error Invalid pin assignment for DCMIPP13 HSYNC pin: DCMIPP13_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP13, DCMIPP13_PIXCLK)
#error Invalid pin assignment for DCMIPP13 PIXCLK pin: DCMIPP13_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP13, DCMIPP13_VSYNC)
#error Invalid pin assignment for DCMIPP13 VSYNC pin: DCMIPP13_VSYNC
#endif
#endif

#ifdef USE_DCMIPP14
#if !FIND_VALUE_DCMIPP_D0(_DCMIPP14, DCMIPP14_D0)
#error Invalid pin assignment for DCMIPP14 D0 pin: DCMIPP14_D0
#endif
#if !FIND_VALUE_DCMIPP_D1(_DCMIPP14, DCMIPP14_D1)
#error Invalid pin assignment for DCMIPP14 D1 pin: DCMIPP14_D1
#endif
#if !FIND_VALUE_DCMIPP_D10(_DCMIPP14, DCMIPP14_D10)
#error Invalid pin assignment for DCMIPP14 D10 pin: DCMIPP14_D10
#endif
#if !FIND_VALUE_DCMIPP_D11(_DCMIPP14, DCMIPP14_D11)
#error Invalid pin assignment for DCMIPP14 D11 pin: DCMIPP14_D11
#endif
#if !FIND_VALUE_DCMIPP_D12(_DCMIPP14, DCMIPP14_D12)
#error Invalid pin assignment for DCMIPP14 D12 pin: DCMIPP14_D12
#endif
#if !FIND_VALUE_DCMIPP_D13(_DCMIPP14, DCMIPP14_D13)
#error Invalid pin assignment for DCMIPP14 D13 pin: DCMIPP14_D13
#endif
#if !FIND_VALUE_DCMIPP_D14(_DCMIPP14, DCMIPP14_D14)
#error Invalid pin assignment for DCMIPP14 D14 pin: DCMIPP14_D14
#endif
#if !FIND_VALUE_DCMIPP_D15(_DCMIPP14, DCMIPP14_D15)
#error Invalid pin assignment for DCMIPP14 D15 pin: DCMIPP14_D15
#endif
#if !FIND_VALUE_DCMIPP_D2(_DCMIPP14, DCMIPP14_D2)
#error Invalid pin assignment for DCMIPP14 D2 pin: DCMIPP14_D2
#endif
#if !FIND_VALUE_DCMIPP_D3(_DCMIPP14, DCMIPP14_D3)
#error Invalid pin assignment for DCMIPP14 D3 pin: DCMIPP14_D3
#endif
#if !FIND_VALUE_DCMIPP_D4(_DCMIPP14, DCMIPP14_D4)
#error Invalid pin assignment for DCMIPP14 D4 pin: DCMIPP14_D4
#endif
#if !FIND_VALUE_DCMIPP_D5(_DCMIPP14, DCMIPP14_D5)
#error Invalid pin assignment for DCMIPP14 D5 pin: DCMIPP14_D5
#endif
#if !FIND_VALUE_DCMIPP_D6(_DCMIPP14, DCMIPP14_D6)
#error Invalid pin assignment for DCMIPP14 D6 pin: DCMIPP14_D6
#endif
#if !FIND_VALUE_DCMIPP_D7(_DCMIPP14, DCMIPP14_D7)
#error Invalid pin assignment for DCMIPP14 D7 pin: DCMIPP14_D7
#endif
#if !FIND_VALUE_DCMIPP_D8(_DCMIPP14, DCMIPP14_D8)
#error Invalid pin assignment for DCMIPP14 D8 pin: DCMIPP14_D8
#endif
#if !FIND_VALUE_DCMIPP_D9(_DCMIPP14, DCMIPP14_D9)
#error Invalid pin assignment for DCMIPP14 D9 pin: DCMIPP14_D9
#endif
#if !FIND_VALUE_DCMIPP_HSYNC(_DCMIPP14, DCMIPP14_HSYNC)
#error Invalid pin assignment for DCMIPP14 HSYNC pin: DCMIPP14_HSYNC
#endif
#if !FIND_VALUE_DCMIPP_PIXCLK(_DCMIPP14, DCMIPP14_PIXCLK)
#error Invalid pin assignment for DCMIPP14 PIXCLK pin: DCMIPP14_PIXCLK
#endif
#if !FIND_VALUE_DCMIPP_VSYNC(_DCMIPP14, DCMIPP14_VSYNC)
#error Invalid pin assignment for DCMIPP14 VSYNC pin: DCMIPP14_VSYNC
#endif
#endif

