/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.401843
 */

#define FIND_VALUE_HRTIM_CHA1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHA1(INDEX,PIN) FIND_VALUE_HRTIM_CHA1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHA2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHA2(INDEX,PIN) FIND_VALUE_HRTIM_CHA2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHB1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHB1(INDEX,PIN) FIND_VALUE_HRTIM_CHB1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHB2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHB2(INDEX,PIN) FIND_VALUE_HRTIM_CHB2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHC1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHC1(INDEX,PIN) FIND_VALUE_HRTIM_CHC1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHC2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHC2(INDEX,PIN) FIND_VALUE_HRTIM_CHC2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHD1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHD1(INDEX,PIN) FIND_VALUE_HRTIM_CHD1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHD2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHD2(INDEX,PIN) FIND_VALUE_HRTIM_CHD2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHE1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHE1(INDEX,PIN) FIND_VALUE_HRTIM_CHE1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHE2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHE2(INDEX,PIN) FIND_VALUE_HRTIM_CHE2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHF1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHF1(INDEX,PIN) FIND_VALUE_HRTIM_CHF1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_CHF2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_CHF2(INDEX,PIN) FIND_VALUE_HRTIM_CHF2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV1(INDEX,PIN) FIND_VALUE_HRTIM_EEV1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV10_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV10(INDEX,PIN) FIND_VALUE_HRTIM_EEV10_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV2(INDEX,PIN) FIND_VALUE_HRTIM_EEV2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV3_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV3(INDEX,PIN) FIND_VALUE_HRTIM_EEV3_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV4_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV4(INDEX,PIN) FIND_VALUE_HRTIM_EEV4_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV5_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV5(INDEX,PIN) FIND_VALUE_HRTIM_EEV5_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV6_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV6(INDEX,PIN) FIND_VALUE_HRTIM_EEV6_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV7_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV7(INDEX,PIN) FIND_VALUE_HRTIM_EEV7_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV8_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV8(INDEX,PIN) FIND_VALUE_HRTIM_EEV8_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_EEV9_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_EEV9(INDEX,PIN) FIND_VALUE_HRTIM_EEV9_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_FLT1_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_FLT1(INDEX,PIN) FIND_VALUE_HRTIM_FLT1_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_FLT2_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_FLT2(INDEX,PIN) FIND_VALUE_HRTIM_FLT2_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_FLT3_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_FLT3(INDEX,PIN) FIND_VALUE_HRTIM_FLT3_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_FLT4_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_FLT4(INDEX,PIN) FIND_VALUE_HRTIM_FLT4_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_FLT5_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_FLT5(INDEX,PIN) FIND_VALUE_HRTIM_FLT5_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_FLT6_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_FLT6(INDEX,PIN) FIND_VALUE_HRTIM_FLT6_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_SCIN_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_SCIN(INDEX,PIN) FIND_VALUE_HRTIM_SCIN_inner(INDEX,PIN)

#define FIND_VALUE_HRTIM_SCOUT_inner(INDEX,PIN) I2C##_HRTIM_##PIN
#define FIND_VALUE_HRTIM_SCOUT(INDEX,PIN) FIND_VALUE_HRTIM_SCOUT_inner(INDEX,PIN)

#ifdef USE_HRTIM0
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM0, HRTIM0_CHA1)
#error Invalid pin assignment for HRTIM0 CHA1 pin: HRTIM0_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM0, HRTIM0_CHA2)
#error Invalid pin assignment for HRTIM0 CHA2 pin: HRTIM0_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM0, HRTIM0_CHB1)
#error Invalid pin assignment for HRTIM0 CHB1 pin: HRTIM0_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM0, HRTIM0_CHB2)
#error Invalid pin assignment for HRTIM0 CHB2 pin: HRTIM0_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM0, HRTIM0_CHC1)
#error Invalid pin assignment for HRTIM0 CHC1 pin: HRTIM0_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM0, HRTIM0_CHC2)
#error Invalid pin assignment for HRTIM0 CHC2 pin: HRTIM0_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM0, HRTIM0_CHD1)
#error Invalid pin assignment for HRTIM0 CHD1 pin: HRTIM0_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM0, HRTIM0_CHD2)
#error Invalid pin assignment for HRTIM0 CHD2 pin: HRTIM0_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM0, HRTIM0_CHE1)
#error Invalid pin assignment for HRTIM0 CHE1 pin: HRTIM0_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM0, HRTIM0_CHE2)
#error Invalid pin assignment for HRTIM0 CHE2 pin: HRTIM0_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM0, HRTIM0_CHF1)
#error Invalid pin assignment for HRTIM0 CHF1 pin: HRTIM0_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM0, HRTIM0_CHF2)
#error Invalid pin assignment for HRTIM0 CHF2 pin: HRTIM0_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM0, HRTIM0_EEV1)
#error Invalid pin assignment for HRTIM0 EEV1 pin: HRTIM0_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM0, HRTIM0_EEV10)
#error Invalid pin assignment for HRTIM0 EEV10 pin: HRTIM0_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM0, HRTIM0_EEV2)
#error Invalid pin assignment for HRTIM0 EEV2 pin: HRTIM0_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM0, HRTIM0_EEV3)
#error Invalid pin assignment for HRTIM0 EEV3 pin: HRTIM0_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM0, HRTIM0_EEV4)
#error Invalid pin assignment for HRTIM0 EEV4 pin: HRTIM0_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM0, HRTIM0_EEV5)
#error Invalid pin assignment for HRTIM0 EEV5 pin: HRTIM0_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM0, HRTIM0_EEV6)
#error Invalid pin assignment for HRTIM0 EEV6 pin: HRTIM0_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM0, HRTIM0_EEV7)
#error Invalid pin assignment for HRTIM0 EEV7 pin: HRTIM0_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM0, HRTIM0_EEV8)
#error Invalid pin assignment for HRTIM0 EEV8 pin: HRTIM0_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM0, HRTIM0_EEV9)
#error Invalid pin assignment for HRTIM0 EEV9 pin: HRTIM0_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM0, HRTIM0_FLT1)
#error Invalid pin assignment for HRTIM0 FLT1 pin: HRTIM0_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM0, HRTIM0_FLT2)
#error Invalid pin assignment for HRTIM0 FLT2 pin: HRTIM0_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM0, HRTIM0_FLT3)
#error Invalid pin assignment for HRTIM0 FLT3 pin: HRTIM0_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM0, HRTIM0_FLT4)
#error Invalid pin assignment for HRTIM0 FLT4 pin: HRTIM0_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM0, HRTIM0_FLT5)
#error Invalid pin assignment for HRTIM0 FLT5 pin: HRTIM0_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM0, HRTIM0_FLT6)
#error Invalid pin assignment for HRTIM0 FLT6 pin: HRTIM0_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM0, HRTIM0_SCIN)
#error Invalid pin assignment for HRTIM0 SCIN pin: HRTIM0_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM0, HRTIM0_SCOUT)
#error Invalid pin assignment for HRTIM0 SCOUT pin: HRTIM0_SCOUT
#endif
#endif

#ifdef USE_HRTIM1
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM1, HRTIM1_CHA1)
#error Invalid pin assignment for HRTIM1 CHA1 pin: HRTIM1_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM1, HRTIM1_CHA2)
#error Invalid pin assignment for HRTIM1 CHA2 pin: HRTIM1_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM1, HRTIM1_CHB1)
#error Invalid pin assignment for HRTIM1 CHB1 pin: HRTIM1_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM1, HRTIM1_CHB2)
#error Invalid pin assignment for HRTIM1 CHB2 pin: HRTIM1_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM1, HRTIM1_CHC1)
#error Invalid pin assignment for HRTIM1 CHC1 pin: HRTIM1_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM1, HRTIM1_CHC2)
#error Invalid pin assignment for HRTIM1 CHC2 pin: HRTIM1_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM1, HRTIM1_CHD1)
#error Invalid pin assignment for HRTIM1 CHD1 pin: HRTIM1_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM1, HRTIM1_CHD2)
#error Invalid pin assignment for HRTIM1 CHD2 pin: HRTIM1_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM1, HRTIM1_CHE1)
#error Invalid pin assignment for HRTIM1 CHE1 pin: HRTIM1_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM1, HRTIM1_CHE2)
#error Invalid pin assignment for HRTIM1 CHE2 pin: HRTIM1_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM1, HRTIM1_CHF1)
#error Invalid pin assignment for HRTIM1 CHF1 pin: HRTIM1_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM1, HRTIM1_CHF2)
#error Invalid pin assignment for HRTIM1 CHF2 pin: HRTIM1_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM1, HRTIM1_EEV1)
#error Invalid pin assignment for HRTIM1 EEV1 pin: HRTIM1_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM1, HRTIM1_EEV10)
#error Invalid pin assignment for HRTIM1 EEV10 pin: HRTIM1_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM1, HRTIM1_EEV2)
#error Invalid pin assignment for HRTIM1 EEV2 pin: HRTIM1_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM1, HRTIM1_EEV3)
#error Invalid pin assignment for HRTIM1 EEV3 pin: HRTIM1_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM1, HRTIM1_EEV4)
#error Invalid pin assignment for HRTIM1 EEV4 pin: HRTIM1_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM1, HRTIM1_EEV5)
#error Invalid pin assignment for HRTIM1 EEV5 pin: HRTIM1_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM1, HRTIM1_EEV6)
#error Invalid pin assignment for HRTIM1 EEV6 pin: HRTIM1_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM1, HRTIM1_EEV7)
#error Invalid pin assignment for HRTIM1 EEV7 pin: HRTIM1_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM1, HRTIM1_EEV8)
#error Invalid pin assignment for HRTIM1 EEV8 pin: HRTIM1_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM1, HRTIM1_EEV9)
#error Invalid pin assignment for HRTIM1 EEV9 pin: HRTIM1_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM1, HRTIM1_FLT1)
#error Invalid pin assignment for HRTIM1 FLT1 pin: HRTIM1_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM1, HRTIM1_FLT2)
#error Invalid pin assignment for HRTIM1 FLT2 pin: HRTIM1_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM1, HRTIM1_FLT3)
#error Invalid pin assignment for HRTIM1 FLT3 pin: HRTIM1_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM1, HRTIM1_FLT4)
#error Invalid pin assignment for HRTIM1 FLT4 pin: HRTIM1_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM1, HRTIM1_FLT5)
#error Invalid pin assignment for HRTIM1 FLT5 pin: HRTIM1_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM1, HRTIM1_FLT6)
#error Invalid pin assignment for HRTIM1 FLT6 pin: HRTIM1_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM1, HRTIM1_SCIN)
#error Invalid pin assignment for HRTIM1 SCIN pin: HRTIM1_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM1, HRTIM1_SCOUT)
#error Invalid pin assignment for HRTIM1 SCOUT pin: HRTIM1_SCOUT
#endif
#endif

#ifdef USE_HRTIM2
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM2, HRTIM2_CHA1)
#error Invalid pin assignment for HRTIM2 CHA1 pin: HRTIM2_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM2, HRTIM2_CHA2)
#error Invalid pin assignment for HRTIM2 CHA2 pin: HRTIM2_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM2, HRTIM2_CHB1)
#error Invalid pin assignment for HRTIM2 CHB1 pin: HRTIM2_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM2, HRTIM2_CHB2)
#error Invalid pin assignment for HRTIM2 CHB2 pin: HRTIM2_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM2, HRTIM2_CHC1)
#error Invalid pin assignment for HRTIM2 CHC1 pin: HRTIM2_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM2, HRTIM2_CHC2)
#error Invalid pin assignment for HRTIM2 CHC2 pin: HRTIM2_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM2, HRTIM2_CHD1)
#error Invalid pin assignment for HRTIM2 CHD1 pin: HRTIM2_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM2, HRTIM2_CHD2)
#error Invalid pin assignment for HRTIM2 CHD2 pin: HRTIM2_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM2, HRTIM2_CHE1)
#error Invalid pin assignment for HRTIM2 CHE1 pin: HRTIM2_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM2, HRTIM2_CHE2)
#error Invalid pin assignment for HRTIM2 CHE2 pin: HRTIM2_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM2, HRTIM2_CHF1)
#error Invalid pin assignment for HRTIM2 CHF1 pin: HRTIM2_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM2, HRTIM2_CHF2)
#error Invalid pin assignment for HRTIM2 CHF2 pin: HRTIM2_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM2, HRTIM2_EEV1)
#error Invalid pin assignment for HRTIM2 EEV1 pin: HRTIM2_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM2, HRTIM2_EEV10)
#error Invalid pin assignment for HRTIM2 EEV10 pin: HRTIM2_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM2, HRTIM2_EEV2)
#error Invalid pin assignment for HRTIM2 EEV2 pin: HRTIM2_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM2, HRTIM2_EEV3)
#error Invalid pin assignment for HRTIM2 EEV3 pin: HRTIM2_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM2, HRTIM2_EEV4)
#error Invalid pin assignment for HRTIM2 EEV4 pin: HRTIM2_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM2, HRTIM2_EEV5)
#error Invalid pin assignment for HRTIM2 EEV5 pin: HRTIM2_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM2, HRTIM2_EEV6)
#error Invalid pin assignment for HRTIM2 EEV6 pin: HRTIM2_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM2, HRTIM2_EEV7)
#error Invalid pin assignment for HRTIM2 EEV7 pin: HRTIM2_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM2, HRTIM2_EEV8)
#error Invalid pin assignment for HRTIM2 EEV8 pin: HRTIM2_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM2, HRTIM2_EEV9)
#error Invalid pin assignment for HRTIM2 EEV9 pin: HRTIM2_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM2, HRTIM2_FLT1)
#error Invalid pin assignment for HRTIM2 FLT1 pin: HRTIM2_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM2, HRTIM2_FLT2)
#error Invalid pin assignment for HRTIM2 FLT2 pin: HRTIM2_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM2, HRTIM2_FLT3)
#error Invalid pin assignment for HRTIM2 FLT3 pin: HRTIM2_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM2, HRTIM2_FLT4)
#error Invalid pin assignment for HRTIM2 FLT4 pin: HRTIM2_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM2, HRTIM2_FLT5)
#error Invalid pin assignment for HRTIM2 FLT5 pin: HRTIM2_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM2, HRTIM2_FLT6)
#error Invalid pin assignment for HRTIM2 FLT6 pin: HRTIM2_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM2, HRTIM2_SCIN)
#error Invalid pin assignment for HRTIM2 SCIN pin: HRTIM2_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM2, HRTIM2_SCOUT)
#error Invalid pin assignment for HRTIM2 SCOUT pin: HRTIM2_SCOUT
#endif
#endif

#ifdef USE_HRTIM3
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM3, HRTIM3_CHA1)
#error Invalid pin assignment for HRTIM3 CHA1 pin: HRTIM3_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM3, HRTIM3_CHA2)
#error Invalid pin assignment for HRTIM3 CHA2 pin: HRTIM3_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM3, HRTIM3_CHB1)
#error Invalid pin assignment for HRTIM3 CHB1 pin: HRTIM3_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM3, HRTIM3_CHB2)
#error Invalid pin assignment for HRTIM3 CHB2 pin: HRTIM3_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM3, HRTIM3_CHC1)
#error Invalid pin assignment for HRTIM3 CHC1 pin: HRTIM3_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM3, HRTIM3_CHC2)
#error Invalid pin assignment for HRTIM3 CHC2 pin: HRTIM3_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM3, HRTIM3_CHD1)
#error Invalid pin assignment for HRTIM3 CHD1 pin: HRTIM3_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM3, HRTIM3_CHD2)
#error Invalid pin assignment for HRTIM3 CHD2 pin: HRTIM3_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM3, HRTIM3_CHE1)
#error Invalid pin assignment for HRTIM3 CHE1 pin: HRTIM3_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM3, HRTIM3_CHE2)
#error Invalid pin assignment for HRTIM3 CHE2 pin: HRTIM3_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM3, HRTIM3_CHF1)
#error Invalid pin assignment for HRTIM3 CHF1 pin: HRTIM3_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM3, HRTIM3_CHF2)
#error Invalid pin assignment for HRTIM3 CHF2 pin: HRTIM3_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM3, HRTIM3_EEV1)
#error Invalid pin assignment for HRTIM3 EEV1 pin: HRTIM3_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM3, HRTIM3_EEV10)
#error Invalid pin assignment for HRTIM3 EEV10 pin: HRTIM3_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM3, HRTIM3_EEV2)
#error Invalid pin assignment for HRTIM3 EEV2 pin: HRTIM3_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM3, HRTIM3_EEV3)
#error Invalid pin assignment for HRTIM3 EEV3 pin: HRTIM3_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM3, HRTIM3_EEV4)
#error Invalid pin assignment for HRTIM3 EEV4 pin: HRTIM3_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM3, HRTIM3_EEV5)
#error Invalid pin assignment for HRTIM3 EEV5 pin: HRTIM3_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM3, HRTIM3_EEV6)
#error Invalid pin assignment for HRTIM3 EEV6 pin: HRTIM3_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM3, HRTIM3_EEV7)
#error Invalid pin assignment for HRTIM3 EEV7 pin: HRTIM3_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM3, HRTIM3_EEV8)
#error Invalid pin assignment for HRTIM3 EEV8 pin: HRTIM3_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM3, HRTIM3_EEV9)
#error Invalid pin assignment for HRTIM3 EEV9 pin: HRTIM3_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM3, HRTIM3_FLT1)
#error Invalid pin assignment for HRTIM3 FLT1 pin: HRTIM3_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM3, HRTIM3_FLT2)
#error Invalid pin assignment for HRTIM3 FLT2 pin: HRTIM3_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM3, HRTIM3_FLT3)
#error Invalid pin assignment for HRTIM3 FLT3 pin: HRTIM3_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM3, HRTIM3_FLT4)
#error Invalid pin assignment for HRTIM3 FLT4 pin: HRTIM3_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM3, HRTIM3_FLT5)
#error Invalid pin assignment for HRTIM3 FLT5 pin: HRTIM3_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM3, HRTIM3_FLT6)
#error Invalid pin assignment for HRTIM3 FLT6 pin: HRTIM3_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM3, HRTIM3_SCIN)
#error Invalid pin assignment for HRTIM3 SCIN pin: HRTIM3_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM3, HRTIM3_SCOUT)
#error Invalid pin assignment for HRTIM3 SCOUT pin: HRTIM3_SCOUT
#endif
#endif

#ifdef USE_HRTIM4
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM4, HRTIM4_CHA1)
#error Invalid pin assignment for HRTIM4 CHA1 pin: HRTIM4_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM4, HRTIM4_CHA2)
#error Invalid pin assignment for HRTIM4 CHA2 pin: HRTIM4_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM4, HRTIM4_CHB1)
#error Invalid pin assignment for HRTIM4 CHB1 pin: HRTIM4_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM4, HRTIM4_CHB2)
#error Invalid pin assignment for HRTIM4 CHB2 pin: HRTIM4_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM4, HRTIM4_CHC1)
#error Invalid pin assignment for HRTIM4 CHC1 pin: HRTIM4_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM4, HRTIM4_CHC2)
#error Invalid pin assignment for HRTIM4 CHC2 pin: HRTIM4_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM4, HRTIM4_CHD1)
#error Invalid pin assignment for HRTIM4 CHD1 pin: HRTIM4_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM4, HRTIM4_CHD2)
#error Invalid pin assignment for HRTIM4 CHD2 pin: HRTIM4_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM4, HRTIM4_CHE1)
#error Invalid pin assignment for HRTIM4 CHE1 pin: HRTIM4_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM4, HRTIM4_CHE2)
#error Invalid pin assignment for HRTIM4 CHE2 pin: HRTIM4_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM4, HRTIM4_CHF1)
#error Invalid pin assignment for HRTIM4 CHF1 pin: HRTIM4_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM4, HRTIM4_CHF2)
#error Invalid pin assignment for HRTIM4 CHF2 pin: HRTIM4_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM4, HRTIM4_EEV1)
#error Invalid pin assignment for HRTIM4 EEV1 pin: HRTIM4_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM4, HRTIM4_EEV10)
#error Invalid pin assignment for HRTIM4 EEV10 pin: HRTIM4_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM4, HRTIM4_EEV2)
#error Invalid pin assignment for HRTIM4 EEV2 pin: HRTIM4_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM4, HRTIM4_EEV3)
#error Invalid pin assignment for HRTIM4 EEV3 pin: HRTIM4_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM4, HRTIM4_EEV4)
#error Invalid pin assignment for HRTIM4 EEV4 pin: HRTIM4_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM4, HRTIM4_EEV5)
#error Invalid pin assignment for HRTIM4 EEV5 pin: HRTIM4_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM4, HRTIM4_EEV6)
#error Invalid pin assignment for HRTIM4 EEV6 pin: HRTIM4_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM4, HRTIM4_EEV7)
#error Invalid pin assignment for HRTIM4 EEV7 pin: HRTIM4_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM4, HRTIM4_EEV8)
#error Invalid pin assignment for HRTIM4 EEV8 pin: HRTIM4_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM4, HRTIM4_EEV9)
#error Invalid pin assignment for HRTIM4 EEV9 pin: HRTIM4_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM4, HRTIM4_FLT1)
#error Invalid pin assignment for HRTIM4 FLT1 pin: HRTIM4_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM4, HRTIM4_FLT2)
#error Invalid pin assignment for HRTIM4 FLT2 pin: HRTIM4_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM4, HRTIM4_FLT3)
#error Invalid pin assignment for HRTIM4 FLT3 pin: HRTIM4_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM4, HRTIM4_FLT4)
#error Invalid pin assignment for HRTIM4 FLT4 pin: HRTIM4_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM4, HRTIM4_FLT5)
#error Invalid pin assignment for HRTIM4 FLT5 pin: HRTIM4_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM4, HRTIM4_FLT6)
#error Invalid pin assignment for HRTIM4 FLT6 pin: HRTIM4_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM4, HRTIM4_SCIN)
#error Invalid pin assignment for HRTIM4 SCIN pin: HRTIM4_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM4, HRTIM4_SCOUT)
#error Invalid pin assignment for HRTIM4 SCOUT pin: HRTIM4_SCOUT
#endif
#endif

#ifdef USE_HRTIM5
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM5, HRTIM5_CHA1)
#error Invalid pin assignment for HRTIM5 CHA1 pin: HRTIM5_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM5, HRTIM5_CHA2)
#error Invalid pin assignment for HRTIM5 CHA2 pin: HRTIM5_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM5, HRTIM5_CHB1)
#error Invalid pin assignment for HRTIM5 CHB1 pin: HRTIM5_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM5, HRTIM5_CHB2)
#error Invalid pin assignment for HRTIM5 CHB2 pin: HRTIM5_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM5, HRTIM5_CHC1)
#error Invalid pin assignment for HRTIM5 CHC1 pin: HRTIM5_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM5, HRTIM5_CHC2)
#error Invalid pin assignment for HRTIM5 CHC2 pin: HRTIM5_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM5, HRTIM5_CHD1)
#error Invalid pin assignment for HRTIM5 CHD1 pin: HRTIM5_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM5, HRTIM5_CHD2)
#error Invalid pin assignment for HRTIM5 CHD2 pin: HRTIM5_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM5, HRTIM5_CHE1)
#error Invalid pin assignment for HRTIM5 CHE1 pin: HRTIM5_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM5, HRTIM5_CHE2)
#error Invalid pin assignment for HRTIM5 CHE2 pin: HRTIM5_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM5, HRTIM5_CHF1)
#error Invalid pin assignment for HRTIM5 CHF1 pin: HRTIM5_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM5, HRTIM5_CHF2)
#error Invalid pin assignment for HRTIM5 CHF2 pin: HRTIM5_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM5, HRTIM5_EEV1)
#error Invalid pin assignment for HRTIM5 EEV1 pin: HRTIM5_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM5, HRTIM5_EEV10)
#error Invalid pin assignment for HRTIM5 EEV10 pin: HRTIM5_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM5, HRTIM5_EEV2)
#error Invalid pin assignment for HRTIM5 EEV2 pin: HRTIM5_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM5, HRTIM5_EEV3)
#error Invalid pin assignment for HRTIM5 EEV3 pin: HRTIM5_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM5, HRTIM5_EEV4)
#error Invalid pin assignment for HRTIM5 EEV4 pin: HRTIM5_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM5, HRTIM5_EEV5)
#error Invalid pin assignment for HRTIM5 EEV5 pin: HRTIM5_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM5, HRTIM5_EEV6)
#error Invalid pin assignment for HRTIM5 EEV6 pin: HRTIM5_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM5, HRTIM5_EEV7)
#error Invalid pin assignment for HRTIM5 EEV7 pin: HRTIM5_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM5, HRTIM5_EEV8)
#error Invalid pin assignment for HRTIM5 EEV8 pin: HRTIM5_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM5, HRTIM5_EEV9)
#error Invalid pin assignment for HRTIM5 EEV9 pin: HRTIM5_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM5, HRTIM5_FLT1)
#error Invalid pin assignment for HRTIM5 FLT1 pin: HRTIM5_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM5, HRTIM5_FLT2)
#error Invalid pin assignment for HRTIM5 FLT2 pin: HRTIM5_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM5, HRTIM5_FLT3)
#error Invalid pin assignment for HRTIM5 FLT3 pin: HRTIM5_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM5, HRTIM5_FLT4)
#error Invalid pin assignment for HRTIM5 FLT4 pin: HRTIM5_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM5, HRTIM5_FLT5)
#error Invalid pin assignment for HRTIM5 FLT5 pin: HRTIM5_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM5, HRTIM5_FLT6)
#error Invalid pin assignment for HRTIM5 FLT6 pin: HRTIM5_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM5, HRTIM5_SCIN)
#error Invalid pin assignment for HRTIM5 SCIN pin: HRTIM5_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM5, HRTIM5_SCOUT)
#error Invalid pin assignment for HRTIM5 SCOUT pin: HRTIM5_SCOUT
#endif
#endif

#ifdef USE_HRTIM6
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM6, HRTIM6_CHA1)
#error Invalid pin assignment for HRTIM6 CHA1 pin: HRTIM6_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM6, HRTIM6_CHA2)
#error Invalid pin assignment for HRTIM6 CHA2 pin: HRTIM6_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM6, HRTIM6_CHB1)
#error Invalid pin assignment for HRTIM6 CHB1 pin: HRTIM6_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM6, HRTIM6_CHB2)
#error Invalid pin assignment for HRTIM6 CHB2 pin: HRTIM6_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM6, HRTIM6_CHC1)
#error Invalid pin assignment for HRTIM6 CHC1 pin: HRTIM6_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM6, HRTIM6_CHC2)
#error Invalid pin assignment for HRTIM6 CHC2 pin: HRTIM6_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM6, HRTIM6_CHD1)
#error Invalid pin assignment for HRTIM6 CHD1 pin: HRTIM6_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM6, HRTIM6_CHD2)
#error Invalid pin assignment for HRTIM6 CHD2 pin: HRTIM6_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM6, HRTIM6_CHE1)
#error Invalid pin assignment for HRTIM6 CHE1 pin: HRTIM6_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM6, HRTIM6_CHE2)
#error Invalid pin assignment for HRTIM6 CHE2 pin: HRTIM6_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM6, HRTIM6_CHF1)
#error Invalid pin assignment for HRTIM6 CHF1 pin: HRTIM6_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM6, HRTIM6_CHF2)
#error Invalid pin assignment for HRTIM6 CHF2 pin: HRTIM6_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM6, HRTIM6_EEV1)
#error Invalid pin assignment for HRTIM6 EEV1 pin: HRTIM6_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM6, HRTIM6_EEV10)
#error Invalid pin assignment for HRTIM6 EEV10 pin: HRTIM6_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM6, HRTIM6_EEV2)
#error Invalid pin assignment for HRTIM6 EEV2 pin: HRTIM6_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM6, HRTIM6_EEV3)
#error Invalid pin assignment for HRTIM6 EEV3 pin: HRTIM6_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM6, HRTIM6_EEV4)
#error Invalid pin assignment for HRTIM6 EEV4 pin: HRTIM6_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM6, HRTIM6_EEV5)
#error Invalid pin assignment for HRTIM6 EEV5 pin: HRTIM6_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM6, HRTIM6_EEV6)
#error Invalid pin assignment for HRTIM6 EEV6 pin: HRTIM6_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM6, HRTIM6_EEV7)
#error Invalid pin assignment for HRTIM6 EEV7 pin: HRTIM6_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM6, HRTIM6_EEV8)
#error Invalid pin assignment for HRTIM6 EEV8 pin: HRTIM6_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM6, HRTIM6_EEV9)
#error Invalid pin assignment for HRTIM6 EEV9 pin: HRTIM6_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM6, HRTIM6_FLT1)
#error Invalid pin assignment for HRTIM6 FLT1 pin: HRTIM6_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM6, HRTIM6_FLT2)
#error Invalid pin assignment for HRTIM6 FLT2 pin: HRTIM6_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM6, HRTIM6_FLT3)
#error Invalid pin assignment for HRTIM6 FLT3 pin: HRTIM6_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM6, HRTIM6_FLT4)
#error Invalid pin assignment for HRTIM6 FLT4 pin: HRTIM6_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM6, HRTIM6_FLT5)
#error Invalid pin assignment for HRTIM6 FLT5 pin: HRTIM6_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM6, HRTIM6_FLT6)
#error Invalid pin assignment for HRTIM6 FLT6 pin: HRTIM6_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM6, HRTIM6_SCIN)
#error Invalid pin assignment for HRTIM6 SCIN pin: HRTIM6_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM6, HRTIM6_SCOUT)
#error Invalid pin assignment for HRTIM6 SCOUT pin: HRTIM6_SCOUT
#endif
#endif

#ifdef USE_HRTIM7
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM7, HRTIM7_CHA1)
#error Invalid pin assignment for HRTIM7 CHA1 pin: HRTIM7_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM7, HRTIM7_CHA2)
#error Invalid pin assignment for HRTIM7 CHA2 pin: HRTIM7_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM7, HRTIM7_CHB1)
#error Invalid pin assignment for HRTIM7 CHB1 pin: HRTIM7_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM7, HRTIM7_CHB2)
#error Invalid pin assignment for HRTIM7 CHB2 pin: HRTIM7_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM7, HRTIM7_CHC1)
#error Invalid pin assignment for HRTIM7 CHC1 pin: HRTIM7_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM7, HRTIM7_CHC2)
#error Invalid pin assignment for HRTIM7 CHC2 pin: HRTIM7_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM7, HRTIM7_CHD1)
#error Invalid pin assignment for HRTIM7 CHD1 pin: HRTIM7_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM7, HRTIM7_CHD2)
#error Invalid pin assignment for HRTIM7 CHD2 pin: HRTIM7_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM7, HRTIM7_CHE1)
#error Invalid pin assignment for HRTIM7 CHE1 pin: HRTIM7_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM7, HRTIM7_CHE2)
#error Invalid pin assignment for HRTIM7 CHE2 pin: HRTIM7_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM7, HRTIM7_CHF1)
#error Invalid pin assignment for HRTIM7 CHF1 pin: HRTIM7_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM7, HRTIM7_CHF2)
#error Invalid pin assignment for HRTIM7 CHF2 pin: HRTIM7_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM7, HRTIM7_EEV1)
#error Invalid pin assignment for HRTIM7 EEV1 pin: HRTIM7_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM7, HRTIM7_EEV10)
#error Invalid pin assignment for HRTIM7 EEV10 pin: HRTIM7_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM7, HRTIM7_EEV2)
#error Invalid pin assignment for HRTIM7 EEV2 pin: HRTIM7_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM7, HRTIM7_EEV3)
#error Invalid pin assignment for HRTIM7 EEV3 pin: HRTIM7_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM7, HRTIM7_EEV4)
#error Invalid pin assignment for HRTIM7 EEV4 pin: HRTIM7_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM7, HRTIM7_EEV5)
#error Invalid pin assignment for HRTIM7 EEV5 pin: HRTIM7_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM7, HRTIM7_EEV6)
#error Invalid pin assignment for HRTIM7 EEV6 pin: HRTIM7_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM7, HRTIM7_EEV7)
#error Invalid pin assignment for HRTIM7 EEV7 pin: HRTIM7_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM7, HRTIM7_EEV8)
#error Invalid pin assignment for HRTIM7 EEV8 pin: HRTIM7_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM7, HRTIM7_EEV9)
#error Invalid pin assignment for HRTIM7 EEV9 pin: HRTIM7_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM7, HRTIM7_FLT1)
#error Invalid pin assignment for HRTIM7 FLT1 pin: HRTIM7_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM7, HRTIM7_FLT2)
#error Invalid pin assignment for HRTIM7 FLT2 pin: HRTIM7_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM7, HRTIM7_FLT3)
#error Invalid pin assignment for HRTIM7 FLT3 pin: HRTIM7_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM7, HRTIM7_FLT4)
#error Invalid pin assignment for HRTIM7 FLT4 pin: HRTIM7_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM7, HRTIM7_FLT5)
#error Invalid pin assignment for HRTIM7 FLT5 pin: HRTIM7_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM7, HRTIM7_FLT6)
#error Invalid pin assignment for HRTIM7 FLT6 pin: HRTIM7_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM7, HRTIM7_SCIN)
#error Invalid pin assignment for HRTIM7 SCIN pin: HRTIM7_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM7, HRTIM7_SCOUT)
#error Invalid pin assignment for HRTIM7 SCOUT pin: HRTIM7_SCOUT
#endif
#endif

#ifdef USE_HRTIM8
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM8, HRTIM8_CHA1)
#error Invalid pin assignment for HRTIM8 CHA1 pin: HRTIM8_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM8, HRTIM8_CHA2)
#error Invalid pin assignment for HRTIM8 CHA2 pin: HRTIM8_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM8, HRTIM8_CHB1)
#error Invalid pin assignment for HRTIM8 CHB1 pin: HRTIM8_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM8, HRTIM8_CHB2)
#error Invalid pin assignment for HRTIM8 CHB2 pin: HRTIM8_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM8, HRTIM8_CHC1)
#error Invalid pin assignment for HRTIM8 CHC1 pin: HRTIM8_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM8, HRTIM8_CHC2)
#error Invalid pin assignment for HRTIM8 CHC2 pin: HRTIM8_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM8, HRTIM8_CHD1)
#error Invalid pin assignment for HRTIM8 CHD1 pin: HRTIM8_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM8, HRTIM8_CHD2)
#error Invalid pin assignment for HRTIM8 CHD2 pin: HRTIM8_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM8, HRTIM8_CHE1)
#error Invalid pin assignment for HRTIM8 CHE1 pin: HRTIM8_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM8, HRTIM8_CHE2)
#error Invalid pin assignment for HRTIM8 CHE2 pin: HRTIM8_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM8, HRTIM8_CHF1)
#error Invalid pin assignment for HRTIM8 CHF1 pin: HRTIM8_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM8, HRTIM8_CHF2)
#error Invalid pin assignment for HRTIM8 CHF2 pin: HRTIM8_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM8, HRTIM8_EEV1)
#error Invalid pin assignment for HRTIM8 EEV1 pin: HRTIM8_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM8, HRTIM8_EEV10)
#error Invalid pin assignment for HRTIM8 EEV10 pin: HRTIM8_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM8, HRTIM8_EEV2)
#error Invalid pin assignment for HRTIM8 EEV2 pin: HRTIM8_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM8, HRTIM8_EEV3)
#error Invalid pin assignment for HRTIM8 EEV3 pin: HRTIM8_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM8, HRTIM8_EEV4)
#error Invalid pin assignment for HRTIM8 EEV4 pin: HRTIM8_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM8, HRTIM8_EEV5)
#error Invalid pin assignment for HRTIM8 EEV5 pin: HRTIM8_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM8, HRTIM8_EEV6)
#error Invalid pin assignment for HRTIM8 EEV6 pin: HRTIM8_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM8, HRTIM8_EEV7)
#error Invalid pin assignment for HRTIM8 EEV7 pin: HRTIM8_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM8, HRTIM8_EEV8)
#error Invalid pin assignment for HRTIM8 EEV8 pin: HRTIM8_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM8, HRTIM8_EEV9)
#error Invalid pin assignment for HRTIM8 EEV9 pin: HRTIM8_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM8, HRTIM8_FLT1)
#error Invalid pin assignment for HRTIM8 FLT1 pin: HRTIM8_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM8, HRTIM8_FLT2)
#error Invalid pin assignment for HRTIM8 FLT2 pin: HRTIM8_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM8, HRTIM8_FLT3)
#error Invalid pin assignment for HRTIM8 FLT3 pin: HRTIM8_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM8, HRTIM8_FLT4)
#error Invalid pin assignment for HRTIM8 FLT4 pin: HRTIM8_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM8, HRTIM8_FLT5)
#error Invalid pin assignment for HRTIM8 FLT5 pin: HRTIM8_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM8, HRTIM8_FLT6)
#error Invalid pin assignment for HRTIM8 FLT6 pin: HRTIM8_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM8, HRTIM8_SCIN)
#error Invalid pin assignment for HRTIM8 SCIN pin: HRTIM8_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM8, HRTIM8_SCOUT)
#error Invalid pin assignment for HRTIM8 SCOUT pin: HRTIM8_SCOUT
#endif
#endif

#ifdef USE_HRTIM9
#if !FIND_VALUE_HRTIM_CHA1(_HRTIM9, HRTIM9_CHA1)
#error Invalid pin assignment for HRTIM9 CHA1 pin: HRTIM9_CHA1
#endif
#if !FIND_VALUE_HRTIM_CHA2(_HRTIM9, HRTIM9_CHA2)
#error Invalid pin assignment for HRTIM9 CHA2 pin: HRTIM9_CHA2
#endif
#if !FIND_VALUE_HRTIM_CHB1(_HRTIM9, HRTIM9_CHB1)
#error Invalid pin assignment for HRTIM9 CHB1 pin: HRTIM9_CHB1
#endif
#if !FIND_VALUE_HRTIM_CHB2(_HRTIM9, HRTIM9_CHB2)
#error Invalid pin assignment for HRTIM9 CHB2 pin: HRTIM9_CHB2
#endif
#if !FIND_VALUE_HRTIM_CHC1(_HRTIM9, HRTIM9_CHC1)
#error Invalid pin assignment for HRTIM9 CHC1 pin: HRTIM9_CHC1
#endif
#if !FIND_VALUE_HRTIM_CHC2(_HRTIM9, HRTIM9_CHC2)
#error Invalid pin assignment for HRTIM9 CHC2 pin: HRTIM9_CHC2
#endif
#if !FIND_VALUE_HRTIM_CHD1(_HRTIM9, HRTIM9_CHD1)
#error Invalid pin assignment for HRTIM9 CHD1 pin: HRTIM9_CHD1
#endif
#if !FIND_VALUE_HRTIM_CHD2(_HRTIM9, HRTIM9_CHD2)
#error Invalid pin assignment for HRTIM9 CHD2 pin: HRTIM9_CHD2
#endif
#if !FIND_VALUE_HRTIM_CHE1(_HRTIM9, HRTIM9_CHE1)
#error Invalid pin assignment for HRTIM9 CHE1 pin: HRTIM9_CHE1
#endif
#if !FIND_VALUE_HRTIM_CHE2(_HRTIM9, HRTIM9_CHE2)
#error Invalid pin assignment for HRTIM9 CHE2 pin: HRTIM9_CHE2
#endif
#if !FIND_VALUE_HRTIM_CHF1(_HRTIM9, HRTIM9_CHF1)
#error Invalid pin assignment for HRTIM9 CHF1 pin: HRTIM9_CHF1
#endif
#if !FIND_VALUE_HRTIM_CHF2(_HRTIM9, HRTIM9_CHF2)
#error Invalid pin assignment for HRTIM9 CHF2 pin: HRTIM9_CHF2
#endif
#if !FIND_VALUE_HRTIM_EEV1(_HRTIM9, HRTIM9_EEV1)
#error Invalid pin assignment for HRTIM9 EEV1 pin: HRTIM9_EEV1
#endif
#if !FIND_VALUE_HRTIM_EEV10(_HRTIM9, HRTIM9_EEV10)
#error Invalid pin assignment for HRTIM9 EEV10 pin: HRTIM9_EEV10
#endif
#if !FIND_VALUE_HRTIM_EEV2(_HRTIM9, HRTIM9_EEV2)
#error Invalid pin assignment for HRTIM9 EEV2 pin: HRTIM9_EEV2
#endif
#if !FIND_VALUE_HRTIM_EEV3(_HRTIM9, HRTIM9_EEV3)
#error Invalid pin assignment for HRTIM9 EEV3 pin: HRTIM9_EEV3
#endif
#if !FIND_VALUE_HRTIM_EEV4(_HRTIM9, HRTIM9_EEV4)
#error Invalid pin assignment for HRTIM9 EEV4 pin: HRTIM9_EEV4
#endif
#if !FIND_VALUE_HRTIM_EEV5(_HRTIM9, HRTIM9_EEV5)
#error Invalid pin assignment for HRTIM9 EEV5 pin: HRTIM9_EEV5
#endif
#if !FIND_VALUE_HRTIM_EEV6(_HRTIM9, HRTIM9_EEV6)
#error Invalid pin assignment for HRTIM9 EEV6 pin: HRTIM9_EEV6
#endif
#if !FIND_VALUE_HRTIM_EEV7(_HRTIM9, HRTIM9_EEV7)
#error Invalid pin assignment for HRTIM9 EEV7 pin: HRTIM9_EEV7
#endif
#if !FIND_VALUE_HRTIM_EEV8(_HRTIM9, HRTIM9_EEV8)
#error Invalid pin assignment for HRTIM9 EEV8 pin: HRTIM9_EEV8
#endif
#if !FIND_VALUE_HRTIM_EEV9(_HRTIM9, HRTIM9_EEV9)
#error Invalid pin assignment for HRTIM9 EEV9 pin: HRTIM9_EEV9
#endif
#if !FIND_VALUE_HRTIM_FLT1(_HRTIM9, HRTIM9_FLT1)
#error Invalid pin assignment for HRTIM9 FLT1 pin: HRTIM9_FLT1
#endif
#if !FIND_VALUE_HRTIM_FLT2(_HRTIM9, HRTIM9_FLT2)
#error Invalid pin assignment for HRTIM9 FLT2 pin: HRTIM9_FLT2
#endif
#if !FIND_VALUE_HRTIM_FLT3(_HRTIM9, HRTIM9_FLT3)
#error Invalid pin assignment for HRTIM9 FLT3 pin: HRTIM9_FLT3
#endif
#if !FIND_VALUE_HRTIM_FLT4(_HRTIM9, HRTIM9_FLT4)
#error Invalid pin assignment for HRTIM9 FLT4 pin: HRTIM9_FLT4
#endif
#if !FIND_VALUE_HRTIM_FLT5(_HRTIM9, HRTIM9_FLT5)
#error Invalid pin assignment for HRTIM9 FLT5 pin: HRTIM9_FLT5
#endif
#if !FIND_VALUE_HRTIM_FLT6(_HRTIM9, HRTIM9_FLT6)
#error Invalid pin assignment for HRTIM9 FLT6 pin: HRTIM9_FLT6
#endif
#if !FIND_VALUE_HRTIM_SCIN(_HRTIM9, HRTIM9_SCIN)
#error Invalid pin assignment for HRTIM9 SCIN pin: HRTIM9_SCIN
#endif
#if !FIND_VALUE_HRTIM_SCOUT(_HRTIM9, HRTIM9_SCOUT)
#error Invalid pin assignment for HRTIM9 SCOUT pin: HRTIM9_SCOUT
#endif
#endif

