/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404279
 */

#define FIND_VALUE_RTC_OUT_ALARM_inner(INDEX,PIN) I2C##_RTC_OUT_##PIN
#define FIND_VALUE_RTC_OUT_ALARM(INDEX,PIN) FIND_VALUE_RTC_OUT_ALARM_inner(INDEX,PIN)

#define FIND_VALUE_RTC_OUT_CALIB_inner(INDEX,PIN) I2C##_RTC_OUT_##PIN
#define FIND_VALUE_RTC_OUT_CALIB(INDEX,PIN) FIND_VALUE_RTC_OUT_CALIB_inner(INDEX,PIN)

#ifdef USE_RTC_OUT0
#if !FIND_VALUE_RTC_OUT_ALARM(_RTC_OUT0, RTC_OUT0_ALARM)
#error Invalid pin assignment for RTC_OUT0 ALARM pin: RTC_OUT0_ALARM
#endif
#if !FIND_VALUE_RTC_OUT_CALIB(_RTC_OUT0, RTC_OUT0_CALIB)
#error Invalid pin assignment for RTC_OUT0 CALIB pin: RTC_OUT0_CALIB
#endif
#endif

