/*
 * SystemClocks.hpp
 *
 *  Created on: 26 Dec 2020
 *      Author: robert
 */

#ifndef SRC_TEST_CPP_LOWLEVEL_CLOCKSLOWLEVEL_SPECIFIC_SYSTEMCLOCKS_HPP_
#define SRC_TEST_CPP_LOWLEVEL_CLOCKSLOWLEVEL_SPECIFIC_SYSTEMCLOCKS_HPP_

enum SystemClock {
    SysClock, HSI, HSI48, LSI, HSE, LSE, VCO, PLL_P, PLL_Q, PLL_R, HCLK, PCLK_1, PCLK_2, NONE
};

#endif /* SRC_TEST_CPP_LOWLEVEL_CLOCKSLOWLEVEL_SPECIFIC_SYSTEMCLOCKS_HPP_ */
