/*
  * This file is automatically generated by pins.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_PINS
#define LOWLEVEL_INCLUDE_DEVICE_PINS

#define PortA 0
#define PortB 1
#define PortC 2
#define PortD 3
#define PortF 4

struct GpioPinName {
    uint8_t port:4;
    uint8_t pin:4;
};


#define PA0 ((GpioPinName){PortA, Pin0})
#define PA1 ((GpioPinName){PortA, Pin1})
#define PA2 ((GpioPinName){PortA, Pin2})
#define PA3 ((GpioPinName){PortA, Pin3})
#define PA4 ((GpioPinName){PortA, Pin4})
#define PA5 ((GpioPinName){PortA, Pin5})
#define PA6 ((GpioPinName){PortA, Pin6})
#define PA7 ((GpioPinName){PortA, Pin7})
#define PA8 ((GpioPinName){PortA, Pin8})
#define PA9 ((GpioPinName){PortA, Pin9})
#define PA10 ((GpioPinName){PortA, Pin10})
#define PA11 ((GpioPinName){PortA, Pin11})
#define PA12 ((GpioPinName){PortA, Pin12})
#define PA13 ((GpioPinName){PortA, Pin13})
#define PA14 ((GpioPinName){PortA, Pin14})
#define PA15 ((GpioPinName){PortA, Pin15})

#define PB0 ((GpioPinName){PortB, Pin0})
#define PB1 ((GpioPinName){PortB, Pin1})
#define PB2 ((GpioPinName){PortB, Pin2})
#define PB3 ((GpioPinName){PortB, Pin3})
#define PB4 ((GpioPinName){PortB, Pin4})
#define PB5 ((GpioPinName){PortB, Pin5})
#define PB6 ((GpioPinName){PortB, Pin6})
#define PB7 ((GpioPinName){PortB, Pin7})
#define PB8 ((GpioPinName){PortB, Pin8})
#define PB9 ((GpioPinName){PortB, Pin9})
#define PB10 ((GpioPinName){PortB, Pin10})
#define PB11 ((GpioPinName){PortB, Pin11})
#define PB12 ((GpioPinName){PortB, Pin12})
#define PB13 ((GpioPinName){PortB, Pin13})
#define PB14 ((GpioPinName){PortB, Pin14})
#define PB15 ((GpioPinName){PortB, Pin15})

#define PC0 ((GpioPinName){PortC, Pin0})
#define PC1 ((GpioPinName){PortC, Pin1})
#define PC2 ((GpioPinName){PortC, Pin2})
#define PC3 ((GpioPinName){PortC, Pin3})
#define PC4 ((GpioPinName){PortC, Pin4})
#define PC5 ((GpioPinName){PortC, Pin5})
#define PC6 ((GpioPinName){PortC, Pin6})
#define PC7 ((GpioPinName){PortC, Pin7})
#define PC8 ((GpioPinName){PortC, Pin8})
#define PC9 ((GpioPinName){PortC, Pin9})
#define PC10 ((GpioPinName){PortC, Pin10})
#define PC11 ((GpioPinName){PortC, Pin11})
#define PC12 ((GpioPinName){PortC, Pin12})
#define PC13 ((GpioPinName){PortC, Pin13})
#define PC14 ((GpioPinName){PortC, Pin14})
#define PC15 ((GpioPinName){PortC, Pin15})

#define PD0 ((GpioPinName){PortD, Pin0})
#define PD1 ((GpioPinName){PortD, Pin1})
#define PD2 ((GpioPinName){PortD, Pin2})
#define PD3 ((GpioPinName){PortD, Pin3})
#define PD4 ((GpioPinName){PortD, Pin4})
#define PD5 ((GpioPinName){PortD, Pin5})
#define PD6 ((GpioPinName){PortD, Pin6})
#define PD8 ((GpioPinName){PortD, Pin8})
#define PD9 ((GpioPinName){PortD, Pin9})

#define PF0 ((GpioPinName){PortF, Pin0})
#define PF1 ((GpioPinName){PortF, Pin1})

#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */