/*
  * This file is automatically generated by pins.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_PINS
#define LOWLEVEL_INCLUDE_DEVICE_PINS

#define Port1 0
#define PortA 1
#define PortB 2
#define PortC 3
#define PortD 4
#define PortH 5

struct GpioPinName {
    uint8_t port:4;
    uint8_t pin:4;
};


#define PA0 ((GpioPinName){PortA, Pin0})
#define PA2 ((GpioPinName){PortA, Pin2})
#define PA3 ((GpioPinName){PortA, Pin3})
#define PA5 ((GpioPinName){PortA, Pin5})
#define PA8 ((GpioPinName){PortA, Pin8})
#define PA12 ((GpioPinName){PortA, Pin12})
#define PA13 ((GpioPinName){PortA, Pin13})
#define PA14 ((GpioPinName){PortA, Pin14})
#define PA15 ((GpioPinName){PortA, Pin15})

#define PB2 ((GpioPinName){PortB, Pin2})
#define PB3 ((GpioPinName){PortB, Pin3})
#define PB4 ((GpioPinName){PortB, Pin4})
#define PB5 ((GpioPinName){PortB, Pin5})
#define PB6 ((GpioPinName){PortB, Pin6})
#define PB7 ((GpioPinName){PortB, Pin7})
#define PB8 ((GpioPinName){PortB, Pin8})
#define PB10 ((GpioPinName){PortB, Pin10})
#define PB12 ((GpioPinName){PortB, Pin12})

#define PC13 ((GpioPinName){PortC, Pin13})
#define PC14 ((GpioPinName){PortC, Pin14})
#define PC15 ((GpioPinName){PortC, Pin15})

#define PH0 ((GpioPinName){PortH, Pin0})
#define PH1 ((GpioPinName){PortH, Pin1})

#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */