#ifndef ZCODE_IDENTIFY_CORE_ZCODE_LANG_STRING
#define ZCODE_IDENTIFY_CORE_ZCODE_LANG_STRING  "zcode.org gen-core"
#endif

#ifndef ZCODE_IDENTIFY_CORE_ZCODE_LANG_VERSION
#define ZCODE_IDENTIFY_CORE_ZCODE_LANG_VERSION 0x0001
#endif
