/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:07.285046
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32G071C.h"
#include "../AlternateFunction/STM32G07x.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32G071CB"
#endif

#define FLASH_SIZE 0x20000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 2

#define SPI_LL_STM32_Ver_2s1_v3_3
#define SPI_COUNT 2

#define UART_LL_STM32_Ver_3_v1_2
#define UART_COUNT 5

#define USART_LL_STM32_Ver_3_v2_1
#define USART_COUNT 4

#define LPUART_LL_STM32_Ver_3_v1_2
#define LPUART_COUNT 1

#define USBC_PD_LL_STM32_Ver_ucpd_v1_0
#define USBC_PD_COUNT 2

#define DAC_LL_STM32_Ver_if_v3_0
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */