/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:06.642831
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F373C.h"
#include "../AlternateFunction/STM32F373.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F373CC"
#endif

#define FLASH_SIZE 0x40000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 2

#define SPI_LL_STM32_Ver_2s1_v3_0
#define SPI_COUNT 3

#define UART_LL_STM32_Ver_2_v2_1
#define UART_COUNT 3

#define USART_LL_STM32_Ver_2_v2_1
#define USART_COUNT 3

#define USB_LL_STM32_Ver_1_v2_0_F3xx
#define USB_COUNT 1

#define DAC_LL_STM32_Ver_F3_if_v1_1
#define DAC_COUNT 2

#define CAN_LL_STM32_Ver_bx1_v1_1
#define CAN_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */