/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:06.448321
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F071V.h"
#include "../AlternateFunction/STM32F052.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F071V8"
#endif

#define FLASH_SIZE 0x10000

#define I2C_LL_STM32_Ver_F0_2_v1_1
#define I2C_COUNT 2

#define SPI_LL_STM32_Ver_2s1_v3_0
#define SPI_COUNT 2

#define UART_LL_STM32_Ver_2_v2_2
#define UART_COUNT 4

#define USART_LL_STM32_Ver_2_v2_0
#define USART_COUNT 4

#define DAC_LL_STM32_Ver_F0if_v1_1
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */