/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:06.514027
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F100C.h"
#include "../AlternateFunction/STM32F100x8.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F100CB"
#endif

#define FLASH_SIZE 0x20000

#define I2C_LL_STM32_Ver_1_v1_5
#define I2C_COUNT 2

#define SPI_LL_STM32_Ver_2s1_v1_0
#define SPI_COUNT 2

#define UART_LL_STM32_Ver_2_v1_2_F1
#define UART_COUNT 3

#define USART_LL_STM32_Ver_2_v1_2_F1
#define USART_COUNT 3

#define DAC_LL_STM32_Ver_if_v1_1F1
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */