/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.401799
 */

#define FIND_VALUE_HDP_HDP0_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP0(INDEX,PIN) FIND_VALUE_HDP_HDP0_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP1_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP1(INDEX,PIN) FIND_VALUE_HDP_HDP1_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP2_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP2(INDEX,PIN) FIND_VALUE_HDP_HDP2_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP3_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP3(INDEX,PIN) FIND_VALUE_HDP_HDP3_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP4_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP4(INDEX,PIN) FIND_VALUE_HDP_HDP4_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP5_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP5(INDEX,PIN) FIND_VALUE_HDP_HDP5_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP6_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP6(INDEX,PIN) FIND_VALUE_HDP_HDP6_inner(INDEX,PIN)

#define FIND_VALUE_HDP_HDP7_inner(INDEX,PIN) I2C##_HDP_##PIN
#define FIND_VALUE_HDP_HDP7(INDEX,PIN) FIND_VALUE_HDP_HDP7_inner(INDEX,PIN)

#ifdef USE_HDP0
#if !FIND_VALUE_HDP_HDP0(_HDP0, HDP0_HDP0)
#error Invalid pin assignment for HDP0 HDP0 pin: HDP0_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP0, HDP0_HDP1)
#error Invalid pin assignment for HDP0 HDP1 pin: HDP0_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP0, HDP0_HDP2)
#error Invalid pin assignment for HDP0 HDP2 pin: HDP0_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP0, HDP0_HDP3)
#error Invalid pin assignment for HDP0 HDP3 pin: HDP0_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP0, HDP0_HDP4)
#error Invalid pin assignment for HDP0 HDP4 pin: HDP0_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP0, HDP0_HDP5)
#error Invalid pin assignment for HDP0 HDP5 pin: HDP0_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP0, HDP0_HDP6)
#error Invalid pin assignment for HDP0 HDP6 pin: HDP0_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP0, HDP0_HDP7)
#error Invalid pin assignment for HDP0 HDP7 pin: HDP0_HDP7
#endif
#endif

#ifdef USE_HDP1
#if !FIND_VALUE_HDP_HDP0(_HDP1, HDP1_HDP0)
#error Invalid pin assignment for HDP1 HDP0 pin: HDP1_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP1, HDP1_HDP1)
#error Invalid pin assignment for HDP1 HDP1 pin: HDP1_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP1, HDP1_HDP2)
#error Invalid pin assignment for HDP1 HDP2 pin: HDP1_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP1, HDP1_HDP3)
#error Invalid pin assignment for HDP1 HDP3 pin: HDP1_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP1, HDP1_HDP4)
#error Invalid pin assignment for HDP1 HDP4 pin: HDP1_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP1, HDP1_HDP5)
#error Invalid pin assignment for HDP1 HDP5 pin: HDP1_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP1, HDP1_HDP6)
#error Invalid pin assignment for HDP1 HDP6 pin: HDP1_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP1, HDP1_HDP7)
#error Invalid pin assignment for HDP1 HDP7 pin: HDP1_HDP7
#endif
#endif

#ifdef USE_HDP2
#if !FIND_VALUE_HDP_HDP0(_HDP2, HDP2_HDP0)
#error Invalid pin assignment for HDP2 HDP0 pin: HDP2_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP2, HDP2_HDP1)
#error Invalid pin assignment for HDP2 HDP1 pin: HDP2_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP2, HDP2_HDP2)
#error Invalid pin assignment for HDP2 HDP2 pin: HDP2_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP2, HDP2_HDP3)
#error Invalid pin assignment for HDP2 HDP3 pin: HDP2_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP2, HDP2_HDP4)
#error Invalid pin assignment for HDP2 HDP4 pin: HDP2_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP2, HDP2_HDP5)
#error Invalid pin assignment for HDP2 HDP5 pin: HDP2_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP2, HDP2_HDP6)
#error Invalid pin assignment for HDP2 HDP6 pin: HDP2_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP2, HDP2_HDP7)
#error Invalid pin assignment for HDP2 HDP7 pin: HDP2_HDP7
#endif
#endif

#ifdef USE_HDP3
#if !FIND_VALUE_HDP_HDP0(_HDP3, HDP3_HDP0)
#error Invalid pin assignment for HDP3 HDP0 pin: HDP3_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP3, HDP3_HDP1)
#error Invalid pin assignment for HDP3 HDP1 pin: HDP3_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP3, HDP3_HDP2)
#error Invalid pin assignment for HDP3 HDP2 pin: HDP3_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP3, HDP3_HDP3)
#error Invalid pin assignment for HDP3 HDP3 pin: HDP3_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP3, HDP3_HDP4)
#error Invalid pin assignment for HDP3 HDP4 pin: HDP3_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP3, HDP3_HDP5)
#error Invalid pin assignment for HDP3 HDP5 pin: HDP3_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP3, HDP3_HDP6)
#error Invalid pin assignment for HDP3 HDP6 pin: HDP3_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP3, HDP3_HDP7)
#error Invalid pin assignment for HDP3 HDP7 pin: HDP3_HDP7
#endif
#endif

#ifdef USE_HDP4
#if !FIND_VALUE_HDP_HDP0(_HDP4, HDP4_HDP0)
#error Invalid pin assignment for HDP4 HDP0 pin: HDP4_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP4, HDP4_HDP1)
#error Invalid pin assignment for HDP4 HDP1 pin: HDP4_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP4, HDP4_HDP2)
#error Invalid pin assignment for HDP4 HDP2 pin: HDP4_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP4, HDP4_HDP3)
#error Invalid pin assignment for HDP4 HDP3 pin: HDP4_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP4, HDP4_HDP4)
#error Invalid pin assignment for HDP4 HDP4 pin: HDP4_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP4, HDP4_HDP5)
#error Invalid pin assignment for HDP4 HDP5 pin: HDP4_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP4, HDP4_HDP6)
#error Invalid pin assignment for HDP4 HDP6 pin: HDP4_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP4, HDP4_HDP7)
#error Invalid pin assignment for HDP4 HDP7 pin: HDP4_HDP7
#endif
#endif

#ifdef USE_HDP5
#if !FIND_VALUE_HDP_HDP0(_HDP5, HDP5_HDP0)
#error Invalid pin assignment for HDP5 HDP0 pin: HDP5_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP5, HDP5_HDP1)
#error Invalid pin assignment for HDP5 HDP1 pin: HDP5_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP5, HDP5_HDP2)
#error Invalid pin assignment for HDP5 HDP2 pin: HDP5_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP5, HDP5_HDP3)
#error Invalid pin assignment for HDP5 HDP3 pin: HDP5_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP5, HDP5_HDP4)
#error Invalid pin assignment for HDP5 HDP4 pin: HDP5_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP5, HDP5_HDP5)
#error Invalid pin assignment for HDP5 HDP5 pin: HDP5_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP5, HDP5_HDP6)
#error Invalid pin assignment for HDP5 HDP6 pin: HDP5_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP5, HDP5_HDP7)
#error Invalid pin assignment for HDP5 HDP7 pin: HDP5_HDP7
#endif
#endif

#ifdef USE_HDP6
#if !FIND_VALUE_HDP_HDP0(_HDP6, HDP6_HDP0)
#error Invalid pin assignment for HDP6 HDP0 pin: HDP6_HDP0
#endif
#if !FIND_VALUE_HDP_HDP1(_HDP6, HDP6_HDP1)
#error Invalid pin assignment for HDP6 HDP1 pin: HDP6_HDP1
#endif
#if !FIND_VALUE_HDP_HDP2(_HDP6, HDP6_HDP2)
#error Invalid pin assignment for HDP6 HDP2 pin: HDP6_HDP2
#endif
#if !FIND_VALUE_HDP_HDP3(_HDP6, HDP6_HDP3)
#error Invalid pin assignment for HDP6 HDP3 pin: HDP6_HDP3
#endif
#if !FIND_VALUE_HDP_HDP4(_HDP6, HDP6_HDP4)
#error Invalid pin assignment for HDP6 HDP4 pin: HDP6_HDP4
#endif
#if !FIND_VALUE_HDP_HDP5(_HDP6, HDP6_HDP5)
#error Invalid pin assignment for HDP6 HDP5 pin: HDP6_HDP5
#endif
#if !FIND_VALUE_HDP_HDP6(_HDP6, HDP6_HDP6)
#error Invalid pin assignment for HDP6 HDP6 pin: HDP6_HDP6
#endif
#if !FIND_VALUE_HDP_HDP7(_HDP6, HDP6_HDP7)
#error Invalid pin assignment for HDP6 HDP7 pin: HDP6_HDP7
#endif
#endif

