/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.403887
 */

#define FIND_VALUE_OPAMP_DIG_inner(INDEX,PIN) I2C##_OPAMP_##PIN
#define FIND_VALUE_OPAMP_DIG(INDEX,PIN) FIND_VALUE_OPAMP_DIG_inner(INDEX,PIN)

#ifdef USE_OPAMP0
#if !FIND_VALUE_OPAMP_DIG(_OPAMP0, OPAMP0_DIG)
#error Invalid pin assignment for OPAMP0 DIG pin: OPAMP0_DIG
#endif
#endif

#ifdef USE_OPAMP1
#if !FIND_VALUE_OPAMP_DIG(_OPAMP1, OPAMP1_DIG)
#error Invalid pin assignment for OPAMP1 DIG pin: OPAMP1_DIG
#endif
#endif

