/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404147
 */

#define FIND_VALUE_RCC_OSC_EN_inner(INDEX,PIN) I2C##_RCC_OSC_##PIN
#define FIND_VALUE_RCC_OSC_EN(INDEX,PIN) FIND_VALUE_RCC_OSC_EN_inner(INDEX,PIN)

#define FIND_VALUE_RCC_OSC_IN_inner(INDEX,PIN) I2C##_RCC_OSC_##PIN
#define FIND_VALUE_RCC_OSC_IN(INDEX,PIN) FIND_VALUE_RCC_OSC_IN_inner(INDEX,PIN)

#define FIND_VALUE_RCC_OSC_OUT_inner(INDEX,PIN) I2C##_RCC_OSC_##PIN
#define FIND_VALUE_RCC_OSC_OUT(INDEX,PIN) FIND_VALUE_RCC_OSC_OUT_inner(INDEX,PIN)

#ifdef USE_RCC_OSC0
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC0, RCC_OSC0_EN)
#error Invalid pin assignment for RCC_OSC0 EN pin: RCC_OSC0_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC0, RCC_OSC0_IN)
#error Invalid pin assignment for RCC_OSC0 IN pin: RCC_OSC0_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC0, RCC_OSC0_OUT)
#error Invalid pin assignment for RCC_OSC0 OUT pin: RCC_OSC0_OUT
#endif
#endif

#ifdef USE_RCC_OSC1
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC1, RCC_OSC1_EN)
#error Invalid pin assignment for RCC_OSC1 EN pin: RCC_OSC1_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC1, RCC_OSC1_IN)
#error Invalid pin assignment for RCC_OSC1 IN pin: RCC_OSC1_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC1, RCC_OSC1_OUT)
#error Invalid pin assignment for RCC_OSC1 OUT pin: RCC_OSC1_OUT
#endif
#endif

#ifdef USE_RCC_OSC2
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC2, RCC_OSC2_EN)
#error Invalid pin assignment for RCC_OSC2 EN pin: RCC_OSC2_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC2, RCC_OSC2_IN)
#error Invalid pin assignment for RCC_OSC2 IN pin: RCC_OSC2_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC2, RCC_OSC2_OUT)
#error Invalid pin assignment for RCC_OSC2 OUT pin: RCC_OSC2_OUT
#endif
#endif

#ifdef USE_RCC_OSC3
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC3, RCC_OSC3_EN)
#error Invalid pin assignment for RCC_OSC3 EN pin: RCC_OSC3_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC3, RCC_OSC3_IN)
#error Invalid pin assignment for RCC_OSC3 IN pin: RCC_OSC3_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC3, RCC_OSC3_OUT)
#error Invalid pin assignment for RCC_OSC3 OUT pin: RCC_OSC3_OUT
#endif
#endif

#ifdef USE_RCC_OSC4
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC4, RCC_OSC4_EN)
#error Invalid pin assignment for RCC_OSC4 EN pin: RCC_OSC4_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC4, RCC_OSC4_IN)
#error Invalid pin assignment for RCC_OSC4 IN pin: RCC_OSC4_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC4, RCC_OSC4_OUT)
#error Invalid pin assignment for RCC_OSC4 OUT pin: RCC_OSC4_OUT
#endif
#endif

#ifdef USE_RCC_OSC5
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC5, RCC_OSC5_EN)
#error Invalid pin assignment for RCC_OSC5 EN pin: RCC_OSC5_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC5, RCC_OSC5_IN)
#error Invalid pin assignment for RCC_OSC5 IN pin: RCC_OSC5_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC5, RCC_OSC5_OUT)
#error Invalid pin assignment for RCC_OSC5 OUT pin: RCC_OSC5_OUT
#endif
#endif

#ifdef USE_RCC_OSC6
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC6, RCC_OSC6_EN)
#error Invalid pin assignment for RCC_OSC6 EN pin: RCC_OSC6_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC6, RCC_OSC6_IN)
#error Invalid pin assignment for RCC_OSC6 IN pin: RCC_OSC6_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC6, RCC_OSC6_OUT)
#error Invalid pin assignment for RCC_OSC6 OUT pin: RCC_OSC6_OUT
#endif
#endif

#ifdef USE_RCC_OSC7
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC7, RCC_OSC7_EN)
#error Invalid pin assignment for RCC_OSC7 EN pin: RCC_OSC7_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC7, RCC_OSC7_IN)
#error Invalid pin assignment for RCC_OSC7 IN pin: RCC_OSC7_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC7, RCC_OSC7_OUT)
#error Invalid pin assignment for RCC_OSC7 OUT pin: RCC_OSC7_OUT
#endif
#endif

#ifdef USE_RCC_OSC8
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC8, RCC_OSC8_EN)
#error Invalid pin assignment for RCC_OSC8 EN pin: RCC_OSC8_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC8, RCC_OSC8_IN)
#error Invalid pin assignment for RCC_OSC8 IN pin: RCC_OSC8_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC8, RCC_OSC8_OUT)
#error Invalid pin assignment for RCC_OSC8 OUT pin: RCC_OSC8_OUT
#endif
#endif

#ifdef USE_RCC_OSC9
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC9, RCC_OSC9_EN)
#error Invalid pin assignment for RCC_OSC9 EN pin: RCC_OSC9_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC9, RCC_OSC9_IN)
#error Invalid pin assignment for RCC_OSC9 IN pin: RCC_OSC9_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC9, RCC_OSC9_OUT)
#error Invalid pin assignment for RCC_OSC9 OUT pin: RCC_OSC9_OUT
#endif
#endif

#ifdef USE_RCC_OSC10
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC10, RCC_OSC10_EN)
#error Invalid pin assignment for RCC_OSC10 EN pin: RCC_OSC10_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC10, RCC_OSC10_IN)
#error Invalid pin assignment for RCC_OSC10 IN pin: RCC_OSC10_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC10, RCC_OSC10_OUT)
#error Invalid pin assignment for RCC_OSC10 OUT pin: RCC_OSC10_OUT
#endif
#endif

#ifdef USE_RCC_OSC11
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC11, RCC_OSC11_EN)
#error Invalid pin assignment for RCC_OSC11 EN pin: RCC_OSC11_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC11, RCC_OSC11_IN)
#error Invalid pin assignment for RCC_OSC11 IN pin: RCC_OSC11_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC11, RCC_OSC11_OUT)
#error Invalid pin assignment for RCC_OSC11 OUT pin: RCC_OSC11_OUT
#endif
#endif

#ifdef USE_RCC_OSC12
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC12, RCC_OSC12_EN)
#error Invalid pin assignment for RCC_OSC12 EN pin: RCC_OSC12_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC12, RCC_OSC12_IN)
#error Invalid pin assignment for RCC_OSC12 IN pin: RCC_OSC12_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC12, RCC_OSC12_OUT)
#error Invalid pin assignment for RCC_OSC12 OUT pin: RCC_OSC12_OUT
#endif
#endif

#ifdef USE_RCC_OSC13
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC13, RCC_OSC13_EN)
#error Invalid pin assignment for RCC_OSC13 EN pin: RCC_OSC13_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC13, RCC_OSC13_IN)
#error Invalid pin assignment for RCC_OSC13 IN pin: RCC_OSC13_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC13, RCC_OSC13_OUT)
#error Invalid pin assignment for RCC_OSC13 OUT pin: RCC_OSC13_OUT
#endif
#endif

#ifdef USE_RCC_OSC14
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC14, RCC_OSC14_EN)
#error Invalid pin assignment for RCC_OSC14 EN pin: RCC_OSC14_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC14, RCC_OSC14_IN)
#error Invalid pin assignment for RCC_OSC14 IN pin: RCC_OSC14_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC14, RCC_OSC14_OUT)
#error Invalid pin assignment for RCC_OSC14 OUT pin: RCC_OSC14_OUT
#endif
#endif

#ifdef USE_RCC_OSC15
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC15, RCC_OSC15_EN)
#error Invalid pin assignment for RCC_OSC15 EN pin: RCC_OSC15_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC15, RCC_OSC15_IN)
#error Invalid pin assignment for RCC_OSC15 IN pin: RCC_OSC15_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC15, RCC_OSC15_OUT)
#error Invalid pin assignment for RCC_OSC15 OUT pin: RCC_OSC15_OUT
#endif
#endif

#ifdef USE_RCC_OSC16
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC16, RCC_OSC16_EN)
#error Invalid pin assignment for RCC_OSC16 EN pin: RCC_OSC16_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC16, RCC_OSC16_IN)
#error Invalid pin assignment for RCC_OSC16 IN pin: RCC_OSC16_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC16, RCC_OSC16_OUT)
#error Invalid pin assignment for RCC_OSC16 OUT pin: RCC_OSC16_OUT
#endif
#endif

#ifdef USE_RCC_OSC17
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC17, RCC_OSC17_EN)
#error Invalid pin assignment for RCC_OSC17 EN pin: RCC_OSC17_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC17, RCC_OSC17_IN)
#error Invalid pin assignment for RCC_OSC17 IN pin: RCC_OSC17_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC17, RCC_OSC17_OUT)
#error Invalid pin assignment for RCC_OSC17 OUT pin: RCC_OSC17_OUT
#endif
#endif

#ifdef USE_RCC_OSC18
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC18, RCC_OSC18_EN)
#error Invalid pin assignment for RCC_OSC18 EN pin: RCC_OSC18_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC18, RCC_OSC18_IN)
#error Invalid pin assignment for RCC_OSC18 IN pin: RCC_OSC18_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC18, RCC_OSC18_OUT)
#error Invalid pin assignment for RCC_OSC18 OUT pin: RCC_OSC18_OUT
#endif
#endif

#ifdef USE_RCC_OSC19
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC19, RCC_OSC19_EN)
#error Invalid pin assignment for RCC_OSC19 EN pin: RCC_OSC19_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC19, RCC_OSC19_IN)
#error Invalid pin assignment for RCC_OSC19 IN pin: RCC_OSC19_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC19, RCC_OSC19_OUT)
#error Invalid pin assignment for RCC_OSC19 OUT pin: RCC_OSC19_OUT
#endif
#endif

#ifdef USE_RCC_OSC20
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC20, RCC_OSC20_EN)
#error Invalid pin assignment for RCC_OSC20 EN pin: RCC_OSC20_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC20, RCC_OSC20_IN)
#error Invalid pin assignment for RCC_OSC20 IN pin: RCC_OSC20_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC20, RCC_OSC20_OUT)
#error Invalid pin assignment for RCC_OSC20 OUT pin: RCC_OSC20_OUT
#endif
#endif

#ifdef USE_RCC_OSC21
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC21, RCC_OSC21_EN)
#error Invalid pin assignment for RCC_OSC21 EN pin: RCC_OSC21_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC21, RCC_OSC21_IN)
#error Invalid pin assignment for RCC_OSC21 IN pin: RCC_OSC21_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC21, RCC_OSC21_OUT)
#error Invalid pin assignment for RCC_OSC21 OUT pin: RCC_OSC21_OUT
#endif
#endif

#ifdef USE_RCC_OSC22
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC22, RCC_OSC22_EN)
#error Invalid pin assignment for RCC_OSC22 EN pin: RCC_OSC22_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC22, RCC_OSC22_IN)
#error Invalid pin assignment for RCC_OSC22 IN pin: RCC_OSC22_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC22, RCC_OSC22_OUT)
#error Invalid pin assignment for RCC_OSC22 OUT pin: RCC_OSC22_OUT
#endif
#endif

#ifdef USE_RCC_OSC23
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC23, RCC_OSC23_EN)
#error Invalid pin assignment for RCC_OSC23 EN pin: RCC_OSC23_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC23, RCC_OSC23_IN)
#error Invalid pin assignment for RCC_OSC23 IN pin: RCC_OSC23_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC23, RCC_OSC23_OUT)
#error Invalid pin assignment for RCC_OSC23 OUT pin: RCC_OSC23_OUT
#endif
#endif

#ifdef USE_RCC_OSC24
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC24, RCC_OSC24_EN)
#error Invalid pin assignment for RCC_OSC24 EN pin: RCC_OSC24_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC24, RCC_OSC24_IN)
#error Invalid pin assignment for RCC_OSC24 IN pin: RCC_OSC24_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC24, RCC_OSC24_OUT)
#error Invalid pin assignment for RCC_OSC24 OUT pin: RCC_OSC24_OUT
#endif
#endif

#ifdef USE_RCC_OSC25
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC25, RCC_OSC25_EN)
#error Invalid pin assignment for RCC_OSC25 EN pin: RCC_OSC25_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC25, RCC_OSC25_IN)
#error Invalid pin assignment for RCC_OSC25 IN pin: RCC_OSC25_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC25, RCC_OSC25_OUT)
#error Invalid pin assignment for RCC_OSC25 OUT pin: RCC_OSC25_OUT
#endif
#endif

#ifdef USE_RCC_OSC26
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC26, RCC_OSC26_EN)
#error Invalid pin assignment for RCC_OSC26 EN pin: RCC_OSC26_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC26, RCC_OSC26_IN)
#error Invalid pin assignment for RCC_OSC26 IN pin: RCC_OSC26_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC26, RCC_OSC26_OUT)
#error Invalid pin assignment for RCC_OSC26 OUT pin: RCC_OSC26_OUT
#endif
#endif

#ifdef USE_RCC_OSC27
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC27, RCC_OSC27_EN)
#error Invalid pin assignment for RCC_OSC27 EN pin: RCC_OSC27_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC27, RCC_OSC27_IN)
#error Invalid pin assignment for RCC_OSC27 IN pin: RCC_OSC27_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC27, RCC_OSC27_OUT)
#error Invalid pin assignment for RCC_OSC27 OUT pin: RCC_OSC27_OUT
#endif
#endif

#ifdef USE_RCC_OSC28
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC28, RCC_OSC28_EN)
#error Invalid pin assignment for RCC_OSC28 EN pin: RCC_OSC28_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC28, RCC_OSC28_IN)
#error Invalid pin assignment for RCC_OSC28 IN pin: RCC_OSC28_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC28, RCC_OSC28_OUT)
#error Invalid pin assignment for RCC_OSC28 OUT pin: RCC_OSC28_OUT
#endif
#endif

#ifdef USE_RCC_OSC29
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC29, RCC_OSC29_EN)
#error Invalid pin assignment for RCC_OSC29 EN pin: RCC_OSC29_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC29, RCC_OSC29_IN)
#error Invalid pin assignment for RCC_OSC29 IN pin: RCC_OSC29_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC29, RCC_OSC29_OUT)
#error Invalid pin assignment for RCC_OSC29 OUT pin: RCC_OSC29_OUT
#endif
#endif

#ifdef USE_RCC_OSC30
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC30, RCC_OSC30_EN)
#error Invalid pin assignment for RCC_OSC30 EN pin: RCC_OSC30_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC30, RCC_OSC30_IN)
#error Invalid pin assignment for RCC_OSC30 IN pin: RCC_OSC30_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC30, RCC_OSC30_OUT)
#error Invalid pin assignment for RCC_OSC30 OUT pin: RCC_OSC30_OUT
#endif
#endif

#ifdef USE_RCC_OSC31
#if !FIND_VALUE_RCC_OSC_EN(_RCC_OSC31, RCC_OSC31_EN)
#error Invalid pin assignment for RCC_OSC31 EN pin: RCC_OSC31_EN
#endif
#if !FIND_VALUE_RCC_OSC_IN(_RCC_OSC31, RCC_OSC31_IN)
#error Invalid pin assignment for RCC_OSC31 IN pin: RCC_OSC31_IN
#endif
#if !FIND_VALUE_RCC_OSC_OUT(_RCC_OSC31, RCC_OSC31_OUT)
#error Invalid pin assignment for RCC_OSC31 OUT pin: RCC_OSC31_OUT
#endif
#endif

