/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398004
 */

#define FIND_VALUE_CAN_RX_inner(INDEX,PIN) I2C##_CAN_##PIN
#define FIND_VALUE_CAN_RX(INDEX,PIN) FIND_VALUE_CAN_RX_inner(INDEX,PIN)

#define FIND_VALUE_CAN_TX_inner(INDEX,PIN) I2C##_CAN_##PIN
#define FIND_VALUE_CAN_TX(INDEX,PIN) FIND_VALUE_CAN_TX_inner(INDEX,PIN)

#ifdef USE_CAN0
#if !FIND_VALUE_CAN_RX(_CAN0, CAN0_RX)
#error Invalid pin assignment for CAN0 RX pin: CAN0_RX
#endif
#if !FIND_VALUE_CAN_TX(_CAN0, CAN0_TX)
#error Invalid pin assignment for CAN0 TX pin: CAN0_TX
#endif
#endif

#ifdef USE_CAN1
#if !FIND_VALUE_CAN_RX(_CAN1, CAN1_RX)
#error Invalid pin assignment for CAN1 RX pin: CAN1_RX
#endif
#if !FIND_VALUE_CAN_TX(_CAN1, CAN1_TX)
#error Invalid pin assignment for CAN1 TX pin: CAN1_TX
#endif
#endif

#ifdef USE_CAN2
#if !FIND_VALUE_CAN_RX(_CAN2, CAN2_RX)
#error Invalid pin assignment for CAN2 RX pin: CAN2_RX
#endif
#if !FIND_VALUE_CAN_TX(_CAN2, CAN2_TX)
#error Invalid pin assignment for CAN2 TX pin: CAN2_TX
#endif
#endif

