/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398634
 */

#define FIND_VALUE_DEBUG_JTCK_SWCLK_inner(INDEX,PIN) I2C##_DEBUG_JTCK_##PIN
#define FIND_VALUE_DEBUG_JTCK_SWCLK(INDEX,PIN) FIND_VALUE_DEBUG_JTCK_SWCLK_inner(INDEX,PIN)

#ifdef USE_DEBUG_JTCK0
#if !FIND_VALUE_DEBUG_JTCK_SWCLK(_DEBUG_JTCK0, DEBUG_JTCK0_SWCLK)
#error Invalid pin assignment for DEBUG_JTCK0 SWCLK pin: DEBUG_JTCK0_SWCLK
#endif
#endif

