/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.405430
 */

#define FIND_VALUE_UCPD_FRSTX_inner(INDEX,PIN) I2C##_UCPD_##PIN
#define FIND_VALUE_UCPD_FRSTX(INDEX,PIN) FIND_VALUE_UCPD_FRSTX_inner(INDEX,PIN)

#define FIND_VALUE_UCPD_FRSTX1_inner(INDEX,PIN) I2C##_UCPD_##PIN
#define FIND_VALUE_UCPD_FRSTX1(INDEX,PIN) FIND_VALUE_UCPD_FRSTX1_inner(INDEX,PIN)

#define FIND_VALUE_UCPD_FRSTX2_inner(INDEX,PIN) I2C##_UCPD_##PIN
#define FIND_VALUE_UCPD_FRSTX2(INDEX,PIN) FIND_VALUE_UCPD_FRSTX2_inner(INDEX,PIN)

#define FIND_VALUE_UCPD_TXDATA_inner(INDEX,PIN) I2C##_UCPD_##PIN
#define FIND_VALUE_UCPD_TXDATA(INDEX,PIN) FIND_VALUE_UCPD_TXDATA_inner(INDEX,PIN)

#define FIND_VALUE_UCPD_TXGND_inner(INDEX,PIN) I2C##_UCPD_##PIN
#define FIND_VALUE_UCPD_TXGND(INDEX,PIN) FIND_VALUE_UCPD_TXGND_inner(INDEX,PIN)

#ifdef USE_UCPD0
#if !FIND_VALUE_UCPD_FRSTX(_UCPD0, UCPD0_FRSTX)
#error Invalid pin assignment for UCPD0 FRSTX pin: UCPD0_FRSTX
#endif
#if !FIND_VALUE_UCPD_FRSTX1(_UCPD0, UCPD0_FRSTX1)
#error Invalid pin assignment for UCPD0 FRSTX1 pin: UCPD0_FRSTX1
#endif
#if !FIND_VALUE_UCPD_FRSTX2(_UCPD0, UCPD0_FRSTX2)
#error Invalid pin assignment for UCPD0 FRSTX2 pin: UCPD0_FRSTX2
#endif
#if !FIND_VALUE_UCPD_TXDATA(_UCPD0, UCPD0_TXDATA)
#error Invalid pin assignment for UCPD0 TXDATA pin: UCPD0_TXDATA
#endif
#if !FIND_VALUE_UCPD_TXGND(_UCPD0, UCPD0_TXGND)
#error Invalid pin assignment for UCPD0 TXGND pin: UCPD0_TXGND
#endif
#endif

#ifdef USE_UCPD1
#if !FIND_VALUE_UCPD_FRSTX(_UCPD1, UCPD1_FRSTX)
#error Invalid pin assignment for UCPD1 FRSTX pin: UCPD1_FRSTX
#endif
#if !FIND_VALUE_UCPD_FRSTX1(_UCPD1, UCPD1_FRSTX1)
#error Invalid pin assignment for UCPD1 FRSTX1 pin: UCPD1_FRSTX1
#endif
#if !FIND_VALUE_UCPD_FRSTX2(_UCPD1, UCPD1_FRSTX2)
#error Invalid pin assignment for UCPD1 FRSTX2 pin: UCPD1_FRSTX2
#endif
#if !FIND_VALUE_UCPD_TXDATA(_UCPD1, UCPD1_TXDATA)
#error Invalid pin assignment for UCPD1 TXDATA pin: UCPD1_TXDATA
#endif
#if !FIND_VALUE_UCPD_TXGND(_UCPD1, UCPD1_TXGND)
#error Invalid pin assignment for UCPD1 TXGND pin: UCPD1_TXGND
#endif
#endif

