/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404294
 */

#define FIND_VALUE_SAI_CK1_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_CK1(INDEX,PIN) FIND_VALUE_SAI_CK1_inner(INDEX,PIN)

#define FIND_VALUE_SAI_CK2_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_CK2(INDEX,PIN) FIND_VALUE_SAI_CK2_inner(INDEX,PIN)

#define FIND_VALUE_SAI_D1_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_D1(INDEX,PIN) FIND_VALUE_SAI_D1_inner(INDEX,PIN)

#define FIND_VALUE_SAI_D2_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_D2(INDEX,PIN) FIND_VALUE_SAI_D2_inner(INDEX,PIN)

#define FIND_VALUE_SAI_D3_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_D3(INDEX,PIN) FIND_VALUE_SAI_D3_inner(INDEX,PIN)

#define FIND_VALUE_SAI_D4_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_D4(INDEX,PIN) FIND_VALUE_SAI_D4_inner(INDEX,PIN)

#define FIND_VALUE_SAI_DI1_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_DI1(INDEX,PIN) FIND_VALUE_SAI_DI1_inner(INDEX,PIN)

#define FIND_VALUE_SAI_DI2_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_DI2(INDEX,PIN) FIND_VALUE_SAI_DI2_inner(INDEX,PIN)

#define FIND_VALUE_SAI_EXTCLK_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_EXTCLK(INDEX,PIN) FIND_VALUE_SAI_EXTCLK_inner(INDEX,PIN)

#define FIND_VALUE_SAI_FS_A_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_FS_A(INDEX,PIN) FIND_VALUE_SAI_FS_A_inner(INDEX,PIN)

#define FIND_VALUE_SAI_FS_B_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_FS_B(INDEX,PIN) FIND_VALUE_SAI_FS_B_inner(INDEX,PIN)

#define FIND_VALUE_SAI_MCLK_A_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_MCLK_A(INDEX,PIN) FIND_VALUE_SAI_MCLK_A_inner(INDEX,PIN)

#define FIND_VALUE_SAI_MCLK_B_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_MCLK_B(INDEX,PIN) FIND_VALUE_SAI_MCLK_B_inner(INDEX,PIN)

#define FIND_VALUE_SAI_SCK_A_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_SCK_A(INDEX,PIN) FIND_VALUE_SAI_SCK_A_inner(INDEX,PIN)

#define FIND_VALUE_SAI_SCK_B_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_SCK_B(INDEX,PIN) FIND_VALUE_SAI_SCK_B_inner(INDEX,PIN)

#define FIND_VALUE_SAI_SD_A_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_SD_A(INDEX,PIN) FIND_VALUE_SAI_SD_A_inner(INDEX,PIN)

#define FIND_VALUE_SAI_SD_B_inner(INDEX,PIN) I2C##_SAI_##PIN
#define FIND_VALUE_SAI_SD_B(INDEX,PIN) FIND_VALUE_SAI_SD_B_inner(INDEX,PIN)

#ifdef USE_SAI0
#if !FIND_VALUE_SAI_CK1(_SAI0, SAI0_CK1)
#error Invalid pin assignment for SAI0 CK1 pin: SAI0_CK1
#endif
#if !FIND_VALUE_SAI_CK2(_SAI0, SAI0_CK2)
#error Invalid pin assignment for SAI0 CK2 pin: SAI0_CK2
#endif
#if !FIND_VALUE_SAI_D1(_SAI0, SAI0_D1)
#error Invalid pin assignment for SAI0 D1 pin: SAI0_D1
#endif
#if !FIND_VALUE_SAI_D2(_SAI0, SAI0_D2)
#error Invalid pin assignment for SAI0 D2 pin: SAI0_D2
#endif
#if !FIND_VALUE_SAI_D3(_SAI0, SAI0_D3)
#error Invalid pin assignment for SAI0 D3 pin: SAI0_D3
#endif
#if !FIND_VALUE_SAI_D4(_SAI0, SAI0_D4)
#error Invalid pin assignment for SAI0 D4 pin: SAI0_D4
#endif
#if !FIND_VALUE_SAI_DI1(_SAI0, SAI0_DI1)
#error Invalid pin assignment for SAI0 DI1 pin: SAI0_DI1
#endif
#if !FIND_VALUE_SAI_DI2(_SAI0, SAI0_DI2)
#error Invalid pin assignment for SAI0 DI2 pin: SAI0_DI2
#endif
#if !FIND_VALUE_SAI_EXTCLK(_SAI0, SAI0_EXTCLK)
#error Invalid pin assignment for SAI0 EXTCLK pin: SAI0_EXTCLK
#endif
#if !FIND_VALUE_SAI_FS_A(_SAI0, SAI0_FS_A)
#error Invalid pin assignment for SAI0 FS_A pin: SAI0_FS_A
#endif
#if !FIND_VALUE_SAI_FS_B(_SAI0, SAI0_FS_B)
#error Invalid pin assignment for SAI0 FS_B pin: SAI0_FS_B
#endif
#if !FIND_VALUE_SAI_MCLK_A(_SAI0, SAI0_MCLK_A)
#error Invalid pin assignment for SAI0 MCLK_A pin: SAI0_MCLK_A
#endif
#if !FIND_VALUE_SAI_MCLK_B(_SAI0, SAI0_MCLK_B)
#error Invalid pin assignment for SAI0 MCLK_B pin: SAI0_MCLK_B
#endif
#if !FIND_VALUE_SAI_SCK_A(_SAI0, SAI0_SCK_A)
#error Invalid pin assignment for SAI0 SCK_A pin: SAI0_SCK_A
#endif
#if !FIND_VALUE_SAI_SCK_B(_SAI0, SAI0_SCK_B)
#error Invalid pin assignment for SAI0 SCK_B pin: SAI0_SCK_B
#endif
#if !FIND_VALUE_SAI_SD_A(_SAI0, SAI0_SD_A)
#error Invalid pin assignment for SAI0 SD_A pin: SAI0_SD_A
#endif
#if !FIND_VALUE_SAI_SD_B(_SAI0, SAI0_SD_B)
#error Invalid pin assignment for SAI0 SD_B pin: SAI0_SD_B
#endif
#endif

#ifdef USE_SAI1
#if !FIND_VALUE_SAI_CK1(_SAI1, SAI1_CK1)
#error Invalid pin assignment for SAI1 CK1 pin: SAI1_CK1
#endif
#if !FIND_VALUE_SAI_CK2(_SAI1, SAI1_CK2)
#error Invalid pin assignment for SAI1 CK2 pin: SAI1_CK2
#endif
#if !FIND_VALUE_SAI_D1(_SAI1, SAI1_D1)
#error Invalid pin assignment for SAI1 D1 pin: SAI1_D1
#endif
#if !FIND_VALUE_SAI_D2(_SAI1, SAI1_D2)
#error Invalid pin assignment for SAI1 D2 pin: SAI1_D2
#endif
#if !FIND_VALUE_SAI_D3(_SAI1, SAI1_D3)
#error Invalid pin assignment for SAI1 D3 pin: SAI1_D3
#endif
#if !FIND_VALUE_SAI_D4(_SAI1, SAI1_D4)
#error Invalid pin assignment for SAI1 D4 pin: SAI1_D4
#endif
#if !FIND_VALUE_SAI_DI1(_SAI1, SAI1_DI1)
#error Invalid pin assignment for SAI1 DI1 pin: SAI1_DI1
#endif
#if !FIND_VALUE_SAI_DI2(_SAI1, SAI1_DI2)
#error Invalid pin assignment for SAI1 DI2 pin: SAI1_DI2
#endif
#if !FIND_VALUE_SAI_EXTCLK(_SAI1, SAI1_EXTCLK)
#error Invalid pin assignment for SAI1 EXTCLK pin: SAI1_EXTCLK
#endif
#if !FIND_VALUE_SAI_FS_A(_SAI1, SAI1_FS_A)
#error Invalid pin assignment for SAI1 FS_A pin: SAI1_FS_A
#endif
#if !FIND_VALUE_SAI_FS_B(_SAI1, SAI1_FS_B)
#error Invalid pin assignment for SAI1 FS_B pin: SAI1_FS_B
#endif
#if !FIND_VALUE_SAI_MCLK_A(_SAI1, SAI1_MCLK_A)
#error Invalid pin assignment for SAI1 MCLK_A pin: SAI1_MCLK_A
#endif
#if !FIND_VALUE_SAI_MCLK_B(_SAI1, SAI1_MCLK_B)
#error Invalid pin assignment for SAI1 MCLK_B pin: SAI1_MCLK_B
#endif
#if !FIND_VALUE_SAI_SCK_A(_SAI1, SAI1_SCK_A)
#error Invalid pin assignment for SAI1 SCK_A pin: SAI1_SCK_A
#endif
#if !FIND_VALUE_SAI_SCK_B(_SAI1, SAI1_SCK_B)
#error Invalid pin assignment for SAI1 SCK_B pin: SAI1_SCK_B
#endif
#if !FIND_VALUE_SAI_SD_A(_SAI1, SAI1_SD_A)
#error Invalid pin assignment for SAI1 SD_A pin: SAI1_SD_A
#endif
#if !FIND_VALUE_SAI_SD_B(_SAI1, SAI1_SD_B)
#error Invalid pin assignment for SAI1 SD_B pin: SAI1_SD_B
#endif
#endif

#ifdef USE_SAI2
#if !FIND_VALUE_SAI_CK1(_SAI2, SAI2_CK1)
#error Invalid pin assignment for SAI2 CK1 pin: SAI2_CK1
#endif
#if !FIND_VALUE_SAI_CK2(_SAI2, SAI2_CK2)
#error Invalid pin assignment for SAI2 CK2 pin: SAI2_CK2
#endif
#if !FIND_VALUE_SAI_D1(_SAI2, SAI2_D1)
#error Invalid pin assignment for SAI2 D1 pin: SAI2_D1
#endif
#if !FIND_VALUE_SAI_D2(_SAI2, SAI2_D2)
#error Invalid pin assignment for SAI2 D2 pin: SAI2_D2
#endif
#if !FIND_VALUE_SAI_D3(_SAI2, SAI2_D3)
#error Invalid pin assignment for SAI2 D3 pin: SAI2_D3
#endif
#if !FIND_VALUE_SAI_D4(_SAI2, SAI2_D4)
#error Invalid pin assignment for SAI2 D4 pin: SAI2_D4
#endif
#if !FIND_VALUE_SAI_DI1(_SAI2, SAI2_DI1)
#error Invalid pin assignment for SAI2 DI1 pin: SAI2_DI1
#endif
#if !FIND_VALUE_SAI_DI2(_SAI2, SAI2_DI2)
#error Invalid pin assignment for SAI2 DI2 pin: SAI2_DI2
#endif
#if !FIND_VALUE_SAI_EXTCLK(_SAI2, SAI2_EXTCLK)
#error Invalid pin assignment for SAI2 EXTCLK pin: SAI2_EXTCLK
#endif
#if !FIND_VALUE_SAI_FS_A(_SAI2, SAI2_FS_A)
#error Invalid pin assignment for SAI2 FS_A pin: SAI2_FS_A
#endif
#if !FIND_VALUE_SAI_FS_B(_SAI2, SAI2_FS_B)
#error Invalid pin assignment for SAI2 FS_B pin: SAI2_FS_B
#endif
#if !FIND_VALUE_SAI_MCLK_A(_SAI2, SAI2_MCLK_A)
#error Invalid pin assignment for SAI2 MCLK_A pin: SAI2_MCLK_A
#endif
#if !FIND_VALUE_SAI_MCLK_B(_SAI2, SAI2_MCLK_B)
#error Invalid pin assignment for SAI2 MCLK_B pin: SAI2_MCLK_B
#endif
#if !FIND_VALUE_SAI_SCK_A(_SAI2, SAI2_SCK_A)
#error Invalid pin assignment for SAI2 SCK_A pin: SAI2_SCK_A
#endif
#if !FIND_VALUE_SAI_SCK_B(_SAI2, SAI2_SCK_B)
#error Invalid pin assignment for SAI2 SCK_B pin: SAI2_SCK_B
#endif
#if !FIND_VALUE_SAI_SD_A(_SAI2, SAI2_SD_A)
#error Invalid pin assignment for SAI2 SD_A pin: SAI2_SD_A
#endif
#if !FIND_VALUE_SAI_SD_B(_SAI2, SAI2_SD_B)
#error Invalid pin assignment for SAI2 SD_B pin: SAI2_SD_B
#endif
#endif

#ifdef USE_SAI3
#if !FIND_VALUE_SAI_CK1(_SAI3, SAI3_CK1)
#error Invalid pin assignment for SAI3 CK1 pin: SAI3_CK1
#endif
#if !FIND_VALUE_SAI_CK2(_SAI3, SAI3_CK2)
#error Invalid pin assignment for SAI3 CK2 pin: SAI3_CK2
#endif
#if !FIND_VALUE_SAI_D1(_SAI3, SAI3_D1)
#error Invalid pin assignment for SAI3 D1 pin: SAI3_D1
#endif
#if !FIND_VALUE_SAI_D2(_SAI3, SAI3_D2)
#error Invalid pin assignment for SAI3 D2 pin: SAI3_D2
#endif
#if !FIND_VALUE_SAI_D3(_SAI3, SAI3_D3)
#error Invalid pin assignment for SAI3 D3 pin: SAI3_D3
#endif
#if !FIND_VALUE_SAI_D4(_SAI3, SAI3_D4)
#error Invalid pin assignment for SAI3 D4 pin: SAI3_D4
#endif
#if !FIND_VALUE_SAI_DI1(_SAI3, SAI3_DI1)
#error Invalid pin assignment for SAI3 DI1 pin: SAI3_DI1
#endif
#if !FIND_VALUE_SAI_DI2(_SAI3, SAI3_DI2)
#error Invalid pin assignment for SAI3 DI2 pin: SAI3_DI2
#endif
#if !FIND_VALUE_SAI_EXTCLK(_SAI3, SAI3_EXTCLK)
#error Invalid pin assignment for SAI3 EXTCLK pin: SAI3_EXTCLK
#endif
#if !FIND_VALUE_SAI_FS_A(_SAI3, SAI3_FS_A)
#error Invalid pin assignment for SAI3 FS_A pin: SAI3_FS_A
#endif
#if !FIND_VALUE_SAI_FS_B(_SAI3, SAI3_FS_B)
#error Invalid pin assignment for SAI3 FS_B pin: SAI3_FS_B
#endif
#if !FIND_VALUE_SAI_MCLK_A(_SAI3, SAI3_MCLK_A)
#error Invalid pin assignment for SAI3 MCLK_A pin: SAI3_MCLK_A
#endif
#if !FIND_VALUE_SAI_MCLK_B(_SAI3, SAI3_MCLK_B)
#error Invalid pin assignment for SAI3 MCLK_B pin: SAI3_MCLK_B
#endif
#if !FIND_VALUE_SAI_SCK_A(_SAI3, SAI3_SCK_A)
#error Invalid pin assignment for SAI3 SCK_A pin: SAI3_SCK_A
#endif
#if !FIND_VALUE_SAI_SCK_B(_SAI3, SAI3_SCK_B)
#error Invalid pin assignment for SAI3 SCK_B pin: SAI3_SCK_B
#endif
#if !FIND_VALUE_SAI_SD_A(_SAI3, SAI3_SD_A)
#error Invalid pin assignment for SAI3 SD_A pin: SAI3_SD_A
#endif
#if !FIND_VALUE_SAI_SD_B(_SAI3, SAI3_SD_B)
#error Invalid pin assignment for SAI3 SD_B pin: SAI3_SD_B
#endif
#endif

