/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.403676
 */

#define FIND_VALUE_LTDC_B0_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B0(INDEX,PIN) FIND_VALUE_LTDC_B0_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B1_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B1(INDEX,PIN) FIND_VALUE_LTDC_B1_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B2_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B2(INDEX,PIN) FIND_VALUE_LTDC_B2_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B3_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B3(INDEX,PIN) FIND_VALUE_LTDC_B3_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B4_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B4(INDEX,PIN) FIND_VALUE_LTDC_B4_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B5_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B5(INDEX,PIN) FIND_VALUE_LTDC_B5_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B6_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B6(INDEX,PIN) FIND_VALUE_LTDC_B6_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B7_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_B7(INDEX,PIN) FIND_VALUE_LTDC_B7_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_CLK_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_CLK(INDEX,PIN) FIND_VALUE_LTDC_CLK_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_DE_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_DE(INDEX,PIN) FIND_VALUE_LTDC_DE_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G0_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G0(INDEX,PIN) FIND_VALUE_LTDC_G0_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G1_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G1(INDEX,PIN) FIND_VALUE_LTDC_G1_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G2_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G2(INDEX,PIN) FIND_VALUE_LTDC_G2_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G3_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G3(INDEX,PIN) FIND_VALUE_LTDC_G3_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G4_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G4(INDEX,PIN) FIND_VALUE_LTDC_G4_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G5_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G5(INDEX,PIN) FIND_VALUE_LTDC_G5_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G6_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G6(INDEX,PIN) FIND_VALUE_LTDC_G6_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G7_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_G7(INDEX,PIN) FIND_VALUE_LTDC_G7_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_HSYNC_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_HSYNC(INDEX,PIN) FIND_VALUE_LTDC_HSYNC_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R0_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R0(INDEX,PIN) FIND_VALUE_LTDC_R0_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R1_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R1(INDEX,PIN) FIND_VALUE_LTDC_R1_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R2_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R2(INDEX,PIN) FIND_VALUE_LTDC_R2_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R3_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R3(INDEX,PIN) FIND_VALUE_LTDC_R3_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R4_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R4(INDEX,PIN) FIND_VALUE_LTDC_R4_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R5_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R5(INDEX,PIN) FIND_VALUE_LTDC_R5_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R6_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R6(INDEX,PIN) FIND_VALUE_LTDC_R6_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R7_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_R7(INDEX,PIN) FIND_VALUE_LTDC_R7_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_VSYNC_inner(INDEX,PIN) I2C##_LTDC_##PIN
#define FIND_VALUE_LTDC_VSYNC(INDEX,PIN) FIND_VALUE_LTDC_VSYNC_inner(INDEX,PIN)

#ifdef USE_LTDC0
#if !FIND_VALUE_LTDC_B0(_LTDC0, LTDC0_B0)
#error Invalid pin assignment for LTDC0 B0 pin: LTDC0_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC0, LTDC0_B1)
#error Invalid pin assignment for LTDC0 B1 pin: LTDC0_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC0, LTDC0_B2)
#error Invalid pin assignment for LTDC0 B2 pin: LTDC0_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC0, LTDC0_B3)
#error Invalid pin assignment for LTDC0 B3 pin: LTDC0_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC0, LTDC0_B4)
#error Invalid pin assignment for LTDC0 B4 pin: LTDC0_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC0, LTDC0_B5)
#error Invalid pin assignment for LTDC0 B5 pin: LTDC0_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC0, LTDC0_B6)
#error Invalid pin assignment for LTDC0 B6 pin: LTDC0_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC0, LTDC0_B7)
#error Invalid pin assignment for LTDC0 B7 pin: LTDC0_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC0, LTDC0_CLK)
#error Invalid pin assignment for LTDC0 CLK pin: LTDC0_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC0, LTDC0_DE)
#error Invalid pin assignment for LTDC0 DE pin: LTDC0_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC0, LTDC0_G0)
#error Invalid pin assignment for LTDC0 G0 pin: LTDC0_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC0, LTDC0_G1)
#error Invalid pin assignment for LTDC0 G1 pin: LTDC0_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC0, LTDC0_G2)
#error Invalid pin assignment for LTDC0 G2 pin: LTDC0_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC0, LTDC0_G3)
#error Invalid pin assignment for LTDC0 G3 pin: LTDC0_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC0, LTDC0_G4)
#error Invalid pin assignment for LTDC0 G4 pin: LTDC0_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC0, LTDC0_G5)
#error Invalid pin assignment for LTDC0 G5 pin: LTDC0_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC0, LTDC0_G6)
#error Invalid pin assignment for LTDC0 G6 pin: LTDC0_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC0, LTDC0_G7)
#error Invalid pin assignment for LTDC0 G7 pin: LTDC0_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC0, LTDC0_HSYNC)
#error Invalid pin assignment for LTDC0 HSYNC pin: LTDC0_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC0, LTDC0_R0)
#error Invalid pin assignment for LTDC0 R0 pin: LTDC0_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC0, LTDC0_R1)
#error Invalid pin assignment for LTDC0 R1 pin: LTDC0_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC0, LTDC0_R2)
#error Invalid pin assignment for LTDC0 R2 pin: LTDC0_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC0, LTDC0_R3)
#error Invalid pin assignment for LTDC0 R3 pin: LTDC0_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC0, LTDC0_R4)
#error Invalid pin assignment for LTDC0 R4 pin: LTDC0_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC0, LTDC0_R5)
#error Invalid pin assignment for LTDC0 R5 pin: LTDC0_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC0, LTDC0_R6)
#error Invalid pin assignment for LTDC0 R6 pin: LTDC0_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC0, LTDC0_R7)
#error Invalid pin assignment for LTDC0 R7 pin: LTDC0_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC0, LTDC0_VSYNC)
#error Invalid pin assignment for LTDC0 VSYNC pin: LTDC0_VSYNC
#endif
#endif

#ifdef USE_LTDC1
#if !FIND_VALUE_LTDC_B0(_LTDC1, LTDC1_B0)
#error Invalid pin assignment for LTDC1 B0 pin: LTDC1_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC1, LTDC1_B1)
#error Invalid pin assignment for LTDC1 B1 pin: LTDC1_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC1, LTDC1_B2)
#error Invalid pin assignment for LTDC1 B2 pin: LTDC1_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC1, LTDC1_B3)
#error Invalid pin assignment for LTDC1 B3 pin: LTDC1_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC1, LTDC1_B4)
#error Invalid pin assignment for LTDC1 B4 pin: LTDC1_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC1, LTDC1_B5)
#error Invalid pin assignment for LTDC1 B5 pin: LTDC1_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC1, LTDC1_B6)
#error Invalid pin assignment for LTDC1 B6 pin: LTDC1_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC1, LTDC1_B7)
#error Invalid pin assignment for LTDC1 B7 pin: LTDC1_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC1, LTDC1_CLK)
#error Invalid pin assignment for LTDC1 CLK pin: LTDC1_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC1, LTDC1_DE)
#error Invalid pin assignment for LTDC1 DE pin: LTDC1_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC1, LTDC1_G0)
#error Invalid pin assignment for LTDC1 G0 pin: LTDC1_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC1, LTDC1_G1)
#error Invalid pin assignment for LTDC1 G1 pin: LTDC1_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC1, LTDC1_G2)
#error Invalid pin assignment for LTDC1 G2 pin: LTDC1_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC1, LTDC1_G3)
#error Invalid pin assignment for LTDC1 G3 pin: LTDC1_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC1, LTDC1_G4)
#error Invalid pin assignment for LTDC1 G4 pin: LTDC1_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC1, LTDC1_G5)
#error Invalid pin assignment for LTDC1 G5 pin: LTDC1_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC1, LTDC1_G6)
#error Invalid pin assignment for LTDC1 G6 pin: LTDC1_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC1, LTDC1_G7)
#error Invalid pin assignment for LTDC1 G7 pin: LTDC1_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC1, LTDC1_HSYNC)
#error Invalid pin assignment for LTDC1 HSYNC pin: LTDC1_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC1, LTDC1_R0)
#error Invalid pin assignment for LTDC1 R0 pin: LTDC1_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC1, LTDC1_R1)
#error Invalid pin assignment for LTDC1 R1 pin: LTDC1_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC1, LTDC1_R2)
#error Invalid pin assignment for LTDC1 R2 pin: LTDC1_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC1, LTDC1_R3)
#error Invalid pin assignment for LTDC1 R3 pin: LTDC1_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC1, LTDC1_R4)
#error Invalid pin assignment for LTDC1 R4 pin: LTDC1_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC1, LTDC1_R5)
#error Invalid pin assignment for LTDC1 R5 pin: LTDC1_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC1, LTDC1_R6)
#error Invalid pin assignment for LTDC1 R6 pin: LTDC1_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC1, LTDC1_R7)
#error Invalid pin assignment for LTDC1 R7 pin: LTDC1_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC1, LTDC1_VSYNC)
#error Invalid pin assignment for LTDC1 VSYNC pin: LTDC1_VSYNC
#endif
#endif

#ifdef USE_LTDC2
#if !FIND_VALUE_LTDC_B0(_LTDC2, LTDC2_B0)
#error Invalid pin assignment for LTDC2 B0 pin: LTDC2_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC2, LTDC2_B1)
#error Invalid pin assignment for LTDC2 B1 pin: LTDC2_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC2, LTDC2_B2)
#error Invalid pin assignment for LTDC2 B2 pin: LTDC2_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC2, LTDC2_B3)
#error Invalid pin assignment for LTDC2 B3 pin: LTDC2_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC2, LTDC2_B4)
#error Invalid pin assignment for LTDC2 B4 pin: LTDC2_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC2, LTDC2_B5)
#error Invalid pin assignment for LTDC2 B5 pin: LTDC2_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC2, LTDC2_B6)
#error Invalid pin assignment for LTDC2 B6 pin: LTDC2_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC2, LTDC2_B7)
#error Invalid pin assignment for LTDC2 B7 pin: LTDC2_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC2, LTDC2_CLK)
#error Invalid pin assignment for LTDC2 CLK pin: LTDC2_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC2, LTDC2_DE)
#error Invalid pin assignment for LTDC2 DE pin: LTDC2_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC2, LTDC2_G0)
#error Invalid pin assignment for LTDC2 G0 pin: LTDC2_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC2, LTDC2_G1)
#error Invalid pin assignment for LTDC2 G1 pin: LTDC2_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC2, LTDC2_G2)
#error Invalid pin assignment for LTDC2 G2 pin: LTDC2_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC2, LTDC2_G3)
#error Invalid pin assignment for LTDC2 G3 pin: LTDC2_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC2, LTDC2_G4)
#error Invalid pin assignment for LTDC2 G4 pin: LTDC2_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC2, LTDC2_G5)
#error Invalid pin assignment for LTDC2 G5 pin: LTDC2_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC2, LTDC2_G6)
#error Invalid pin assignment for LTDC2 G6 pin: LTDC2_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC2, LTDC2_G7)
#error Invalid pin assignment for LTDC2 G7 pin: LTDC2_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC2, LTDC2_HSYNC)
#error Invalid pin assignment for LTDC2 HSYNC pin: LTDC2_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC2, LTDC2_R0)
#error Invalid pin assignment for LTDC2 R0 pin: LTDC2_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC2, LTDC2_R1)
#error Invalid pin assignment for LTDC2 R1 pin: LTDC2_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC2, LTDC2_R2)
#error Invalid pin assignment for LTDC2 R2 pin: LTDC2_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC2, LTDC2_R3)
#error Invalid pin assignment for LTDC2 R3 pin: LTDC2_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC2, LTDC2_R4)
#error Invalid pin assignment for LTDC2 R4 pin: LTDC2_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC2, LTDC2_R5)
#error Invalid pin assignment for LTDC2 R5 pin: LTDC2_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC2, LTDC2_R6)
#error Invalid pin assignment for LTDC2 R6 pin: LTDC2_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC2, LTDC2_R7)
#error Invalid pin assignment for LTDC2 R7 pin: LTDC2_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC2, LTDC2_VSYNC)
#error Invalid pin assignment for LTDC2 VSYNC pin: LTDC2_VSYNC
#endif
#endif

#ifdef USE_LTDC3
#if !FIND_VALUE_LTDC_B0(_LTDC3, LTDC3_B0)
#error Invalid pin assignment for LTDC3 B0 pin: LTDC3_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC3, LTDC3_B1)
#error Invalid pin assignment for LTDC3 B1 pin: LTDC3_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC3, LTDC3_B2)
#error Invalid pin assignment for LTDC3 B2 pin: LTDC3_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC3, LTDC3_B3)
#error Invalid pin assignment for LTDC3 B3 pin: LTDC3_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC3, LTDC3_B4)
#error Invalid pin assignment for LTDC3 B4 pin: LTDC3_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC3, LTDC3_B5)
#error Invalid pin assignment for LTDC3 B5 pin: LTDC3_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC3, LTDC3_B6)
#error Invalid pin assignment for LTDC3 B6 pin: LTDC3_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC3, LTDC3_B7)
#error Invalid pin assignment for LTDC3 B7 pin: LTDC3_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC3, LTDC3_CLK)
#error Invalid pin assignment for LTDC3 CLK pin: LTDC3_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC3, LTDC3_DE)
#error Invalid pin assignment for LTDC3 DE pin: LTDC3_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC3, LTDC3_G0)
#error Invalid pin assignment for LTDC3 G0 pin: LTDC3_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC3, LTDC3_G1)
#error Invalid pin assignment for LTDC3 G1 pin: LTDC3_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC3, LTDC3_G2)
#error Invalid pin assignment for LTDC3 G2 pin: LTDC3_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC3, LTDC3_G3)
#error Invalid pin assignment for LTDC3 G3 pin: LTDC3_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC3, LTDC3_G4)
#error Invalid pin assignment for LTDC3 G4 pin: LTDC3_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC3, LTDC3_G5)
#error Invalid pin assignment for LTDC3 G5 pin: LTDC3_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC3, LTDC3_G6)
#error Invalid pin assignment for LTDC3 G6 pin: LTDC3_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC3, LTDC3_G7)
#error Invalid pin assignment for LTDC3 G7 pin: LTDC3_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC3, LTDC3_HSYNC)
#error Invalid pin assignment for LTDC3 HSYNC pin: LTDC3_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC3, LTDC3_R0)
#error Invalid pin assignment for LTDC3 R0 pin: LTDC3_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC3, LTDC3_R1)
#error Invalid pin assignment for LTDC3 R1 pin: LTDC3_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC3, LTDC3_R2)
#error Invalid pin assignment for LTDC3 R2 pin: LTDC3_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC3, LTDC3_R3)
#error Invalid pin assignment for LTDC3 R3 pin: LTDC3_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC3, LTDC3_R4)
#error Invalid pin assignment for LTDC3 R4 pin: LTDC3_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC3, LTDC3_R5)
#error Invalid pin assignment for LTDC3 R5 pin: LTDC3_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC3, LTDC3_R6)
#error Invalid pin assignment for LTDC3 R6 pin: LTDC3_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC3, LTDC3_R7)
#error Invalid pin assignment for LTDC3 R7 pin: LTDC3_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC3, LTDC3_VSYNC)
#error Invalid pin assignment for LTDC3 VSYNC pin: LTDC3_VSYNC
#endif
#endif

#ifdef USE_LTDC4
#if !FIND_VALUE_LTDC_B0(_LTDC4, LTDC4_B0)
#error Invalid pin assignment for LTDC4 B0 pin: LTDC4_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC4, LTDC4_B1)
#error Invalid pin assignment for LTDC4 B1 pin: LTDC4_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC4, LTDC4_B2)
#error Invalid pin assignment for LTDC4 B2 pin: LTDC4_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC4, LTDC4_B3)
#error Invalid pin assignment for LTDC4 B3 pin: LTDC4_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC4, LTDC4_B4)
#error Invalid pin assignment for LTDC4 B4 pin: LTDC4_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC4, LTDC4_B5)
#error Invalid pin assignment for LTDC4 B5 pin: LTDC4_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC4, LTDC4_B6)
#error Invalid pin assignment for LTDC4 B6 pin: LTDC4_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC4, LTDC4_B7)
#error Invalid pin assignment for LTDC4 B7 pin: LTDC4_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC4, LTDC4_CLK)
#error Invalid pin assignment for LTDC4 CLK pin: LTDC4_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC4, LTDC4_DE)
#error Invalid pin assignment for LTDC4 DE pin: LTDC4_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC4, LTDC4_G0)
#error Invalid pin assignment for LTDC4 G0 pin: LTDC4_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC4, LTDC4_G1)
#error Invalid pin assignment for LTDC4 G1 pin: LTDC4_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC4, LTDC4_G2)
#error Invalid pin assignment for LTDC4 G2 pin: LTDC4_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC4, LTDC4_G3)
#error Invalid pin assignment for LTDC4 G3 pin: LTDC4_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC4, LTDC4_G4)
#error Invalid pin assignment for LTDC4 G4 pin: LTDC4_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC4, LTDC4_G5)
#error Invalid pin assignment for LTDC4 G5 pin: LTDC4_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC4, LTDC4_G6)
#error Invalid pin assignment for LTDC4 G6 pin: LTDC4_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC4, LTDC4_G7)
#error Invalid pin assignment for LTDC4 G7 pin: LTDC4_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC4, LTDC4_HSYNC)
#error Invalid pin assignment for LTDC4 HSYNC pin: LTDC4_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC4, LTDC4_R0)
#error Invalid pin assignment for LTDC4 R0 pin: LTDC4_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC4, LTDC4_R1)
#error Invalid pin assignment for LTDC4 R1 pin: LTDC4_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC4, LTDC4_R2)
#error Invalid pin assignment for LTDC4 R2 pin: LTDC4_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC4, LTDC4_R3)
#error Invalid pin assignment for LTDC4 R3 pin: LTDC4_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC4, LTDC4_R4)
#error Invalid pin assignment for LTDC4 R4 pin: LTDC4_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC4, LTDC4_R5)
#error Invalid pin assignment for LTDC4 R5 pin: LTDC4_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC4, LTDC4_R6)
#error Invalid pin assignment for LTDC4 R6 pin: LTDC4_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC4, LTDC4_R7)
#error Invalid pin assignment for LTDC4 R7 pin: LTDC4_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC4, LTDC4_VSYNC)
#error Invalid pin assignment for LTDC4 VSYNC pin: LTDC4_VSYNC
#endif
#endif

#ifdef USE_LTDC5
#if !FIND_VALUE_LTDC_B0(_LTDC5, LTDC5_B0)
#error Invalid pin assignment for LTDC5 B0 pin: LTDC5_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC5, LTDC5_B1)
#error Invalid pin assignment for LTDC5 B1 pin: LTDC5_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC5, LTDC5_B2)
#error Invalid pin assignment for LTDC5 B2 pin: LTDC5_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC5, LTDC5_B3)
#error Invalid pin assignment for LTDC5 B3 pin: LTDC5_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC5, LTDC5_B4)
#error Invalid pin assignment for LTDC5 B4 pin: LTDC5_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC5, LTDC5_B5)
#error Invalid pin assignment for LTDC5 B5 pin: LTDC5_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC5, LTDC5_B6)
#error Invalid pin assignment for LTDC5 B6 pin: LTDC5_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC5, LTDC5_B7)
#error Invalid pin assignment for LTDC5 B7 pin: LTDC5_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC5, LTDC5_CLK)
#error Invalid pin assignment for LTDC5 CLK pin: LTDC5_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC5, LTDC5_DE)
#error Invalid pin assignment for LTDC5 DE pin: LTDC5_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC5, LTDC5_G0)
#error Invalid pin assignment for LTDC5 G0 pin: LTDC5_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC5, LTDC5_G1)
#error Invalid pin assignment for LTDC5 G1 pin: LTDC5_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC5, LTDC5_G2)
#error Invalid pin assignment for LTDC5 G2 pin: LTDC5_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC5, LTDC5_G3)
#error Invalid pin assignment for LTDC5 G3 pin: LTDC5_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC5, LTDC5_G4)
#error Invalid pin assignment for LTDC5 G4 pin: LTDC5_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC5, LTDC5_G5)
#error Invalid pin assignment for LTDC5 G5 pin: LTDC5_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC5, LTDC5_G6)
#error Invalid pin assignment for LTDC5 G6 pin: LTDC5_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC5, LTDC5_G7)
#error Invalid pin assignment for LTDC5 G7 pin: LTDC5_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC5, LTDC5_HSYNC)
#error Invalid pin assignment for LTDC5 HSYNC pin: LTDC5_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC5, LTDC5_R0)
#error Invalid pin assignment for LTDC5 R0 pin: LTDC5_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC5, LTDC5_R1)
#error Invalid pin assignment for LTDC5 R1 pin: LTDC5_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC5, LTDC5_R2)
#error Invalid pin assignment for LTDC5 R2 pin: LTDC5_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC5, LTDC5_R3)
#error Invalid pin assignment for LTDC5 R3 pin: LTDC5_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC5, LTDC5_R4)
#error Invalid pin assignment for LTDC5 R4 pin: LTDC5_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC5, LTDC5_R5)
#error Invalid pin assignment for LTDC5 R5 pin: LTDC5_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC5, LTDC5_R6)
#error Invalid pin assignment for LTDC5 R6 pin: LTDC5_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC5, LTDC5_R7)
#error Invalid pin assignment for LTDC5 R7 pin: LTDC5_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC5, LTDC5_VSYNC)
#error Invalid pin assignment for LTDC5 VSYNC pin: LTDC5_VSYNC
#endif
#endif

#ifdef USE_LTDC6
#if !FIND_VALUE_LTDC_B0(_LTDC6, LTDC6_B0)
#error Invalid pin assignment for LTDC6 B0 pin: LTDC6_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC6, LTDC6_B1)
#error Invalid pin assignment for LTDC6 B1 pin: LTDC6_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC6, LTDC6_B2)
#error Invalid pin assignment for LTDC6 B2 pin: LTDC6_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC6, LTDC6_B3)
#error Invalid pin assignment for LTDC6 B3 pin: LTDC6_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC6, LTDC6_B4)
#error Invalid pin assignment for LTDC6 B4 pin: LTDC6_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC6, LTDC6_B5)
#error Invalid pin assignment for LTDC6 B5 pin: LTDC6_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC6, LTDC6_B6)
#error Invalid pin assignment for LTDC6 B6 pin: LTDC6_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC6, LTDC6_B7)
#error Invalid pin assignment for LTDC6 B7 pin: LTDC6_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC6, LTDC6_CLK)
#error Invalid pin assignment for LTDC6 CLK pin: LTDC6_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC6, LTDC6_DE)
#error Invalid pin assignment for LTDC6 DE pin: LTDC6_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC6, LTDC6_G0)
#error Invalid pin assignment for LTDC6 G0 pin: LTDC6_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC6, LTDC6_G1)
#error Invalid pin assignment for LTDC6 G1 pin: LTDC6_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC6, LTDC6_G2)
#error Invalid pin assignment for LTDC6 G2 pin: LTDC6_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC6, LTDC6_G3)
#error Invalid pin assignment for LTDC6 G3 pin: LTDC6_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC6, LTDC6_G4)
#error Invalid pin assignment for LTDC6 G4 pin: LTDC6_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC6, LTDC6_G5)
#error Invalid pin assignment for LTDC6 G5 pin: LTDC6_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC6, LTDC6_G6)
#error Invalid pin assignment for LTDC6 G6 pin: LTDC6_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC6, LTDC6_G7)
#error Invalid pin assignment for LTDC6 G7 pin: LTDC6_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC6, LTDC6_HSYNC)
#error Invalid pin assignment for LTDC6 HSYNC pin: LTDC6_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC6, LTDC6_R0)
#error Invalid pin assignment for LTDC6 R0 pin: LTDC6_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC6, LTDC6_R1)
#error Invalid pin assignment for LTDC6 R1 pin: LTDC6_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC6, LTDC6_R2)
#error Invalid pin assignment for LTDC6 R2 pin: LTDC6_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC6, LTDC6_R3)
#error Invalid pin assignment for LTDC6 R3 pin: LTDC6_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC6, LTDC6_R4)
#error Invalid pin assignment for LTDC6 R4 pin: LTDC6_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC6, LTDC6_R5)
#error Invalid pin assignment for LTDC6 R5 pin: LTDC6_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC6, LTDC6_R6)
#error Invalid pin assignment for LTDC6 R6 pin: LTDC6_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC6, LTDC6_R7)
#error Invalid pin assignment for LTDC6 R7 pin: LTDC6_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC6, LTDC6_VSYNC)
#error Invalid pin assignment for LTDC6 VSYNC pin: LTDC6_VSYNC
#endif
#endif

