/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.405018
 */

#define FIND_VALUE_SYS_V_REF_OUT_inner(INDEX,PIN) I2C##_SYS_V_REF_##PIN
#define FIND_VALUE_SYS_V_REF_OUT(INDEX,PIN) FIND_VALUE_SYS_V_REF_OUT_inner(INDEX,PIN)

#ifdef USE_SYS_V_REF0
#if !FIND_VALUE_SYS_V_REF_OUT(_SYS_V_REF0, SYS_V_REF0_OUT)
#error Invalid pin assignment for SYS_V_REF0 OUT pin: SYS_V_REF0_OUT
#endif
#endif

