/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398076
 */

#define FIND_VALUE_COMP_TIM_BKIN_inner(INDEX,PIN) I2C##_COMP_TIM_##PIN
#define FIND_VALUE_COMP_TIM_BKIN(INDEX,PIN) FIND_VALUE_COMP_TIM_BKIN_inner(INDEX,PIN)

#ifdef USE_COMP_TIM0
#if !FIND_VALUE_COMP_TIM_BKIN(_COMP_TIM0, COMP_TIM0_BKIN)
#error Invalid pin assignment for COMP_TIM0 BKIN pin: COMP_TIM0_BKIN
#endif
#endif

