/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398647
 */

#define FIND_VALUE_DEBUG_JTDO_SWO_inner(INDEX,PIN) I2C##_DEBUG_JTDO_##PIN
#define FIND_VALUE_DEBUG_JTDO_SWO(INDEX,PIN) FIND_VALUE_DEBUG_JTDO_SWO_inner(INDEX,PIN)

#ifdef USE_DEBUG_JTDO0
#if !FIND_VALUE_DEBUG_JTDO_SWO(_DEBUG_JTDO0, DEBUG_JTDO0_SWO)
#error Invalid pin assignment for DEBUG_JTDO0 SWO pin: DEBUG_JTDO0_SWO
#endif
#endif

