/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398660
 */

#define FIND_VALUE_DEBUG_JTMS_SWDIO_inner(INDEX,PIN) I2C##_DEBUG_JTMS_##PIN
#define FIND_VALUE_DEBUG_JTMS_SWDIO(INDEX,PIN) FIND_VALUE_DEBUG_JTMS_SWDIO_inner(INDEX,PIN)

#ifdef USE_DEBUG_JTMS0
#if !FIND_VALUE_DEBUG_JTMS_SWDIO(_DEBUG_JTMS0, DEBUG_JTMS0_SWDIO)
#error Invalid pin assignment for DEBUG_JTMS0 SWDIO pin: DEBUG_JTMS0_SWDIO
#endif
#endif

