/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404953
 */

#define FIND_VALUE_SYS_IR_Out_inner(INDEX,PIN) I2C##_SYS_IR_##PIN
#define FIND_VALUE_SYS_IR_Out(INDEX,PIN) FIND_VALUE_SYS_IR_Out_inner(INDEX,PIN)

#ifdef USE_SYS_IR0
#if !FIND_VALUE_SYS_IR_Out(_SYS_IR0, SYS_IR0_Out)
#error Invalid pin assignment for SYS_IR0 Out pin: SYS_IR0_Out
#endif
#endif

