/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404507
 */

#define FIND_VALUE_SYS_CAN_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_CAN(INDEX,PIN) FIND_VALUE_SYS_CAN_inner(INDEX,PIN)

#define FIND_VALUE_SYS_COMP_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_COMP(INDEX,PIN) FIND_VALUE_SYS_COMP_inner(INDEX,PIN)

#define FIND_VALUE_SYS_DAC_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_DAC(INDEX,PIN) FIND_VALUE_SYS_DAC_inner(INDEX,PIN)

#define FIND_VALUE_SYS_I2C_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_I2C(INDEX,PIN) FIND_VALUE_SYS_I2C_inner(INDEX,PIN)

#define FIND_VALUE_SYS_JTDI_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_JTDI(INDEX,PIN) FIND_VALUE_SYS_JTDI_inner(INDEX,PIN)

#define FIND_VALUE_SYS_JTRST_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_JTRST(INDEX,PIN) FIND_VALUE_SYS_JTRST_inner(INDEX,PIN)

#define FIND_VALUE_SYS_NJTRST_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_NJTRST(INDEX,PIN) FIND_VALUE_SYS_NJTRST_inner(INDEX,PIN)

#define FIND_VALUE_SYS_SLEEP_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_SLEEP(INDEX,PIN) FIND_VALUE_SYS_SLEEP_inner(INDEX,PIN)

#define FIND_VALUE_SYS_SPI_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_SPI(INDEX,PIN) FIND_VALUE_SYS_SPI_inner(INDEX,PIN)

#define FIND_VALUE_SYS_SWCLK_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_SWCLK(INDEX,PIN) FIND_VALUE_SYS_SWCLK_inner(INDEX,PIN)

#define FIND_VALUE_SYS_SWDIO_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_SWDIO(INDEX,PIN) FIND_VALUE_SYS_SWDIO_inner(INDEX,PIN)

#define FIND_VALUE_SYS_SYSTEM_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_SYSTEM(INDEX,PIN) FIND_VALUE_SYS_SYSTEM_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM1_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM1(INDEX,PIN) FIND_VALUE_SYS_TIM1_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM14_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM14(INDEX,PIN) FIND_VALUE_SYS_TIM14_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM15_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM15(INDEX,PIN) FIND_VALUE_SYS_TIM15_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM16_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM16(INDEX,PIN) FIND_VALUE_SYS_TIM16_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM17_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM17(INDEX,PIN) FIND_VALUE_SYS_TIM17_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM2_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM2(INDEX,PIN) FIND_VALUE_SYS_TIM2_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TIM3_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TIM3(INDEX,PIN) FIND_VALUE_SYS_TIM3_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TOUCH_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TOUCH(INDEX,PIN) FIND_VALUE_SYS_TOUCH_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TRACECK_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TRACECK(INDEX,PIN) FIND_VALUE_SYS_TRACECK_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TRACECLK_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TRACECLK(INDEX,PIN) FIND_VALUE_SYS_TRACECLK_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TRACED0_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TRACED0(INDEX,PIN) FIND_VALUE_SYS_TRACED0_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TRACED1_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TRACED1(INDEX,PIN) FIND_VALUE_SYS_TRACED1_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TRACED2_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TRACED2(INDEX,PIN) FIND_VALUE_SYS_TRACED2_inner(INDEX,PIN)

#define FIND_VALUE_SYS_TRACED3_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_TRACED3(INDEX,PIN) FIND_VALUE_SYS_TRACED3_inner(INDEX,PIN)

#define FIND_VALUE_SYS_USART_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_USART(INDEX,PIN) FIND_VALUE_SYS_USART_inner(INDEX,PIN)

#define FIND_VALUE_SYS_WKUP_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_WKUP(INDEX,PIN) FIND_VALUE_SYS_WKUP_inner(INDEX,PIN)

#define FIND_VALUE_SYS_WKUP1_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_WKUP1(INDEX,PIN) FIND_VALUE_SYS_WKUP1_inner(INDEX,PIN)

#define FIND_VALUE_SYS_WKUP2_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_WKUP2(INDEX,PIN) FIND_VALUE_SYS_WKUP2_inner(INDEX,PIN)

#define FIND_VALUE_SYS_WKUP3_inner(INDEX,PIN) I2C##_SYS_##PIN
#define FIND_VALUE_SYS_WKUP3(INDEX,PIN) FIND_VALUE_SYS_WKUP3_inner(INDEX,PIN)

#ifdef USE_SYS0
#if !FIND_VALUE_SYS_CAN(_SYS0, SYS0_CAN)
#error Invalid pin assignment for SYS0 CAN pin: SYS0_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS0, SYS0_COMP)
#error Invalid pin assignment for SYS0 COMP pin: SYS0_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS0, SYS0_DAC)
#error Invalid pin assignment for SYS0 DAC pin: SYS0_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS0, SYS0_I2C)
#error Invalid pin assignment for SYS0 I2C pin: SYS0_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS0, SYS0_JTDI)
#error Invalid pin assignment for SYS0 JTDI pin: SYS0_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS0, SYS0_JTRST)
#error Invalid pin assignment for SYS0 JTRST pin: SYS0_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS0, SYS0_NJTRST)
#error Invalid pin assignment for SYS0 NJTRST pin: SYS0_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS0, SYS0_SLEEP)
#error Invalid pin assignment for SYS0 SLEEP pin: SYS0_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS0, SYS0_SPI)
#error Invalid pin assignment for SYS0 SPI pin: SYS0_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS0, SYS0_SWCLK)
#error Invalid pin assignment for SYS0 SWCLK pin: SYS0_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS0, SYS0_SWDIO)
#error Invalid pin assignment for SYS0 SWDIO pin: SYS0_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS0, SYS0_SYSTEM)
#error Invalid pin assignment for SYS0 SYSTEM pin: SYS0_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS0, SYS0_TIM1)
#error Invalid pin assignment for SYS0 TIM1 pin: SYS0_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS0, SYS0_TIM14)
#error Invalid pin assignment for SYS0 TIM14 pin: SYS0_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS0, SYS0_TIM15)
#error Invalid pin assignment for SYS0 TIM15 pin: SYS0_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS0, SYS0_TIM16)
#error Invalid pin assignment for SYS0 TIM16 pin: SYS0_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS0, SYS0_TIM17)
#error Invalid pin assignment for SYS0 TIM17 pin: SYS0_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS0, SYS0_TIM2)
#error Invalid pin assignment for SYS0 TIM2 pin: SYS0_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS0, SYS0_TIM3)
#error Invalid pin assignment for SYS0 TIM3 pin: SYS0_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS0, SYS0_TOUCH)
#error Invalid pin assignment for SYS0 TOUCH pin: SYS0_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS0, SYS0_TRACECK)
#error Invalid pin assignment for SYS0 TRACECK pin: SYS0_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS0, SYS0_TRACECLK)
#error Invalid pin assignment for SYS0 TRACECLK pin: SYS0_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS0, SYS0_TRACED0)
#error Invalid pin assignment for SYS0 TRACED0 pin: SYS0_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS0, SYS0_TRACED1)
#error Invalid pin assignment for SYS0 TRACED1 pin: SYS0_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS0, SYS0_TRACED2)
#error Invalid pin assignment for SYS0 TRACED2 pin: SYS0_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS0, SYS0_TRACED3)
#error Invalid pin assignment for SYS0 TRACED3 pin: SYS0_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS0, SYS0_USART)
#error Invalid pin assignment for SYS0 USART pin: SYS0_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS0, SYS0_WKUP)
#error Invalid pin assignment for SYS0 WKUP pin: SYS0_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS0, SYS0_WKUP1)
#error Invalid pin assignment for SYS0 WKUP1 pin: SYS0_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS0, SYS0_WKUP2)
#error Invalid pin assignment for SYS0 WKUP2 pin: SYS0_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS0, SYS0_WKUP3)
#error Invalid pin assignment for SYS0 WKUP3 pin: SYS0_WKUP3
#endif
#endif

#ifdef USE_SYS1
#if !FIND_VALUE_SYS_CAN(_SYS1, SYS1_CAN)
#error Invalid pin assignment for SYS1 CAN pin: SYS1_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS1, SYS1_COMP)
#error Invalid pin assignment for SYS1 COMP pin: SYS1_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS1, SYS1_DAC)
#error Invalid pin assignment for SYS1 DAC pin: SYS1_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS1, SYS1_I2C)
#error Invalid pin assignment for SYS1 I2C pin: SYS1_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS1, SYS1_JTDI)
#error Invalid pin assignment for SYS1 JTDI pin: SYS1_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS1, SYS1_JTRST)
#error Invalid pin assignment for SYS1 JTRST pin: SYS1_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS1, SYS1_NJTRST)
#error Invalid pin assignment for SYS1 NJTRST pin: SYS1_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS1, SYS1_SLEEP)
#error Invalid pin assignment for SYS1 SLEEP pin: SYS1_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS1, SYS1_SPI)
#error Invalid pin assignment for SYS1 SPI pin: SYS1_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS1, SYS1_SWCLK)
#error Invalid pin assignment for SYS1 SWCLK pin: SYS1_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS1, SYS1_SWDIO)
#error Invalid pin assignment for SYS1 SWDIO pin: SYS1_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS1, SYS1_SYSTEM)
#error Invalid pin assignment for SYS1 SYSTEM pin: SYS1_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS1, SYS1_TIM1)
#error Invalid pin assignment for SYS1 TIM1 pin: SYS1_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS1, SYS1_TIM14)
#error Invalid pin assignment for SYS1 TIM14 pin: SYS1_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS1, SYS1_TIM15)
#error Invalid pin assignment for SYS1 TIM15 pin: SYS1_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS1, SYS1_TIM16)
#error Invalid pin assignment for SYS1 TIM16 pin: SYS1_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS1, SYS1_TIM17)
#error Invalid pin assignment for SYS1 TIM17 pin: SYS1_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS1, SYS1_TIM2)
#error Invalid pin assignment for SYS1 TIM2 pin: SYS1_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS1, SYS1_TIM3)
#error Invalid pin assignment for SYS1 TIM3 pin: SYS1_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS1, SYS1_TOUCH)
#error Invalid pin assignment for SYS1 TOUCH pin: SYS1_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS1, SYS1_TRACECK)
#error Invalid pin assignment for SYS1 TRACECK pin: SYS1_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS1, SYS1_TRACECLK)
#error Invalid pin assignment for SYS1 TRACECLK pin: SYS1_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS1, SYS1_TRACED0)
#error Invalid pin assignment for SYS1 TRACED0 pin: SYS1_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS1, SYS1_TRACED1)
#error Invalid pin assignment for SYS1 TRACED1 pin: SYS1_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS1, SYS1_TRACED2)
#error Invalid pin assignment for SYS1 TRACED2 pin: SYS1_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS1, SYS1_TRACED3)
#error Invalid pin assignment for SYS1 TRACED3 pin: SYS1_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS1, SYS1_USART)
#error Invalid pin assignment for SYS1 USART pin: SYS1_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS1, SYS1_WKUP)
#error Invalid pin assignment for SYS1 WKUP pin: SYS1_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS1, SYS1_WKUP1)
#error Invalid pin assignment for SYS1 WKUP1 pin: SYS1_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS1, SYS1_WKUP2)
#error Invalid pin assignment for SYS1 WKUP2 pin: SYS1_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS1, SYS1_WKUP3)
#error Invalid pin assignment for SYS1 WKUP3 pin: SYS1_WKUP3
#endif
#endif

#ifdef USE_SYS2
#if !FIND_VALUE_SYS_CAN(_SYS2, SYS2_CAN)
#error Invalid pin assignment for SYS2 CAN pin: SYS2_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS2, SYS2_COMP)
#error Invalid pin assignment for SYS2 COMP pin: SYS2_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS2, SYS2_DAC)
#error Invalid pin assignment for SYS2 DAC pin: SYS2_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS2, SYS2_I2C)
#error Invalid pin assignment for SYS2 I2C pin: SYS2_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS2, SYS2_JTDI)
#error Invalid pin assignment for SYS2 JTDI pin: SYS2_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS2, SYS2_JTRST)
#error Invalid pin assignment for SYS2 JTRST pin: SYS2_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS2, SYS2_NJTRST)
#error Invalid pin assignment for SYS2 NJTRST pin: SYS2_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS2, SYS2_SLEEP)
#error Invalid pin assignment for SYS2 SLEEP pin: SYS2_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS2, SYS2_SPI)
#error Invalid pin assignment for SYS2 SPI pin: SYS2_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS2, SYS2_SWCLK)
#error Invalid pin assignment for SYS2 SWCLK pin: SYS2_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS2, SYS2_SWDIO)
#error Invalid pin assignment for SYS2 SWDIO pin: SYS2_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS2, SYS2_SYSTEM)
#error Invalid pin assignment for SYS2 SYSTEM pin: SYS2_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS2, SYS2_TIM1)
#error Invalid pin assignment for SYS2 TIM1 pin: SYS2_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS2, SYS2_TIM14)
#error Invalid pin assignment for SYS2 TIM14 pin: SYS2_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS2, SYS2_TIM15)
#error Invalid pin assignment for SYS2 TIM15 pin: SYS2_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS2, SYS2_TIM16)
#error Invalid pin assignment for SYS2 TIM16 pin: SYS2_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS2, SYS2_TIM17)
#error Invalid pin assignment for SYS2 TIM17 pin: SYS2_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS2, SYS2_TIM2)
#error Invalid pin assignment for SYS2 TIM2 pin: SYS2_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS2, SYS2_TIM3)
#error Invalid pin assignment for SYS2 TIM3 pin: SYS2_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS2, SYS2_TOUCH)
#error Invalid pin assignment for SYS2 TOUCH pin: SYS2_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS2, SYS2_TRACECK)
#error Invalid pin assignment for SYS2 TRACECK pin: SYS2_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS2, SYS2_TRACECLK)
#error Invalid pin assignment for SYS2 TRACECLK pin: SYS2_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS2, SYS2_TRACED0)
#error Invalid pin assignment for SYS2 TRACED0 pin: SYS2_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS2, SYS2_TRACED1)
#error Invalid pin assignment for SYS2 TRACED1 pin: SYS2_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS2, SYS2_TRACED2)
#error Invalid pin assignment for SYS2 TRACED2 pin: SYS2_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS2, SYS2_TRACED3)
#error Invalid pin assignment for SYS2 TRACED3 pin: SYS2_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS2, SYS2_USART)
#error Invalid pin assignment for SYS2 USART pin: SYS2_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS2, SYS2_WKUP)
#error Invalid pin assignment for SYS2 WKUP pin: SYS2_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS2, SYS2_WKUP1)
#error Invalid pin assignment for SYS2 WKUP1 pin: SYS2_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS2, SYS2_WKUP2)
#error Invalid pin assignment for SYS2 WKUP2 pin: SYS2_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS2, SYS2_WKUP3)
#error Invalid pin assignment for SYS2 WKUP3 pin: SYS2_WKUP3
#endif
#endif

#ifdef USE_SYS3
#if !FIND_VALUE_SYS_CAN(_SYS3, SYS3_CAN)
#error Invalid pin assignment for SYS3 CAN pin: SYS3_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS3, SYS3_COMP)
#error Invalid pin assignment for SYS3 COMP pin: SYS3_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS3, SYS3_DAC)
#error Invalid pin assignment for SYS3 DAC pin: SYS3_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS3, SYS3_I2C)
#error Invalid pin assignment for SYS3 I2C pin: SYS3_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS3, SYS3_JTDI)
#error Invalid pin assignment for SYS3 JTDI pin: SYS3_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS3, SYS3_JTRST)
#error Invalid pin assignment for SYS3 JTRST pin: SYS3_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS3, SYS3_NJTRST)
#error Invalid pin assignment for SYS3 NJTRST pin: SYS3_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS3, SYS3_SLEEP)
#error Invalid pin assignment for SYS3 SLEEP pin: SYS3_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS3, SYS3_SPI)
#error Invalid pin assignment for SYS3 SPI pin: SYS3_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS3, SYS3_SWCLK)
#error Invalid pin assignment for SYS3 SWCLK pin: SYS3_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS3, SYS3_SWDIO)
#error Invalid pin assignment for SYS3 SWDIO pin: SYS3_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS3, SYS3_SYSTEM)
#error Invalid pin assignment for SYS3 SYSTEM pin: SYS3_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS3, SYS3_TIM1)
#error Invalid pin assignment for SYS3 TIM1 pin: SYS3_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS3, SYS3_TIM14)
#error Invalid pin assignment for SYS3 TIM14 pin: SYS3_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS3, SYS3_TIM15)
#error Invalid pin assignment for SYS3 TIM15 pin: SYS3_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS3, SYS3_TIM16)
#error Invalid pin assignment for SYS3 TIM16 pin: SYS3_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS3, SYS3_TIM17)
#error Invalid pin assignment for SYS3 TIM17 pin: SYS3_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS3, SYS3_TIM2)
#error Invalid pin assignment for SYS3 TIM2 pin: SYS3_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS3, SYS3_TIM3)
#error Invalid pin assignment for SYS3 TIM3 pin: SYS3_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS3, SYS3_TOUCH)
#error Invalid pin assignment for SYS3 TOUCH pin: SYS3_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS3, SYS3_TRACECK)
#error Invalid pin assignment for SYS3 TRACECK pin: SYS3_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS3, SYS3_TRACECLK)
#error Invalid pin assignment for SYS3 TRACECLK pin: SYS3_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS3, SYS3_TRACED0)
#error Invalid pin assignment for SYS3 TRACED0 pin: SYS3_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS3, SYS3_TRACED1)
#error Invalid pin assignment for SYS3 TRACED1 pin: SYS3_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS3, SYS3_TRACED2)
#error Invalid pin assignment for SYS3 TRACED2 pin: SYS3_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS3, SYS3_TRACED3)
#error Invalid pin assignment for SYS3 TRACED3 pin: SYS3_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS3, SYS3_USART)
#error Invalid pin assignment for SYS3 USART pin: SYS3_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS3, SYS3_WKUP)
#error Invalid pin assignment for SYS3 WKUP pin: SYS3_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS3, SYS3_WKUP1)
#error Invalid pin assignment for SYS3 WKUP1 pin: SYS3_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS3, SYS3_WKUP2)
#error Invalid pin assignment for SYS3 WKUP2 pin: SYS3_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS3, SYS3_WKUP3)
#error Invalid pin assignment for SYS3 WKUP3 pin: SYS3_WKUP3
#endif
#endif

#ifdef USE_SYS4
#if !FIND_VALUE_SYS_CAN(_SYS4, SYS4_CAN)
#error Invalid pin assignment for SYS4 CAN pin: SYS4_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS4, SYS4_COMP)
#error Invalid pin assignment for SYS4 COMP pin: SYS4_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS4, SYS4_DAC)
#error Invalid pin assignment for SYS4 DAC pin: SYS4_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS4, SYS4_I2C)
#error Invalid pin assignment for SYS4 I2C pin: SYS4_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS4, SYS4_JTDI)
#error Invalid pin assignment for SYS4 JTDI pin: SYS4_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS4, SYS4_JTRST)
#error Invalid pin assignment for SYS4 JTRST pin: SYS4_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS4, SYS4_NJTRST)
#error Invalid pin assignment for SYS4 NJTRST pin: SYS4_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS4, SYS4_SLEEP)
#error Invalid pin assignment for SYS4 SLEEP pin: SYS4_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS4, SYS4_SPI)
#error Invalid pin assignment for SYS4 SPI pin: SYS4_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS4, SYS4_SWCLK)
#error Invalid pin assignment for SYS4 SWCLK pin: SYS4_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS4, SYS4_SWDIO)
#error Invalid pin assignment for SYS4 SWDIO pin: SYS4_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS4, SYS4_SYSTEM)
#error Invalid pin assignment for SYS4 SYSTEM pin: SYS4_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS4, SYS4_TIM1)
#error Invalid pin assignment for SYS4 TIM1 pin: SYS4_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS4, SYS4_TIM14)
#error Invalid pin assignment for SYS4 TIM14 pin: SYS4_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS4, SYS4_TIM15)
#error Invalid pin assignment for SYS4 TIM15 pin: SYS4_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS4, SYS4_TIM16)
#error Invalid pin assignment for SYS4 TIM16 pin: SYS4_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS4, SYS4_TIM17)
#error Invalid pin assignment for SYS4 TIM17 pin: SYS4_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS4, SYS4_TIM2)
#error Invalid pin assignment for SYS4 TIM2 pin: SYS4_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS4, SYS4_TIM3)
#error Invalid pin assignment for SYS4 TIM3 pin: SYS4_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS4, SYS4_TOUCH)
#error Invalid pin assignment for SYS4 TOUCH pin: SYS4_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS4, SYS4_TRACECK)
#error Invalid pin assignment for SYS4 TRACECK pin: SYS4_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS4, SYS4_TRACECLK)
#error Invalid pin assignment for SYS4 TRACECLK pin: SYS4_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS4, SYS4_TRACED0)
#error Invalid pin assignment for SYS4 TRACED0 pin: SYS4_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS4, SYS4_TRACED1)
#error Invalid pin assignment for SYS4 TRACED1 pin: SYS4_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS4, SYS4_TRACED2)
#error Invalid pin assignment for SYS4 TRACED2 pin: SYS4_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS4, SYS4_TRACED3)
#error Invalid pin assignment for SYS4 TRACED3 pin: SYS4_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS4, SYS4_USART)
#error Invalid pin assignment for SYS4 USART pin: SYS4_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS4, SYS4_WKUP)
#error Invalid pin assignment for SYS4 WKUP pin: SYS4_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS4, SYS4_WKUP1)
#error Invalid pin assignment for SYS4 WKUP1 pin: SYS4_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS4, SYS4_WKUP2)
#error Invalid pin assignment for SYS4 WKUP2 pin: SYS4_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS4, SYS4_WKUP3)
#error Invalid pin assignment for SYS4 WKUP3 pin: SYS4_WKUP3
#endif
#endif

#ifdef USE_SYS5
#if !FIND_VALUE_SYS_CAN(_SYS5, SYS5_CAN)
#error Invalid pin assignment for SYS5 CAN pin: SYS5_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS5, SYS5_COMP)
#error Invalid pin assignment for SYS5 COMP pin: SYS5_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS5, SYS5_DAC)
#error Invalid pin assignment for SYS5 DAC pin: SYS5_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS5, SYS5_I2C)
#error Invalid pin assignment for SYS5 I2C pin: SYS5_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS5, SYS5_JTDI)
#error Invalid pin assignment for SYS5 JTDI pin: SYS5_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS5, SYS5_JTRST)
#error Invalid pin assignment for SYS5 JTRST pin: SYS5_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS5, SYS5_NJTRST)
#error Invalid pin assignment for SYS5 NJTRST pin: SYS5_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS5, SYS5_SLEEP)
#error Invalid pin assignment for SYS5 SLEEP pin: SYS5_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS5, SYS5_SPI)
#error Invalid pin assignment for SYS5 SPI pin: SYS5_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS5, SYS5_SWCLK)
#error Invalid pin assignment for SYS5 SWCLK pin: SYS5_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS5, SYS5_SWDIO)
#error Invalid pin assignment for SYS5 SWDIO pin: SYS5_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS5, SYS5_SYSTEM)
#error Invalid pin assignment for SYS5 SYSTEM pin: SYS5_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS5, SYS5_TIM1)
#error Invalid pin assignment for SYS5 TIM1 pin: SYS5_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS5, SYS5_TIM14)
#error Invalid pin assignment for SYS5 TIM14 pin: SYS5_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS5, SYS5_TIM15)
#error Invalid pin assignment for SYS5 TIM15 pin: SYS5_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS5, SYS5_TIM16)
#error Invalid pin assignment for SYS5 TIM16 pin: SYS5_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS5, SYS5_TIM17)
#error Invalid pin assignment for SYS5 TIM17 pin: SYS5_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS5, SYS5_TIM2)
#error Invalid pin assignment for SYS5 TIM2 pin: SYS5_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS5, SYS5_TIM3)
#error Invalid pin assignment for SYS5 TIM3 pin: SYS5_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS5, SYS5_TOUCH)
#error Invalid pin assignment for SYS5 TOUCH pin: SYS5_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS5, SYS5_TRACECK)
#error Invalid pin assignment for SYS5 TRACECK pin: SYS5_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS5, SYS5_TRACECLK)
#error Invalid pin assignment for SYS5 TRACECLK pin: SYS5_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS5, SYS5_TRACED0)
#error Invalid pin assignment for SYS5 TRACED0 pin: SYS5_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS5, SYS5_TRACED1)
#error Invalid pin assignment for SYS5 TRACED1 pin: SYS5_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS5, SYS5_TRACED2)
#error Invalid pin assignment for SYS5 TRACED2 pin: SYS5_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS5, SYS5_TRACED3)
#error Invalid pin assignment for SYS5 TRACED3 pin: SYS5_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS5, SYS5_USART)
#error Invalid pin assignment for SYS5 USART pin: SYS5_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS5, SYS5_WKUP)
#error Invalid pin assignment for SYS5 WKUP pin: SYS5_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS5, SYS5_WKUP1)
#error Invalid pin assignment for SYS5 WKUP1 pin: SYS5_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS5, SYS5_WKUP2)
#error Invalid pin assignment for SYS5 WKUP2 pin: SYS5_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS5, SYS5_WKUP3)
#error Invalid pin assignment for SYS5 WKUP3 pin: SYS5_WKUP3
#endif
#endif

#ifdef USE_SYS6
#if !FIND_VALUE_SYS_CAN(_SYS6, SYS6_CAN)
#error Invalid pin assignment for SYS6 CAN pin: SYS6_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS6, SYS6_COMP)
#error Invalid pin assignment for SYS6 COMP pin: SYS6_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS6, SYS6_DAC)
#error Invalid pin assignment for SYS6 DAC pin: SYS6_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS6, SYS6_I2C)
#error Invalid pin assignment for SYS6 I2C pin: SYS6_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS6, SYS6_JTDI)
#error Invalid pin assignment for SYS6 JTDI pin: SYS6_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS6, SYS6_JTRST)
#error Invalid pin assignment for SYS6 JTRST pin: SYS6_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS6, SYS6_NJTRST)
#error Invalid pin assignment for SYS6 NJTRST pin: SYS6_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS6, SYS6_SLEEP)
#error Invalid pin assignment for SYS6 SLEEP pin: SYS6_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS6, SYS6_SPI)
#error Invalid pin assignment for SYS6 SPI pin: SYS6_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS6, SYS6_SWCLK)
#error Invalid pin assignment for SYS6 SWCLK pin: SYS6_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS6, SYS6_SWDIO)
#error Invalid pin assignment for SYS6 SWDIO pin: SYS6_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS6, SYS6_SYSTEM)
#error Invalid pin assignment for SYS6 SYSTEM pin: SYS6_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS6, SYS6_TIM1)
#error Invalid pin assignment for SYS6 TIM1 pin: SYS6_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS6, SYS6_TIM14)
#error Invalid pin assignment for SYS6 TIM14 pin: SYS6_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS6, SYS6_TIM15)
#error Invalid pin assignment for SYS6 TIM15 pin: SYS6_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS6, SYS6_TIM16)
#error Invalid pin assignment for SYS6 TIM16 pin: SYS6_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS6, SYS6_TIM17)
#error Invalid pin assignment for SYS6 TIM17 pin: SYS6_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS6, SYS6_TIM2)
#error Invalid pin assignment for SYS6 TIM2 pin: SYS6_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS6, SYS6_TIM3)
#error Invalid pin assignment for SYS6 TIM3 pin: SYS6_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS6, SYS6_TOUCH)
#error Invalid pin assignment for SYS6 TOUCH pin: SYS6_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS6, SYS6_TRACECK)
#error Invalid pin assignment for SYS6 TRACECK pin: SYS6_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS6, SYS6_TRACECLK)
#error Invalid pin assignment for SYS6 TRACECLK pin: SYS6_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS6, SYS6_TRACED0)
#error Invalid pin assignment for SYS6 TRACED0 pin: SYS6_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS6, SYS6_TRACED1)
#error Invalid pin assignment for SYS6 TRACED1 pin: SYS6_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS6, SYS6_TRACED2)
#error Invalid pin assignment for SYS6 TRACED2 pin: SYS6_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS6, SYS6_TRACED3)
#error Invalid pin assignment for SYS6 TRACED3 pin: SYS6_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS6, SYS6_USART)
#error Invalid pin assignment for SYS6 USART pin: SYS6_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS6, SYS6_WKUP)
#error Invalid pin assignment for SYS6 WKUP pin: SYS6_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS6, SYS6_WKUP1)
#error Invalid pin assignment for SYS6 WKUP1 pin: SYS6_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS6, SYS6_WKUP2)
#error Invalid pin assignment for SYS6 WKUP2 pin: SYS6_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS6, SYS6_WKUP3)
#error Invalid pin assignment for SYS6 WKUP3 pin: SYS6_WKUP3
#endif
#endif

#ifdef USE_SYS7
#if !FIND_VALUE_SYS_CAN(_SYS7, SYS7_CAN)
#error Invalid pin assignment for SYS7 CAN pin: SYS7_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS7, SYS7_COMP)
#error Invalid pin assignment for SYS7 COMP pin: SYS7_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS7, SYS7_DAC)
#error Invalid pin assignment for SYS7 DAC pin: SYS7_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS7, SYS7_I2C)
#error Invalid pin assignment for SYS7 I2C pin: SYS7_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS7, SYS7_JTDI)
#error Invalid pin assignment for SYS7 JTDI pin: SYS7_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS7, SYS7_JTRST)
#error Invalid pin assignment for SYS7 JTRST pin: SYS7_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS7, SYS7_NJTRST)
#error Invalid pin assignment for SYS7 NJTRST pin: SYS7_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS7, SYS7_SLEEP)
#error Invalid pin assignment for SYS7 SLEEP pin: SYS7_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS7, SYS7_SPI)
#error Invalid pin assignment for SYS7 SPI pin: SYS7_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS7, SYS7_SWCLK)
#error Invalid pin assignment for SYS7 SWCLK pin: SYS7_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS7, SYS7_SWDIO)
#error Invalid pin assignment for SYS7 SWDIO pin: SYS7_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS7, SYS7_SYSTEM)
#error Invalid pin assignment for SYS7 SYSTEM pin: SYS7_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS7, SYS7_TIM1)
#error Invalid pin assignment for SYS7 TIM1 pin: SYS7_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS7, SYS7_TIM14)
#error Invalid pin assignment for SYS7 TIM14 pin: SYS7_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS7, SYS7_TIM15)
#error Invalid pin assignment for SYS7 TIM15 pin: SYS7_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS7, SYS7_TIM16)
#error Invalid pin assignment for SYS7 TIM16 pin: SYS7_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS7, SYS7_TIM17)
#error Invalid pin assignment for SYS7 TIM17 pin: SYS7_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS7, SYS7_TIM2)
#error Invalid pin assignment for SYS7 TIM2 pin: SYS7_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS7, SYS7_TIM3)
#error Invalid pin assignment for SYS7 TIM3 pin: SYS7_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS7, SYS7_TOUCH)
#error Invalid pin assignment for SYS7 TOUCH pin: SYS7_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS7, SYS7_TRACECK)
#error Invalid pin assignment for SYS7 TRACECK pin: SYS7_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS7, SYS7_TRACECLK)
#error Invalid pin assignment for SYS7 TRACECLK pin: SYS7_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS7, SYS7_TRACED0)
#error Invalid pin assignment for SYS7 TRACED0 pin: SYS7_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS7, SYS7_TRACED1)
#error Invalid pin assignment for SYS7 TRACED1 pin: SYS7_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS7, SYS7_TRACED2)
#error Invalid pin assignment for SYS7 TRACED2 pin: SYS7_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS7, SYS7_TRACED3)
#error Invalid pin assignment for SYS7 TRACED3 pin: SYS7_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS7, SYS7_USART)
#error Invalid pin assignment for SYS7 USART pin: SYS7_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS7, SYS7_WKUP)
#error Invalid pin assignment for SYS7 WKUP pin: SYS7_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS7, SYS7_WKUP1)
#error Invalid pin assignment for SYS7 WKUP1 pin: SYS7_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS7, SYS7_WKUP2)
#error Invalid pin assignment for SYS7 WKUP2 pin: SYS7_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS7, SYS7_WKUP3)
#error Invalid pin assignment for SYS7 WKUP3 pin: SYS7_WKUP3
#endif
#endif

#ifdef USE_SYS8
#if !FIND_VALUE_SYS_CAN(_SYS8, SYS8_CAN)
#error Invalid pin assignment for SYS8 CAN pin: SYS8_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS8, SYS8_COMP)
#error Invalid pin assignment for SYS8 COMP pin: SYS8_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS8, SYS8_DAC)
#error Invalid pin assignment for SYS8 DAC pin: SYS8_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS8, SYS8_I2C)
#error Invalid pin assignment for SYS8 I2C pin: SYS8_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS8, SYS8_JTDI)
#error Invalid pin assignment for SYS8 JTDI pin: SYS8_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS8, SYS8_JTRST)
#error Invalid pin assignment for SYS8 JTRST pin: SYS8_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS8, SYS8_NJTRST)
#error Invalid pin assignment for SYS8 NJTRST pin: SYS8_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS8, SYS8_SLEEP)
#error Invalid pin assignment for SYS8 SLEEP pin: SYS8_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS8, SYS8_SPI)
#error Invalid pin assignment for SYS8 SPI pin: SYS8_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS8, SYS8_SWCLK)
#error Invalid pin assignment for SYS8 SWCLK pin: SYS8_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS8, SYS8_SWDIO)
#error Invalid pin assignment for SYS8 SWDIO pin: SYS8_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS8, SYS8_SYSTEM)
#error Invalid pin assignment for SYS8 SYSTEM pin: SYS8_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS8, SYS8_TIM1)
#error Invalid pin assignment for SYS8 TIM1 pin: SYS8_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS8, SYS8_TIM14)
#error Invalid pin assignment for SYS8 TIM14 pin: SYS8_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS8, SYS8_TIM15)
#error Invalid pin assignment for SYS8 TIM15 pin: SYS8_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS8, SYS8_TIM16)
#error Invalid pin assignment for SYS8 TIM16 pin: SYS8_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS8, SYS8_TIM17)
#error Invalid pin assignment for SYS8 TIM17 pin: SYS8_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS8, SYS8_TIM2)
#error Invalid pin assignment for SYS8 TIM2 pin: SYS8_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS8, SYS8_TIM3)
#error Invalid pin assignment for SYS8 TIM3 pin: SYS8_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS8, SYS8_TOUCH)
#error Invalid pin assignment for SYS8 TOUCH pin: SYS8_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS8, SYS8_TRACECK)
#error Invalid pin assignment for SYS8 TRACECK pin: SYS8_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS8, SYS8_TRACECLK)
#error Invalid pin assignment for SYS8 TRACECLK pin: SYS8_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS8, SYS8_TRACED0)
#error Invalid pin assignment for SYS8 TRACED0 pin: SYS8_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS8, SYS8_TRACED1)
#error Invalid pin assignment for SYS8 TRACED1 pin: SYS8_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS8, SYS8_TRACED2)
#error Invalid pin assignment for SYS8 TRACED2 pin: SYS8_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS8, SYS8_TRACED3)
#error Invalid pin assignment for SYS8 TRACED3 pin: SYS8_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS8, SYS8_USART)
#error Invalid pin assignment for SYS8 USART pin: SYS8_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS8, SYS8_WKUP)
#error Invalid pin assignment for SYS8 WKUP pin: SYS8_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS8, SYS8_WKUP1)
#error Invalid pin assignment for SYS8 WKUP1 pin: SYS8_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS8, SYS8_WKUP2)
#error Invalid pin assignment for SYS8 WKUP2 pin: SYS8_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS8, SYS8_WKUP3)
#error Invalid pin assignment for SYS8 WKUP3 pin: SYS8_WKUP3
#endif
#endif

#ifdef USE_SYS9
#if !FIND_VALUE_SYS_CAN(_SYS9, SYS9_CAN)
#error Invalid pin assignment for SYS9 CAN pin: SYS9_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS9, SYS9_COMP)
#error Invalid pin assignment for SYS9 COMP pin: SYS9_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS9, SYS9_DAC)
#error Invalid pin assignment for SYS9 DAC pin: SYS9_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS9, SYS9_I2C)
#error Invalid pin assignment for SYS9 I2C pin: SYS9_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS9, SYS9_JTDI)
#error Invalid pin assignment for SYS9 JTDI pin: SYS9_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS9, SYS9_JTRST)
#error Invalid pin assignment for SYS9 JTRST pin: SYS9_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS9, SYS9_NJTRST)
#error Invalid pin assignment for SYS9 NJTRST pin: SYS9_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS9, SYS9_SLEEP)
#error Invalid pin assignment for SYS9 SLEEP pin: SYS9_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS9, SYS9_SPI)
#error Invalid pin assignment for SYS9 SPI pin: SYS9_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS9, SYS9_SWCLK)
#error Invalid pin assignment for SYS9 SWCLK pin: SYS9_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS9, SYS9_SWDIO)
#error Invalid pin assignment for SYS9 SWDIO pin: SYS9_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS9, SYS9_SYSTEM)
#error Invalid pin assignment for SYS9 SYSTEM pin: SYS9_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS9, SYS9_TIM1)
#error Invalid pin assignment for SYS9 TIM1 pin: SYS9_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS9, SYS9_TIM14)
#error Invalid pin assignment for SYS9 TIM14 pin: SYS9_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS9, SYS9_TIM15)
#error Invalid pin assignment for SYS9 TIM15 pin: SYS9_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS9, SYS9_TIM16)
#error Invalid pin assignment for SYS9 TIM16 pin: SYS9_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS9, SYS9_TIM17)
#error Invalid pin assignment for SYS9 TIM17 pin: SYS9_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS9, SYS9_TIM2)
#error Invalid pin assignment for SYS9 TIM2 pin: SYS9_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS9, SYS9_TIM3)
#error Invalid pin assignment for SYS9 TIM3 pin: SYS9_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS9, SYS9_TOUCH)
#error Invalid pin assignment for SYS9 TOUCH pin: SYS9_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS9, SYS9_TRACECK)
#error Invalid pin assignment for SYS9 TRACECK pin: SYS9_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS9, SYS9_TRACECLK)
#error Invalid pin assignment for SYS9 TRACECLK pin: SYS9_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS9, SYS9_TRACED0)
#error Invalid pin assignment for SYS9 TRACED0 pin: SYS9_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS9, SYS9_TRACED1)
#error Invalid pin assignment for SYS9 TRACED1 pin: SYS9_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS9, SYS9_TRACED2)
#error Invalid pin assignment for SYS9 TRACED2 pin: SYS9_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS9, SYS9_TRACED3)
#error Invalid pin assignment for SYS9 TRACED3 pin: SYS9_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS9, SYS9_USART)
#error Invalid pin assignment for SYS9 USART pin: SYS9_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS9, SYS9_WKUP)
#error Invalid pin assignment for SYS9 WKUP pin: SYS9_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS9, SYS9_WKUP1)
#error Invalid pin assignment for SYS9 WKUP1 pin: SYS9_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS9, SYS9_WKUP2)
#error Invalid pin assignment for SYS9 WKUP2 pin: SYS9_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS9, SYS9_WKUP3)
#error Invalid pin assignment for SYS9 WKUP3 pin: SYS9_WKUP3
#endif
#endif

#ifdef USE_SYS10
#if !FIND_VALUE_SYS_CAN(_SYS10, SYS10_CAN)
#error Invalid pin assignment for SYS10 CAN pin: SYS10_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS10, SYS10_COMP)
#error Invalid pin assignment for SYS10 COMP pin: SYS10_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS10, SYS10_DAC)
#error Invalid pin assignment for SYS10 DAC pin: SYS10_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS10, SYS10_I2C)
#error Invalid pin assignment for SYS10 I2C pin: SYS10_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS10, SYS10_JTDI)
#error Invalid pin assignment for SYS10 JTDI pin: SYS10_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS10, SYS10_JTRST)
#error Invalid pin assignment for SYS10 JTRST pin: SYS10_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS10, SYS10_NJTRST)
#error Invalid pin assignment for SYS10 NJTRST pin: SYS10_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS10, SYS10_SLEEP)
#error Invalid pin assignment for SYS10 SLEEP pin: SYS10_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS10, SYS10_SPI)
#error Invalid pin assignment for SYS10 SPI pin: SYS10_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS10, SYS10_SWCLK)
#error Invalid pin assignment for SYS10 SWCLK pin: SYS10_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS10, SYS10_SWDIO)
#error Invalid pin assignment for SYS10 SWDIO pin: SYS10_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS10, SYS10_SYSTEM)
#error Invalid pin assignment for SYS10 SYSTEM pin: SYS10_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS10, SYS10_TIM1)
#error Invalid pin assignment for SYS10 TIM1 pin: SYS10_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS10, SYS10_TIM14)
#error Invalid pin assignment for SYS10 TIM14 pin: SYS10_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS10, SYS10_TIM15)
#error Invalid pin assignment for SYS10 TIM15 pin: SYS10_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS10, SYS10_TIM16)
#error Invalid pin assignment for SYS10 TIM16 pin: SYS10_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS10, SYS10_TIM17)
#error Invalid pin assignment for SYS10 TIM17 pin: SYS10_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS10, SYS10_TIM2)
#error Invalid pin assignment for SYS10 TIM2 pin: SYS10_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS10, SYS10_TIM3)
#error Invalid pin assignment for SYS10 TIM3 pin: SYS10_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS10, SYS10_TOUCH)
#error Invalid pin assignment for SYS10 TOUCH pin: SYS10_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS10, SYS10_TRACECK)
#error Invalid pin assignment for SYS10 TRACECK pin: SYS10_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS10, SYS10_TRACECLK)
#error Invalid pin assignment for SYS10 TRACECLK pin: SYS10_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS10, SYS10_TRACED0)
#error Invalid pin assignment for SYS10 TRACED0 pin: SYS10_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS10, SYS10_TRACED1)
#error Invalid pin assignment for SYS10 TRACED1 pin: SYS10_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS10, SYS10_TRACED2)
#error Invalid pin assignment for SYS10 TRACED2 pin: SYS10_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS10, SYS10_TRACED3)
#error Invalid pin assignment for SYS10 TRACED3 pin: SYS10_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS10, SYS10_USART)
#error Invalid pin assignment for SYS10 USART pin: SYS10_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS10, SYS10_WKUP)
#error Invalid pin assignment for SYS10 WKUP pin: SYS10_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS10, SYS10_WKUP1)
#error Invalid pin assignment for SYS10 WKUP1 pin: SYS10_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS10, SYS10_WKUP2)
#error Invalid pin assignment for SYS10 WKUP2 pin: SYS10_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS10, SYS10_WKUP3)
#error Invalid pin assignment for SYS10 WKUP3 pin: SYS10_WKUP3
#endif
#endif

#ifdef USE_SYS11
#if !FIND_VALUE_SYS_CAN(_SYS11, SYS11_CAN)
#error Invalid pin assignment for SYS11 CAN pin: SYS11_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS11, SYS11_COMP)
#error Invalid pin assignment for SYS11 COMP pin: SYS11_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS11, SYS11_DAC)
#error Invalid pin assignment for SYS11 DAC pin: SYS11_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS11, SYS11_I2C)
#error Invalid pin assignment for SYS11 I2C pin: SYS11_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS11, SYS11_JTDI)
#error Invalid pin assignment for SYS11 JTDI pin: SYS11_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS11, SYS11_JTRST)
#error Invalid pin assignment for SYS11 JTRST pin: SYS11_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS11, SYS11_NJTRST)
#error Invalid pin assignment for SYS11 NJTRST pin: SYS11_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS11, SYS11_SLEEP)
#error Invalid pin assignment for SYS11 SLEEP pin: SYS11_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS11, SYS11_SPI)
#error Invalid pin assignment for SYS11 SPI pin: SYS11_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS11, SYS11_SWCLK)
#error Invalid pin assignment for SYS11 SWCLK pin: SYS11_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS11, SYS11_SWDIO)
#error Invalid pin assignment for SYS11 SWDIO pin: SYS11_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS11, SYS11_SYSTEM)
#error Invalid pin assignment for SYS11 SYSTEM pin: SYS11_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS11, SYS11_TIM1)
#error Invalid pin assignment for SYS11 TIM1 pin: SYS11_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS11, SYS11_TIM14)
#error Invalid pin assignment for SYS11 TIM14 pin: SYS11_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS11, SYS11_TIM15)
#error Invalid pin assignment for SYS11 TIM15 pin: SYS11_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS11, SYS11_TIM16)
#error Invalid pin assignment for SYS11 TIM16 pin: SYS11_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS11, SYS11_TIM17)
#error Invalid pin assignment for SYS11 TIM17 pin: SYS11_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS11, SYS11_TIM2)
#error Invalid pin assignment for SYS11 TIM2 pin: SYS11_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS11, SYS11_TIM3)
#error Invalid pin assignment for SYS11 TIM3 pin: SYS11_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS11, SYS11_TOUCH)
#error Invalid pin assignment for SYS11 TOUCH pin: SYS11_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS11, SYS11_TRACECK)
#error Invalid pin assignment for SYS11 TRACECK pin: SYS11_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS11, SYS11_TRACECLK)
#error Invalid pin assignment for SYS11 TRACECLK pin: SYS11_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS11, SYS11_TRACED0)
#error Invalid pin assignment for SYS11 TRACED0 pin: SYS11_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS11, SYS11_TRACED1)
#error Invalid pin assignment for SYS11 TRACED1 pin: SYS11_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS11, SYS11_TRACED2)
#error Invalid pin assignment for SYS11 TRACED2 pin: SYS11_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS11, SYS11_TRACED3)
#error Invalid pin assignment for SYS11 TRACED3 pin: SYS11_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS11, SYS11_USART)
#error Invalid pin assignment for SYS11 USART pin: SYS11_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS11, SYS11_WKUP)
#error Invalid pin assignment for SYS11 WKUP pin: SYS11_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS11, SYS11_WKUP1)
#error Invalid pin assignment for SYS11 WKUP1 pin: SYS11_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS11, SYS11_WKUP2)
#error Invalid pin assignment for SYS11 WKUP2 pin: SYS11_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS11, SYS11_WKUP3)
#error Invalid pin assignment for SYS11 WKUP3 pin: SYS11_WKUP3
#endif
#endif

#ifdef USE_SYS12
#if !FIND_VALUE_SYS_CAN(_SYS12, SYS12_CAN)
#error Invalid pin assignment for SYS12 CAN pin: SYS12_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS12, SYS12_COMP)
#error Invalid pin assignment for SYS12 COMP pin: SYS12_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS12, SYS12_DAC)
#error Invalid pin assignment for SYS12 DAC pin: SYS12_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS12, SYS12_I2C)
#error Invalid pin assignment for SYS12 I2C pin: SYS12_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS12, SYS12_JTDI)
#error Invalid pin assignment for SYS12 JTDI pin: SYS12_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS12, SYS12_JTRST)
#error Invalid pin assignment for SYS12 JTRST pin: SYS12_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS12, SYS12_NJTRST)
#error Invalid pin assignment for SYS12 NJTRST pin: SYS12_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS12, SYS12_SLEEP)
#error Invalid pin assignment for SYS12 SLEEP pin: SYS12_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS12, SYS12_SPI)
#error Invalid pin assignment for SYS12 SPI pin: SYS12_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS12, SYS12_SWCLK)
#error Invalid pin assignment for SYS12 SWCLK pin: SYS12_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS12, SYS12_SWDIO)
#error Invalid pin assignment for SYS12 SWDIO pin: SYS12_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS12, SYS12_SYSTEM)
#error Invalid pin assignment for SYS12 SYSTEM pin: SYS12_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS12, SYS12_TIM1)
#error Invalid pin assignment for SYS12 TIM1 pin: SYS12_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS12, SYS12_TIM14)
#error Invalid pin assignment for SYS12 TIM14 pin: SYS12_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS12, SYS12_TIM15)
#error Invalid pin assignment for SYS12 TIM15 pin: SYS12_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS12, SYS12_TIM16)
#error Invalid pin assignment for SYS12 TIM16 pin: SYS12_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS12, SYS12_TIM17)
#error Invalid pin assignment for SYS12 TIM17 pin: SYS12_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS12, SYS12_TIM2)
#error Invalid pin assignment for SYS12 TIM2 pin: SYS12_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS12, SYS12_TIM3)
#error Invalid pin assignment for SYS12 TIM3 pin: SYS12_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS12, SYS12_TOUCH)
#error Invalid pin assignment for SYS12 TOUCH pin: SYS12_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS12, SYS12_TRACECK)
#error Invalid pin assignment for SYS12 TRACECK pin: SYS12_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS12, SYS12_TRACECLK)
#error Invalid pin assignment for SYS12 TRACECLK pin: SYS12_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS12, SYS12_TRACED0)
#error Invalid pin assignment for SYS12 TRACED0 pin: SYS12_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS12, SYS12_TRACED1)
#error Invalid pin assignment for SYS12 TRACED1 pin: SYS12_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS12, SYS12_TRACED2)
#error Invalid pin assignment for SYS12 TRACED2 pin: SYS12_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS12, SYS12_TRACED3)
#error Invalid pin assignment for SYS12 TRACED3 pin: SYS12_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS12, SYS12_USART)
#error Invalid pin assignment for SYS12 USART pin: SYS12_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS12, SYS12_WKUP)
#error Invalid pin assignment for SYS12 WKUP pin: SYS12_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS12, SYS12_WKUP1)
#error Invalid pin assignment for SYS12 WKUP1 pin: SYS12_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS12, SYS12_WKUP2)
#error Invalid pin assignment for SYS12 WKUP2 pin: SYS12_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS12, SYS12_WKUP3)
#error Invalid pin assignment for SYS12 WKUP3 pin: SYS12_WKUP3
#endif
#endif

#ifdef USE_SYS13
#if !FIND_VALUE_SYS_CAN(_SYS13, SYS13_CAN)
#error Invalid pin assignment for SYS13 CAN pin: SYS13_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS13, SYS13_COMP)
#error Invalid pin assignment for SYS13 COMP pin: SYS13_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS13, SYS13_DAC)
#error Invalid pin assignment for SYS13 DAC pin: SYS13_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS13, SYS13_I2C)
#error Invalid pin assignment for SYS13 I2C pin: SYS13_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS13, SYS13_JTDI)
#error Invalid pin assignment for SYS13 JTDI pin: SYS13_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS13, SYS13_JTRST)
#error Invalid pin assignment for SYS13 JTRST pin: SYS13_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS13, SYS13_NJTRST)
#error Invalid pin assignment for SYS13 NJTRST pin: SYS13_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS13, SYS13_SLEEP)
#error Invalid pin assignment for SYS13 SLEEP pin: SYS13_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS13, SYS13_SPI)
#error Invalid pin assignment for SYS13 SPI pin: SYS13_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS13, SYS13_SWCLK)
#error Invalid pin assignment for SYS13 SWCLK pin: SYS13_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS13, SYS13_SWDIO)
#error Invalid pin assignment for SYS13 SWDIO pin: SYS13_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS13, SYS13_SYSTEM)
#error Invalid pin assignment for SYS13 SYSTEM pin: SYS13_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS13, SYS13_TIM1)
#error Invalid pin assignment for SYS13 TIM1 pin: SYS13_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS13, SYS13_TIM14)
#error Invalid pin assignment for SYS13 TIM14 pin: SYS13_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS13, SYS13_TIM15)
#error Invalid pin assignment for SYS13 TIM15 pin: SYS13_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS13, SYS13_TIM16)
#error Invalid pin assignment for SYS13 TIM16 pin: SYS13_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS13, SYS13_TIM17)
#error Invalid pin assignment for SYS13 TIM17 pin: SYS13_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS13, SYS13_TIM2)
#error Invalid pin assignment for SYS13 TIM2 pin: SYS13_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS13, SYS13_TIM3)
#error Invalid pin assignment for SYS13 TIM3 pin: SYS13_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS13, SYS13_TOUCH)
#error Invalid pin assignment for SYS13 TOUCH pin: SYS13_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS13, SYS13_TRACECK)
#error Invalid pin assignment for SYS13 TRACECK pin: SYS13_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS13, SYS13_TRACECLK)
#error Invalid pin assignment for SYS13 TRACECLK pin: SYS13_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS13, SYS13_TRACED0)
#error Invalid pin assignment for SYS13 TRACED0 pin: SYS13_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS13, SYS13_TRACED1)
#error Invalid pin assignment for SYS13 TRACED1 pin: SYS13_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS13, SYS13_TRACED2)
#error Invalid pin assignment for SYS13 TRACED2 pin: SYS13_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS13, SYS13_TRACED3)
#error Invalid pin assignment for SYS13 TRACED3 pin: SYS13_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS13, SYS13_USART)
#error Invalid pin assignment for SYS13 USART pin: SYS13_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS13, SYS13_WKUP)
#error Invalid pin assignment for SYS13 WKUP pin: SYS13_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS13, SYS13_WKUP1)
#error Invalid pin assignment for SYS13 WKUP1 pin: SYS13_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS13, SYS13_WKUP2)
#error Invalid pin assignment for SYS13 WKUP2 pin: SYS13_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS13, SYS13_WKUP3)
#error Invalid pin assignment for SYS13 WKUP3 pin: SYS13_WKUP3
#endif
#endif

#ifdef USE_SYS14
#if !FIND_VALUE_SYS_CAN(_SYS14, SYS14_CAN)
#error Invalid pin assignment for SYS14 CAN pin: SYS14_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS14, SYS14_COMP)
#error Invalid pin assignment for SYS14 COMP pin: SYS14_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS14, SYS14_DAC)
#error Invalid pin assignment for SYS14 DAC pin: SYS14_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS14, SYS14_I2C)
#error Invalid pin assignment for SYS14 I2C pin: SYS14_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS14, SYS14_JTDI)
#error Invalid pin assignment for SYS14 JTDI pin: SYS14_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS14, SYS14_JTRST)
#error Invalid pin assignment for SYS14 JTRST pin: SYS14_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS14, SYS14_NJTRST)
#error Invalid pin assignment for SYS14 NJTRST pin: SYS14_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS14, SYS14_SLEEP)
#error Invalid pin assignment for SYS14 SLEEP pin: SYS14_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS14, SYS14_SPI)
#error Invalid pin assignment for SYS14 SPI pin: SYS14_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS14, SYS14_SWCLK)
#error Invalid pin assignment for SYS14 SWCLK pin: SYS14_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS14, SYS14_SWDIO)
#error Invalid pin assignment for SYS14 SWDIO pin: SYS14_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS14, SYS14_SYSTEM)
#error Invalid pin assignment for SYS14 SYSTEM pin: SYS14_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS14, SYS14_TIM1)
#error Invalid pin assignment for SYS14 TIM1 pin: SYS14_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS14, SYS14_TIM14)
#error Invalid pin assignment for SYS14 TIM14 pin: SYS14_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS14, SYS14_TIM15)
#error Invalid pin assignment for SYS14 TIM15 pin: SYS14_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS14, SYS14_TIM16)
#error Invalid pin assignment for SYS14 TIM16 pin: SYS14_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS14, SYS14_TIM17)
#error Invalid pin assignment for SYS14 TIM17 pin: SYS14_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS14, SYS14_TIM2)
#error Invalid pin assignment for SYS14 TIM2 pin: SYS14_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS14, SYS14_TIM3)
#error Invalid pin assignment for SYS14 TIM3 pin: SYS14_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS14, SYS14_TOUCH)
#error Invalid pin assignment for SYS14 TOUCH pin: SYS14_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS14, SYS14_TRACECK)
#error Invalid pin assignment for SYS14 TRACECK pin: SYS14_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS14, SYS14_TRACECLK)
#error Invalid pin assignment for SYS14 TRACECLK pin: SYS14_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS14, SYS14_TRACED0)
#error Invalid pin assignment for SYS14 TRACED0 pin: SYS14_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS14, SYS14_TRACED1)
#error Invalid pin assignment for SYS14 TRACED1 pin: SYS14_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS14, SYS14_TRACED2)
#error Invalid pin assignment for SYS14 TRACED2 pin: SYS14_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS14, SYS14_TRACED3)
#error Invalid pin assignment for SYS14 TRACED3 pin: SYS14_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS14, SYS14_USART)
#error Invalid pin assignment for SYS14 USART pin: SYS14_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS14, SYS14_WKUP)
#error Invalid pin assignment for SYS14 WKUP pin: SYS14_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS14, SYS14_WKUP1)
#error Invalid pin assignment for SYS14 WKUP1 pin: SYS14_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS14, SYS14_WKUP2)
#error Invalid pin assignment for SYS14 WKUP2 pin: SYS14_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS14, SYS14_WKUP3)
#error Invalid pin assignment for SYS14 WKUP3 pin: SYS14_WKUP3
#endif
#endif

#ifdef USE_SYS15
#if !FIND_VALUE_SYS_CAN(_SYS15, SYS15_CAN)
#error Invalid pin assignment for SYS15 CAN pin: SYS15_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS15, SYS15_COMP)
#error Invalid pin assignment for SYS15 COMP pin: SYS15_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS15, SYS15_DAC)
#error Invalid pin assignment for SYS15 DAC pin: SYS15_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS15, SYS15_I2C)
#error Invalid pin assignment for SYS15 I2C pin: SYS15_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS15, SYS15_JTDI)
#error Invalid pin assignment for SYS15 JTDI pin: SYS15_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS15, SYS15_JTRST)
#error Invalid pin assignment for SYS15 JTRST pin: SYS15_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS15, SYS15_NJTRST)
#error Invalid pin assignment for SYS15 NJTRST pin: SYS15_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS15, SYS15_SLEEP)
#error Invalid pin assignment for SYS15 SLEEP pin: SYS15_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS15, SYS15_SPI)
#error Invalid pin assignment for SYS15 SPI pin: SYS15_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS15, SYS15_SWCLK)
#error Invalid pin assignment for SYS15 SWCLK pin: SYS15_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS15, SYS15_SWDIO)
#error Invalid pin assignment for SYS15 SWDIO pin: SYS15_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS15, SYS15_SYSTEM)
#error Invalid pin assignment for SYS15 SYSTEM pin: SYS15_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS15, SYS15_TIM1)
#error Invalid pin assignment for SYS15 TIM1 pin: SYS15_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS15, SYS15_TIM14)
#error Invalid pin assignment for SYS15 TIM14 pin: SYS15_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS15, SYS15_TIM15)
#error Invalid pin assignment for SYS15 TIM15 pin: SYS15_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS15, SYS15_TIM16)
#error Invalid pin assignment for SYS15 TIM16 pin: SYS15_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS15, SYS15_TIM17)
#error Invalid pin assignment for SYS15 TIM17 pin: SYS15_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS15, SYS15_TIM2)
#error Invalid pin assignment for SYS15 TIM2 pin: SYS15_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS15, SYS15_TIM3)
#error Invalid pin assignment for SYS15 TIM3 pin: SYS15_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS15, SYS15_TOUCH)
#error Invalid pin assignment for SYS15 TOUCH pin: SYS15_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS15, SYS15_TRACECK)
#error Invalid pin assignment for SYS15 TRACECK pin: SYS15_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS15, SYS15_TRACECLK)
#error Invalid pin assignment for SYS15 TRACECLK pin: SYS15_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS15, SYS15_TRACED0)
#error Invalid pin assignment for SYS15 TRACED0 pin: SYS15_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS15, SYS15_TRACED1)
#error Invalid pin assignment for SYS15 TRACED1 pin: SYS15_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS15, SYS15_TRACED2)
#error Invalid pin assignment for SYS15 TRACED2 pin: SYS15_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS15, SYS15_TRACED3)
#error Invalid pin assignment for SYS15 TRACED3 pin: SYS15_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS15, SYS15_USART)
#error Invalid pin assignment for SYS15 USART pin: SYS15_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS15, SYS15_WKUP)
#error Invalid pin assignment for SYS15 WKUP pin: SYS15_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS15, SYS15_WKUP1)
#error Invalid pin assignment for SYS15 WKUP1 pin: SYS15_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS15, SYS15_WKUP2)
#error Invalid pin assignment for SYS15 WKUP2 pin: SYS15_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS15, SYS15_WKUP3)
#error Invalid pin assignment for SYS15 WKUP3 pin: SYS15_WKUP3
#endif
#endif

#ifdef USE_SYS16
#if !FIND_VALUE_SYS_CAN(_SYS16, SYS16_CAN)
#error Invalid pin assignment for SYS16 CAN pin: SYS16_CAN
#endif
#if !FIND_VALUE_SYS_COMP(_SYS16, SYS16_COMP)
#error Invalid pin assignment for SYS16 COMP pin: SYS16_COMP
#endif
#if !FIND_VALUE_SYS_DAC(_SYS16, SYS16_DAC)
#error Invalid pin assignment for SYS16 DAC pin: SYS16_DAC
#endif
#if !FIND_VALUE_SYS_I2C(_SYS16, SYS16_I2C)
#error Invalid pin assignment for SYS16 I2C pin: SYS16_I2C
#endif
#if !FIND_VALUE_SYS_JTDI(_SYS16, SYS16_JTDI)
#error Invalid pin assignment for SYS16 JTDI pin: SYS16_JTDI
#endif
#if !FIND_VALUE_SYS_JTRST(_SYS16, SYS16_JTRST)
#error Invalid pin assignment for SYS16 JTRST pin: SYS16_JTRST
#endif
#if !FIND_VALUE_SYS_NJTRST(_SYS16, SYS16_NJTRST)
#error Invalid pin assignment for SYS16 NJTRST pin: SYS16_NJTRST
#endif
#if !FIND_VALUE_SYS_SLEEP(_SYS16, SYS16_SLEEP)
#error Invalid pin assignment for SYS16 SLEEP pin: SYS16_SLEEP
#endif
#if !FIND_VALUE_SYS_SPI(_SYS16, SYS16_SPI)
#error Invalid pin assignment for SYS16 SPI pin: SYS16_SPI
#endif
#if !FIND_VALUE_SYS_SWCLK(_SYS16, SYS16_SWCLK)
#error Invalid pin assignment for SYS16 SWCLK pin: SYS16_SWCLK
#endif
#if !FIND_VALUE_SYS_SWDIO(_SYS16, SYS16_SWDIO)
#error Invalid pin assignment for SYS16 SWDIO pin: SYS16_SWDIO
#endif
#if !FIND_VALUE_SYS_SYSTEM(_SYS16, SYS16_SYSTEM)
#error Invalid pin assignment for SYS16 SYSTEM pin: SYS16_SYSTEM
#endif
#if !FIND_VALUE_SYS_TIM1(_SYS16, SYS16_TIM1)
#error Invalid pin assignment for SYS16 TIM1 pin: SYS16_TIM1
#endif
#if !FIND_VALUE_SYS_TIM14(_SYS16, SYS16_TIM14)
#error Invalid pin assignment for SYS16 TIM14 pin: SYS16_TIM14
#endif
#if !FIND_VALUE_SYS_TIM15(_SYS16, SYS16_TIM15)
#error Invalid pin assignment for SYS16 TIM15 pin: SYS16_TIM15
#endif
#if !FIND_VALUE_SYS_TIM16(_SYS16, SYS16_TIM16)
#error Invalid pin assignment for SYS16 TIM16 pin: SYS16_TIM16
#endif
#if !FIND_VALUE_SYS_TIM17(_SYS16, SYS16_TIM17)
#error Invalid pin assignment for SYS16 TIM17 pin: SYS16_TIM17
#endif
#if !FIND_VALUE_SYS_TIM2(_SYS16, SYS16_TIM2)
#error Invalid pin assignment for SYS16 TIM2 pin: SYS16_TIM2
#endif
#if !FIND_VALUE_SYS_TIM3(_SYS16, SYS16_TIM3)
#error Invalid pin assignment for SYS16 TIM3 pin: SYS16_TIM3
#endif
#if !FIND_VALUE_SYS_TOUCH(_SYS16, SYS16_TOUCH)
#error Invalid pin assignment for SYS16 TOUCH pin: SYS16_TOUCH
#endif
#if !FIND_VALUE_SYS_TRACECK(_SYS16, SYS16_TRACECK)
#error Invalid pin assignment for SYS16 TRACECK pin: SYS16_TRACECK
#endif
#if !FIND_VALUE_SYS_TRACECLK(_SYS16, SYS16_TRACECLK)
#error Invalid pin assignment for SYS16 TRACECLK pin: SYS16_TRACECLK
#endif
#if !FIND_VALUE_SYS_TRACED0(_SYS16, SYS16_TRACED0)
#error Invalid pin assignment for SYS16 TRACED0 pin: SYS16_TRACED0
#endif
#if !FIND_VALUE_SYS_TRACED1(_SYS16, SYS16_TRACED1)
#error Invalid pin assignment for SYS16 TRACED1 pin: SYS16_TRACED1
#endif
#if !FIND_VALUE_SYS_TRACED2(_SYS16, SYS16_TRACED2)
#error Invalid pin assignment for SYS16 TRACED2 pin: SYS16_TRACED2
#endif
#if !FIND_VALUE_SYS_TRACED3(_SYS16, SYS16_TRACED3)
#error Invalid pin assignment for SYS16 TRACED3 pin: SYS16_TRACED3
#endif
#if !FIND_VALUE_SYS_USART(_SYS16, SYS16_USART)
#error Invalid pin assignment for SYS16 USART pin: SYS16_USART
#endif
#if !FIND_VALUE_SYS_WKUP(_SYS16, SYS16_WKUP)
#error Invalid pin assignment for SYS16 WKUP pin: SYS16_WKUP
#endif
#if !FIND_VALUE_SYS_WKUP1(_SYS16, SYS16_WKUP1)
#error Invalid pin assignment for SYS16 WKUP1 pin: SYS16_WKUP1
#endif
#if !FIND_VALUE_SYS_WKUP2(_SYS16, SYS16_WKUP2)
#error Invalid pin assignment for SYS16 WKUP2 pin: SYS16_WKUP2
#endif
#if !FIND_VALUE_SYS_WKUP3(_SYS16, SYS16_WKUP3)
#error Invalid pin assignment for SYS16 WKUP3 pin: SYS16_WKUP3
#endif
#endif

