/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404966
 */

#define FIND_VALUE_SYS_JTCK_SWCLK_inner(INDEX,PIN) I2C##_SYS_JTCK_##PIN
#define FIND_VALUE_SYS_JTCK_SWCLK(INDEX,PIN) FIND_VALUE_SYS_JTCK_SWCLK_inner(INDEX,PIN)

#ifdef USE_SYS_JTCK0
#if !FIND_VALUE_SYS_JTCK_SWCLK(_SYS_JTCK0, SYS_JTCK0_SWCLK)
#error Invalid pin assignment for SYS_JTCK0 SWCLK pin: SYS_JTCK0_SWCLK
#endif
#endif

