/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.398088
 */

#define FIND_VALUE_CRS_SYNC_inner(INDEX,PIN) I2C##_CRS_##PIN
#define FIND_VALUE_CRS_SYNC(INDEX,PIN) FIND_VALUE_CRS_SYNC_inner(INDEX,PIN)

#ifdef USE_CRS0
#if !FIND_VALUE_CRS_SYNC(_CRS0, CRS0_SYNC)
#error Invalid pin assignment for CRS0 SYNC pin: CRS0_SYNC
#endif
#endif

