/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.405005
 */

#define FIND_VALUE_SYS_PVD_IN_inner(INDEX,PIN) I2C##_SYS_PVD_##PIN
#define FIND_VALUE_SYS_PVD_IN(INDEX,PIN) FIND_VALUE_SYS_PVD_IN_inner(INDEX,PIN)

#ifdef USE_SYS_PVD0
#if !FIND_VALUE_SYS_PVD_IN(_SYS_PVD0, SYS_PVD0_IN)
#error Invalid pin assignment for SYS_PVD0 IN pin: SYS_PVD0_IN
#endif
#endif

