/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.405251
 */

#define FIND_VALUE_TIMX_IC1_inner(INDEX,PIN) I2C##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC1(INDEX,PIN) FIND_VALUE_TIMX_IC1_inner(INDEX,PIN)

#define FIND_VALUE_TIMX_IC2_inner(INDEX,PIN) I2C##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC2(INDEX,PIN) FIND_VALUE_TIMX_IC2_inner(INDEX,PIN)

#define FIND_VALUE_TIMX_IC3_inner(INDEX,PIN) I2C##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC3(INDEX,PIN) FIND_VALUE_TIMX_IC3_inner(INDEX,PIN)

#define FIND_VALUE_TIMX_IC4_inner(INDEX,PIN) I2C##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC4(INDEX,PIN) FIND_VALUE_TIMX_IC4_inner(INDEX,PIN)

#ifdef USE_TIMX0
#if !FIND_VALUE_TIMX_IC1(_TIMX0, TIMX0_IC1)
#error Invalid pin assignment for TIMX0 IC1 pin: TIMX0_IC1
#endif
#if !FIND_VALUE_TIMX_IC2(_TIMX0, TIMX0_IC2)
#error Invalid pin assignment for TIMX0 IC2 pin: TIMX0_IC2
#endif
#if !FIND_VALUE_TIMX_IC3(_TIMX0, TIMX0_IC3)
#error Invalid pin assignment for TIMX0 IC3 pin: TIMX0_IC3
#endif
#if !FIND_VALUE_TIMX_IC4(_TIMX0, TIMX0_IC4)
#error Invalid pin assignment for TIMX0 IC4 pin: TIMX0_IC4
#endif
#endif

#ifdef USE_TIMX1
#if !FIND_VALUE_TIMX_IC1(_TIMX1, TIMX1_IC1)
#error Invalid pin assignment for TIMX1 IC1 pin: TIMX1_IC1
#endif
#if !FIND_VALUE_TIMX_IC2(_TIMX1, TIMX1_IC2)
#error Invalid pin assignment for TIMX1 IC2 pin: TIMX1_IC2
#endif
#if !FIND_VALUE_TIMX_IC3(_TIMX1, TIMX1_IC3)
#error Invalid pin assignment for TIMX1 IC3 pin: TIMX1_IC3
#endif
#if !FIND_VALUE_TIMX_IC4(_TIMX1, TIMX1_IC4)
#error Invalid pin assignment for TIMX1 IC4 pin: TIMX1_IC4
#endif
#endif

#ifdef USE_TIMX2
#if !FIND_VALUE_TIMX_IC1(_TIMX2, TIMX2_IC1)
#error Invalid pin assignment for TIMX2 IC1 pin: TIMX2_IC1
#endif
#if !FIND_VALUE_TIMX_IC2(_TIMX2, TIMX2_IC2)
#error Invalid pin assignment for TIMX2 IC2 pin: TIMX2_IC2
#endif
#if !FIND_VALUE_TIMX_IC3(_TIMX2, TIMX2_IC3)
#error Invalid pin assignment for TIMX2 IC3 pin: TIMX2_IC3
#endif
#if !FIND_VALUE_TIMX_IC4(_TIMX2, TIMX2_IC4)
#error Invalid pin assignment for TIMX2 IC4 pin: TIMX2_IC4
#endif
#endif

#ifdef USE_TIMX3
#if !FIND_VALUE_TIMX_IC1(_TIMX3, TIMX3_IC1)
#error Invalid pin assignment for TIMX3 IC1 pin: TIMX3_IC1
#endif
#if !FIND_VALUE_TIMX_IC2(_TIMX3, TIMX3_IC2)
#error Invalid pin assignment for TIMX3 IC2 pin: TIMX3_IC2
#endif
#if !FIND_VALUE_TIMX_IC3(_TIMX3, TIMX3_IC3)
#error Invalid pin assignment for TIMX3 IC3 pin: TIMX3_IC3
#endif
#if !FIND_VALUE_TIMX_IC4(_TIMX3, TIMX3_IC4)
#error Invalid pin assignment for TIMX3 IC4 pin: TIMX3_IC4
#endif
#endif

