/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.402127
 */

#define FIND_VALUE_IR_OUT_inner(INDEX,PIN) I2C##_IR_##PIN
#define FIND_VALUE_IR_OUT(INDEX,PIN) FIND_VALUE_IR_OUT_inner(INDEX,PIN)

#ifdef USE_IR0
#if !FIND_VALUE_IR_OUT(_IR0, IR0_OUT)
#error Invalid pin assignment for IR0 OUT pin: IR0_OUT
#endif
#endif

