/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.404346
 */

#define FIND_VALUE_SDIO_CK_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_CK(INDEX,PIN) FIND_VALUE_SDIO_CK_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_CMD_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_CMD(INDEX,PIN) FIND_VALUE_SDIO_CMD_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D0_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D0(INDEX,PIN) FIND_VALUE_SDIO_D0_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D1_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D1(INDEX,PIN) FIND_VALUE_SDIO_D1_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D2_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D2(INDEX,PIN) FIND_VALUE_SDIO_D2_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D3_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D3(INDEX,PIN) FIND_VALUE_SDIO_D3_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D4_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D4(INDEX,PIN) FIND_VALUE_SDIO_D4_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D5_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D5(INDEX,PIN) FIND_VALUE_SDIO_D5_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D6_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D6(INDEX,PIN) FIND_VALUE_SDIO_D6_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D7_inner(INDEX,PIN) I2C##_SDIO_##PIN
#define FIND_VALUE_SDIO_D7(INDEX,PIN) FIND_VALUE_SDIO_D7_inner(INDEX,PIN)

#ifdef USE_SDIO0
#if !FIND_VALUE_SDIO_CK(_SDIO0, SDIO0_CK)
#error Invalid pin assignment for SDIO0 CK pin: SDIO0_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO0, SDIO0_CMD)
#error Invalid pin assignment for SDIO0 CMD pin: SDIO0_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO0, SDIO0_D0)
#error Invalid pin assignment for SDIO0 D0 pin: SDIO0_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO0, SDIO0_D1)
#error Invalid pin assignment for SDIO0 D1 pin: SDIO0_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO0, SDIO0_D2)
#error Invalid pin assignment for SDIO0 D2 pin: SDIO0_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO0, SDIO0_D3)
#error Invalid pin assignment for SDIO0 D3 pin: SDIO0_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO0, SDIO0_D4)
#error Invalid pin assignment for SDIO0 D4 pin: SDIO0_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO0, SDIO0_D5)
#error Invalid pin assignment for SDIO0 D5 pin: SDIO0_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO0, SDIO0_D6)
#error Invalid pin assignment for SDIO0 D6 pin: SDIO0_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO0, SDIO0_D7)
#error Invalid pin assignment for SDIO0 D7 pin: SDIO0_D7
#endif
#endif

#ifdef USE_SDIO1
#if !FIND_VALUE_SDIO_CK(_SDIO1, SDIO1_CK)
#error Invalid pin assignment for SDIO1 CK pin: SDIO1_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO1, SDIO1_CMD)
#error Invalid pin assignment for SDIO1 CMD pin: SDIO1_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO1, SDIO1_D0)
#error Invalid pin assignment for SDIO1 D0 pin: SDIO1_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO1, SDIO1_D1)
#error Invalid pin assignment for SDIO1 D1 pin: SDIO1_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO1, SDIO1_D2)
#error Invalid pin assignment for SDIO1 D2 pin: SDIO1_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO1, SDIO1_D3)
#error Invalid pin assignment for SDIO1 D3 pin: SDIO1_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO1, SDIO1_D4)
#error Invalid pin assignment for SDIO1 D4 pin: SDIO1_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO1, SDIO1_D5)
#error Invalid pin assignment for SDIO1 D5 pin: SDIO1_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO1, SDIO1_D6)
#error Invalid pin assignment for SDIO1 D6 pin: SDIO1_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO1, SDIO1_D7)
#error Invalid pin assignment for SDIO1 D7 pin: SDIO1_D7
#endif
#endif

#ifdef USE_SDIO2
#if !FIND_VALUE_SDIO_CK(_SDIO2, SDIO2_CK)
#error Invalid pin assignment for SDIO2 CK pin: SDIO2_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO2, SDIO2_CMD)
#error Invalid pin assignment for SDIO2 CMD pin: SDIO2_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO2, SDIO2_D0)
#error Invalid pin assignment for SDIO2 D0 pin: SDIO2_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO2, SDIO2_D1)
#error Invalid pin assignment for SDIO2 D1 pin: SDIO2_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO2, SDIO2_D2)
#error Invalid pin assignment for SDIO2 D2 pin: SDIO2_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO2, SDIO2_D3)
#error Invalid pin assignment for SDIO2 D3 pin: SDIO2_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO2, SDIO2_D4)
#error Invalid pin assignment for SDIO2 D4 pin: SDIO2_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO2, SDIO2_D5)
#error Invalid pin assignment for SDIO2 D5 pin: SDIO2_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO2, SDIO2_D6)
#error Invalid pin assignment for SDIO2 D6 pin: SDIO2_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO2, SDIO2_D7)
#error Invalid pin assignment for SDIO2 D7 pin: SDIO2_D7
#endif
#endif

#ifdef USE_SDIO3
#if !FIND_VALUE_SDIO_CK(_SDIO3, SDIO3_CK)
#error Invalid pin assignment for SDIO3 CK pin: SDIO3_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO3, SDIO3_CMD)
#error Invalid pin assignment for SDIO3 CMD pin: SDIO3_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO3, SDIO3_D0)
#error Invalid pin assignment for SDIO3 D0 pin: SDIO3_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO3, SDIO3_D1)
#error Invalid pin assignment for SDIO3 D1 pin: SDIO3_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO3, SDIO3_D2)
#error Invalid pin assignment for SDIO3 D2 pin: SDIO3_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO3, SDIO3_D3)
#error Invalid pin assignment for SDIO3 D3 pin: SDIO3_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO3, SDIO3_D4)
#error Invalid pin assignment for SDIO3 D4 pin: SDIO3_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO3, SDIO3_D5)
#error Invalid pin assignment for SDIO3 D5 pin: SDIO3_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO3, SDIO3_D6)
#error Invalid pin assignment for SDIO3 D6 pin: SDIO3_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO3, SDIO3_D7)
#error Invalid pin assignment for SDIO3 D7 pin: SDIO3_D7
#endif
#endif

#ifdef USE_SDIO4
#if !FIND_VALUE_SDIO_CK(_SDIO4, SDIO4_CK)
#error Invalid pin assignment for SDIO4 CK pin: SDIO4_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO4, SDIO4_CMD)
#error Invalid pin assignment for SDIO4 CMD pin: SDIO4_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO4, SDIO4_D0)
#error Invalid pin assignment for SDIO4 D0 pin: SDIO4_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO4, SDIO4_D1)
#error Invalid pin assignment for SDIO4 D1 pin: SDIO4_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO4, SDIO4_D2)
#error Invalid pin assignment for SDIO4 D2 pin: SDIO4_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO4, SDIO4_D3)
#error Invalid pin assignment for SDIO4 D3 pin: SDIO4_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO4, SDIO4_D4)
#error Invalid pin assignment for SDIO4 D4 pin: SDIO4_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO4, SDIO4_D5)
#error Invalid pin assignment for SDIO4 D5 pin: SDIO4_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO4, SDIO4_D6)
#error Invalid pin assignment for SDIO4 D6 pin: SDIO4_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO4, SDIO4_D7)
#error Invalid pin assignment for SDIO4 D7 pin: SDIO4_D7
#endif
#endif

#ifdef USE_SDIO5
#if !FIND_VALUE_SDIO_CK(_SDIO5, SDIO5_CK)
#error Invalid pin assignment for SDIO5 CK pin: SDIO5_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO5, SDIO5_CMD)
#error Invalid pin assignment for SDIO5 CMD pin: SDIO5_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO5, SDIO5_D0)
#error Invalid pin assignment for SDIO5 D0 pin: SDIO5_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO5, SDIO5_D1)
#error Invalid pin assignment for SDIO5 D1 pin: SDIO5_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO5, SDIO5_D2)
#error Invalid pin assignment for SDIO5 D2 pin: SDIO5_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO5, SDIO5_D3)
#error Invalid pin assignment for SDIO5 D3 pin: SDIO5_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO5, SDIO5_D4)
#error Invalid pin assignment for SDIO5 D4 pin: SDIO5_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO5, SDIO5_D5)
#error Invalid pin assignment for SDIO5 D5 pin: SDIO5_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO5, SDIO5_D6)
#error Invalid pin assignment for SDIO5 D6 pin: SDIO5_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO5, SDIO5_D7)
#error Invalid pin assignment for SDIO5 D7 pin: SDIO5_D7
#endif
#endif

#ifdef USE_SDIO6
#if !FIND_VALUE_SDIO_CK(_SDIO6, SDIO6_CK)
#error Invalid pin assignment for SDIO6 CK pin: SDIO6_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO6, SDIO6_CMD)
#error Invalid pin assignment for SDIO6 CMD pin: SDIO6_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO6, SDIO6_D0)
#error Invalid pin assignment for SDIO6 D0 pin: SDIO6_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO6, SDIO6_D1)
#error Invalid pin assignment for SDIO6 D1 pin: SDIO6_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO6, SDIO6_D2)
#error Invalid pin assignment for SDIO6 D2 pin: SDIO6_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO6, SDIO6_D3)
#error Invalid pin assignment for SDIO6 D3 pin: SDIO6_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO6, SDIO6_D4)
#error Invalid pin assignment for SDIO6 D4 pin: SDIO6_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO6, SDIO6_D5)
#error Invalid pin assignment for SDIO6 D5 pin: SDIO6_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO6, SDIO6_D6)
#error Invalid pin assignment for SDIO6 D6 pin: SDIO6_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO6, SDIO6_D7)
#error Invalid pin assignment for SDIO6 D7 pin: SDIO6_D7
#endif
#endif

