/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.402109
 */

#define FIND_VALUE_I2S3ext_CK_inner(INDEX,PIN) I2C##_I2S3ext_##PIN
#define FIND_VALUE_I2S3ext_CK(INDEX,PIN) FIND_VALUE_I2S3ext_CK_inner(INDEX,PIN)

#define FIND_VALUE_I2S3ext_MISO_inner(INDEX,PIN) I2C##_I2S3ext_##PIN
#define FIND_VALUE_I2S3ext_MISO(INDEX,PIN) FIND_VALUE_I2S3ext_MISO_inner(INDEX,PIN)

#define FIND_VALUE_I2S3ext_WS_inner(INDEX,PIN) I2C##_I2S3ext_##PIN
#define FIND_VALUE_I2S3ext_WS(INDEX,PIN) FIND_VALUE_I2S3ext_WS_inner(INDEX,PIN)

#ifdef USE_I2S3ext0
#if !FIND_VALUE_I2S3ext_CK(_I2S3ext0, I2S3ext0_CK)
#error Invalid pin assignment for I2S3ext0 CK pin: I2S3ext0_CK
#endif
#if !FIND_VALUE_I2S3ext_MISO(_I2S3ext0, I2S3ext0_MISO)
#error Invalid pin assignment for I2S3ext0 MISO pin: I2S3ext0_MISO
#endif
#if !FIND_VALUE_I2S3ext_WS(_I2S3ext0, I2S3ext0_WS)
#error Invalid pin assignment for I2S3ext0 WS pin: I2S3ext0_WS
#endif
#endif

#ifdef USE_I2S3ext1
#if !FIND_VALUE_I2S3ext_CK(_I2S3ext1, I2S3ext1_CK)
#error Invalid pin assignment for I2S3ext1 CK pin: I2S3ext1_CK
#endif
#if !FIND_VALUE_I2S3ext_MISO(_I2S3ext1, I2S3ext1_MISO)
#error Invalid pin assignment for I2S3ext1 MISO pin: I2S3ext1_MISO
#endif
#if !FIND_VALUE_I2S3ext_WS(_I2S3ext1, I2S3ext1_WS)
#error Invalid pin assignment for I2S3ext1 WS pin: I2S3ext1_WS
#endif
#endif

