/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.402050
 */

#define FIND_VALUE_I2C_SCL_inner(INDEX,PIN) I2C##_I2C_##PIN
#define FIND_VALUE_I2C_SCL(INDEX,PIN) FIND_VALUE_I2C_SCL_inner(INDEX,PIN)

#define FIND_VALUE_I2C_SDA_inner(INDEX,PIN) I2C##_I2C_##PIN
#define FIND_VALUE_I2C_SDA(INDEX,PIN) FIND_VALUE_I2C_SDA_inner(INDEX,PIN)

#define FIND_VALUE_I2C_SMBA_inner(INDEX,PIN) I2C##_I2C_##PIN
#define FIND_VALUE_I2C_SMBA(INDEX,PIN) FIND_VALUE_I2C_SMBA_inner(INDEX,PIN)

#ifdef USE_I2C0
#if !FIND_VALUE_I2C_SCL(_I2C0, I2C0_SCL)
#error Invalid pin assignment for I2C0 SCL pin: I2C0_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C0, I2C0_SDA)
#error Invalid pin assignment for I2C0 SDA pin: I2C0_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C0, I2C0_SMBA)
#error Invalid pin assignment for I2C0 SMBA pin: I2C0_SMBA
#endif
#endif

#ifdef USE_I2C1
#if !FIND_VALUE_I2C_SCL(_I2C1, I2C1_SCL)
#error Invalid pin assignment for I2C1 SCL pin: I2C1_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C1, I2C1_SDA)
#error Invalid pin assignment for I2C1 SDA pin: I2C1_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C1, I2C1_SMBA)
#error Invalid pin assignment for I2C1 SMBA pin: I2C1_SMBA
#endif
#endif

