/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T23:52:17.405295
 */

#define FIND_VALUE_TSC_G_IO1_inner(INDEX,PIN) I2C##_TSC_G_##PIN
#define FIND_VALUE_TSC_G_IO1(INDEX,PIN) FIND_VALUE_TSC_G_IO1_inner(INDEX,PIN)

#define FIND_VALUE_TSC_G_IO2_inner(INDEX,PIN) I2C##_TSC_G_##PIN
#define FIND_VALUE_TSC_G_IO2(INDEX,PIN) FIND_VALUE_TSC_G_IO2_inner(INDEX,PIN)

#define FIND_VALUE_TSC_G_IO3_inner(INDEX,PIN) I2C##_TSC_G_##PIN
#define FIND_VALUE_TSC_G_IO3(INDEX,PIN) FIND_VALUE_TSC_G_IO3_inner(INDEX,PIN)

#define FIND_VALUE_TSC_G_IO4_inner(INDEX,PIN) I2C##_TSC_G_##PIN
#define FIND_VALUE_TSC_G_IO4(INDEX,PIN) FIND_VALUE_TSC_G_IO4_inner(INDEX,PIN)

#ifdef USE_TSC_G0
#if !FIND_VALUE_TSC_G_IO1(_TSC_G0, TSC_G0_IO1)
#error Invalid pin assignment for TSC_G0 IO1 pin: TSC_G0_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G0, TSC_G0_IO2)
#error Invalid pin assignment for TSC_G0 IO2 pin: TSC_G0_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G0, TSC_G0_IO3)
#error Invalid pin assignment for TSC_G0 IO3 pin: TSC_G0_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G0, TSC_G0_IO4)
#error Invalid pin assignment for TSC_G0 IO4 pin: TSC_G0_IO4
#endif
#endif

#ifdef USE_TSC_G1
#if !FIND_VALUE_TSC_G_IO1(_TSC_G1, TSC_G1_IO1)
#error Invalid pin assignment for TSC_G1 IO1 pin: TSC_G1_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G1, TSC_G1_IO2)
#error Invalid pin assignment for TSC_G1 IO2 pin: TSC_G1_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G1, TSC_G1_IO3)
#error Invalid pin assignment for TSC_G1 IO3 pin: TSC_G1_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G1, TSC_G1_IO4)
#error Invalid pin assignment for TSC_G1 IO4 pin: TSC_G1_IO4
#endif
#endif

#ifdef USE_TSC_G2
#if !FIND_VALUE_TSC_G_IO1(_TSC_G2, TSC_G2_IO1)
#error Invalid pin assignment for TSC_G2 IO1 pin: TSC_G2_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G2, TSC_G2_IO2)
#error Invalid pin assignment for TSC_G2 IO2 pin: TSC_G2_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G2, TSC_G2_IO3)
#error Invalid pin assignment for TSC_G2 IO3 pin: TSC_G2_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G2, TSC_G2_IO4)
#error Invalid pin assignment for TSC_G2 IO4 pin: TSC_G2_IO4
#endif
#endif

#ifdef USE_TSC_G3
#if !FIND_VALUE_TSC_G_IO1(_TSC_G3, TSC_G3_IO1)
#error Invalid pin assignment for TSC_G3 IO1 pin: TSC_G3_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G3, TSC_G3_IO2)
#error Invalid pin assignment for TSC_G3 IO2 pin: TSC_G3_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G3, TSC_G3_IO3)
#error Invalid pin assignment for TSC_G3 IO3 pin: TSC_G3_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G3, TSC_G3_IO4)
#error Invalid pin assignment for TSC_G3 IO4 pin: TSC_G3_IO4
#endif
#endif

#ifdef USE_TSC_G4
#if !FIND_VALUE_TSC_G_IO1(_TSC_G4, TSC_G4_IO1)
#error Invalid pin assignment for TSC_G4 IO1 pin: TSC_G4_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G4, TSC_G4_IO2)
#error Invalid pin assignment for TSC_G4 IO2 pin: TSC_G4_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G4, TSC_G4_IO3)
#error Invalid pin assignment for TSC_G4 IO3 pin: TSC_G4_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G4, TSC_G4_IO4)
#error Invalid pin assignment for TSC_G4 IO4 pin: TSC_G4_IO4
#endif
#endif

#ifdef USE_TSC_G5
#if !FIND_VALUE_TSC_G_IO1(_TSC_G5, TSC_G5_IO1)
#error Invalid pin assignment for TSC_G5 IO1 pin: TSC_G5_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G5, TSC_G5_IO2)
#error Invalid pin assignment for TSC_G5 IO2 pin: TSC_G5_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G5, TSC_G5_IO3)
#error Invalid pin assignment for TSC_G5 IO3 pin: TSC_G5_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G5, TSC_G5_IO4)
#error Invalid pin assignment for TSC_G5 IO4 pin: TSC_G5_IO4
#endif
#endif

#ifdef USE_TSC_G6
#if !FIND_VALUE_TSC_G_IO1(_TSC_G6, TSC_G6_IO1)
#error Invalid pin assignment for TSC_G6 IO1 pin: TSC_G6_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G6, TSC_G6_IO2)
#error Invalid pin assignment for TSC_G6 IO2 pin: TSC_G6_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G6, TSC_G6_IO3)
#error Invalid pin assignment for TSC_G6 IO3 pin: TSC_G6_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G6, TSC_G6_IO4)
#error Invalid pin assignment for TSC_G6 IO4 pin: TSC_G6_IO4
#endif
#endif

#ifdef USE_TSC_G7
#if !FIND_VALUE_TSC_G_IO1(_TSC_G7, TSC_G7_IO1)
#error Invalid pin assignment for TSC_G7 IO1 pin: TSC_G7_IO1
#endif
#if !FIND_VALUE_TSC_G_IO2(_TSC_G7, TSC_G7_IO2)
#error Invalid pin assignment for TSC_G7 IO2 pin: TSC_G7_IO2
#endif
#if !FIND_VALUE_TSC_G_IO3(_TSC_G7, TSC_G7_IO3)
#error Invalid pin assignment for TSC_G7 IO3 pin: TSC_G7_IO3
#endif
#if !FIND_VALUE_TSC_G_IO4(_TSC_G7, TSC_G7_IO4)
#error Invalid pin assignment for TSC_G7 IO4 pin: TSC_G7_IO4
#endif
#endif

