/*
 * ErrorPacketSerialRingBuffer.hpp
 *
 *  Created on: 17 Dec 2022
 *      Author: alicia
 */

#ifndef PERIPHERALS_SERIAL_SERIAL_LL_SRC_MAIN_C___SERIAL_LL_LOWLEVEL_ERRORPACKETSERIALRINGBUFFER_HPP_
#define PERIPHERALS_SERIAL_SERIAL_LL_SRC_MAIN_C___SERIAL_LL_LOWLEVEL_ERRORPACKETSERIALRINGBUFFER_HPP_





#endif /* PERIPHERALS_SERIAL_SERIAL_LL_SRC_MAIN_C___SERIAL_LL_LOWLEVEL_ERRORPACKETSERIALRINGBUFFER_HPP_ */
