/*
 * SystemClocks.hpp
 *
 *  Created on: 26 Dec 2020
 *      Author: robert
 */

#ifndef SRC_TEST_CPP_LOWLEVEL_CLOCKSLOWLEVEL_SPECIFIC_SYSTEMCLOCKS_HPP_
#define SRC_TEST_CPP_LOWLEVEL_CLOCKSLOWLEVEL_SPECIFIC_SYSTEMCLOCKS_HPP_

enum SystemClock {
    SysClock, HSI, HSI14, LSI, HSE, LSE, PLL, HCLK, PCLK, NONE
};

#endif /* SRC_TEST_CPP_LOWLEVEL_CLOCKSLOWLEVEL_SPECIFIC_SYSTEMCLOCKS_HPP_ */
