/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546733
 */

#define FIND_VALUE_RCC_LSCO_inner(INDEX,PIN) INDEX##_RCC_##PIN
#define FIND_VALUE_RCC_LSCO(INDEX,PIN) FIND_VALUE_RCC_LSCO_inner(INDEX,PIN)

#define FIND_VALUE_RCC_MCO_inner(INDEX,PIN) INDEX##_RCC_##PIN
#define FIND_VALUE_RCC_MCO(INDEX,PIN) FIND_VALUE_RCC_MCO_inner(INDEX,PIN)

#ifdef USE_RCC0
#if !FIND_VALUE_RCC_LSCO(_RCC0, RCC0_LSCO)
#error Invalid pin assignment for RCC0 LSCO pin: RCC0_LSCO
#endif
#if !FIND_VALUE_RCC_MCO(_RCC0, RCC0_MCO)
#error Invalid pin assignment for RCC0 MCO pin: RCC0_MCO
#endif
#endif

