/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547738
 */

#define FIND_VALUE_V_REF_OUT_inner(INDEX,PIN) INDEX##_V_REF_##PIN
#define FIND_VALUE_V_REF_OUT(INDEX,PIN) FIND_VALUE_V_REF_OUT_inner(INDEX,PIN)

#ifdef USE_V_REF0
#if !FIND_VALUE_V_REF_OUT(_V_REF0, V_REF0_OUT)
#error Invalid pin assignment for V_REF0 OUT pin: V_REF0_OUT
#endif
#endif

