/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545872
 */

#define FIND_VALUE_ETH_PPS_OUT_inner(INDEX,PIN) INDEX##_ETH_PPS_##PIN
#define FIND_VALUE_ETH_PPS_OUT(INDEX,PIN) FIND_VALUE_ETH_PPS_OUT_inner(INDEX,PIN)

#ifdef USE_ETH_PPS0
#if !FIND_VALUE_ETH_PPS_OUT(_ETH_PPS0, ETH_PPS0_OUT)
#error Invalid pin assignment for ETH_PPS0 OUT pin: ETH_PPS0_OUT
#endif
#endif

