/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545910
 */

#define FIND_VALUE_ETH_TX_CLK_inner(INDEX,PIN) INDEX##_ETH_TX_##PIN
#define FIND_VALUE_ETH_TX_CLK(INDEX,PIN) FIND_VALUE_ETH_TX_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TX_EN_inner(INDEX,PIN) INDEX##_ETH_TX_##PIN
#define FIND_VALUE_ETH_TX_EN(INDEX,PIN) FIND_VALUE_ETH_TX_EN_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TX_ER_inner(INDEX,PIN) INDEX##_ETH_TX_##PIN
#define FIND_VALUE_ETH_TX_ER(INDEX,PIN) FIND_VALUE_ETH_TX_ER_inner(INDEX,PIN)

#ifdef USE_ETH_TX0
#if !FIND_VALUE_ETH_TX_CLK(_ETH_TX0, ETH_TX0_CLK)
#error Invalid pin assignment for ETH_TX0 CLK pin: ETH_TX0_CLK
#endif
#if !FIND_VALUE_ETH_TX_EN(_ETH_TX0, ETH_TX0_EN)
#error Invalid pin assignment for ETH_TX0 EN pin: ETH_TX0_EN
#endif
#if !FIND_VALUE_ETH_TX_ER(_ETH_TX0, ETH_TX0_ER)
#error Invalid pin assignment for ETH_TX0 ER pin: ETH_TX0_ER
#endif
#endif

