/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547042
 */

#define FIND_VALUE_SWPMI_IO_inner(INDEX,PIN) INDEX##_SWPMI_##PIN
#define FIND_VALUE_SWPMI_IO(INDEX,PIN) FIND_VALUE_SWPMI_IO_inner(INDEX,PIN)

#define FIND_VALUE_SWPMI_RX_inner(INDEX,PIN) INDEX##_SWPMI_##PIN
#define FIND_VALUE_SWPMI_RX(INDEX,PIN) FIND_VALUE_SWPMI_RX_inner(INDEX,PIN)

#define FIND_VALUE_SWPMI_SUSPEND_inner(INDEX,PIN) INDEX##_SWPMI_##PIN
#define FIND_VALUE_SWPMI_SUSPEND(INDEX,PIN) FIND_VALUE_SWPMI_SUSPEND_inner(INDEX,PIN)

#define FIND_VALUE_SWPMI_TX_inner(INDEX,PIN) INDEX##_SWPMI_##PIN
#define FIND_VALUE_SWPMI_TX(INDEX,PIN) FIND_VALUE_SWPMI_TX_inner(INDEX,PIN)

#ifdef USE_SWPMI0
#if !FIND_VALUE_SWPMI_IO(_SWPMI0, SWPMI0_IO)
#error Invalid pin assignment for SWPMI0 IO pin: SWPMI0_IO
#endif
#if !FIND_VALUE_SWPMI_RX(_SWPMI0, SWPMI0_RX)
#error Invalid pin assignment for SWPMI0 RX pin: SWPMI0_RX
#endif
#if !FIND_VALUE_SWPMI_SUSPEND(_SWPMI0, SWPMI0_SUSPEND)
#error Invalid pin assignment for SWPMI0 SUSPEND pin: SWPMI0_SUSPEND
#endif
#if !FIND_VALUE_SWPMI_TX(_SWPMI0, SWPMI0_TX)
#error Invalid pin assignment for SWPMI0 TX pin: SWPMI0_TX
#endif
#endif

