/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546550
 */

#define FIND_VALUE_MDF_CCK0_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CCK0(INDEX,PIN) FIND_VALUE_MDF_CCK0_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CCK1_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CCK1(INDEX,PIN) FIND_VALUE_MDF_CCK1_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CKI0_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CKI0(INDEX,PIN) FIND_VALUE_MDF_CKI0_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CKI1_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CKI1(INDEX,PIN) FIND_VALUE_MDF_CKI1_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CKI2_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CKI2(INDEX,PIN) FIND_VALUE_MDF_CKI2_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CKI3_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CKI3(INDEX,PIN) FIND_VALUE_MDF_CKI3_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CKI4_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CKI4(INDEX,PIN) FIND_VALUE_MDF_CKI4_inner(INDEX,PIN)

#define FIND_VALUE_MDF_CKI5_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_CKI5(INDEX,PIN) FIND_VALUE_MDF_CKI5_inner(INDEX,PIN)

#define FIND_VALUE_MDF_SDI0_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_SDI0(INDEX,PIN) FIND_VALUE_MDF_SDI0_inner(INDEX,PIN)

#define FIND_VALUE_MDF_SDI1_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_SDI1(INDEX,PIN) FIND_VALUE_MDF_SDI1_inner(INDEX,PIN)

#define FIND_VALUE_MDF_SDI2_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_SDI2(INDEX,PIN) FIND_VALUE_MDF_SDI2_inner(INDEX,PIN)

#define FIND_VALUE_MDF_SDI3_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_SDI3(INDEX,PIN) FIND_VALUE_MDF_SDI3_inner(INDEX,PIN)

#define FIND_VALUE_MDF_SDI4_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_SDI4(INDEX,PIN) FIND_VALUE_MDF_SDI4_inner(INDEX,PIN)

#define FIND_VALUE_MDF_SDI5_inner(INDEX,PIN) INDEX##_MDF_##PIN
#define FIND_VALUE_MDF_SDI5(INDEX,PIN) FIND_VALUE_MDF_SDI5_inner(INDEX,PIN)

#ifdef USE_MDF0
#if !FIND_VALUE_MDF_CCK0(_MDF0, MDF0_CCK0)
#error Invalid pin assignment for MDF0 CCK0 pin: MDF0_CCK0
#endif
#if !FIND_VALUE_MDF_CCK1(_MDF0, MDF0_CCK1)
#error Invalid pin assignment for MDF0 CCK1 pin: MDF0_CCK1
#endif
#if !FIND_VALUE_MDF_CKI0(_MDF0, MDF0_CKI0)
#error Invalid pin assignment for MDF0 CKI0 pin: MDF0_CKI0
#endif
#if !FIND_VALUE_MDF_CKI1(_MDF0, MDF0_CKI1)
#error Invalid pin assignment for MDF0 CKI1 pin: MDF0_CKI1
#endif
#if !FIND_VALUE_MDF_CKI2(_MDF0, MDF0_CKI2)
#error Invalid pin assignment for MDF0 CKI2 pin: MDF0_CKI2
#endif
#if !FIND_VALUE_MDF_CKI3(_MDF0, MDF0_CKI3)
#error Invalid pin assignment for MDF0 CKI3 pin: MDF0_CKI3
#endif
#if !FIND_VALUE_MDF_CKI4(_MDF0, MDF0_CKI4)
#error Invalid pin assignment for MDF0 CKI4 pin: MDF0_CKI4
#endif
#if !FIND_VALUE_MDF_CKI5(_MDF0, MDF0_CKI5)
#error Invalid pin assignment for MDF0 CKI5 pin: MDF0_CKI5
#endif
#if !FIND_VALUE_MDF_SDI0(_MDF0, MDF0_SDI0)
#error Invalid pin assignment for MDF0 SDI0 pin: MDF0_SDI0
#endif
#if !FIND_VALUE_MDF_SDI1(_MDF0, MDF0_SDI1)
#error Invalid pin assignment for MDF0 SDI1 pin: MDF0_SDI1
#endif
#if !FIND_VALUE_MDF_SDI2(_MDF0, MDF0_SDI2)
#error Invalid pin assignment for MDF0 SDI2 pin: MDF0_SDI2
#endif
#if !FIND_VALUE_MDF_SDI3(_MDF0, MDF0_SDI3)
#error Invalid pin assignment for MDF0 SDI3 pin: MDF0_SDI3
#endif
#if !FIND_VALUE_MDF_SDI4(_MDF0, MDF0_SDI4)
#error Invalid pin assignment for MDF0 SDI4 pin: MDF0_SDI4
#endif
#if !FIND_VALUE_MDF_SDI5(_MDF0, MDF0_SDI5)
#error Invalid pin assignment for MDF0 SDI5 pin: MDF0_SDI5
#endif
#endif

