/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546498
 */

#define FIND_VALUE_LPUART_CTS_inner(INDEX,PIN) INDEX##_LPUART_##PIN
#define FIND_VALUE_LPUART_CTS(INDEX,PIN) FIND_VALUE_LPUART_CTS_inner(INDEX,PIN)

#define FIND_VALUE_LPUART_DE_inner(INDEX,PIN) INDEX##_LPUART_##PIN
#define FIND_VALUE_LPUART_DE(INDEX,PIN) FIND_VALUE_LPUART_DE_inner(INDEX,PIN)

#define FIND_VALUE_LPUART_RTS_inner(INDEX,PIN) INDEX##_LPUART_##PIN
#define FIND_VALUE_LPUART_RTS(INDEX,PIN) FIND_VALUE_LPUART_RTS_inner(INDEX,PIN)

#define FIND_VALUE_LPUART_RX_inner(INDEX,PIN) INDEX##_LPUART_##PIN
#define FIND_VALUE_LPUART_RX(INDEX,PIN) FIND_VALUE_LPUART_RX_inner(INDEX,PIN)

#define FIND_VALUE_LPUART_TX_inner(INDEX,PIN) INDEX##_LPUART_##PIN
#define FIND_VALUE_LPUART_TX(INDEX,PIN) FIND_VALUE_LPUART_TX_inner(INDEX,PIN)

#ifdef USE_LPUART0
#if !FIND_VALUE_LPUART_CTS(_LPUART0, LPUART0_CTS)
#error Invalid pin assignment for LPUART0 CTS pin: LPUART0_CTS
#endif
#if !FIND_VALUE_LPUART_DE(_LPUART0, LPUART0_DE)
#error Invalid pin assignment for LPUART0 DE pin: LPUART0_DE
#endif
#if !FIND_VALUE_LPUART_RTS(_LPUART0, LPUART0_RTS)
#error Invalid pin assignment for LPUART0 RTS pin: LPUART0_RTS
#endif
#if !FIND_VALUE_LPUART_RX(_LPUART0, LPUART0_RX)
#error Invalid pin assignment for LPUART0 RX pin: LPUART0_RX
#endif
#if !FIND_VALUE_LPUART_TX(_LPUART0, LPUART0_TX)
#error Invalid pin assignment for LPUART0 TX pin: LPUART0_TX
#endif
#endif

#ifdef USE_LPUART1
#if !FIND_VALUE_LPUART_CTS(_LPUART1, LPUART1_CTS)
#error Invalid pin assignment for LPUART1 CTS pin: LPUART1_CTS
#endif
#if !FIND_VALUE_LPUART_DE(_LPUART1, LPUART1_DE)
#error Invalid pin assignment for LPUART1 DE pin: LPUART1_DE
#endif
#if !FIND_VALUE_LPUART_RTS(_LPUART1, LPUART1_RTS)
#error Invalid pin assignment for LPUART1 RTS pin: LPUART1_RTS
#endif
#if !FIND_VALUE_LPUART_RX(_LPUART1, LPUART1_RX)
#error Invalid pin assignment for LPUART1 RX pin: LPUART1_RX
#endif
#if !FIND_VALUE_LPUART_TX(_LPUART1, LPUART1_TX)
#error Invalid pin assignment for LPUART1 TX pin: LPUART1_TX
#endif
#endif

