/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546960
 */

#define FIND_VALUE_SDMMC_CDIR_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_CDIR(INDEX,PIN) FIND_VALUE_SDMMC_CDIR_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_CK_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_CK(INDEX,PIN) FIND_VALUE_SDMMC_CK_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_CKIN_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_CKIN(INDEX,PIN) FIND_VALUE_SDMMC_CKIN_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_CMD_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_CMD(INDEX,PIN) FIND_VALUE_SDMMC_CMD_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D0_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D0(INDEX,PIN) FIND_VALUE_SDMMC_D0_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D0DIR_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D0DIR(INDEX,PIN) FIND_VALUE_SDMMC_D0DIR_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D1_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D1(INDEX,PIN) FIND_VALUE_SDMMC_D1_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D123DIR_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D123DIR(INDEX,PIN) FIND_VALUE_SDMMC_D123DIR_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D2_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D2(INDEX,PIN) FIND_VALUE_SDMMC_D2_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D3_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D3(INDEX,PIN) FIND_VALUE_SDMMC_D3_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D4_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D4(INDEX,PIN) FIND_VALUE_SDMMC_D4_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D5_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D5(INDEX,PIN) FIND_VALUE_SDMMC_D5_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D6_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D6(INDEX,PIN) FIND_VALUE_SDMMC_D6_inner(INDEX,PIN)

#define FIND_VALUE_SDMMC_D7_inner(INDEX,PIN) INDEX##_SDMMC_##PIN
#define FIND_VALUE_SDMMC_D7(INDEX,PIN) FIND_VALUE_SDMMC_D7_inner(INDEX,PIN)

#ifdef USE_SDMMC0
#if !FIND_VALUE_SDMMC_CDIR(_SDMMC0, SDMMC0_CDIR)
#error Invalid pin assignment for SDMMC0 CDIR pin: SDMMC0_CDIR
#endif
#if !FIND_VALUE_SDMMC_CK(_SDMMC0, SDMMC0_CK)
#error Invalid pin assignment for SDMMC0 CK pin: SDMMC0_CK
#endif
#if !FIND_VALUE_SDMMC_CKIN(_SDMMC0, SDMMC0_CKIN)
#error Invalid pin assignment for SDMMC0 CKIN pin: SDMMC0_CKIN
#endif
#if !FIND_VALUE_SDMMC_CMD(_SDMMC0, SDMMC0_CMD)
#error Invalid pin assignment for SDMMC0 CMD pin: SDMMC0_CMD
#endif
#if !FIND_VALUE_SDMMC_D0(_SDMMC0, SDMMC0_D0)
#error Invalid pin assignment for SDMMC0 D0 pin: SDMMC0_D0
#endif
#if !FIND_VALUE_SDMMC_D0DIR(_SDMMC0, SDMMC0_D0DIR)
#error Invalid pin assignment for SDMMC0 D0DIR pin: SDMMC0_D0DIR
#endif
#if !FIND_VALUE_SDMMC_D1(_SDMMC0, SDMMC0_D1)
#error Invalid pin assignment for SDMMC0 D1 pin: SDMMC0_D1
#endif
#if !FIND_VALUE_SDMMC_D123DIR(_SDMMC0, SDMMC0_D123DIR)
#error Invalid pin assignment for SDMMC0 D123DIR pin: SDMMC0_D123DIR
#endif
#if !FIND_VALUE_SDMMC_D2(_SDMMC0, SDMMC0_D2)
#error Invalid pin assignment for SDMMC0 D2 pin: SDMMC0_D2
#endif
#if !FIND_VALUE_SDMMC_D3(_SDMMC0, SDMMC0_D3)
#error Invalid pin assignment for SDMMC0 D3 pin: SDMMC0_D3
#endif
#if !FIND_VALUE_SDMMC_D4(_SDMMC0, SDMMC0_D4)
#error Invalid pin assignment for SDMMC0 D4 pin: SDMMC0_D4
#endif
#if !FIND_VALUE_SDMMC_D5(_SDMMC0, SDMMC0_D5)
#error Invalid pin assignment for SDMMC0 D5 pin: SDMMC0_D5
#endif
#if !FIND_VALUE_SDMMC_D6(_SDMMC0, SDMMC0_D6)
#error Invalid pin assignment for SDMMC0 D6 pin: SDMMC0_D6
#endif
#if !FIND_VALUE_SDMMC_D7(_SDMMC0, SDMMC0_D7)
#error Invalid pin assignment for SDMMC0 D7 pin: SDMMC0_D7
#endif
#endif

#ifdef USE_SDMMC1
#if !FIND_VALUE_SDMMC_CDIR(_SDMMC1, SDMMC1_CDIR)
#error Invalid pin assignment for SDMMC1 CDIR pin: SDMMC1_CDIR
#endif
#if !FIND_VALUE_SDMMC_CK(_SDMMC1, SDMMC1_CK)
#error Invalid pin assignment for SDMMC1 CK pin: SDMMC1_CK
#endif
#if !FIND_VALUE_SDMMC_CKIN(_SDMMC1, SDMMC1_CKIN)
#error Invalid pin assignment for SDMMC1 CKIN pin: SDMMC1_CKIN
#endif
#if !FIND_VALUE_SDMMC_CMD(_SDMMC1, SDMMC1_CMD)
#error Invalid pin assignment for SDMMC1 CMD pin: SDMMC1_CMD
#endif
#if !FIND_VALUE_SDMMC_D0(_SDMMC1, SDMMC1_D0)
#error Invalid pin assignment for SDMMC1 D0 pin: SDMMC1_D0
#endif
#if !FIND_VALUE_SDMMC_D0DIR(_SDMMC1, SDMMC1_D0DIR)
#error Invalid pin assignment for SDMMC1 D0DIR pin: SDMMC1_D0DIR
#endif
#if !FIND_VALUE_SDMMC_D1(_SDMMC1, SDMMC1_D1)
#error Invalid pin assignment for SDMMC1 D1 pin: SDMMC1_D1
#endif
#if !FIND_VALUE_SDMMC_D123DIR(_SDMMC1, SDMMC1_D123DIR)
#error Invalid pin assignment for SDMMC1 D123DIR pin: SDMMC1_D123DIR
#endif
#if !FIND_VALUE_SDMMC_D2(_SDMMC1, SDMMC1_D2)
#error Invalid pin assignment for SDMMC1 D2 pin: SDMMC1_D2
#endif
#if !FIND_VALUE_SDMMC_D3(_SDMMC1, SDMMC1_D3)
#error Invalid pin assignment for SDMMC1 D3 pin: SDMMC1_D3
#endif
#if !FIND_VALUE_SDMMC_D4(_SDMMC1, SDMMC1_D4)
#error Invalid pin assignment for SDMMC1 D4 pin: SDMMC1_D4
#endif
#if !FIND_VALUE_SDMMC_D5(_SDMMC1, SDMMC1_D5)
#error Invalid pin assignment for SDMMC1 D5 pin: SDMMC1_D5
#endif
#if !FIND_VALUE_SDMMC_D6(_SDMMC1, SDMMC1_D6)
#error Invalid pin assignment for SDMMC1 D6 pin: SDMMC1_D6
#endif
#if !FIND_VALUE_SDMMC_D7(_SDMMC1, SDMMC1_D7)
#error Invalid pin assignment for SDMMC1 D7 pin: SDMMC1_D7
#endif
#endif

#ifdef USE_SDMMC2
#if !FIND_VALUE_SDMMC_CDIR(_SDMMC2, SDMMC2_CDIR)
#error Invalid pin assignment for SDMMC2 CDIR pin: SDMMC2_CDIR
#endif
#if !FIND_VALUE_SDMMC_CK(_SDMMC2, SDMMC2_CK)
#error Invalid pin assignment for SDMMC2 CK pin: SDMMC2_CK
#endif
#if !FIND_VALUE_SDMMC_CKIN(_SDMMC2, SDMMC2_CKIN)
#error Invalid pin assignment for SDMMC2 CKIN pin: SDMMC2_CKIN
#endif
#if !FIND_VALUE_SDMMC_CMD(_SDMMC2, SDMMC2_CMD)
#error Invalid pin assignment for SDMMC2 CMD pin: SDMMC2_CMD
#endif
#if !FIND_VALUE_SDMMC_D0(_SDMMC2, SDMMC2_D0)
#error Invalid pin assignment for SDMMC2 D0 pin: SDMMC2_D0
#endif
#if !FIND_VALUE_SDMMC_D0DIR(_SDMMC2, SDMMC2_D0DIR)
#error Invalid pin assignment for SDMMC2 D0DIR pin: SDMMC2_D0DIR
#endif
#if !FIND_VALUE_SDMMC_D1(_SDMMC2, SDMMC2_D1)
#error Invalid pin assignment for SDMMC2 D1 pin: SDMMC2_D1
#endif
#if !FIND_VALUE_SDMMC_D123DIR(_SDMMC2, SDMMC2_D123DIR)
#error Invalid pin assignment for SDMMC2 D123DIR pin: SDMMC2_D123DIR
#endif
#if !FIND_VALUE_SDMMC_D2(_SDMMC2, SDMMC2_D2)
#error Invalid pin assignment for SDMMC2 D2 pin: SDMMC2_D2
#endif
#if !FIND_VALUE_SDMMC_D3(_SDMMC2, SDMMC2_D3)
#error Invalid pin assignment for SDMMC2 D3 pin: SDMMC2_D3
#endif
#if !FIND_VALUE_SDMMC_D4(_SDMMC2, SDMMC2_D4)
#error Invalid pin assignment for SDMMC2 D4 pin: SDMMC2_D4
#endif
#if !FIND_VALUE_SDMMC_D5(_SDMMC2, SDMMC2_D5)
#error Invalid pin assignment for SDMMC2 D5 pin: SDMMC2_D5
#endif
#if !FIND_VALUE_SDMMC_D6(_SDMMC2, SDMMC2_D6)
#error Invalid pin assignment for SDMMC2 D6 pin: SDMMC2_D6
#endif
#if !FIND_VALUE_SDMMC_D7(_SDMMC2, SDMMC2_D7)
#error Invalid pin assignment for SDMMC2 D7 pin: SDMMC2_D7
#endif
#endif

