/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545570
 */

#define FIND_VALUE_CRS_SYNC_inner(INDEX,PIN) INDEX##_CRS_##PIN
#define FIND_VALUE_CRS_SYNC(INDEX,PIN) FIND_VALUE_CRS_SYNC_inner(INDEX,PIN)

#ifdef USE_CRS0
#if !FIND_VALUE_CRS_SYNC(_CRS0, CRS0_SYNC)
#error Invalid pin assignment for CRS0 SYNC pin: CRS0_SYNC
#endif
#endif

