/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547094
 */

#define FIND_VALUE_SYS__ functionality on new pin (forecasted in Stingray 64K pinout file)_inner(INDEX,PIN) INDEX##_SYS__##PIN
#define FIND_VALUE_SYS__ functionality on new pin (forecasted in Stingray 64K pinout file)(INDEX,PIN) FIND_VALUE_SYS__ functionality on new pin (forecasted in Stingray 64K pinout file)_inner(INDEX,PIN)

#define FIND_VALUE_SYS__ new functionality (not forecasted in Stingray 64K pinout file)_inner(INDEX,PIN) INDEX##_SYS__##PIN
#define FIND_VALUE_SYS__ new functionality (not forecasted in Stingray 64K pinout file)(INDEX,PIN) FIND_VALUE_SYS__ new functionality (not forecasted in Stingray 64K pinout file)_inner(INDEX,PIN)

#define FIND_VALUE_SYS__ new pin (not existing on Stingray 64K)_inner(INDEX,PIN) INDEX##_SYS__##PIN
#define FIND_VALUE_SYS__ new pin (not existing on Stingray 64K)(INDEX,PIN) FIND_VALUE_SYS__ new pin (not existing on Stingray 64K)_inner(INDEX,PIN)

#ifdef USE_SYS_0
#if !FIND_VALUE_SYS__ functionality on new pin (forecasted in Stingray 64K pinout file)(_SYS_0, SYS_0_ functionality on new pin (forecasted in Stingray 64K pinout file))
#error Invalid pin assignment for SYS_0  functionality on new pin (forecasted in Stingray 64K pinout file) pin: SYS_0_ functionality on new pin (forecasted in Stingray 64K pinout file)
#endif
#if !FIND_VALUE_SYS__ new functionality (not forecasted in Stingray 64K pinout file)(_SYS_0, SYS_0_ new functionality (not forecasted in Stingray 64K pinout file))
#error Invalid pin assignment for SYS_0  new functionality (not forecasted in Stingray 64K pinout file) pin: SYS_0_ new functionality (not forecasted in Stingray 64K pinout file)
#endif
#if !FIND_VALUE_SYS__ new pin (not existing on Stingray 64K)(_SYS_0, SYS_0_ new pin (not existing on Stingray 64K))
#error Invalid pin assignment for SYS_0  new pin (not existing on Stingray 64K) pin: SYS_0_ new pin (not existing on Stingray 64K)
#endif
#endif

