/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547456
 */

#define FIND_VALUE_TSC_SYNC_inner(INDEX,PIN) INDEX##_TSC_##PIN
#define FIND_VALUE_TSC_SYNC(INDEX,PIN) FIND_VALUE_TSC_SYNC_inner(INDEX,PIN)

#ifdef USE_TSC0
#if !FIND_VALUE_TSC_SYNC(_TSC0, TSC0_SYNC)
#error Invalid pin assignment for TSC0 SYNC pin: TSC0_SYNC
#endif
#endif

