/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547553
 */

#define FIND_VALUE_UART_CTS_inner(INDEX,PIN) INDEX##_UART_##PIN
#define FIND_VALUE_UART_CTS(INDEX,PIN) FIND_VALUE_UART_CTS_inner(INDEX,PIN)

#define FIND_VALUE_UART_CTS_NSS_inner(INDEX,PIN) INDEX##_UART_##PIN
#define FIND_VALUE_UART_CTS_NSS(INDEX,PIN) FIND_VALUE_UART_CTS_NSS_inner(INDEX,PIN)

#define FIND_VALUE_UART_DE_inner(INDEX,PIN) INDEX##_UART_##PIN
#define FIND_VALUE_UART_DE(INDEX,PIN) FIND_VALUE_UART_DE_inner(INDEX,PIN)

#define FIND_VALUE_UART_RTS_inner(INDEX,PIN) INDEX##_UART_##PIN
#define FIND_VALUE_UART_RTS(INDEX,PIN) FIND_VALUE_UART_RTS_inner(INDEX,PIN)

#define FIND_VALUE_UART_RX_inner(INDEX,PIN) INDEX##_UART_##PIN
#define FIND_VALUE_UART_RX(INDEX,PIN) FIND_VALUE_UART_RX_inner(INDEX,PIN)

#define FIND_VALUE_UART_TX_inner(INDEX,PIN) INDEX##_UART_##PIN
#define FIND_VALUE_UART_TX(INDEX,PIN) FIND_VALUE_UART_TX_inner(INDEX,PIN)

#ifdef USE_UART0
#if !FIND_VALUE_UART_CTS(_UART0, UART0_CTS)
#error Invalid pin assignment for UART0 CTS pin: UART0_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART0, UART0_CTS_NSS)
#error Invalid pin assignment for UART0 CTS_NSS pin: UART0_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART0, UART0_DE)
#error Invalid pin assignment for UART0 DE pin: UART0_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART0, UART0_RTS)
#error Invalid pin assignment for UART0 RTS pin: UART0_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART0, UART0_RX)
#error Invalid pin assignment for UART0 RX pin: UART0_RX
#endif
#if !FIND_VALUE_UART_TX(_UART0, UART0_TX)
#error Invalid pin assignment for UART0 TX pin: UART0_TX
#endif
#endif

#ifdef USE_UART1
#if !FIND_VALUE_UART_CTS(_UART1, UART1_CTS)
#error Invalid pin assignment for UART1 CTS pin: UART1_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART1, UART1_CTS_NSS)
#error Invalid pin assignment for UART1 CTS_NSS pin: UART1_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART1, UART1_DE)
#error Invalid pin assignment for UART1 DE pin: UART1_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART1, UART1_RTS)
#error Invalid pin assignment for UART1 RTS pin: UART1_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART1, UART1_RX)
#error Invalid pin assignment for UART1 RX pin: UART1_RX
#endif
#if !FIND_VALUE_UART_TX(_UART1, UART1_TX)
#error Invalid pin assignment for UART1 TX pin: UART1_TX
#endif
#endif

#ifdef USE_UART2
#if !FIND_VALUE_UART_CTS(_UART2, UART2_CTS)
#error Invalid pin assignment for UART2 CTS pin: UART2_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART2, UART2_CTS_NSS)
#error Invalid pin assignment for UART2 CTS_NSS pin: UART2_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART2, UART2_DE)
#error Invalid pin assignment for UART2 DE pin: UART2_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART2, UART2_RTS)
#error Invalid pin assignment for UART2 RTS pin: UART2_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART2, UART2_RX)
#error Invalid pin assignment for UART2 RX pin: UART2_RX
#endif
#if !FIND_VALUE_UART_TX(_UART2, UART2_TX)
#error Invalid pin assignment for UART2 TX pin: UART2_TX
#endif
#endif

#ifdef USE_UART3
#if !FIND_VALUE_UART_CTS(_UART3, UART3_CTS)
#error Invalid pin assignment for UART3 CTS pin: UART3_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART3, UART3_CTS_NSS)
#error Invalid pin assignment for UART3 CTS_NSS pin: UART3_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART3, UART3_DE)
#error Invalid pin assignment for UART3 DE pin: UART3_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART3, UART3_RTS)
#error Invalid pin assignment for UART3 RTS pin: UART3_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART3, UART3_RX)
#error Invalid pin assignment for UART3 RX pin: UART3_RX
#endif
#if !FIND_VALUE_UART_TX(_UART3, UART3_TX)
#error Invalid pin assignment for UART3 TX pin: UART3_TX
#endif
#endif

#ifdef USE_UART4
#if !FIND_VALUE_UART_CTS(_UART4, UART4_CTS)
#error Invalid pin assignment for UART4 CTS pin: UART4_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART4, UART4_CTS_NSS)
#error Invalid pin assignment for UART4 CTS_NSS pin: UART4_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART4, UART4_DE)
#error Invalid pin assignment for UART4 DE pin: UART4_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART4, UART4_RTS)
#error Invalid pin assignment for UART4 RTS pin: UART4_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART4, UART4_RX)
#error Invalid pin assignment for UART4 RX pin: UART4_RX
#endif
#if !FIND_VALUE_UART_TX(_UART4, UART4_TX)
#error Invalid pin assignment for UART4 TX pin: UART4_TX
#endif
#endif

#ifdef USE_UART5
#if !FIND_VALUE_UART_CTS(_UART5, UART5_CTS)
#error Invalid pin assignment for UART5 CTS pin: UART5_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART5, UART5_CTS_NSS)
#error Invalid pin assignment for UART5 CTS_NSS pin: UART5_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART5, UART5_DE)
#error Invalid pin assignment for UART5 DE pin: UART5_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART5, UART5_RTS)
#error Invalid pin assignment for UART5 RTS pin: UART5_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART5, UART5_RX)
#error Invalid pin assignment for UART5 RX pin: UART5_RX
#endif
#if !FIND_VALUE_UART_TX(_UART5, UART5_TX)
#error Invalid pin assignment for UART5 TX pin: UART5_TX
#endif
#endif

#ifdef USE_UART6
#if !FIND_VALUE_UART_CTS(_UART6, UART6_CTS)
#error Invalid pin assignment for UART6 CTS pin: UART6_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART6, UART6_CTS_NSS)
#error Invalid pin assignment for UART6 CTS_NSS pin: UART6_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART6, UART6_DE)
#error Invalid pin assignment for UART6 DE pin: UART6_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART6, UART6_RTS)
#error Invalid pin assignment for UART6 RTS pin: UART6_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART6, UART6_RX)
#error Invalid pin assignment for UART6 RX pin: UART6_RX
#endif
#if !FIND_VALUE_UART_TX(_UART6, UART6_TX)
#error Invalid pin assignment for UART6 TX pin: UART6_TX
#endif
#endif

#ifdef USE_UART7
#if !FIND_VALUE_UART_CTS(_UART7, UART7_CTS)
#error Invalid pin assignment for UART7 CTS pin: UART7_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART7, UART7_CTS_NSS)
#error Invalid pin assignment for UART7 CTS_NSS pin: UART7_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART7, UART7_DE)
#error Invalid pin assignment for UART7 DE pin: UART7_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART7, UART7_RTS)
#error Invalid pin assignment for UART7 RTS pin: UART7_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART7, UART7_RX)
#error Invalid pin assignment for UART7 RX pin: UART7_RX
#endif
#if !FIND_VALUE_UART_TX(_UART7, UART7_TX)
#error Invalid pin assignment for UART7 TX pin: UART7_TX
#endif
#endif

#ifdef USE_UART8
#if !FIND_VALUE_UART_CTS(_UART8, UART8_CTS)
#error Invalid pin assignment for UART8 CTS pin: UART8_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART8, UART8_CTS_NSS)
#error Invalid pin assignment for UART8 CTS_NSS pin: UART8_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART8, UART8_DE)
#error Invalid pin assignment for UART8 DE pin: UART8_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART8, UART8_RTS)
#error Invalid pin assignment for UART8 RTS pin: UART8_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART8, UART8_RX)
#error Invalid pin assignment for UART8 RX pin: UART8_RX
#endif
#if !FIND_VALUE_UART_TX(_UART8, UART8_TX)
#error Invalid pin assignment for UART8 TX pin: UART8_TX
#endif
#endif

#ifdef USE_UART9
#if !FIND_VALUE_UART_CTS(_UART9, UART9_CTS)
#error Invalid pin assignment for UART9 CTS pin: UART9_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART9, UART9_CTS_NSS)
#error Invalid pin assignment for UART9 CTS_NSS pin: UART9_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART9, UART9_DE)
#error Invalid pin assignment for UART9 DE pin: UART9_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART9, UART9_RTS)
#error Invalid pin assignment for UART9 RTS pin: UART9_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART9, UART9_RX)
#error Invalid pin assignment for UART9 RX pin: UART9_RX
#endif
#if !FIND_VALUE_UART_TX(_UART9, UART9_TX)
#error Invalid pin assignment for UART9 TX pin: UART9_TX
#endif
#endif

#ifdef USE_UART10
#if !FIND_VALUE_UART_CTS(_UART10, UART10_CTS)
#error Invalid pin assignment for UART10 CTS pin: UART10_CTS
#endif
#if !FIND_VALUE_UART_CTS_NSS(_UART10, UART10_CTS_NSS)
#error Invalid pin assignment for UART10 CTS_NSS pin: UART10_CTS_NSS
#endif
#if !FIND_VALUE_UART_DE(_UART10, UART10_DE)
#error Invalid pin assignment for UART10 DE pin: UART10_DE
#endif
#if !FIND_VALUE_UART_RTS(_UART10, UART10_RTS)
#error Invalid pin assignment for UART10 RTS pin: UART10_RTS
#endif
#if !FIND_VALUE_UART_RX(_UART10, UART10_RX)
#error Invalid pin assignment for UART10 RX pin: UART10_RX
#endif
#if !FIND_VALUE_UART_TX(_UART10, UART10_TX)
#error Invalid pin assignment for UART10 TX pin: UART10_TX
#endif
#endif

