/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546745
 */

#define FIND_VALUE_RCC_MCO_1_inner(INDEX,PIN) INDEX##_RCC_MCO_##PIN
#define FIND_VALUE_RCC_MCO_1(INDEX,PIN) FIND_VALUE_RCC_MCO_1_inner(INDEX,PIN)

#define FIND_VALUE_RCC_MCO_2_inner(INDEX,PIN) INDEX##_RCC_MCO_##PIN
#define FIND_VALUE_RCC_MCO_2(INDEX,PIN) FIND_VALUE_RCC_MCO_2_inner(INDEX,PIN)

#ifdef USE_RCC_MCO0
#if !FIND_VALUE_RCC_MCO_1(_RCC_MCO0, RCC_MCO0_1)
#error Invalid pin assignment for RCC_MCO0 1 pin: RCC_MCO0_1
#endif
#if !FIND_VALUE_RCC_MCO_2(_RCC_MCO0, RCC_MCO0_2)
#error Invalid pin assignment for RCC_MCO0 2 pin: RCC_MCO0_2
#endif
#endif

