/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546515
 */

#define FIND_VALUE_LTDC_B0_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B0(INDEX,PIN) FIND_VALUE_LTDC_B0_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B1_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B1(INDEX,PIN) FIND_VALUE_LTDC_B1_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B2_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B2(INDEX,PIN) FIND_VALUE_LTDC_B2_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B3_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B3(INDEX,PIN) FIND_VALUE_LTDC_B3_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B4_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B4(INDEX,PIN) FIND_VALUE_LTDC_B4_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B5_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B5(INDEX,PIN) FIND_VALUE_LTDC_B5_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B6_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B6(INDEX,PIN) FIND_VALUE_LTDC_B6_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_B7_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_B7(INDEX,PIN) FIND_VALUE_LTDC_B7_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_CLK_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_CLK(INDEX,PIN) FIND_VALUE_LTDC_CLK_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_DE_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_DE(INDEX,PIN) FIND_VALUE_LTDC_DE_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G0_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G0(INDEX,PIN) FIND_VALUE_LTDC_G0_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G1_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G1(INDEX,PIN) FIND_VALUE_LTDC_G1_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G2_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G2(INDEX,PIN) FIND_VALUE_LTDC_G2_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G3_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G3(INDEX,PIN) FIND_VALUE_LTDC_G3_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G4_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G4(INDEX,PIN) FIND_VALUE_LTDC_G4_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G5_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G5(INDEX,PIN) FIND_VALUE_LTDC_G5_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G6_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G6(INDEX,PIN) FIND_VALUE_LTDC_G6_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_G7_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_G7(INDEX,PIN) FIND_VALUE_LTDC_G7_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_HSYNC_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_HSYNC(INDEX,PIN) FIND_VALUE_LTDC_HSYNC_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R0_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R0(INDEX,PIN) FIND_VALUE_LTDC_R0_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R1_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R1(INDEX,PIN) FIND_VALUE_LTDC_R1_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R2_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R2(INDEX,PIN) FIND_VALUE_LTDC_R2_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R3_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R3(INDEX,PIN) FIND_VALUE_LTDC_R3_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R4_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R4(INDEX,PIN) FIND_VALUE_LTDC_R4_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R5_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R5(INDEX,PIN) FIND_VALUE_LTDC_R5_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R6_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R6(INDEX,PIN) FIND_VALUE_LTDC_R6_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_R7_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_R7(INDEX,PIN) FIND_VALUE_LTDC_R7_inner(INDEX,PIN)

#define FIND_VALUE_LTDC_VSYNC_inner(INDEX,PIN) INDEX##_LTDC_##PIN
#define FIND_VALUE_LTDC_VSYNC(INDEX,PIN) FIND_VALUE_LTDC_VSYNC_inner(INDEX,PIN)

#ifdef USE_LTDC0
#if !FIND_VALUE_LTDC_B0(_LTDC0, LTDC0_B0)
#error Invalid pin assignment for LTDC0 B0 pin: LTDC0_B0
#endif
#if !FIND_VALUE_LTDC_B1(_LTDC0, LTDC0_B1)
#error Invalid pin assignment for LTDC0 B1 pin: LTDC0_B1
#endif
#if !FIND_VALUE_LTDC_B2(_LTDC0, LTDC0_B2)
#error Invalid pin assignment for LTDC0 B2 pin: LTDC0_B2
#endif
#if !FIND_VALUE_LTDC_B3(_LTDC0, LTDC0_B3)
#error Invalid pin assignment for LTDC0 B3 pin: LTDC0_B3
#endif
#if !FIND_VALUE_LTDC_B4(_LTDC0, LTDC0_B4)
#error Invalid pin assignment for LTDC0 B4 pin: LTDC0_B4
#endif
#if !FIND_VALUE_LTDC_B5(_LTDC0, LTDC0_B5)
#error Invalid pin assignment for LTDC0 B5 pin: LTDC0_B5
#endif
#if !FIND_VALUE_LTDC_B6(_LTDC0, LTDC0_B6)
#error Invalid pin assignment for LTDC0 B6 pin: LTDC0_B6
#endif
#if !FIND_VALUE_LTDC_B7(_LTDC0, LTDC0_B7)
#error Invalid pin assignment for LTDC0 B7 pin: LTDC0_B7
#endif
#if !FIND_VALUE_LTDC_CLK(_LTDC0, LTDC0_CLK)
#error Invalid pin assignment for LTDC0 CLK pin: LTDC0_CLK
#endif
#if !FIND_VALUE_LTDC_DE(_LTDC0, LTDC0_DE)
#error Invalid pin assignment for LTDC0 DE pin: LTDC0_DE
#endif
#if !FIND_VALUE_LTDC_G0(_LTDC0, LTDC0_G0)
#error Invalid pin assignment for LTDC0 G0 pin: LTDC0_G0
#endif
#if !FIND_VALUE_LTDC_G1(_LTDC0, LTDC0_G1)
#error Invalid pin assignment for LTDC0 G1 pin: LTDC0_G1
#endif
#if !FIND_VALUE_LTDC_G2(_LTDC0, LTDC0_G2)
#error Invalid pin assignment for LTDC0 G2 pin: LTDC0_G2
#endif
#if !FIND_VALUE_LTDC_G3(_LTDC0, LTDC0_G3)
#error Invalid pin assignment for LTDC0 G3 pin: LTDC0_G3
#endif
#if !FIND_VALUE_LTDC_G4(_LTDC0, LTDC0_G4)
#error Invalid pin assignment for LTDC0 G4 pin: LTDC0_G4
#endif
#if !FIND_VALUE_LTDC_G5(_LTDC0, LTDC0_G5)
#error Invalid pin assignment for LTDC0 G5 pin: LTDC0_G5
#endif
#if !FIND_VALUE_LTDC_G6(_LTDC0, LTDC0_G6)
#error Invalid pin assignment for LTDC0 G6 pin: LTDC0_G6
#endif
#if !FIND_VALUE_LTDC_G7(_LTDC0, LTDC0_G7)
#error Invalid pin assignment for LTDC0 G7 pin: LTDC0_G7
#endif
#if !FIND_VALUE_LTDC_HSYNC(_LTDC0, LTDC0_HSYNC)
#error Invalid pin assignment for LTDC0 HSYNC pin: LTDC0_HSYNC
#endif
#if !FIND_VALUE_LTDC_R0(_LTDC0, LTDC0_R0)
#error Invalid pin assignment for LTDC0 R0 pin: LTDC0_R0
#endif
#if !FIND_VALUE_LTDC_R1(_LTDC0, LTDC0_R1)
#error Invalid pin assignment for LTDC0 R1 pin: LTDC0_R1
#endif
#if !FIND_VALUE_LTDC_R2(_LTDC0, LTDC0_R2)
#error Invalid pin assignment for LTDC0 R2 pin: LTDC0_R2
#endif
#if !FIND_VALUE_LTDC_R3(_LTDC0, LTDC0_R3)
#error Invalid pin assignment for LTDC0 R3 pin: LTDC0_R3
#endif
#if !FIND_VALUE_LTDC_R4(_LTDC0, LTDC0_R4)
#error Invalid pin assignment for LTDC0 R4 pin: LTDC0_R4
#endif
#if !FIND_VALUE_LTDC_R5(_LTDC0, LTDC0_R5)
#error Invalid pin assignment for LTDC0 R5 pin: LTDC0_R5
#endif
#if !FIND_VALUE_LTDC_R6(_LTDC0, LTDC0_R6)
#error Invalid pin assignment for LTDC0 R6 pin: LTDC0_R6
#endif
#if !FIND_VALUE_LTDC_R7(_LTDC0, LTDC0_R7)
#error Invalid pin assignment for LTDC0 R7 pin: LTDC0_R7
#endif
#if !FIND_VALUE_LTDC_VSYNC(_LTDC0, LTDC0_VSYNC)
#error Invalid pin assignment for LTDC0 VSYNC pin: LTDC0_VSYNC
#endif
#endif

