/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546843
 */

#define FIND_VALUE_RF_TX_MOD_EXT_PA_inner(INDEX,PIN) INDEX##_RF_TX_MOD_EXT_##PIN
#define FIND_VALUE_RF_TX_MOD_EXT_PA(INDEX,PIN) FIND_VALUE_RF_TX_MOD_EXT_PA_inner(INDEX,PIN)

#ifdef USE_RF_TX_MOD_EXT0
#if !FIND_VALUE_RF_TX_MOD_EXT_PA(_RF_TX_MOD_EXT0, RF_TX_MOD_EXT0_PA)
#error Invalid pin assignment for RF_TX_MOD_EXT0 PA pin: RF_TX_MOD_EXT0_PA
#endif
#endif

