/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546941
 */

#define FIND_VALUE_SDIO_CK_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_CK(INDEX,PIN) FIND_VALUE_SDIO_CK_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_CMD_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_CMD(INDEX,PIN) FIND_VALUE_SDIO_CMD_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D0_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D0(INDEX,PIN) FIND_VALUE_SDIO_D0_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D1_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D1(INDEX,PIN) FIND_VALUE_SDIO_D1_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D2_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D2(INDEX,PIN) FIND_VALUE_SDIO_D2_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D3_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D3(INDEX,PIN) FIND_VALUE_SDIO_D3_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D4_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D4(INDEX,PIN) FIND_VALUE_SDIO_D4_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D5_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D5(INDEX,PIN) FIND_VALUE_SDIO_D5_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D6_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D6(INDEX,PIN) FIND_VALUE_SDIO_D6_inner(INDEX,PIN)

#define FIND_VALUE_SDIO_D7_inner(INDEX,PIN) INDEX##_SDIO_##PIN
#define FIND_VALUE_SDIO_D7(INDEX,PIN) FIND_VALUE_SDIO_D7_inner(INDEX,PIN)

#ifdef USE_SDIO0
#if !FIND_VALUE_SDIO_CK(_SDIO0, SDIO0_CK)
#error Invalid pin assignment for SDIO0 CK pin: SDIO0_CK
#endif
#if !FIND_VALUE_SDIO_CMD(_SDIO0, SDIO0_CMD)
#error Invalid pin assignment for SDIO0 CMD pin: SDIO0_CMD
#endif
#if !FIND_VALUE_SDIO_D0(_SDIO0, SDIO0_D0)
#error Invalid pin assignment for SDIO0 D0 pin: SDIO0_D0
#endif
#if !FIND_VALUE_SDIO_D1(_SDIO0, SDIO0_D1)
#error Invalid pin assignment for SDIO0 D1 pin: SDIO0_D1
#endif
#if !FIND_VALUE_SDIO_D2(_SDIO0, SDIO0_D2)
#error Invalid pin assignment for SDIO0 D2 pin: SDIO0_D2
#endif
#if !FIND_VALUE_SDIO_D3(_SDIO0, SDIO0_D3)
#error Invalid pin assignment for SDIO0 D3 pin: SDIO0_D3
#endif
#if !FIND_VALUE_SDIO_D4(_SDIO0, SDIO0_D4)
#error Invalid pin assignment for SDIO0 D4 pin: SDIO0_D4
#endif
#if !FIND_VALUE_SDIO_D5(_SDIO0, SDIO0_D5)
#error Invalid pin assignment for SDIO0 D5 pin: SDIO0_D5
#endif
#if !FIND_VALUE_SDIO_D6(_SDIO0, SDIO0_D6)
#error Invalid pin assignment for SDIO0 D6 pin: SDIO0_D6
#endif
#if !FIND_VALUE_SDIO_D7(_SDIO0, SDIO0_D7)
#error Invalid pin assignment for SDIO0 D7 pin: SDIO0_D7
#endif
#endif

