/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545897
 */

#define FIND_VALUE_ETH_RX_CLK_inner(INDEX,PIN) INDEX##_ETH_RX_##PIN
#define FIND_VALUE_ETH_RX_CLK(INDEX,PIN) FIND_VALUE_ETH_RX_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RX_DV_inner(INDEX,PIN) INDEX##_ETH_RX_##PIN
#define FIND_VALUE_ETH_RX_DV(INDEX,PIN) FIND_VALUE_ETH_RX_DV_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RX_ER_inner(INDEX,PIN) INDEX##_ETH_RX_##PIN
#define FIND_VALUE_ETH_RX_ER(INDEX,PIN) FIND_VALUE_ETH_RX_ER_inner(INDEX,PIN)

#ifdef USE_ETH_RX0
#if !FIND_VALUE_ETH_RX_CLK(_ETH_RX0, ETH_RX0_CLK)
#error Invalid pin assignment for ETH_RX0 CLK pin: ETH_RX0_CLK
#endif
#if !FIND_VALUE_ETH_RX_DV(_ETH_RX0, ETH_RX0_DV)
#error Invalid pin assignment for ETH_RX0 DV pin: ETH_RX0_DV
#endif
#if !FIND_VALUE_ETH_RX_ER(_ETH_RX0, ETH_RX0_ER)
#error Invalid pin assignment for ETH_RX0 ER pin: ETH_RX0_ER
#endif
#endif

