/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545798
 */

#define FIND_VALUE_ETH_CLK_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_CLK(INDEX,PIN) FIND_VALUE_ETH_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_CLK125_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_CLK125(INDEX,PIN) FIND_VALUE_ETH_CLK125_inner(INDEX,PIN)

#define FIND_VALUE_ETH_COL_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_COL(INDEX,PIN) FIND_VALUE_ETH_COL_inner(INDEX,PIN)

#define FIND_VALUE_ETH_CRS_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_CRS(INDEX,PIN) FIND_VALUE_ETH_CRS_inner(INDEX,PIN)

#define FIND_VALUE_ETH_CRS_DV_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_CRS_DV(INDEX,PIN) FIND_VALUE_ETH_CRS_DV_inner(INDEX,PIN)

#define FIND_VALUE_ETH_GTX_CLK_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_GTX_CLK(INDEX,PIN) FIND_VALUE_ETH_GTX_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_MDC_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_MDC(INDEX,PIN) FIND_VALUE_ETH_MDC_inner(INDEX,PIN)

#define FIND_VALUE_ETH_MDIO_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_MDIO(INDEX,PIN) FIND_VALUE_ETH_MDIO_inner(INDEX,PIN)

#define FIND_VALUE_ETH_PHY_INTN_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_PHY_INTN(INDEX,PIN) FIND_VALUE_ETH_PHY_INTN_inner(INDEX,PIN)

#define FIND_VALUE_ETH_PPS_OUT_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_PPS_OUT(INDEX,PIN) FIND_VALUE_ETH_PPS_OUT_inner(INDEX,PIN)

#define FIND_VALUE_ETH_REF_CLK_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_REF_CLK(INDEX,PIN) FIND_VALUE_ETH_REF_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD0_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD0(INDEX,PIN) FIND_VALUE_ETH_RXD0_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD1_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD1(INDEX,PIN) FIND_VALUE_ETH_RXD1_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD2_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD2(INDEX,PIN) FIND_VALUE_ETH_RXD2_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD3_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD3(INDEX,PIN) FIND_VALUE_ETH_RXD3_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD4_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD4(INDEX,PIN) FIND_VALUE_ETH_RXD4_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD5_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD5(INDEX,PIN) FIND_VALUE_ETH_RXD5_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD6_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD6(INDEX,PIN) FIND_VALUE_ETH_RXD6_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RXD7_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RXD7(INDEX,PIN) FIND_VALUE_ETH_RXD7_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RX_CLK_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RX_CLK(INDEX,PIN) FIND_VALUE_ETH_RX_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RX_CTL_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RX_CTL(INDEX,PIN) FIND_VALUE_ETH_RX_CTL_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RX_DV_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RX_DV(INDEX,PIN) FIND_VALUE_ETH_RX_DV_inner(INDEX,PIN)

#define FIND_VALUE_ETH_RX_ER_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_RX_ER(INDEX,PIN) FIND_VALUE_ETH_RX_ER_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD0_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD0(INDEX,PIN) FIND_VALUE_ETH_TXD0_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD1_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD1(INDEX,PIN) FIND_VALUE_ETH_TXD1_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD2_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD2(INDEX,PIN) FIND_VALUE_ETH_TXD2_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD3_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD3(INDEX,PIN) FIND_VALUE_ETH_TXD3_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD4_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD4(INDEX,PIN) FIND_VALUE_ETH_TXD4_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD5_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD5(INDEX,PIN) FIND_VALUE_ETH_TXD5_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD6_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD6(INDEX,PIN) FIND_VALUE_ETH_TXD6_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TXD7_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TXD7(INDEX,PIN) FIND_VALUE_ETH_TXD7_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TX_CLK_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TX_CLK(INDEX,PIN) FIND_VALUE_ETH_TX_CLK_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TX_CTL_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TX_CTL(INDEX,PIN) FIND_VALUE_ETH_TX_CTL_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TX_EN_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TX_EN(INDEX,PIN) FIND_VALUE_ETH_TX_EN_inner(INDEX,PIN)

#define FIND_VALUE_ETH_TX_ER_inner(INDEX,PIN) INDEX##_ETH_##PIN
#define FIND_VALUE_ETH_TX_ER(INDEX,PIN) FIND_VALUE_ETH_TX_ER_inner(INDEX,PIN)

#ifdef USE_ETH0
#if !FIND_VALUE_ETH_CLK(_ETH0, ETH0_CLK)
#error Invalid pin assignment for ETH0 CLK pin: ETH0_CLK
#endif
#if !FIND_VALUE_ETH_CLK125(_ETH0, ETH0_CLK125)
#error Invalid pin assignment for ETH0 CLK125 pin: ETH0_CLK125
#endif
#if !FIND_VALUE_ETH_COL(_ETH0, ETH0_COL)
#error Invalid pin assignment for ETH0 COL pin: ETH0_COL
#endif
#if !FIND_VALUE_ETH_CRS(_ETH0, ETH0_CRS)
#error Invalid pin assignment for ETH0 CRS pin: ETH0_CRS
#endif
#if !FIND_VALUE_ETH_CRS_DV(_ETH0, ETH0_CRS_DV)
#error Invalid pin assignment for ETH0 CRS_DV pin: ETH0_CRS_DV
#endif
#if !FIND_VALUE_ETH_GTX_CLK(_ETH0, ETH0_GTX_CLK)
#error Invalid pin assignment for ETH0 GTX_CLK pin: ETH0_GTX_CLK
#endif
#if !FIND_VALUE_ETH_MDC(_ETH0, ETH0_MDC)
#error Invalid pin assignment for ETH0 MDC pin: ETH0_MDC
#endif
#if !FIND_VALUE_ETH_MDIO(_ETH0, ETH0_MDIO)
#error Invalid pin assignment for ETH0 MDIO pin: ETH0_MDIO
#endif
#if !FIND_VALUE_ETH_PHY_INTN(_ETH0, ETH0_PHY_INTN)
#error Invalid pin assignment for ETH0 PHY_INTN pin: ETH0_PHY_INTN
#endif
#if !FIND_VALUE_ETH_PPS_OUT(_ETH0, ETH0_PPS_OUT)
#error Invalid pin assignment for ETH0 PPS_OUT pin: ETH0_PPS_OUT
#endif
#if !FIND_VALUE_ETH_REF_CLK(_ETH0, ETH0_REF_CLK)
#error Invalid pin assignment for ETH0 REF_CLK pin: ETH0_REF_CLK
#endif
#if !FIND_VALUE_ETH_RXD0(_ETH0, ETH0_RXD0)
#error Invalid pin assignment for ETH0 RXD0 pin: ETH0_RXD0
#endif
#if !FIND_VALUE_ETH_RXD1(_ETH0, ETH0_RXD1)
#error Invalid pin assignment for ETH0 RXD1 pin: ETH0_RXD1
#endif
#if !FIND_VALUE_ETH_RXD2(_ETH0, ETH0_RXD2)
#error Invalid pin assignment for ETH0 RXD2 pin: ETH0_RXD2
#endif
#if !FIND_VALUE_ETH_RXD3(_ETH0, ETH0_RXD3)
#error Invalid pin assignment for ETH0 RXD3 pin: ETH0_RXD3
#endif
#if !FIND_VALUE_ETH_RXD4(_ETH0, ETH0_RXD4)
#error Invalid pin assignment for ETH0 RXD4 pin: ETH0_RXD4
#endif
#if !FIND_VALUE_ETH_RXD5(_ETH0, ETH0_RXD5)
#error Invalid pin assignment for ETH0 RXD5 pin: ETH0_RXD5
#endif
#if !FIND_VALUE_ETH_RXD6(_ETH0, ETH0_RXD6)
#error Invalid pin assignment for ETH0 RXD6 pin: ETH0_RXD6
#endif
#if !FIND_VALUE_ETH_RXD7(_ETH0, ETH0_RXD7)
#error Invalid pin assignment for ETH0 RXD7 pin: ETH0_RXD7
#endif
#if !FIND_VALUE_ETH_RX_CLK(_ETH0, ETH0_RX_CLK)
#error Invalid pin assignment for ETH0 RX_CLK pin: ETH0_RX_CLK
#endif
#if !FIND_VALUE_ETH_RX_CTL(_ETH0, ETH0_RX_CTL)
#error Invalid pin assignment for ETH0 RX_CTL pin: ETH0_RX_CTL
#endif
#if !FIND_VALUE_ETH_RX_DV(_ETH0, ETH0_RX_DV)
#error Invalid pin assignment for ETH0 RX_DV pin: ETH0_RX_DV
#endif
#if !FIND_VALUE_ETH_RX_ER(_ETH0, ETH0_RX_ER)
#error Invalid pin assignment for ETH0 RX_ER pin: ETH0_RX_ER
#endif
#if !FIND_VALUE_ETH_TXD0(_ETH0, ETH0_TXD0)
#error Invalid pin assignment for ETH0 TXD0 pin: ETH0_TXD0
#endif
#if !FIND_VALUE_ETH_TXD1(_ETH0, ETH0_TXD1)
#error Invalid pin assignment for ETH0 TXD1 pin: ETH0_TXD1
#endif
#if !FIND_VALUE_ETH_TXD2(_ETH0, ETH0_TXD2)
#error Invalid pin assignment for ETH0 TXD2 pin: ETH0_TXD2
#endif
#if !FIND_VALUE_ETH_TXD3(_ETH0, ETH0_TXD3)
#error Invalid pin assignment for ETH0 TXD3 pin: ETH0_TXD3
#endif
#if !FIND_VALUE_ETH_TXD4(_ETH0, ETH0_TXD4)
#error Invalid pin assignment for ETH0 TXD4 pin: ETH0_TXD4
#endif
#if !FIND_VALUE_ETH_TXD5(_ETH0, ETH0_TXD5)
#error Invalid pin assignment for ETH0 TXD5 pin: ETH0_TXD5
#endif
#if !FIND_VALUE_ETH_TXD6(_ETH0, ETH0_TXD6)
#error Invalid pin assignment for ETH0 TXD6 pin: ETH0_TXD6
#endif
#if !FIND_VALUE_ETH_TXD7(_ETH0, ETH0_TXD7)
#error Invalid pin assignment for ETH0 TXD7 pin: ETH0_TXD7
#endif
#if !FIND_VALUE_ETH_TX_CLK(_ETH0, ETH0_TX_CLK)
#error Invalid pin assignment for ETH0 TX_CLK pin: ETH0_TX_CLK
#endif
#if !FIND_VALUE_ETH_TX_CTL(_ETH0, ETH0_TX_CTL)
#error Invalid pin assignment for ETH0 TX_CTL pin: ETH0_TX_CTL
#endif
#if !FIND_VALUE_ETH_TX_EN(_ETH0, ETH0_TX_EN)
#error Invalid pin assignment for ETH0 TX_EN pin: ETH0_TX_EN
#endif
#if !FIND_VALUE_ETH_TX_ER(_ETH0, ETH0_TX_ER)
#error Invalid pin assignment for ETH0 TX_ER pin: ETH0_TX_ER
#endif
#endif

#ifdef USE_ETH1
#if !FIND_VALUE_ETH_CLK(_ETH1, ETH1_CLK)
#error Invalid pin assignment for ETH1 CLK pin: ETH1_CLK
#endif
#if !FIND_VALUE_ETH_CLK125(_ETH1, ETH1_CLK125)
#error Invalid pin assignment for ETH1 CLK125 pin: ETH1_CLK125
#endif
#if !FIND_VALUE_ETH_COL(_ETH1, ETH1_COL)
#error Invalid pin assignment for ETH1 COL pin: ETH1_COL
#endif
#if !FIND_VALUE_ETH_CRS(_ETH1, ETH1_CRS)
#error Invalid pin assignment for ETH1 CRS pin: ETH1_CRS
#endif
#if !FIND_VALUE_ETH_CRS_DV(_ETH1, ETH1_CRS_DV)
#error Invalid pin assignment for ETH1 CRS_DV pin: ETH1_CRS_DV
#endif
#if !FIND_VALUE_ETH_GTX_CLK(_ETH1, ETH1_GTX_CLK)
#error Invalid pin assignment for ETH1 GTX_CLK pin: ETH1_GTX_CLK
#endif
#if !FIND_VALUE_ETH_MDC(_ETH1, ETH1_MDC)
#error Invalid pin assignment for ETH1 MDC pin: ETH1_MDC
#endif
#if !FIND_VALUE_ETH_MDIO(_ETH1, ETH1_MDIO)
#error Invalid pin assignment for ETH1 MDIO pin: ETH1_MDIO
#endif
#if !FIND_VALUE_ETH_PHY_INTN(_ETH1, ETH1_PHY_INTN)
#error Invalid pin assignment for ETH1 PHY_INTN pin: ETH1_PHY_INTN
#endif
#if !FIND_VALUE_ETH_PPS_OUT(_ETH1, ETH1_PPS_OUT)
#error Invalid pin assignment for ETH1 PPS_OUT pin: ETH1_PPS_OUT
#endif
#if !FIND_VALUE_ETH_REF_CLK(_ETH1, ETH1_REF_CLK)
#error Invalid pin assignment for ETH1 REF_CLK pin: ETH1_REF_CLK
#endif
#if !FIND_VALUE_ETH_RXD0(_ETH1, ETH1_RXD0)
#error Invalid pin assignment for ETH1 RXD0 pin: ETH1_RXD0
#endif
#if !FIND_VALUE_ETH_RXD1(_ETH1, ETH1_RXD1)
#error Invalid pin assignment for ETH1 RXD1 pin: ETH1_RXD1
#endif
#if !FIND_VALUE_ETH_RXD2(_ETH1, ETH1_RXD2)
#error Invalid pin assignment for ETH1 RXD2 pin: ETH1_RXD2
#endif
#if !FIND_VALUE_ETH_RXD3(_ETH1, ETH1_RXD3)
#error Invalid pin assignment for ETH1 RXD3 pin: ETH1_RXD3
#endif
#if !FIND_VALUE_ETH_RXD4(_ETH1, ETH1_RXD4)
#error Invalid pin assignment for ETH1 RXD4 pin: ETH1_RXD4
#endif
#if !FIND_VALUE_ETH_RXD5(_ETH1, ETH1_RXD5)
#error Invalid pin assignment for ETH1 RXD5 pin: ETH1_RXD5
#endif
#if !FIND_VALUE_ETH_RXD6(_ETH1, ETH1_RXD6)
#error Invalid pin assignment for ETH1 RXD6 pin: ETH1_RXD6
#endif
#if !FIND_VALUE_ETH_RXD7(_ETH1, ETH1_RXD7)
#error Invalid pin assignment for ETH1 RXD7 pin: ETH1_RXD7
#endif
#if !FIND_VALUE_ETH_RX_CLK(_ETH1, ETH1_RX_CLK)
#error Invalid pin assignment for ETH1 RX_CLK pin: ETH1_RX_CLK
#endif
#if !FIND_VALUE_ETH_RX_CTL(_ETH1, ETH1_RX_CTL)
#error Invalid pin assignment for ETH1 RX_CTL pin: ETH1_RX_CTL
#endif
#if !FIND_VALUE_ETH_RX_DV(_ETH1, ETH1_RX_DV)
#error Invalid pin assignment for ETH1 RX_DV pin: ETH1_RX_DV
#endif
#if !FIND_VALUE_ETH_RX_ER(_ETH1, ETH1_RX_ER)
#error Invalid pin assignment for ETH1 RX_ER pin: ETH1_RX_ER
#endif
#if !FIND_VALUE_ETH_TXD0(_ETH1, ETH1_TXD0)
#error Invalid pin assignment for ETH1 TXD0 pin: ETH1_TXD0
#endif
#if !FIND_VALUE_ETH_TXD1(_ETH1, ETH1_TXD1)
#error Invalid pin assignment for ETH1 TXD1 pin: ETH1_TXD1
#endif
#if !FIND_VALUE_ETH_TXD2(_ETH1, ETH1_TXD2)
#error Invalid pin assignment for ETH1 TXD2 pin: ETH1_TXD2
#endif
#if !FIND_VALUE_ETH_TXD3(_ETH1, ETH1_TXD3)
#error Invalid pin assignment for ETH1 TXD3 pin: ETH1_TXD3
#endif
#if !FIND_VALUE_ETH_TXD4(_ETH1, ETH1_TXD4)
#error Invalid pin assignment for ETH1 TXD4 pin: ETH1_TXD4
#endif
#if !FIND_VALUE_ETH_TXD5(_ETH1, ETH1_TXD5)
#error Invalid pin assignment for ETH1 TXD5 pin: ETH1_TXD5
#endif
#if !FIND_VALUE_ETH_TXD6(_ETH1, ETH1_TXD6)
#error Invalid pin assignment for ETH1 TXD6 pin: ETH1_TXD6
#endif
#if !FIND_VALUE_ETH_TXD7(_ETH1, ETH1_TXD7)
#error Invalid pin assignment for ETH1 TXD7 pin: ETH1_TXD7
#endif
#if !FIND_VALUE_ETH_TX_CLK(_ETH1, ETH1_TX_CLK)
#error Invalid pin assignment for ETH1 TX_CLK pin: ETH1_TX_CLK
#endif
#if !FIND_VALUE_ETH_TX_CTL(_ETH1, ETH1_TX_CTL)
#error Invalid pin assignment for ETH1 TX_CTL pin: ETH1_TX_CTL
#endif
#if !FIND_VALUE_ETH_TX_EN(_ETH1, ETH1_TX_EN)
#error Invalid pin assignment for ETH1 TX_EN pin: ETH1_TX_EN
#endif
#if !FIND_VALUE_ETH_TX_ER(_ETH1, ETH1_TX_ER)
#error Invalid pin assignment for ETH1 TX_ER pin: ETH1_TX_ER
#endif
#endif

