/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546301
 */

#define FIND_VALUE_I2C_SCL_inner(INDEX,PIN) INDEX##_I2C_##PIN
#define FIND_VALUE_I2C_SCL(INDEX,PIN) FIND_VALUE_I2C_SCL_inner(INDEX,PIN)

#define FIND_VALUE_I2C_SDA_inner(INDEX,PIN) INDEX##_I2C_##PIN
#define FIND_VALUE_I2C_SDA(INDEX,PIN) FIND_VALUE_I2C_SDA_inner(INDEX,PIN)

#define FIND_VALUE_I2C_SMBA_inner(INDEX,PIN) INDEX##_I2C_##PIN
#define FIND_VALUE_I2C_SMBA(INDEX,PIN) FIND_VALUE_I2C_SMBA_inner(INDEX,PIN)

#ifdef USE_I2C0
#if !FIND_VALUE_I2C_SCL(_I2C0, I2C0_SCL)
#error Invalid pin assignment for I2C0 SCL pin: I2C0_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C0, I2C0_SDA)
#error Invalid pin assignment for I2C0 SDA pin: I2C0_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C0, I2C0_SMBA)
#error Invalid pin assignment for I2C0 SMBA pin: I2C0_SMBA
#endif
#endif

#ifdef USE_I2C1
#if !FIND_VALUE_I2C_SCL(_I2C1, I2C1_SCL)
#error Invalid pin assignment for I2C1 SCL pin: I2C1_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C1, I2C1_SDA)
#error Invalid pin assignment for I2C1 SDA pin: I2C1_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C1, I2C1_SMBA)
#error Invalid pin assignment for I2C1 SMBA pin: I2C1_SMBA
#endif
#endif

#ifdef USE_I2C2
#if !FIND_VALUE_I2C_SCL(_I2C2, I2C2_SCL)
#error Invalid pin assignment for I2C2 SCL pin: I2C2_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C2, I2C2_SDA)
#error Invalid pin assignment for I2C2 SDA pin: I2C2_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C2, I2C2_SMBA)
#error Invalid pin assignment for I2C2 SMBA pin: I2C2_SMBA
#endif
#endif

#ifdef USE_I2C3
#if !FIND_VALUE_I2C_SCL(_I2C3, I2C3_SCL)
#error Invalid pin assignment for I2C3 SCL pin: I2C3_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C3, I2C3_SDA)
#error Invalid pin assignment for I2C3 SDA pin: I2C3_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C3, I2C3_SMBA)
#error Invalid pin assignment for I2C3 SMBA pin: I2C3_SMBA
#endif
#endif

#ifdef USE_I2C4
#if !FIND_VALUE_I2C_SCL(_I2C4, I2C4_SCL)
#error Invalid pin assignment for I2C4 SCL pin: I2C4_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C4, I2C4_SDA)
#error Invalid pin assignment for I2C4 SDA pin: I2C4_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C4, I2C4_SMBA)
#error Invalid pin assignment for I2C4 SMBA pin: I2C4_SMBA
#endif
#endif

#ifdef USE_I2C5
#if !FIND_VALUE_I2C_SCL(_I2C5, I2C5_SCL)
#error Invalid pin assignment for I2C5 SCL pin: I2C5_SCL
#endif
#if !FIND_VALUE_I2C_SDA(_I2C5, I2C5_SDA)
#error Invalid pin assignment for I2C5 SDA pin: I2C5_SDA
#endif
#if !FIND_VALUE_I2C_SMBA(_I2C5, I2C5_SMBA)
#error Invalid pin assignment for I2C5 SMBA pin: I2C5_SMBA
#endif
#endif

