/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545453
 */

#define FIND_VALUE_ADF_CCK0_inner(INDEX,PIN) INDEX##_ADF_##PIN
#define FIND_VALUE_ADF_CCK0(INDEX,PIN) FIND_VALUE_ADF_CCK0_inner(INDEX,PIN)

#define FIND_VALUE_ADF_CCK1_inner(INDEX,PIN) INDEX##_ADF_##PIN
#define FIND_VALUE_ADF_CCK1(INDEX,PIN) FIND_VALUE_ADF_CCK1_inner(INDEX,PIN)

#define FIND_VALUE_ADF_SDI0_inner(INDEX,PIN) INDEX##_ADF_##PIN
#define FIND_VALUE_ADF_SDI0(INDEX,PIN) FIND_VALUE_ADF_SDI0_inner(INDEX,PIN)

#ifdef USE_ADF0
#if !FIND_VALUE_ADF_CCK0(_ADF0, ADF0_CCK0)
#error Invalid pin assignment for ADF0 CCK0 pin: ADF0_CCK0
#endif
#if !FIND_VALUE_ADF_CCK1(_ADF0, ADF0_CCK1)
#error Invalid pin assignment for ADF0 CCK1 pin: ADF0_CCK1
#endif
#if !FIND_VALUE_ADF_SDI0(_ADF0, ADF0_SDI0)
#error Invalid pin assignment for ADF0 SDI0 pin: ADF0_SDI0
#endif
#endif

