/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546366
 */

#define FIND_VALUE_I2S2ext_CK_inner(INDEX,PIN) INDEX##_I2S2ext_##PIN
#define FIND_VALUE_I2S2ext_CK(INDEX,PIN) FIND_VALUE_I2S2ext_CK_inner(INDEX,PIN)

#define FIND_VALUE_I2S2ext_MISO_inner(INDEX,PIN) INDEX##_I2S2ext_##PIN
#define FIND_VALUE_I2S2ext_MISO(INDEX,PIN) FIND_VALUE_I2S2ext_MISO_inner(INDEX,PIN)

#define FIND_VALUE_I2S2ext_WS_inner(INDEX,PIN) INDEX##_I2S2ext_##PIN
#define FIND_VALUE_I2S2ext_WS(INDEX,PIN) FIND_VALUE_I2S2ext_WS_inner(INDEX,PIN)

#ifdef USE_I2S2ext0
#if !FIND_VALUE_I2S2ext_CK(_I2S2ext0, I2S2ext0_CK)
#error Invalid pin assignment for I2S2ext0 CK pin: I2S2ext0_CK
#endif
#if !FIND_VALUE_I2S2ext_MISO(_I2S2ext0, I2S2ext0_MISO)
#error Invalid pin assignment for I2S2ext0 MISO pin: I2S2ext0_MISO
#endif
#if !FIND_VALUE_I2S2ext_WS(_I2S2ext0, I2S2ext0_WS)
#error Invalid pin assignment for I2S2ext0 WS pin: I2S2ext0_WS
#endif
#endif

