/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547402
 */

#define FIND_VALUE_TIMX_IC1_inner(INDEX,PIN) INDEX##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC1(INDEX,PIN) FIND_VALUE_TIMX_IC1_inner(INDEX,PIN)

#define FIND_VALUE_TIMX_IC2_inner(INDEX,PIN) INDEX##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC2(INDEX,PIN) FIND_VALUE_TIMX_IC2_inner(INDEX,PIN)

#define FIND_VALUE_TIMX_IC3_inner(INDEX,PIN) INDEX##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC3(INDEX,PIN) FIND_VALUE_TIMX_IC3_inner(INDEX,PIN)

#define FIND_VALUE_TIMX_IC4_inner(INDEX,PIN) INDEX##_TIMX_##PIN
#define FIND_VALUE_TIMX_IC4(INDEX,PIN) FIND_VALUE_TIMX_IC4_inner(INDEX,PIN)

#ifdef USE_TIMX0
#if !FIND_VALUE_TIMX_IC1(_TIMX0, TIMX0_IC1)
#error Invalid pin assignment for TIMX0 IC1 pin: TIMX0_IC1
#endif
#if !FIND_VALUE_TIMX_IC2(_TIMX0, TIMX0_IC2)
#error Invalid pin assignment for TIMX0 IC2 pin: TIMX0_IC2
#endif
#if !FIND_VALUE_TIMX_IC3(_TIMX0, TIMX0_IC3)
#error Invalid pin assignment for TIMX0 IC3 pin: TIMX0_IC3
#endif
#if !FIND_VALUE_TIMX_IC4(_TIMX0, TIMX0_IC4)
#error Invalid pin assignment for TIMX0 IC4 pin: TIMX0_IC4
#endif
#endif

