/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546855
 */

#define FIND_VALUE_RTC_AF1_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_AF1(INDEX,PIN) FIND_VALUE_RTC_AF1_inner(INDEX,PIN)

#define FIND_VALUE_RTC_AF2_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_AF2(INDEX,PIN) FIND_VALUE_RTC_AF2_inner(INDEX,PIN)

#define FIND_VALUE_RTC_OUT_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_OUT(INDEX,PIN) FIND_VALUE_RTC_OUT_inner(INDEX,PIN)

#define FIND_VALUE_RTC_OUT2_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_OUT2(INDEX,PIN) FIND_VALUE_RTC_OUT2_inner(INDEX,PIN)

#define FIND_VALUE_RTC_REFIN_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_REFIN(INDEX,PIN) FIND_VALUE_RTC_REFIN_inner(INDEX,PIN)

#define FIND_VALUE_RTC_TAMP1_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_TAMP1(INDEX,PIN) FIND_VALUE_RTC_TAMP1_inner(INDEX,PIN)

#define FIND_VALUE_RTC_TAMP2_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_TAMP2(INDEX,PIN) FIND_VALUE_RTC_TAMP2_inner(INDEX,PIN)

#define FIND_VALUE_RTC_TAMP3_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_TAMP3(INDEX,PIN) FIND_VALUE_RTC_TAMP3_inner(INDEX,PIN)

#define FIND_VALUE_RTC_TS_inner(INDEX,PIN) INDEX##_RTC_##PIN
#define FIND_VALUE_RTC_TS(INDEX,PIN) FIND_VALUE_RTC_TS_inner(INDEX,PIN)

#ifdef USE_RTC0
#if !FIND_VALUE_RTC_AF1(_RTC0, RTC0_AF1)
#error Invalid pin assignment for RTC0 AF1 pin: RTC0_AF1
#endif
#if !FIND_VALUE_RTC_AF2(_RTC0, RTC0_AF2)
#error Invalid pin assignment for RTC0 AF2 pin: RTC0_AF2
#endif
#if !FIND_VALUE_RTC_OUT(_RTC0, RTC0_OUT)
#error Invalid pin assignment for RTC0 OUT pin: RTC0_OUT
#endif
#if !FIND_VALUE_RTC_OUT2(_RTC0, RTC0_OUT2)
#error Invalid pin assignment for RTC0 OUT2 pin: RTC0_OUT2
#endif
#if !FIND_VALUE_RTC_REFIN(_RTC0, RTC0_REFIN)
#error Invalid pin assignment for RTC0 REFIN pin: RTC0_REFIN
#endif
#if !FIND_VALUE_RTC_TAMP1(_RTC0, RTC0_TAMP1)
#error Invalid pin assignment for RTC0 TAMP1 pin: RTC0_TAMP1
#endif
#if !FIND_VALUE_RTC_TAMP2(_RTC0, RTC0_TAMP2)
#error Invalid pin assignment for RTC0 TAMP2 pin: RTC0_TAMP2
#endif
#if !FIND_VALUE_RTC_TAMP3(_RTC0, RTC0_TAMP3)
#error Invalid pin assignment for RTC0 TAMP3 pin: RTC0_TAMP3
#endif
#if !FIND_VALUE_RTC_TS(_RTC0, RTC0_TS)
#error Invalid pin assignment for RTC0 TS pin: RTC0_TS
#endif
#endif

