/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545933
 */

#define FIND_VALUE_EXT_PA_TX_inner(INDEX,PIN) INDEX##_EXT_PA_##PIN
#define FIND_VALUE_EXT_PA_TX(INDEX,PIN) FIND_VALUE_EXT_PA_TX_inner(INDEX,PIN)

#ifdef USE_EXT_PA0
#if !FIND_VALUE_EXT_PA_TX(_EXT_PA0, EXT_PA0_TX)
#error Invalid pin assignment for EXT_PA0 TX pin: EXT_PA0_TX
#endif
#endif

