/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546202
 */

#define FIND_VALUE_HDMI_CEC_CEC_inner(INDEX,PIN) INDEX##_HDMI_CEC_##PIN
#define FIND_VALUE_HDMI_CEC_CEC(INDEX,PIN) FIND_VALUE_HDMI_CEC_CEC_inner(INDEX,PIN)

#ifdef USE_HDMI_CEC0
#if !FIND_VALUE_HDMI_CEC_CEC(_HDMI_CEC0, HDMI_CEC0_CEC)
#error Invalid pin assignment for HDMI_CEC0 CEC pin: HDMI_CEC0_CEC
#endif
#endif

