/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546573
 */

#define FIND_VALUE_MDIOS_MDC_inner(INDEX,PIN) INDEX##_MDIOS_##PIN
#define FIND_VALUE_MDIOS_MDC(INDEX,PIN) FIND_VALUE_MDIOS_MDC_inner(INDEX,PIN)

#define FIND_VALUE_MDIOS_MDIO_inner(INDEX,PIN) INDEX##_MDIOS_##PIN
#define FIND_VALUE_MDIOS_MDIO(INDEX,PIN) FIND_VALUE_MDIOS_MDIO_inner(INDEX,PIN)

#ifdef USE_MDIOS0
#if !FIND_VALUE_MDIOS_MDC(_MDIOS0, MDIOS0_MDC)
#error Invalid pin assignment for MDIOS0 MDC pin: MDIOS0_MDC
#endif
#if !FIND_VALUE_MDIOS_MDIO(_MDIOS0, MDIOS0_MDIO)
#error Invalid pin assignment for MDIOS0 MDIO pin: MDIOS0_MDIO
#endif
#endif

