/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547750
 */

#define FIND_VALUE_V_REF_PVD_IN_inner(INDEX,PIN) INDEX##_V_REF_PVD_##PIN
#define FIND_VALUE_V_REF_PVD_IN(INDEX,PIN) FIND_VALUE_V_REF_PVD_IN_inner(INDEX,PIN)

#ifdef USE_V_REF_PVD0
#if !FIND_VALUE_V_REF_PVD_IN(_V_REF_PVD0, V_REF_PVD0_IN)
#error Invalid pin assignment for V_REF_PVD0 IN pin: V_REF_PVD0_IN
#endif
#endif

