/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545515
 */

#define FIND_VALUE_CM_EVENTOUT_inner(INDEX,PIN) INDEX##_CM_##PIN
#define FIND_VALUE_CM_EVENTOUT(INDEX,PIN) FIND_VALUE_CM_EVENTOUT_inner(INDEX,PIN)

#ifdef USE_CM0
#if !FIND_VALUE_CM_EVENTOUT(_CM0, CM0_EVENTOUT)
#error Invalid pin assignment for CM0 EVENTOUT pin: CM0_EVENTOUT
#endif
#endif

#ifdef USE_CM1
#if !FIND_VALUE_CM_EVENTOUT(_CM1, CM1_EVENTOUT)
#error Invalid pin assignment for CM1 EVENTOUT pin: CM1_EVENTOUT
#endif
#endif

#ifdef USE_CM2
#if !FIND_VALUE_CM_EVENTOUT(_CM2, CM2_EVENTOUT)
#error Invalid pin assignment for CM2 EVENTOUT pin: CM2_EVENTOUT
#endif
#endif

#ifdef USE_CM3
#if !FIND_VALUE_CM_EVENTOUT(_CM3, CM3_EVENTOUT)
#error Invalid pin assignment for CM3 EVENTOUT pin: CM3_EVENTOUT
#endif
#endif

