/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547185
 */

#define FIND_VALUE_TIM_BK_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BK(INDEX,PIN) FIND_VALUE_TIM_BK_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BK2_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BK2(INDEX,PIN) FIND_VALUE_TIM_BK2_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BKIN_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BKIN(INDEX,PIN) FIND_VALUE_TIM_BKIN_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BKIN2_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BKIN2(INDEX,PIN) FIND_VALUE_TIM_BKIN2_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BKIN2_COMP1_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BKIN2_COMP1(INDEX,PIN) FIND_VALUE_TIM_BKIN2_COMP1_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BKIN2_COMP2_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BKIN2_COMP2(INDEX,PIN) FIND_VALUE_TIM_BKIN2_COMP2_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BKIN_COMP1_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BKIN_COMP1(INDEX,PIN) FIND_VALUE_TIM_BKIN_COMP1_inner(INDEX,PIN)

#define FIND_VALUE_TIM_BKIN_COMP2_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_BKIN_COMP2(INDEX,PIN) FIND_VALUE_TIM_BKIN_COMP2_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH1_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH1(INDEX,PIN) FIND_VALUE_TIM_CH1_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH1N_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH1N(INDEX,PIN) FIND_VALUE_TIM_CH1N_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH2_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH2(INDEX,PIN) FIND_VALUE_TIM_CH2_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH2N_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH2N(INDEX,PIN) FIND_VALUE_TIM_CH2N_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH3_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH3(INDEX,PIN) FIND_VALUE_TIM_CH3_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH3N_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH3N(INDEX,PIN) FIND_VALUE_TIM_CH3N_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH4_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH4(INDEX,PIN) FIND_VALUE_TIM_CH4_inner(INDEX,PIN)

#define FIND_VALUE_TIM_CH4N_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_CH4N(INDEX,PIN) FIND_VALUE_TIM_CH4N_inner(INDEX,PIN)

#define FIND_VALUE_TIM_ETR_inner(INDEX,PIN) INDEX##_TIM_##PIN
#define FIND_VALUE_TIM_ETR(INDEX,PIN) FIND_VALUE_TIM_ETR_inner(INDEX,PIN)

#ifdef USE_TIM0
#if !FIND_VALUE_TIM_BK(_TIM0, TIM0_BK)
#error Invalid pin assignment for TIM0 BK pin: TIM0_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM0, TIM0_BK2)
#error Invalid pin assignment for TIM0 BK2 pin: TIM0_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM0, TIM0_BKIN)
#error Invalid pin assignment for TIM0 BKIN pin: TIM0_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM0, TIM0_BKIN2)
#error Invalid pin assignment for TIM0 BKIN2 pin: TIM0_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM0, TIM0_BKIN2_COMP1)
#error Invalid pin assignment for TIM0 BKIN2_COMP1 pin: TIM0_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM0, TIM0_BKIN2_COMP2)
#error Invalid pin assignment for TIM0 BKIN2_COMP2 pin: TIM0_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM0, TIM0_BKIN_COMP1)
#error Invalid pin assignment for TIM0 BKIN_COMP1 pin: TIM0_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM0, TIM0_BKIN_COMP2)
#error Invalid pin assignment for TIM0 BKIN_COMP2 pin: TIM0_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM0, TIM0_CH1)
#error Invalid pin assignment for TIM0 CH1 pin: TIM0_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM0, TIM0_CH1N)
#error Invalid pin assignment for TIM0 CH1N pin: TIM0_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM0, TIM0_CH2)
#error Invalid pin assignment for TIM0 CH2 pin: TIM0_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM0, TIM0_CH2N)
#error Invalid pin assignment for TIM0 CH2N pin: TIM0_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM0, TIM0_CH3)
#error Invalid pin assignment for TIM0 CH3 pin: TIM0_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM0, TIM0_CH3N)
#error Invalid pin assignment for TIM0 CH3N pin: TIM0_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM0, TIM0_CH4)
#error Invalid pin assignment for TIM0 CH4 pin: TIM0_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM0, TIM0_CH4N)
#error Invalid pin assignment for TIM0 CH4N pin: TIM0_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM0, TIM0_ETR)
#error Invalid pin assignment for TIM0 ETR pin: TIM0_ETR
#endif
#endif

#ifdef USE_TIM1
#if !FIND_VALUE_TIM_BK(_TIM1, TIM1_BK)
#error Invalid pin assignment for TIM1 BK pin: TIM1_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM1, TIM1_BK2)
#error Invalid pin assignment for TIM1 BK2 pin: TIM1_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM1, TIM1_BKIN)
#error Invalid pin assignment for TIM1 BKIN pin: TIM1_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM1, TIM1_BKIN2)
#error Invalid pin assignment for TIM1 BKIN2 pin: TIM1_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM1, TIM1_BKIN2_COMP1)
#error Invalid pin assignment for TIM1 BKIN2_COMP1 pin: TIM1_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM1, TIM1_BKIN2_COMP2)
#error Invalid pin assignment for TIM1 BKIN2_COMP2 pin: TIM1_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM1, TIM1_BKIN_COMP1)
#error Invalid pin assignment for TIM1 BKIN_COMP1 pin: TIM1_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM1, TIM1_BKIN_COMP2)
#error Invalid pin assignment for TIM1 BKIN_COMP2 pin: TIM1_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM1, TIM1_CH1)
#error Invalid pin assignment for TIM1 CH1 pin: TIM1_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM1, TIM1_CH1N)
#error Invalid pin assignment for TIM1 CH1N pin: TIM1_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM1, TIM1_CH2)
#error Invalid pin assignment for TIM1 CH2 pin: TIM1_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM1, TIM1_CH2N)
#error Invalid pin assignment for TIM1 CH2N pin: TIM1_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM1, TIM1_CH3)
#error Invalid pin assignment for TIM1 CH3 pin: TIM1_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM1, TIM1_CH3N)
#error Invalid pin assignment for TIM1 CH3N pin: TIM1_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM1, TIM1_CH4)
#error Invalid pin assignment for TIM1 CH4 pin: TIM1_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM1, TIM1_CH4N)
#error Invalid pin assignment for TIM1 CH4N pin: TIM1_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM1, TIM1_ETR)
#error Invalid pin assignment for TIM1 ETR pin: TIM1_ETR
#endif
#endif

#ifdef USE_TIM2
#if !FIND_VALUE_TIM_BK(_TIM2, TIM2_BK)
#error Invalid pin assignment for TIM2 BK pin: TIM2_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM2, TIM2_BK2)
#error Invalid pin assignment for TIM2 BK2 pin: TIM2_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM2, TIM2_BKIN)
#error Invalid pin assignment for TIM2 BKIN pin: TIM2_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM2, TIM2_BKIN2)
#error Invalid pin assignment for TIM2 BKIN2 pin: TIM2_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM2, TIM2_BKIN2_COMP1)
#error Invalid pin assignment for TIM2 BKIN2_COMP1 pin: TIM2_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM2, TIM2_BKIN2_COMP2)
#error Invalid pin assignment for TIM2 BKIN2_COMP2 pin: TIM2_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM2, TIM2_BKIN_COMP1)
#error Invalid pin assignment for TIM2 BKIN_COMP1 pin: TIM2_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM2, TIM2_BKIN_COMP2)
#error Invalid pin assignment for TIM2 BKIN_COMP2 pin: TIM2_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM2, TIM2_CH1)
#error Invalid pin assignment for TIM2 CH1 pin: TIM2_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM2, TIM2_CH1N)
#error Invalid pin assignment for TIM2 CH1N pin: TIM2_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM2, TIM2_CH2)
#error Invalid pin assignment for TIM2 CH2 pin: TIM2_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM2, TIM2_CH2N)
#error Invalid pin assignment for TIM2 CH2N pin: TIM2_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM2, TIM2_CH3)
#error Invalid pin assignment for TIM2 CH3 pin: TIM2_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM2, TIM2_CH3N)
#error Invalid pin assignment for TIM2 CH3N pin: TIM2_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM2, TIM2_CH4)
#error Invalid pin assignment for TIM2 CH4 pin: TIM2_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM2, TIM2_CH4N)
#error Invalid pin assignment for TIM2 CH4N pin: TIM2_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM2, TIM2_ETR)
#error Invalid pin assignment for TIM2 ETR pin: TIM2_ETR
#endif
#endif

#ifdef USE_TIM3
#if !FIND_VALUE_TIM_BK(_TIM3, TIM3_BK)
#error Invalid pin assignment for TIM3 BK pin: TIM3_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM3, TIM3_BK2)
#error Invalid pin assignment for TIM3 BK2 pin: TIM3_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM3, TIM3_BKIN)
#error Invalid pin assignment for TIM3 BKIN pin: TIM3_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM3, TIM3_BKIN2)
#error Invalid pin assignment for TIM3 BKIN2 pin: TIM3_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM3, TIM3_BKIN2_COMP1)
#error Invalid pin assignment for TIM3 BKIN2_COMP1 pin: TIM3_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM3, TIM3_BKIN2_COMP2)
#error Invalid pin assignment for TIM3 BKIN2_COMP2 pin: TIM3_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM3, TIM3_BKIN_COMP1)
#error Invalid pin assignment for TIM3 BKIN_COMP1 pin: TIM3_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM3, TIM3_BKIN_COMP2)
#error Invalid pin assignment for TIM3 BKIN_COMP2 pin: TIM3_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM3, TIM3_CH1)
#error Invalid pin assignment for TIM3 CH1 pin: TIM3_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM3, TIM3_CH1N)
#error Invalid pin assignment for TIM3 CH1N pin: TIM3_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM3, TIM3_CH2)
#error Invalid pin assignment for TIM3 CH2 pin: TIM3_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM3, TIM3_CH2N)
#error Invalid pin assignment for TIM3 CH2N pin: TIM3_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM3, TIM3_CH3)
#error Invalid pin assignment for TIM3 CH3 pin: TIM3_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM3, TIM3_CH3N)
#error Invalid pin assignment for TIM3 CH3N pin: TIM3_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM3, TIM3_CH4)
#error Invalid pin assignment for TIM3 CH4 pin: TIM3_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM3, TIM3_CH4N)
#error Invalid pin assignment for TIM3 CH4N pin: TIM3_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM3, TIM3_ETR)
#error Invalid pin assignment for TIM3 ETR pin: TIM3_ETR
#endif
#endif

#ifdef USE_TIM4
#if !FIND_VALUE_TIM_BK(_TIM4, TIM4_BK)
#error Invalid pin assignment for TIM4 BK pin: TIM4_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM4, TIM4_BK2)
#error Invalid pin assignment for TIM4 BK2 pin: TIM4_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM4, TIM4_BKIN)
#error Invalid pin assignment for TIM4 BKIN pin: TIM4_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM4, TIM4_BKIN2)
#error Invalid pin assignment for TIM4 BKIN2 pin: TIM4_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM4, TIM4_BKIN2_COMP1)
#error Invalid pin assignment for TIM4 BKIN2_COMP1 pin: TIM4_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM4, TIM4_BKIN2_COMP2)
#error Invalid pin assignment for TIM4 BKIN2_COMP2 pin: TIM4_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM4, TIM4_BKIN_COMP1)
#error Invalid pin assignment for TIM4 BKIN_COMP1 pin: TIM4_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM4, TIM4_BKIN_COMP2)
#error Invalid pin assignment for TIM4 BKIN_COMP2 pin: TIM4_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM4, TIM4_CH1)
#error Invalid pin assignment for TIM4 CH1 pin: TIM4_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM4, TIM4_CH1N)
#error Invalid pin assignment for TIM4 CH1N pin: TIM4_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM4, TIM4_CH2)
#error Invalid pin assignment for TIM4 CH2 pin: TIM4_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM4, TIM4_CH2N)
#error Invalid pin assignment for TIM4 CH2N pin: TIM4_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM4, TIM4_CH3)
#error Invalid pin assignment for TIM4 CH3 pin: TIM4_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM4, TIM4_CH3N)
#error Invalid pin assignment for TIM4 CH3N pin: TIM4_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM4, TIM4_CH4)
#error Invalid pin assignment for TIM4 CH4 pin: TIM4_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM4, TIM4_CH4N)
#error Invalid pin assignment for TIM4 CH4N pin: TIM4_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM4, TIM4_ETR)
#error Invalid pin assignment for TIM4 ETR pin: TIM4_ETR
#endif
#endif

#ifdef USE_TIM5
#if !FIND_VALUE_TIM_BK(_TIM5, TIM5_BK)
#error Invalid pin assignment for TIM5 BK pin: TIM5_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM5, TIM5_BK2)
#error Invalid pin assignment for TIM5 BK2 pin: TIM5_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM5, TIM5_BKIN)
#error Invalid pin assignment for TIM5 BKIN pin: TIM5_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM5, TIM5_BKIN2)
#error Invalid pin assignment for TIM5 BKIN2 pin: TIM5_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM5, TIM5_BKIN2_COMP1)
#error Invalid pin assignment for TIM5 BKIN2_COMP1 pin: TIM5_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM5, TIM5_BKIN2_COMP2)
#error Invalid pin assignment for TIM5 BKIN2_COMP2 pin: TIM5_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM5, TIM5_BKIN_COMP1)
#error Invalid pin assignment for TIM5 BKIN_COMP1 pin: TIM5_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM5, TIM5_BKIN_COMP2)
#error Invalid pin assignment for TIM5 BKIN_COMP2 pin: TIM5_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM5, TIM5_CH1)
#error Invalid pin assignment for TIM5 CH1 pin: TIM5_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM5, TIM5_CH1N)
#error Invalid pin assignment for TIM5 CH1N pin: TIM5_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM5, TIM5_CH2)
#error Invalid pin assignment for TIM5 CH2 pin: TIM5_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM5, TIM5_CH2N)
#error Invalid pin assignment for TIM5 CH2N pin: TIM5_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM5, TIM5_CH3)
#error Invalid pin assignment for TIM5 CH3 pin: TIM5_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM5, TIM5_CH3N)
#error Invalid pin assignment for TIM5 CH3N pin: TIM5_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM5, TIM5_CH4)
#error Invalid pin assignment for TIM5 CH4 pin: TIM5_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM5, TIM5_CH4N)
#error Invalid pin assignment for TIM5 CH4N pin: TIM5_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM5, TIM5_ETR)
#error Invalid pin assignment for TIM5 ETR pin: TIM5_ETR
#endif
#endif

#ifdef USE_TIM6
#if !FIND_VALUE_TIM_BK(_TIM6, TIM6_BK)
#error Invalid pin assignment for TIM6 BK pin: TIM6_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM6, TIM6_BK2)
#error Invalid pin assignment for TIM6 BK2 pin: TIM6_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM6, TIM6_BKIN)
#error Invalid pin assignment for TIM6 BKIN pin: TIM6_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM6, TIM6_BKIN2)
#error Invalid pin assignment for TIM6 BKIN2 pin: TIM6_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM6, TIM6_BKIN2_COMP1)
#error Invalid pin assignment for TIM6 BKIN2_COMP1 pin: TIM6_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM6, TIM6_BKIN2_COMP2)
#error Invalid pin assignment for TIM6 BKIN2_COMP2 pin: TIM6_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM6, TIM6_BKIN_COMP1)
#error Invalid pin assignment for TIM6 BKIN_COMP1 pin: TIM6_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM6, TIM6_BKIN_COMP2)
#error Invalid pin assignment for TIM6 BKIN_COMP2 pin: TIM6_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM6, TIM6_CH1)
#error Invalid pin assignment for TIM6 CH1 pin: TIM6_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM6, TIM6_CH1N)
#error Invalid pin assignment for TIM6 CH1N pin: TIM6_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM6, TIM6_CH2)
#error Invalid pin assignment for TIM6 CH2 pin: TIM6_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM6, TIM6_CH2N)
#error Invalid pin assignment for TIM6 CH2N pin: TIM6_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM6, TIM6_CH3)
#error Invalid pin assignment for TIM6 CH3 pin: TIM6_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM6, TIM6_CH3N)
#error Invalid pin assignment for TIM6 CH3N pin: TIM6_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM6, TIM6_CH4)
#error Invalid pin assignment for TIM6 CH4 pin: TIM6_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM6, TIM6_CH4N)
#error Invalid pin assignment for TIM6 CH4N pin: TIM6_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM6, TIM6_ETR)
#error Invalid pin assignment for TIM6 ETR pin: TIM6_ETR
#endif
#endif

#ifdef USE_TIM7
#if !FIND_VALUE_TIM_BK(_TIM7, TIM7_BK)
#error Invalid pin assignment for TIM7 BK pin: TIM7_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM7, TIM7_BK2)
#error Invalid pin assignment for TIM7 BK2 pin: TIM7_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM7, TIM7_BKIN)
#error Invalid pin assignment for TIM7 BKIN pin: TIM7_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM7, TIM7_BKIN2)
#error Invalid pin assignment for TIM7 BKIN2 pin: TIM7_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM7, TIM7_BKIN2_COMP1)
#error Invalid pin assignment for TIM7 BKIN2_COMP1 pin: TIM7_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM7, TIM7_BKIN2_COMP2)
#error Invalid pin assignment for TIM7 BKIN2_COMP2 pin: TIM7_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM7, TIM7_BKIN_COMP1)
#error Invalid pin assignment for TIM7 BKIN_COMP1 pin: TIM7_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM7, TIM7_BKIN_COMP2)
#error Invalid pin assignment for TIM7 BKIN_COMP2 pin: TIM7_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM7, TIM7_CH1)
#error Invalid pin assignment for TIM7 CH1 pin: TIM7_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM7, TIM7_CH1N)
#error Invalid pin assignment for TIM7 CH1N pin: TIM7_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM7, TIM7_CH2)
#error Invalid pin assignment for TIM7 CH2 pin: TIM7_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM7, TIM7_CH2N)
#error Invalid pin assignment for TIM7 CH2N pin: TIM7_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM7, TIM7_CH3)
#error Invalid pin assignment for TIM7 CH3 pin: TIM7_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM7, TIM7_CH3N)
#error Invalid pin assignment for TIM7 CH3N pin: TIM7_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM7, TIM7_CH4)
#error Invalid pin assignment for TIM7 CH4 pin: TIM7_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM7, TIM7_CH4N)
#error Invalid pin assignment for TIM7 CH4N pin: TIM7_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM7, TIM7_ETR)
#error Invalid pin assignment for TIM7 ETR pin: TIM7_ETR
#endif
#endif

#ifdef USE_TIM8
#if !FIND_VALUE_TIM_BK(_TIM8, TIM8_BK)
#error Invalid pin assignment for TIM8 BK pin: TIM8_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM8, TIM8_BK2)
#error Invalid pin assignment for TIM8 BK2 pin: TIM8_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM8, TIM8_BKIN)
#error Invalid pin assignment for TIM8 BKIN pin: TIM8_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM8, TIM8_BKIN2)
#error Invalid pin assignment for TIM8 BKIN2 pin: TIM8_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM8, TIM8_BKIN2_COMP1)
#error Invalid pin assignment for TIM8 BKIN2_COMP1 pin: TIM8_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM8, TIM8_BKIN2_COMP2)
#error Invalid pin assignment for TIM8 BKIN2_COMP2 pin: TIM8_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM8, TIM8_BKIN_COMP1)
#error Invalid pin assignment for TIM8 BKIN_COMP1 pin: TIM8_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM8, TIM8_BKIN_COMP2)
#error Invalid pin assignment for TIM8 BKIN_COMP2 pin: TIM8_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM8, TIM8_CH1)
#error Invalid pin assignment for TIM8 CH1 pin: TIM8_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM8, TIM8_CH1N)
#error Invalid pin assignment for TIM8 CH1N pin: TIM8_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM8, TIM8_CH2)
#error Invalid pin assignment for TIM8 CH2 pin: TIM8_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM8, TIM8_CH2N)
#error Invalid pin assignment for TIM8 CH2N pin: TIM8_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM8, TIM8_CH3)
#error Invalid pin assignment for TIM8 CH3 pin: TIM8_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM8, TIM8_CH3N)
#error Invalid pin assignment for TIM8 CH3N pin: TIM8_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM8, TIM8_CH4)
#error Invalid pin assignment for TIM8 CH4 pin: TIM8_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM8, TIM8_CH4N)
#error Invalid pin assignment for TIM8 CH4N pin: TIM8_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM8, TIM8_ETR)
#error Invalid pin assignment for TIM8 ETR pin: TIM8_ETR
#endif
#endif

#ifdef USE_TIM9
#if !FIND_VALUE_TIM_BK(_TIM9, TIM9_BK)
#error Invalid pin assignment for TIM9 BK pin: TIM9_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM9, TIM9_BK2)
#error Invalid pin assignment for TIM9 BK2 pin: TIM9_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM9, TIM9_BKIN)
#error Invalid pin assignment for TIM9 BKIN pin: TIM9_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM9, TIM9_BKIN2)
#error Invalid pin assignment for TIM9 BKIN2 pin: TIM9_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM9, TIM9_BKIN2_COMP1)
#error Invalid pin assignment for TIM9 BKIN2_COMP1 pin: TIM9_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM9, TIM9_BKIN2_COMP2)
#error Invalid pin assignment for TIM9 BKIN2_COMP2 pin: TIM9_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM9, TIM9_BKIN_COMP1)
#error Invalid pin assignment for TIM9 BKIN_COMP1 pin: TIM9_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM9, TIM9_BKIN_COMP2)
#error Invalid pin assignment for TIM9 BKIN_COMP2 pin: TIM9_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM9, TIM9_CH1)
#error Invalid pin assignment for TIM9 CH1 pin: TIM9_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM9, TIM9_CH1N)
#error Invalid pin assignment for TIM9 CH1N pin: TIM9_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM9, TIM9_CH2)
#error Invalid pin assignment for TIM9 CH2 pin: TIM9_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM9, TIM9_CH2N)
#error Invalid pin assignment for TIM9 CH2N pin: TIM9_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM9, TIM9_CH3)
#error Invalid pin assignment for TIM9 CH3 pin: TIM9_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM9, TIM9_CH3N)
#error Invalid pin assignment for TIM9 CH3N pin: TIM9_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM9, TIM9_CH4)
#error Invalid pin assignment for TIM9 CH4 pin: TIM9_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM9, TIM9_CH4N)
#error Invalid pin assignment for TIM9 CH4N pin: TIM9_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM9, TIM9_ETR)
#error Invalid pin assignment for TIM9 ETR pin: TIM9_ETR
#endif
#endif

#ifdef USE_TIM10
#if !FIND_VALUE_TIM_BK(_TIM10, TIM10_BK)
#error Invalid pin assignment for TIM10 BK pin: TIM10_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM10, TIM10_BK2)
#error Invalid pin assignment for TIM10 BK2 pin: TIM10_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM10, TIM10_BKIN)
#error Invalid pin assignment for TIM10 BKIN pin: TIM10_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM10, TIM10_BKIN2)
#error Invalid pin assignment for TIM10 BKIN2 pin: TIM10_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM10, TIM10_BKIN2_COMP1)
#error Invalid pin assignment for TIM10 BKIN2_COMP1 pin: TIM10_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM10, TIM10_BKIN2_COMP2)
#error Invalid pin assignment for TIM10 BKIN2_COMP2 pin: TIM10_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM10, TIM10_BKIN_COMP1)
#error Invalid pin assignment for TIM10 BKIN_COMP1 pin: TIM10_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM10, TIM10_BKIN_COMP2)
#error Invalid pin assignment for TIM10 BKIN_COMP2 pin: TIM10_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM10, TIM10_CH1)
#error Invalid pin assignment for TIM10 CH1 pin: TIM10_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM10, TIM10_CH1N)
#error Invalid pin assignment for TIM10 CH1N pin: TIM10_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM10, TIM10_CH2)
#error Invalid pin assignment for TIM10 CH2 pin: TIM10_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM10, TIM10_CH2N)
#error Invalid pin assignment for TIM10 CH2N pin: TIM10_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM10, TIM10_CH3)
#error Invalid pin assignment for TIM10 CH3 pin: TIM10_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM10, TIM10_CH3N)
#error Invalid pin assignment for TIM10 CH3N pin: TIM10_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM10, TIM10_CH4)
#error Invalid pin assignment for TIM10 CH4 pin: TIM10_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM10, TIM10_CH4N)
#error Invalid pin assignment for TIM10 CH4N pin: TIM10_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM10, TIM10_ETR)
#error Invalid pin assignment for TIM10 ETR pin: TIM10_ETR
#endif
#endif

#ifdef USE_TIM11
#if !FIND_VALUE_TIM_BK(_TIM11, TIM11_BK)
#error Invalid pin assignment for TIM11 BK pin: TIM11_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM11, TIM11_BK2)
#error Invalid pin assignment for TIM11 BK2 pin: TIM11_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM11, TIM11_BKIN)
#error Invalid pin assignment for TIM11 BKIN pin: TIM11_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM11, TIM11_BKIN2)
#error Invalid pin assignment for TIM11 BKIN2 pin: TIM11_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM11, TIM11_BKIN2_COMP1)
#error Invalid pin assignment for TIM11 BKIN2_COMP1 pin: TIM11_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM11, TIM11_BKIN2_COMP2)
#error Invalid pin assignment for TIM11 BKIN2_COMP2 pin: TIM11_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM11, TIM11_BKIN_COMP1)
#error Invalid pin assignment for TIM11 BKIN_COMP1 pin: TIM11_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM11, TIM11_BKIN_COMP2)
#error Invalid pin assignment for TIM11 BKIN_COMP2 pin: TIM11_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM11, TIM11_CH1)
#error Invalid pin assignment for TIM11 CH1 pin: TIM11_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM11, TIM11_CH1N)
#error Invalid pin assignment for TIM11 CH1N pin: TIM11_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM11, TIM11_CH2)
#error Invalid pin assignment for TIM11 CH2 pin: TIM11_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM11, TIM11_CH2N)
#error Invalid pin assignment for TIM11 CH2N pin: TIM11_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM11, TIM11_CH3)
#error Invalid pin assignment for TIM11 CH3 pin: TIM11_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM11, TIM11_CH3N)
#error Invalid pin assignment for TIM11 CH3N pin: TIM11_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM11, TIM11_CH4)
#error Invalid pin assignment for TIM11 CH4 pin: TIM11_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM11, TIM11_CH4N)
#error Invalid pin assignment for TIM11 CH4N pin: TIM11_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM11, TIM11_ETR)
#error Invalid pin assignment for TIM11 ETR pin: TIM11_ETR
#endif
#endif

#ifdef USE_TIM12
#if !FIND_VALUE_TIM_BK(_TIM12, TIM12_BK)
#error Invalid pin assignment for TIM12 BK pin: TIM12_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM12, TIM12_BK2)
#error Invalid pin assignment for TIM12 BK2 pin: TIM12_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM12, TIM12_BKIN)
#error Invalid pin assignment for TIM12 BKIN pin: TIM12_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM12, TIM12_BKIN2)
#error Invalid pin assignment for TIM12 BKIN2 pin: TIM12_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM12, TIM12_BKIN2_COMP1)
#error Invalid pin assignment for TIM12 BKIN2_COMP1 pin: TIM12_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM12, TIM12_BKIN2_COMP2)
#error Invalid pin assignment for TIM12 BKIN2_COMP2 pin: TIM12_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM12, TIM12_BKIN_COMP1)
#error Invalid pin assignment for TIM12 BKIN_COMP1 pin: TIM12_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM12, TIM12_BKIN_COMP2)
#error Invalid pin assignment for TIM12 BKIN_COMP2 pin: TIM12_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM12, TIM12_CH1)
#error Invalid pin assignment for TIM12 CH1 pin: TIM12_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM12, TIM12_CH1N)
#error Invalid pin assignment for TIM12 CH1N pin: TIM12_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM12, TIM12_CH2)
#error Invalid pin assignment for TIM12 CH2 pin: TIM12_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM12, TIM12_CH2N)
#error Invalid pin assignment for TIM12 CH2N pin: TIM12_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM12, TIM12_CH3)
#error Invalid pin assignment for TIM12 CH3 pin: TIM12_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM12, TIM12_CH3N)
#error Invalid pin assignment for TIM12 CH3N pin: TIM12_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM12, TIM12_CH4)
#error Invalid pin assignment for TIM12 CH4 pin: TIM12_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM12, TIM12_CH4N)
#error Invalid pin assignment for TIM12 CH4N pin: TIM12_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM12, TIM12_ETR)
#error Invalid pin assignment for TIM12 ETR pin: TIM12_ETR
#endif
#endif

#ifdef USE_TIM13
#if !FIND_VALUE_TIM_BK(_TIM13, TIM13_BK)
#error Invalid pin assignment for TIM13 BK pin: TIM13_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM13, TIM13_BK2)
#error Invalid pin assignment for TIM13 BK2 pin: TIM13_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM13, TIM13_BKIN)
#error Invalid pin assignment for TIM13 BKIN pin: TIM13_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM13, TIM13_BKIN2)
#error Invalid pin assignment for TIM13 BKIN2 pin: TIM13_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM13, TIM13_BKIN2_COMP1)
#error Invalid pin assignment for TIM13 BKIN2_COMP1 pin: TIM13_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM13, TIM13_BKIN2_COMP2)
#error Invalid pin assignment for TIM13 BKIN2_COMP2 pin: TIM13_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM13, TIM13_BKIN_COMP1)
#error Invalid pin assignment for TIM13 BKIN_COMP1 pin: TIM13_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM13, TIM13_BKIN_COMP2)
#error Invalid pin assignment for TIM13 BKIN_COMP2 pin: TIM13_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM13, TIM13_CH1)
#error Invalid pin assignment for TIM13 CH1 pin: TIM13_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM13, TIM13_CH1N)
#error Invalid pin assignment for TIM13 CH1N pin: TIM13_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM13, TIM13_CH2)
#error Invalid pin assignment for TIM13 CH2 pin: TIM13_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM13, TIM13_CH2N)
#error Invalid pin assignment for TIM13 CH2N pin: TIM13_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM13, TIM13_CH3)
#error Invalid pin assignment for TIM13 CH3 pin: TIM13_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM13, TIM13_CH3N)
#error Invalid pin assignment for TIM13 CH3N pin: TIM13_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM13, TIM13_CH4)
#error Invalid pin assignment for TIM13 CH4 pin: TIM13_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM13, TIM13_CH4N)
#error Invalid pin assignment for TIM13 CH4N pin: TIM13_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM13, TIM13_ETR)
#error Invalid pin assignment for TIM13 ETR pin: TIM13_ETR
#endif
#endif

#ifdef USE_TIM14
#if !FIND_VALUE_TIM_BK(_TIM14, TIM14_BK)
#error Invalid pin assignment for TIM14 BK pin: TIM14_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM14, TIM14_BK2)
#error Invalid pin assignment for TIM14 BK2 pin: TIM14_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM14, TIM14_BKIN)
#error Invalid pin assignment for TIM14 BKIN pin: TIM14_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM14, TIM14_BKIN2)
#error Invalid pin assignment for TIM14 BKIN2 pin: TIM14_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM14, TIM14_BKIN2_COMP1)
#error Invalid pin assignment for TIM14 BKIN2_COMP1 pin: TIM14_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM14, TIM14_BKIN2_COMP2)
#error Invalid pin assignment for TIM14 BKIN2_COMP2 pin: TIM14_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM14, TIM14_BKIN_COMP1)
#error Invalid pin assignment for TIM14 BKIN_COMP1 pin: TIM14_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM14, TIM14_BKIN_COMP2)
#error Invalid pin assignment for TIM14 BKIN_COMP2 pin: TIM14_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM14, TIM14_CH1)
#error Invalid pin assignment for TIM14 CH1 pin: TIM14_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM14, TIM14_CH1N)
#error Invalid pin assignment for TIM14 CH1N pin: TIM14_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM14, TIM14_CH2)
#error Invalid pin assignment for TIM14 CH2 pin: TIM14_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM14, TIM14_CH2N)
#error Invalid pin assignment for TIM14 CH2N pin: TIM14_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM14, TIM14_CH3)
#error Invalid pin assignment for TIM14 CH3 pin: TIM14_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM14, TIM14_CH3N)
#error Invalid pin assignment for TIM14 CH3N pin: TIM14_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM14, TIM14_CH4)
#error Invalid pin assignment for TIM14 CH4 pin: TIM14_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM14, TIM14_CH4N)
#error Invalid pin assignment for TIM14 CH4N pin: TIM14_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM14, TIM14_ETR)
#error Invalid pin assignment for TIM14 ETR pin: TIM14_ETR
#endif
#endif

#ifdef USE_TIM15
#if !FIND_VALUE_TIM_BK(_TIM15, TIM15_BK)
#error Invalid pin assignment for TIM15 BK pin: TIM15_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM15, TIM15_BK2)
#error Invalid pin assignment for TIM15 BK2 pin: TIM15_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM15, TIM15_BKIN)
#error Invalid pin assignment for TIM15 BKIN pin: TIM15_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM15, TIM15_BKIN2)
#error Invalid pin assignment for TIM15 BKIN2 pin: TIM15_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM15, TIM15_BKIN2_COMP1)
#error Invalid pin assignment for TIM15 BKIN2_COMP1 pin: TIM15_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM15, TIM15_BKIN2_COMP2)
#error Invalid pin assignment for TIM15 BKIN2_COMP2 pin: TIM15_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM15, TIM15_BKIN_COMP1)
#error Invalid pin assignment for TIM15 BKIN_COMP1 pin: TIM15_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM15, TIM15_BKIN_COMP2)
#error Invalid pin assignment for TIM15 BKIN_COMP2 pin: TIM15_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM15, TIM15_CH1)
#error Invalid pin assignment for TIM15 CH1 pin: TIM15_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM15, TIM15_CH1N)
#error Invalid pin assignment for TIM15 CH1N pin: TIM15_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM15, TIM15_CH2)
#error Invalid pin assignment for TIM15 CH2 pin: TIM15_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM15, TIM15_CH2N)
#error Invalid pin assignment for TIM15 CH2N pin: TIM15_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM15, TIM15_CH3)
#error Invalid pin assignment for TIM15 CH3 pin: TIM15_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM15, TIM15_CH3N)
#error Invalid pin assignment for TIM15 CH3N pin: TIM15_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM15, TIM15_CH4)
#error Invalid pin assignment for TIM15 CH4 pin: TIM15_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM15, TIM15_CH4N)
#error Invalid pin assignment for TIM15 CH4N pin: TIM15_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM15, TIM15_ETR)
#error Invalid pin assignment for TIM15 ETR pin: TIM15_ETR
#endif
#endif

#ifdef USE_TIM16
#if !FIND_VALUE_TIM_BK(_TIM16, TIM16_BK)
#error Invalid pin assignment for TIM16 BK pin: TIM16_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM16, TIM16_BK2)
#error Invalid pin assignment for TIM16 BK2 pin: TIM16_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM16, TIM16_BKIN)
#error Invalid pin assignment for TIM16 BKIN pin: TIM16_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM16, TIM16_BKIN2)
#error Invalid pin assignment for TIM16 BKIN2 pin: TIM16_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM16, TIM16_BKIN2_COMP1)
#error Invalid pin assignment for TIM16 BKIN2_COMP1 pin: TIM16_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM16, TIM16_BKIN2_COMP2)
#error Invalid pin assignment for TIM16 BKIN2_COMP2 pin: TIM16_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM16, TIM16_BKIN_COMP1)
#error Invalid pin assignment for TIM16 BKIN_COMP1 pin: TIM16_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM16, TIM16_BKIN_COMP2)
#error Invalid pin assignment for TIM16 BKIN_COMP2 pin: TIM16_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM16, TIM16_CH1)
#error Invalid pin assignment for TIM16 CH1 pin: TIM16_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM16, TIM16_CH1N)
#error Invalid pin assignment for TIM16 CH1N pin: TIM16_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM16, TIM16_CH2)
#error Invalid pin assignment for TIM16 CH2 pin: TIM16_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM16, TIM16_CH2N)
#error Invalid pin assignment for TIM16 CH2N pin: TIM16_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM16, TIM16_CH3)
#error Invalid pin assignment for TIM16 CH3 pin: TIM16_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM16, TIM16_CH3N)
#error Invalid pin assignment for TIM16 CH3N pin: TIM16_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM16, TIM16_CH4)
#error Invalid pin assignment for TIM16 CH4 pin: TIM16_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM16, TIM16_CH4N)
#error Invalid pin assignment for TIM16 CH4N pin: TIM16_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM16, TIM16_ETR)
#error Invalid pin assignment for TIM16 ETR pin: TIM16_ETR
#endif
#endif

#ifdef USE_TIM17
#if !FIND_VALUE_TIM_BK(_TIM17, TIM17_BK)
#error Invalid pin assignment for TIM17 BK pin: TIM17_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM17, TIM17_BK2)
#error Invalid pin assignment for TIM17 BK2 pin: TIM17_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM17, TIM17_BKIN)
#error Invalid pin assignment for TIM17 BKIN pin: TIM17_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM17, TIM17_BKIN2)
#error Invalid pin assignment for TIM17 BKIN2 pin: TIM17_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM17, TIM17_BKIN2_COMP1)
#error Invalid pin assignment for TIM17 BKIN2_COMP1 pin: TIM17_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM17, TIM17_BKIN2_COMP2)
#error Invalid pin assignment for TIM17 BKIN2_COMP2 pin: TIM17_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM17, TIM17_BKIN_COMP1)
#error Invalid pin assignment for TIM17 BKIN_COMP1 pin: TIM17_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM17, TIM17_BKIN_COMP2)
#error Invalid pin assignment for TIM17 BKIN_COMP2 pin: TIM17_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM17, TIM17_CH1)
#error Invalid pin assignment for TIM17 CH1 pin: TIM17_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM17, TIM17_CH1N)
#error Invalid pin assignment for TIM17 CH1N pin: TIM17_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM17, TIM17_CH2)
#error Invalid pin assignment for TIM17 CH2 pin: TIM17_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM17, TIM17_CH2N)
#error Invalid pin assignment for TIM17 CH2N pin: TIM17_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM17, TIM17_CH3)
#error Invalid pin assignment for TIM17 CH3 pin: TIM17_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM17, TIM17_CH3N)
#error Invalid pin assignment for TIM17 CH3N pin: TIM17_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM17, TIM17_CH4)
#error Invalid pin assignment for TIM17 CH4 pin: TIM17_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM17, TIM17_CH4N)
#error Invalid pin assignment for TIM17 CH4N pin: TIM17_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM17, TIM17_ETR)
#error Invalid pin assignment for TIM17 ETR pin: TIM17_ETR
#endif
#endif

#ifdef USE_TIM18
#if !FIND_VALUE_TIM_BK(_TIM18, TIM18_BK)
#error Invalid pin assignment for TIM18 BK pin: TIM18_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM18, TIM18_BK2)
#error Invalid pin assignment for TIM18 BK2 pin: TIM18_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM18, TIM18_BKIN)
#error Invalid pin assignment for TIM18 BKIN pin: TIM18_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM18, TIM18_BKIN2)
#error Invalid pin assignment for TIM18 BKIN2 pin: TIM18_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM18, TIM18_BKIN2_COMP1)
#error Invalid pin assignment for TIM18 BKIN2_COMP1 pin: TIM18_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM18, TIM18_BKIN2_COMP2)
#error Invalid pin assignment for TIM18 BKIN2_COMP2 pin: TIM18_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM18, TIM18_BKIN_COMP1)
#error Invalid pin assignment for TIM18 BKIN_COMP1 pin: TIM18_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM18, TIM18_BKIN_COMP2)
#error Invalid pin assignment for TIM18 BKIN_COMP2 pin: TIM18_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM18, TIM18_CH1)
#error Invalid pin assignment for TIM18 CH1 pin: TIM18_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM18, TIM18_CH1N)
#error Invalid pin assignment for TIM18 CH1N pin: TIM18_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM18, TIM18_CH2)
#error Invalid pin assignment for TIM18 CH2 pin: TIM18_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM18, TIM18_CH2N)
#error Invalid pin assignment for TIM18 CH2N pin: TIM18_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM18, TIM18_CH3)
#error Invalid pin assignment for TIM18 CH3 pin: TIM18_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM18, TIM18_CH3N)
#error Invalid pin assignment for TIM18 CH3N pin: TIM18_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM18, TIM18_CH4)
#error Invalid pin assignment for TIM18 CH4 pin: TIM18_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM18, TIM18_CH4N)
#error Invalid pin assignment for TIM18 CH4N pin: TIM18_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM18, TIM18_ETR)
#error Invalid pin assignment for TIM18 ETR pin: TIM18_ETR
#endif
#endif

#ifdef USE_TIM19
#if !FIND_VALUE_TIM_BK(_TIM19, TIM19_BK)
#error Invalid pin assignment for TIM19 BK pin: TIM19_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM19, TIM19_BK2)
#error Invalid pin assignment for TIM19 BK2 pin: TIM19_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM19, TIM19_BKIN)
#error Invalid pin assignment for TIM19 BKIN pin: TIM19_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM19, TIM19_BKIN2)
#error Invalid pin assignment for TIM19 BKIN2 pin: TIM19_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM19, TIM19_BKIN2_COMP1)
#error Invalid pin assignment for TIM19 BKIN2_COMP1 pin: TIM19_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM19, TIM19_BKIN2_COMP2)
#error Invalid pin assignment for TIM19 BKIN2_COMP2 pin: TIM19_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM19, TIM19_BKIN_COMP1)
#error Invalid pin assignment for TIM19 BKIN_COMP1 pin: TIM19_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM19, TIM19_BKIN_COMP2)
#error Invalid pin assignment for TIM19 BKIN_COMP2 pin: TIM19_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM19, TIM19_CH1)
#error Invalid pin assignment for TIM19 CH1 pin: TIM19_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM19, TIM19_CH1N)
#error Invalid pin assignment for TIM19 CH1N pin: TIM19_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM19, TIM19_CH2)
#error Invalid pin assignment for TIM19 CH2 pin: TIM19_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM19, TIM19_CH2N)
#error Invalid pin assignment for TIM19 CH2N pin: TIM19_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM19, TIM19_CH3)
#error Invalid pin assignment for TIM19 CH3 pin: TIM19_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM19, TIM19_CH3N)
#error Invalid pin assignment for TIM19 CH3N pin: TIM19_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM19, TIM19_CH4)
#error Invalid pin assignment for TIM19 CH4 pin: TIM19_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM19, TIM19_CH4N)
#error Invalid pin assignment for TIM19 CH4N pin: TIM19_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM19, TIM19_ETR)
#error Invalid pin assignment for TIM19 ETR pin: TIM19_ETR
#endif
#endif

#ifdef USE_TIM20
#if !FIND_VALUE_TIM_BK(_TIM20, TIM20_BK)
#error Invalid pin assignment for TIM20 BK pin: TIM20_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM20, TIM20_BK2)
#error Invalid pin assignment for TIM20 BK2 pin: TIM20_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM20, TIM20_BKIN)
#error Invalid pin assignment for TIM20 BKIN pin: TIM20_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM20, TIM20_BKIN2)
#error Invalid pin assignment for TIM20 BKIN2 pin: TIM20_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM20, TIM20_BKIN2_COMP1)
#error Invalid pin assignment for TIM20 BKIN2_COMP1 pin: TIM20_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM20, TIM20_BKIN2_COMP2)
#error Invalid pin assignment for TIM20 BKIN2_COMP2 pin: TIM20_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM20, TIM20_BKIN_COMP1)
#error Invalid pin assignment for TIM20 BKIN_COMP1 pin: TIM20_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM20, TIM20_BKIN_COMP2)
#error Invalid pin assignment for TIM20 BKIN_COMP2 pin: TIM20_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM20, TIM20_CH1)
#error Invalid pin assignment for TIM20 CH1 pin: TIM20_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM20, TIM20_CH1N)
#error Invalid pin assignment for TIM20 CH1N pin: TIM20_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM20, TIM20_CH2)
#error Invalid pin assignment for TIM20 CH2 pin: TIM20_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM20, TIM20_CH2N)
#error Invalid pin assignment for TIM20 CH2N pin: TIM20_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM20, TIM20_CH3)
#error Invalid pin assignment for TIM20 CH3 pin: TIM20_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM20, TIM20_CH3N)
#error Invalid pin assignment for TIM20 CH3N pin: TIM20_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM20, TIM20_CH4)
#error Invalid pin assignment for TIM20 CH4 pin: TIM20_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM20, TIM20_CH4N)
#error Invalid pin assignment for TIM20 CH4N pin: TIM20_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM20, TIM20_ETR)
#error Invalid pin assignment for TIM20 ETR pin: TIM20_ETR
#endif
#endif

#ifdef USE_TIM21
#if !FIND_VALUE_TIM_BK(_TIM21, TIM21_BK)
#error Invalid pin assignment for TIM21 BK pin: TIM21_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM21, TIM21_BK2)
#error Invalid pin assignment for TIM21 BK2 pin: TIM21_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM21, TIM21_BKIN)
#error Invalid pin assignment for TIM21 BKIN pin: TIM21_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM21, TIM21_BKIN2)
#error Invalid pin assignment for TIM21 BKIN2 pin: TIM21_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM21, TIM21_BKIN2_COMP1)
#error Invalid pin assignment for TIM21 BKIN2_COMP1 pin: TIM21_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM21, TIM21_BKIN2_COMP2)
#error Invalid pin assignment for TIM21 BKIN2_COMP2 pin: TIM21_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM21, TIM21_BKIN_COMP1)
#error Invalid pin assignment for TIM21 BKIN_COMP1 pin: TIM21_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM21, TIM21_BKIN_COMP2)
#error Invalid pin assignment for TIM21 BKIN_COMP2 pin: TIM21_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM21, TIM21_CH1)
#error Invalid pin assignment for TIM21 CH1 pin: TIM21_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM21, TIM21_CH1N)
#error Invalid pin assignment for TIM21 CH1N pin: TIM21_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM21, TIM21_CH2)
#error Invalid pin assignment for TIM21 CH2 pin: TIM21_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM21, TIM21_CH2N)
#error Invalid pin assignment for TIM21 CH2N pin: TIM21_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM21, TIM21_CH3)
#error Invalid pin assignment for TIM21 CH3 pin: TIM21_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM21, TIM21_CH3N)
#error Invalid pin assignment for TIM21 CH3N pin: TIM21_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM21, TIM21_CH4)
#error Invalid pin assignment for TIM21 CH4 pin: TIM21_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM21, TIM21_CH4N)
#error Invalid pin assignment for TIM21 CH4N pin: TIM21_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM21, TIM21_ETR)
#error Invalid pin assignment for TIM21 ETR pin: TIM21_ETR
#endif
#endif

#ifdef USE_TIM22
#if !FIND_VALUE_TIM_BK(_TIM22, TIM22_BK)
#error Invalid pin assignment for TIM22 BK pin: TIM22_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM22, TIM22_BK2)
#error Invalid pin assignment for TIM22 BK2 pin: TIM22_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM22, TIM22_BKIN)
#error Invalid pin assignment for TIM22 BKIN pin: TIM22_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM22, TIM22_BKIN2)
#error Invalid pin assignment for TIM22 BKIN2 pin: TIM22_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM22, TIM22_BKIN2_COMP1)
#error Invalid pin assignment for TIM22 BKIN2_COMP1 pin: TIM22_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM22, TIM22_BKIN2_COMP2)
#error Invalid pin assignment for TIM22 BKIN2_COMP2 pin: TIM22_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM22, TIM22_BKIN_COMP1)
#error Invalid pin assignment for TIM22 BKIN_COMP1 pin: TIM22_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM22, TIM22_BKIN_COMP2)
#error Invalid pin assignment for TIM22 BKIN_COMP2 pin: TIM22_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM22, TIM22_CH1)
#error Invalid pin assignment for TIM22 CH1 pin: TIM22_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM22, TIM22_CH1N)
#error Invalid pin assignment for TIM22 CH1N pin: TIM22_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM22, TIM22_CH2)
#error Invalid pin assignment for TIM22 CH2 pin: TIM22_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM22, TIM22_CH2N)
#error Invalid pin assignment for TIM22 CH2N pin: TIM22_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM22, TIM22_CH3)
#error Invalid pin assignment for TIM22 CH3 pin: TIM22_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM22, TIM22_CH3N)
#error Invalid pin assignment for TIM22 CH3N pin: TIM22_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM22, TIM22_CH4)
#error Invalid pin assignment for TIM22 CH4 pin: TIM22_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM22, TIM22_CH4N)
#error Invalid pin assignment for TIM22 CH4N pin: TIM22_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM22, TIM22_ETR)
#error Invalid pin assignment for TIM22 ETR pin: TIM22_ETR
#endif
#endif

#ifdef USE_TIM23
#if !FIND_VALUE_TIM_BK(_TIM23, TIM23_BK)
#error Invalid pin assignment for TIM23 BK pin: TIM23_BK
#endif
#if !FIND_VALUE_TIM_BK2(_TIM23, TIM23_BK2)
#error Invalid pin assignment for TIM23 BK2 pin: TIM23_BK2
#endif
#if !FIND_VALUE_TIM_BKIN(_TIM23, TIM23_BKIN)
#error Invalid pin assignment for TIM23 BKIN pin: TIM23_BKIN
#endif
#if !FIND_VALUE_TIM_BKIN2(_TIM23, TIM23_BKIN2)
#error Invalid pin assignment for TIM23 BKIN2 pin: TIM23_BKIN2
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP1(_TIM23, TIM23_BKIN2_COMP1)
#error Invalid pin assignment for TIM23 BKIN2_COMP1 pin: TIM23_BKIN2_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN2_COMP2(_TIM23, TIM23_BKIN2_COMP2)
#error Invalid pin assignment for TIM23 BKIN2_COMP2 pin: TIM23_BKIN2_COMP2
#endif
#if !FIND_VALUE_TIM_BKIN_COMP1(_TIM23, TIM23_BKIN_COMP1)
#error Invalid pin assignment for TIM23 BKIN_COMP1 pin: TIM23_BKIN_COMP1
#endif
#if !FIND_VALUE_TIM_BKIN_COMP2(_TIM23, TIM23_BKIN_COMP2)
#error Invalid pin assignment for TIM23 BKIN_COMP2 pin: TIM23_BKIN_COMP2
#endif
#if !FIND_VALUE_TIM_CH1(_TIM23, TIM23_CH1)
#error Invalid pin assignment for TIM23 CH1 pin: TIM23_CH1
#endif
#if !FIND_VALUE_TIM_CH1N(_TIM23, TIM23_CH1N)
#error Invalid pin assignment for TIM23 CH1N pin: TIM23_CH1N
#endif
#if !FIND_VALUE_TIM_CH2(_TIM23, TIM23_CH2)
#error Invalid pin assignment for TIM23 CH2 pin: TIM23_CH2
#endif
#if !FIND_VALUE_TIM_CH2N(_TIM23, TIM23_CH2N)
#error Invalid pin assignment for TIM23 CH2N pin: TIM23_CH2N
#endif
#if !FIND_VALUE_TIM_CH3(_TIM23, TIM23_CH3)
#error Invalid pin assignment for TIM23 CH3 pin: TIM23_CH3
#endif
#if !FIND_VALUE_TIM_CH3N(_TIM23, TIM23_CH3N)
#error Invalid pin assignment for TIM23 CH3N pin: TIM23_CH3N
#endif
#if !FIND_VALUE_TIM_CH4(_TIM23, TIM23_CH4)
#error Invalid pin assignment for TIM23 CH4 pin: TIM23_CH4
#endif
#if !FIND_VALUE_TIM_CH4N(_TIM23, TIM23_CH4N)
#error Invalid pin assignment for TIM23 CH4N pin: TIM23_CH4N
#endif
#if !FIND_VALUE_TIM_ETR(_TIM23, TIM23_ETR)
#error Invalid pin assignment for TIM23 ETR pin: TIM23_ETR
#endif
#endif

