/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.547666
 */

#define FIND_VALUE_USB_DM_inner(INDEX,PIN) INDEX##_USB_##PIN
#define FIND_VALUE_USB_DM(INDEX,PIN) FIND_VALUE_USB_DM_inner(INDEX,PIN)

#define FIND_VALUE_USB_DP_inner(INDEX,PIN) INDEX##_USB_##PIN
#define FIND_VALUE_USB_DP(INDEX,PIN) FIND_VALUE_USB_DP_inner(INDEX,PIN)

#define FIND_VALUE_USB_NOE_inner(INDEX,PIN) INDEX##_USB_##PIN
#define FIND_VALUE_USB_NOE(INDEX,PIN) FIND_VALUE_USB_NOE_inner(INDEX,PIN)

#define FIND_VALUE_USB_OE_inner(INDEX,PIN) INDEX##_USB_##PIN
#define FIND_VALUE_USB_OE(INDEX,PIN) FIND_VALUE_USB_OE_inner(INDEX,PIN)

#ifdef USE_USB0
#if !FIND_VALUE_USB_DM(_USB0, USB0_DM)
#error Invalid pin assignment for USB0 DM pin: USB0_DM
#endif
#if !FIND_VALUE_USB_DP(_USB0, USB0_DP)
#error Invalid pin assignment for USB0 DP pin: USB0_DP
#endif
#if !FIND_VALUE_USB_NOE(_USB0, USB0_NOE)
#error Invalid pin assignment for USB0 NOE pin: USB0_NOE
#endif
#if !FIND_VALUE_USB_OE(_USB0, USB0_OE)
#error Invalid pin assignment for USB0 OE pin: USB0_OE
#endif
#endif

