/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.545886
 */

#define FIND_VALUE_ETH_REF_CLK_inner(INDEX,PIN) INDEX##_ETH_REF_##PIN
#define FIND_VALUE_ETH_REF_CLK(INDEX,PIN) FIND_VALUE_ETH_REF_CLK_inner(INDEX,PIN)

#ifdef USE_ETH_REF0
#if !FIND_VALUE_ETH_REF_CLK(_ETH_REF0, ETH_REF0_CLK)
#error Invalid pin assignment for ETH_REF0 CLK pin: ETH_REF0_CLK
#endif
#endif

