/*
 * This file is automatically generated by afTable.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:58:56.546073
 */

#define FIND_VALUE_FMC_NCE_1_inner(INDEX,PIN) INDEX##_FMC_NCE_##PIN
#define FIND_VALUE_FMC_NCE_1(INDEX,PIN) FIND_VALUE_FMC_NCE_1_inner(INDEX,PIN)

#define FIND_VALUE_FMC_NCE_2_inner(INDEX,PIN) INDEX##_FMC_NCE_##PIN
#define FIND_VALUE_FMC_NCE_2(INDEX,PIN) FIND_VALUE_FMC_NCE_2_inner(INDEX,PIN)

#ifdef USE_FMC_NCE0
#if !FIND_VALUE_FMC_NCE_1(_FMC_NCE0, FMC_NCE0_1)
#error Invalid pin assignment for FMC_NCE0 1 pin: FMC_NCE0_1
#endif
#if !FIND_VALUE_FMC_NCE_2(_FMC_NCE0, FMC_NCE0_2)
#error Invalid pin assignment for FMC_NCE0 2 pin: FMC_NCE0_2
#endif
#endif

#ifdef USE_FMC_NCE1
#if !FIND_VALUE_FMC_NCE_1(_FMC_NCE1, FMC_NCE1_1)
#error Invalid pin assignment for FMC_NCE1 1 pin: FMC_NCE1_1
#endif
#if !FIND_VALUE_FMC_NCE_2(_FMC_NCE1, FMC_NCE1_2)
#error Invalid pin assignment for FMC_NCE1 2 pin: FMC_NCE1_2
#endif
#endif

#ifdef USE_FMC_NCE2
#if !FIND_VALUE_FMC_NCE_1(_FMC_NCE2, FMC_NCE2_1)
#error Invalid pin assignment for FMC_NCE2 1 pin: FMC_NCE2_1
#endif
#if !FIND_VALUE_FMC_NCE_2(_FMC_NCE2, FMC_NCE2_2)
#error Invalid pin assignment for FMC_NCE2 2 pin: FMC_NCE2_2
#endif
#endif

#ifdef USE_FMC_NCE3
#if !FIND_VALUE_FMC_NCE_1(_FMC_NCE3, FMC_NCE3_1)
#error Invalid pin assignment for FMC_NCE3 1 pin: FMC_NCE3_1
#endif
#if !FIND_VALUE_FMC_NCE_2(_FMC_NCE3, FMC_NCE3_2)
#error Invalid pin assignment for FMC_NCE3 2 pin: FMC_NCE3_2
#endif
#endif

