#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_STRING  "zcode.org ARM STM32G484"
#endif

#ifndef ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION
#define ZCODE_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0002
#endif
