/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:07.240820
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32G070R.h"
#include "../AlternateFunction/STM32G07x.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32G070RB"
#endif

#define FLASH_SIZE 0x20000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 2

#define SPI_LL_STM32_Ver_2s1_v3_3
#define SPI_COUNT 2

#define UART_LL_STM32_Ver_3_v2_1
#define UART_COUNT 4

#define USART_LL_STM32_Ver_3_v2_1
#define USART_COUNT 4


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */