/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:07.086710
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F765V.h"
#include "../AlternateFunction/STM32F76x.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F765VG"
#endif

#define FLASH_SIZE 0x100000

#define I2C_LL_STM32_Ver_2_v1_1F7
#define I2C_COUNT 4

#define SPI_LL_STM32_Ver_2s1_v3_2
#define SPI_COUNT 5

#define UART_LL_STM32_Ver_2_v2_1
#define UART_COUNT 8

#define USART_LL_STM32_Ver_3_v1_1
#define USART_COUNT 4

#define DAC_LL_STM32_Ver_if_v1_1
#define DAC_COUNT 1

#define CAN_LL_STM32_Ver_bx1_v1_1_F7
#define CAN_COUNT 3


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */