/*
  * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32L062K.h"
#include "../AlternateFunction/STM32L051.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32L062K8"
#endif

#define FLASH_SIZE 0x10000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 1

#define SPI_LL_STM32_Ver_2s1_v3_1
#define SPI_COUNT 1

#define UART_LL_STM32_Ver_3_v1_1
#define UART_COUNT 2

#define USART_LL_STM32_Ver_3_v1_1
#define USART_COUNT 2

#define USB_LL_STM32_Ver_1_v2_0
#define USB_COUNT 1

#define DAC_LL_STM32_Ver_if_v1_2
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */