/*
  * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32H725Z.h"
#include "../AlternateFunction/STM32H72.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32H725ZE"
#endif

#define FLASH_SIZE 0x80000

#define I2C_LL_STM32_Ver_2_v1_1F7
#define I2C_COUNT 5

#define SPI_LL_STM32_Ver_2s2_v1_1
#define SPI_COUNT 6

#define UART_LL_STM32_Ver_2_v3_0
#define UART_COUNT 11

#define USART_LL_STM32_Ver_3_v2_0
#define USART_COUNT 5

#define LPUART_LL_STM32_Ver_3_v1_3
#define LPUART_COUNT 1

#define DAC_LL_STM32_Ver_if_v3_0
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */