/*
  * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32G0B0V.h"
#include "../AlternateFunction/STM32G0Bx.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32G0B0VE"
#endif

#define FLASH_SIZE 0x80000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 3

#define SPI_LL_STM32_Ver_2s1_v3_5
#define SPI_COUNT 3

#define UART_LL_STM32_Ver_3_v2_1
#define UART_COUNT 6

#define USART_LL_STM32_Ver_3_v2_1
#define USART_COUNT 6


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */