/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:07.466721
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32G483Q.h"
#include "../AlternateFunction/STM32G47x.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32G483QE"
#endif

#define FLASH_SIZE 0x80000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 4

#define SPI_LL_STM32_Ver_2s1_v3_5
#define SPI_COUNT 4

#define UART_LL_STM32_Ver_2_v3_1
#define UART_COUNT 6

#define USART_LL_STM32_Ver_3_v2_1
#define USART_COUNT 3

#define LPUART_LL_STM32_Ver_3_v1_3
#define LPUART_COUNT 1

#define USBC_PD_LL_STM32_Ver_ucpd_v1_0
#define USBC_PD_COUNT 1

#define USB_LL_STM32_Ver_1_v2_2_G4
#define USB_COUNT 1

#define DAC_LL_STM32_Ver_G4_if_v4_0
#define DAC_COUNT 4


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */