/*
  * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F411R.h"
#include "../AlternateFunction/STM32F411.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F411RE"
#endif

#define FLASH_SIZE 0x80000

#define I2C_LL_STM32_Ver_1_v1_5
#define I2C_COUNT 3

#define SPI_LL_STM32_Ver_2s1_v2_2
#define SPI_COUNT 5

#define UART_LL_STM32_Ver_2_v1_2
#define UART_COUNT 3

#define USART_LL_STM32_Ver_2_v1_2
#define USART_COUNT 3


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */