/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2022-12-19T22:39:08.638634
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32L552V.h"
#include "../AlternateFunction/STM32L55x.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32L552VC"
#endif

#define FLASH_SIZE 0x40000

#define I2C_LL_STM32_Ver_2_v1_1
#define I2C_COUNT 4

#define SPI_LL_STM32_Ver_2s1_v3_5
#define SPI_COUNT 3

#define UART_LL_STM32_Ver_2_v3_0
#define UART_COUNT 6

#define USART_LL_STM32_Ver_3_v2_0
#define USART_COUNT 3

#define LPUART_LL_STM32_Ver_3_v1_3
#define LPUART_COUNT 1

#define USBC_PD_LL_STM32_Ver_ucpd_v1_0
#define USBC_PD_COUNT 1

#define USB_LL_STM32_Ver_1_v2_2
#define USB_COUNT 1

#define DAC_LL_STM32_Ver_if_v2_0
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */