/*
  * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F030C.h"
#include "../AlternateFunction/STM32F091.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F030CC"
#endif

#define FLASH_SIZE 0x40000

#define I2C_LL_STM32_Ver_F0_2_v1_1
#define I2C_COUNT 2

#define SPI_LL_STM32_Ver_2s1_v3_0
#define SPI_COUNT 2

#define UART_LL_STM32_Ver_3_v1_0
#define UART_COUNT 6

#define USART_LL_STM32_Ver_3_v1_0
#define USART_COUNT 6


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */