/*
  * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
*/

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include "../Pins/STM32F429Z.h"
#include "../AlternateFunction/STM32F427.h"

#ifndef ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZCODE_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F429ZI"
#endif

#define FLASH_SIZE 0x200000

#define I2C_LL_STM32_Ver_1_v1_5
#define I2C_COUNT 3

#define SPI_LL_STM32_Ver_2s1_v2_2
#define SPI_COUNT 6

#define UART_LL_STM32_Ver_2_v1_2_F4
#define UART_COUNT 8

#define USART_LL_STM32_Ver_2_v1_2
#define USART_COUNT 4

#define DAC_LL_STM32_Ver_if_v1_1
#define DAC_COUNT 1

#define CAN_LL_STM32_Ver_bx1_v1_1
#define CAN_COUNT 2


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */