package net.zscript.javaclient.commandpaths;

/**
 * A command, matched to its response. Generated by {@link CommandExecutionPath#compareResponses(ResponseExecutionPath)}.
 */
public class MatchedCommandResponse {
    private final CommandElement  command;
    private final ResponseElement response;

    public MatchedCommandResponse(CommandElement command, ResponseElement response) {
        this.command = command;
        this.response = response;
    }

    public CommandElement getCommand() {
        return command;
    }

    public ResponseElement getResponse() {
        return response;
    }
}
