/*
 * This file is automatically generated by pins.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T19:01:20.067610
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_PINS
#define LOWLEVEL_INCLUDE_DEVICE_PINS

#define PortA 0
#define PortB 1
#define PortC 2

struct GpioPinName {
    uint8_t port:4;
    uint8_t pin:4;
};


#define PA0 ((GpioPinName){PortA, Pin0})
#define PA1 ((GpioPinName){PortA, Pin1})
#define PA4 ((GpioPinName){PortA, Pin4})
#define PA7 ((GpioPinName){PortA, Pin7})
#define PA9 ((GpioPinName){PortA, Pin9})
#define PA10 ((GpioPinName){PortA, Pin10})
#define PA13 ((GpioPinName){PortA, Pin13})
#define PA14 ((GpioPinName){PortA, Pin14})

#define PB9 ((GpioPinName){PortB, Pin9})

#define PC14 ((GpioPinName){PortC, Pin14})
#define PC15 ((GpioPinName){PortC, Pin15})

#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */