/*
 * This file is automatically generated by pins.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T19:01:20.520215
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_PINS
#define LOWLEVEL_INCLUDE_DEVICE_PINS

#define PortA 0
#define PortB 1
#define PortC 2
#define PortD 3
#define PortE 4
#define PortH 5

struct GpioPinName {
    uint8_t port:4;
    uint8_t pin:4;
};


#define PA0 ((GpioPinName){PortA, Pin0})
#define PA1 ((GpioPinName){PortA, Pin1})
#define PA2 ((GpioPinName){PortA, Pin2})
#define PA3 ((GpioPinName){PortA, Pin3})
#define PA4 ((GpioPinName){PortA, Pin4})
#define PA5 ((GpioPinName){PortA, Pin5})
#define PA6 ((GpioPinName){PortA, Pin6})
#define PA7 ((GpioPinName){PortA, Pin7})
#define PA8 ((GpioPinName){PortA, Pin8})
#define PA9 ((GpioPinName){PortA, Pin9})
#define PA10 ((GpioPinName){PortA, Pin10})
#define PA11 ((GpioPinName){PortA, Pin11})
#define PA12 ((GpioPinName){PortA, Pin12})
#define PA13 ((GpioPinName){PortA, Pin13})
#define PA14 ((GpioPinName){PortA, Pin14})
#define PA15 ((GpioPinName){PortA, Pin15})

#define PB0 ((GpioPinName){PortB, Pin0})
#define PB1 ((GpioPinName){PortB, Pin1})
#define PB2 ((GpioPinName){PortB, Pin2})
#define PB3 ((GpioPinName){PortB, Pin3})
#define PB4 ((GpioPinName){PortB, Pin4})
#define PB5 ((GpioPinName){PortB, Pin5})
#define PB6 ((GpioPinName){PortB, Pin6})
#define PB7 ((GpioPinName){PortB, Pin7})
#define PB8 ((GpioPinName){PortB, Pin8})
#define PB9 ((GpioPinName){PortB, Pin9})
#define PB10 ((GpioPinName){PortB, Pin10})
#define PB12 ((GpioPinName){PortB, Pin12})
#define PB13 ((GpioPinName){PortB, Pin13})
#define PB14 ((GpioPinName){PortB, Pin14})
#define PB15 ((GpioPinName){PortB, Pin15})

#define PC0 ((GpioPinName){PortC, Pin0})
#define PC1 ((GpioPinName){PortC, Pin1})
#define PC2 ((GpioPinName){PortC, Pin2})
#define PC3 ((GpioPinName){PortC, Pin3})
#define PC4 ((GpioPinName){PortC, Pin4})
#define PC5 ((GpioPinName){PortC, Pin5})
#define PC6 ((GpioPinName){PortC, Pin6})
#define PC7 ((GpioPinName){PortC, Pin7})
#define PC8 ((GpioPinName){PortC, Pin8})
#define PC9 ((GpioPinName){PortC, Pin9})
#define PC10 ((GpioPinName){PortC, Pin10})
#define PC11 ((GpioPinName){PortC, Pin11})
#define PC12 ((GpioPinName){PortC, Pin12})
#define PC13 ((GpioPinName){PortC, Pin13})
#define PC14 ((GpioPinName){PortC, Pin14})
#define PC15 ((GpioPinName){PortC, Pin15})

#define PD0 ((GpioPinName){PortD, Pin0})
#define PD1 ((GpioPinName){PortD, Pin1})
#define PD2 ((GpioPinName){PortD, Pin2})
#define PD3 ((GpioPinName){PortD, Pin3})
#define PD4 ((GpioPinName){PortD, Pin4})
#define PD5 ((GpioPinName){PortD, Pin5})
#define PD6 ((GpioPinName){PortD, Pin6})
#define PD7 ((GpioPinName){PortD, Pin7})
#define PD8 ((GpioPinName){PortD, Pin8})
#define PD9 ((GpioPinName){PortD, Pin9})
#define PD10 ((GpioPinName){PortD, Pin10})
#define PD11 ((GpioPinName){PortD, Pin11})
#define PD12 ((GpioPinName){PortD, Pin12})
#define PD13 ((GpioPinName){PortD, Pin13})
#define PD14 ((GpioPinName){PortD, Pin14})
#define PD15 ((GpioPinName){PortD, Pin15})

#define PE0 ((GpioPinName){PortE, Pin0})
#define PE1 ((GpioPinName){PortE, Pin1})
#define PE2 ((GpioPinName){PortE, Pin2})
#define PE3 ((GpioPinName){PortE, Pin3})
#define PE4 ((GpioPinName){PortE, Pin4})
#define PE5 ((GpioPinName){PortE, Pin5})
#define PE6 ((GpioPinName){PortE, Pin6})
#define PE7 ((GpioPinName){PortE, Pin7})
#define PE8 ((GpioPinName){PortE, Pin8})
#define PE9 ((GpioPinName){PortE, Pin9})
#define PE10 ((GpioPinName){PortE, Pin10})
#define PE11 ((GpioPinName){PortE, Pin11})
#define PE12 ((GpioPinName){PortE, Pin12})
#define PE13 ((GpioPinName){PortE, Pin13})
#define PE14 ((GpioPinName){PortE, Pin14})
#define PE15 ((GpioPinName){PortE, Pin15})

#define PH0 ((GpioPinName){PortH, Pin0})
#define PH1 ((GpioPinName){PortH, Pin1})
#define PH3 ((GpioPinName){PortH, Pin3})

#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */