/*
 * test-defines.hpp
 *
 *  Created on: 15 Aug 2023
 *      Author: alicia
 */

#define ZSCRIPT_IDENTIFY_USER_FIRMWARE_STRING  "Firmware"
#define ZSCRIPT_IDENTIFY_USER_FIRMWARE_VERSION 0x0023

#define ZSCRIPT_IDENTIFY_USER_HARDWARE_STRING  "Hardware"
#define ZSCRIPT_IDENTIFY_USER_HARDWARE_VERSION 0x0042

#define ZSCRIPT_IDENTIFY_PLATFORM_FIRMWARE_STRING "Platform Firmware"
#define ZSCRIPT_IDENTIFY_PLATFORM_FIRMWARE_VERSION 0x0015

#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING "Platform Hardware"
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_VERSION 0x0016
