/*
 * PreprocessorArrayInitialiser.hpp
 *
 *  Created on: 16 Dec 2022
 *      Author: alicia
 */

#ifndef PERIPHERALS_UTILITY_SRC_MAIN_C___UTILITY_PREPROCESSORARRAYINITIALISER_HPP_
#define PERIPHERALS_UTILITY_SRC_MAIN_C___UTILITY_PREPROCESSORARRAYINITIALISER_HPP_

#define ARRAY_INITIALISE_0 DONOTHING___
#define ARRAY_INITIALISE_1 EXECUTE____,DONOTHING___
#define ARRAY_INITIALISE_2 EXECUTE____,EXECUTE____,DONOTHING___
#define ARRAY_INITIALISE_3 EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___
#define ARRAY_INITIALISE_4 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___
#define ARRAY_INITIALISE_5 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___
#define ARRAY_INITIALISE_6 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___
#define ARRAY_INITIALISE_7 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    DONOTHING___

#define ARRAY_INITIALISE_8 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_9 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_10 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_11 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_12 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_13 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_14 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_15 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_16 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    DONOTHING___

#define ARRAY_INITIALISE_17 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_18 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_19 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_20 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_21 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_22 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_23 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_24 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_25 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    DONOTHING___

#define ARRAY_INITIALISE_26 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_27 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_28 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_29 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_30 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_31 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_32 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define ARRAY_INITIALISE_33 EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,\
    EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,EXECUTE____,DONOTHING___

#define EXECUTE____(...) __VA_ARGS__
#define DONOTHING___(...)

#define ARRAY_INITIALISE_LOOP30(argumentFunc, exec, ...) argumentFunc(30)exec(, Warning_LoopVariableTooLargeForArrayInitialiser__PleaseAddMoreLines)

#define ARRAY_INITIALISE_LOOP29(argumentFunc, exec, ...) argumentFunc(29)exec(, ARRAY_INITIALISE_LOOP30(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP28(argumentFunc, exec, ...) argumentFunc(28)exec(, ARRAY_INITIALISE_LOOP29(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP27(argumentFunc, exec, ...) argumentFunc(27)exec(, ARRAY_INITIALISE_LOOP28(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP26(argumentFunc, exec, ...) argumentFunc(26)exec(, ARRAY_INITIALISE_LOOP27(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP25(argumentFunc, exec, ...) argumentFunc(25)exec(, ARRAY_INITIALISE_LOOP26(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP24(argumentFunc, exec, ...) argumentFunc(24)exec(, ARRAY_INITIALISE_LOOP25(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP23(argumentFunc, exec, ...) argumentFunc(23)exec(, ARRAY_INITIALISE_LOOP24(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP22(argumentFunc, exec, ...) argumentFunc(22)exec(, ARRAY_INITIALISE_LOOP23(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP21(argumentFunc, exec, ...) argumentFunc(21)exec(, ARRAY_INITIALISE_LOOP22(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP20(argumentFunc, exec, ...) argumentFunc(20)exec(, ARRAY_INITIALISE_LOOP21(argumentFunc, __VA_ARGS__))

#define ARRAY_INITIALISE_LOOP19(argumentFunc, exec, ...) argumentFunc(19)exec(, ARRAY_INITIALISE_LOOP20(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP18(argumentFunc, exec, ...) argumentFunc(18)exec(, ARRAY_INITIALISE_LOOP19(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP17(argumentFunc, exec, ...) argumentFunc(17)exec(, ARRAY_INITIALISE_LOOP18(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP16(argumentFunc, exec, ...) argumentFunc(16)exec(, ARRAY_INITIALISE_LOOP17(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP15(argumentFunc, exec, ...) argumentFunc(15)exec(, ARRAY_INITIALISE_LOOP16(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP14(argumentFunc, exec, ...) argumentFunc(14)exec(, ARRAY_INITIALISE_LOOP15(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP13(argumentFunc, exec, ...) argumentFunc(13)exec(, ARRAY_INITIALISE_LOOP14(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP12(argumentFunc, exec, ...) argumentFunc(12)exec(, ARRAY_INITIALISE_LOOP13(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP11(argumentFunc, exec, ...) argumentFunc(11)exec(, ARRAY_INITIALISE_LOOP12(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP10(argumentFunc, exec, ...) argumentFunc(10)exec(, ARRAY_INITIALISE_LOOP11(argumentFunc, __VA_ARGS__))

#define ARRAY_INITIALISE_LOOP9(argumentFunc, exec, ...) argumentFunc(9)exec(, ARRAY_INITIALISE_LOOP10(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP8(argumentFunc, exec, ...) argumentFunc(8)exec(, ARRAY_INITIALISE_LOOP9(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP7(argumentFunc, exec, ...) argumentFunc(7)exec(, ARRAY_INITIALISE_LOOP8(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP6(argumentFunc, exec, ...) argumentFunc(6)exec(, ARRAY_INITIALISE_LOOP7(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP5(argumentFunc, exec, ...) argumentFunc(5)exec(, ARRAY_INITIALISE_LOOP6(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP4(argumentFunc, exec, ...) argumentFunc(4)exec(, ARRAY_INITIALISE_LOOP5(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP3(argumentFunc, exec, ...) argumentFunc(3)exec(, ARRAY_INITIALISE_LOOP4(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP2(argumentFunc, exec, ...) argumentFunc(2)exec(, ARRAY_INITIALISE_LOOP3(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP1(argumentFunc, exec, ...) argumentFunc(1)exec(, ARRAY_INITIALISE_LOOP2(argumentFunc, __VA_ARGS__))
#define ARRAY_INITIALISE_LOOP0(argumentFunc, exec, ...) argumentFunc(0)exec(, ARRAY_INITIALISE_LOOP1(argumentFunc, __VA_ARGS__))

//

#define ARRAY_INITIALISE_0_LOOP(argumentFunc, exec, ...) exec(ARRAY_INITIALISE_LOOP0(argumentFunc, __VA_ARGS__))

#define ARRAY_INITIALISE_0_REPEATED(argumentFunc, ...) ARRAY_INITIALISE_0_LOOP(argumentFunc,  __VA_ARGS__)
#define ARRAY_INITIALISE_0_REAL8(argumentFunc, count) ARRAY_INITIALISE_0_REPEATED(argumentFunc, ARRAY_INITIALISE_##count)
#define ARRAY_INITIALISE_0_REAL7(argumentFunc, count) ARRAY_INITIALISE_0_REAL8(argumentFunc, count)
#define ARRAY_INITIALISE_0_REAL6(argumentFunc, count) ARRAY_INITIALISE_0_REAL7(argumentFunc, count)
#define ARRAY_INITIALISE_0_REAL5(argumentFunc, count) ARRAY_INITIALISE_0_REAL6(argumentFunc, count)
#define ARRAY_INITIALISE_0_REAL4(argumentFunc, count) ARRAY_INITIALISE_0_REAL5(argumentFunc, count)
#define ARRAY_INITIALISE_0_REAL3(argumentFunc, count) ARRAY_INITIALISE_0_REAL4(argumentFunc, count)
#define ARRAY_INITIALISE_0_REAL2(argumentFunc, count) ARRAY_INITIALISE_0_REAL3(argumentFunc, count)

#define ARRAY_INITIALISE_0START(argumentFunc, count) ARRAY_INITIALISE_0_REAL2(argumentFunc,  count)

//

#define ARRAY_INITIALISE_1_LOOP(argumentFunc, exec, ...) exec(ARRAY_INITIALISE_LOOP1(argumentFunc, __VA_ARGS__))

#define ARRAY_INITIALISE_1_REPEATED(argumentFunc, ...) ARRAY_INITIALISE_1_LOOP(argumentFunc,  __VA_ARGS__)
#define ARRAY_INITIALISE_1_REAL8(argumentFunc, count) ARRAY_INITIALISE_1_REPEATED(argumentFunc, ARRAY_INITIALISE_##count)
#define ARRAY_INITIALISE_1_REAL7(argumentFunc, count) ARRAY_INITIALISE_1_REAL8(argumentFunc, count)
#define ARRAY_INITIALISE_1_REAL6(argumentFunc, count) ARRAY_INITIALISE_1_REAL7(argumentFunc, count)
#define ARRAY_INITIALISE_1_REAL5(argumentFunc, count) ARRAY_INITIALISE_1_REAL6(argumentFunc, count)
#define ARRAY_INITIALISE_1_REAL4(argumentFunc, count) ARRAY_INITIALISE_1_REAL5(argumentFunc, count)
#define ARRAY_INITIALISE_1_REAL3(argumentFunc, count) ARRAY_INITIALISE_1_REAL4(argumentFunc, count)
#define ARRAY_INITIALISE_1_REAL2(argumentFunc, count) ARRAY_INITIALISE_1_REAL3(argumentFunc, count)

#define ARRAY_INITIALISE_1START(argumentFunc, count) ARRAY_INITIALISE_1_REAL2(argumentFunc,  count)

//device definition:

//#define I2C_COUNT 1
//
////Code itself:
//
//#define I2C_SCL_PIN_FIND(x) I2C##x##_SCL
//
//ARRAY_INITIALISE_REAL(I2C_SCL_PIN_FIND, I2C_COUNT)

#endif /* PERIPHERALS_UTILITY_SRC_MAIN_C___UTILITY_PREPROCESSORARRAYINITIALISER_HPP_ */
