/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:57:53.796625
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include <zscript/stm32/devices/stm32Setup.h>
#include <zscript/stm32/devices/Pins/STM32H743Z.h>
#include <zscript/stm32/devices/AlternateFunction/STM32H747.h>

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32H743ZI"
#endif

#define FLASH_SIZE 0x200000

#define I2C_LL_STM32_Ver_2v1
#define I2C_COUNT 4

#define ADC_LL_STM32_Ver_5v3
#define ADC_COUNT 3

#define DMA_LL_STM32_Ver_2v1
#define DMA_COUNT 1

#define SPI_LL_STM32_Ver_2v1
#define SPI_COUNT 6

#define UART_LL_STM32_Ver_2v3
#define UART_COUNT 9

#define USART_LL_STM32_Ver_3v2
#define USART_COUNT 4

#define LPUART_LL_STM32_Ver_3v1
#define LPUART_COUNT 1

#define DAC_LL_STM32_Ver_v3
#define DAC_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */