/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:57:53.304551
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include <zscript/stm32/devices/stm32Setup.h>
#include <zscript/stm32/devices/Pins/STM32G0B0C.h>
#include <zscript/stm32/devices/AlternateFunction/STM32G0Bx.h>

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32G0B0CE"
#endif

#define FLASH_SIZE 0x80000

#define I2C_LL_STM32_Ver_2v1
#define I2C_COUNT 3

#define ADC_LL_STM32_Ver_4v3
#define ADC_COUNT 1

#define DMA_LL_STM32_Ver_1v1
#define DMA_COUNT 1

#define SPI_LL_STM32_Ver_1v3
#define SPI_COUNT 3

#define UART_LL_STM32_Ver_3v2
#define UART_COUNT 6

#define USART_LL_STM32_Ver_3v2
#define USART_COUNT 6


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */