/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:57:53.073694
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include <zscript/stm32/devices/stm32Setup.h>
#include <zscript/stm32/devices/Pins/STM32F722I.h>
#include <zscript/stm32/devices/AlternateFunction/STM32F72x.h>

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F722IC"
#endif

#define FLASH_SIZE 0x40000

#define I2C_LL_STM32_Ver_2v1
#define I2C_COUNT 3

#define ADC_LL_STM32_Ver_2v1
#define ADC_COUNT 3

#define DMA_LL_STM32_Ver_v2
#define DMA_COUNT 1

#define SPI_LL_STM32_Ver_1v3
#define SPI_COUNT 5

#define UART_LL_STM32_Ver_2v2
#define UART_COUNT 8

#define USART_LL_STM32_Ver_3v1
#define USART_COUNT 4

#define DAC_LL_STM32_Ver_v1
#define DAC_COUNT 1

#define CAN_LL_STM32_Ver_1v1
#define CAN_COUNT 1


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */