/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:57:52.758703
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include <zscript/stm32/devices/stm32Setup.h>
#include <zscript/stm32/devices/Pins/STM32F401C.h>
#include <zscript/stm32/devices/AlternateFunction/STM32F401.h>

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F401CD"
#endif

#define FLASH_SIZE 0x60000

#define I2C_LL_STM32_Ver_1v1
#define I2C_COUNT 3

#define ADC_LL_STM32_Ver_2v1
#define ADC_COUNT 1

#define DMA_LL_STM32_Ver_v2
#define DMA_COUNT 1

#define SPI_LL_STM32_Ver_1v2
#define SPI_COUNT 3

#define UART_LL_STM32_Ver_2v1
#define UART_COUNT 3

#define USART_LL_STM32_Ver_2v1
#define USART_COUNT 3


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */