/*
 * This file is automatically generated by setup.py from the xml descriptions provided as part of the STM32Cube IDE
 * Timestamp: 2023-12-12T18:57:52.855395
 */

#ifndef LOWLEVEL_INCLUDE_DEVICE_SETUP
#define LOWLEVEL_INCLUDE_DEVICE_SETUP
#include <zscript/stm32/devices/stm32Setup.h>
#include <zscript/stm32/devices/Pins/STM32F412V.h>
#include <zscript/stm32/devices/AlternateFunction/STM32F412.h>

#ifndef ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING
#define ZSCRIPT_IDENTIFY_PLATFORM_HARDWARE_STRING  "ARM STM32F412VE"
#endif

#define FLASH_SIZE 0x80000

#define I2C_LL_STM32_Ver_1v1
#define I2C_COUNT 3

#define ADC_LL_STM32_Ver_2v1
#define ADC_COUNT 1

#define DMA_LL_STM32_Ver_v2
#define DMA_COUNT 1

#define SPI_LL_STM32_Ver_1v2
#define SPI_COUNT 5

#define UART_LL_STM32_Ver_2v1
#define UART_COUNT 4

#define USART_LL_STM32_Ver_2v1
#define USART_COUNT 4

#define CAN_LL_STM32_Ver_1v1
#define CAN_COUNT 2


#endif /* LOWLEVEL_INCLUDE_DEVICE_PINS */