name: Java Build

on: [ push ]

jobs:
    build:
        name: Maven Build
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v3

        -   name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: 11
                distribution: temurin
                cache: maven

        -   uses: carlosperate/arm-none-eabi-gcc-action@v1
        -   run: arm-none-eabi-gcc --version
        -   run: gcc --version

        -   name: Build with Maven
            run: mvn -B verify --file pom.xml -Pbuild-native

        -   name: Upload Java code coverage reports to Codecov
            uses: codecov/codecov-action@v3
            env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#        file: jacoco.xml #optional
#        name: codecov-umbrella #optional
#        yml: ./codecov.yml #optional
#        fail_ci_if_error: true #optional (default = false)
